// Materi Bahasa Indonesia — Fase A–B (SD Kelas 1–4), Kurikulum Merdeka.
// Mengacu pada kaidah EYD (Ejaan yang Disempurnakan) edisi V.

import type { SeedLesson } from './types';

export const bahasaIndonesiaFaseAB: SeedLesson[] = [
  {
    slug: 'bindo-huruf-kapital',
    theme: 'Bahasa Indonesia: Ejaan',
    emoji: '🔠',
    title: 'Penggunaan Huruf Kapital',
    titleId: 'Kapan memakai huruf besar',
    minutes: 5,
    intro: [
      '**Huruf kapital** (huruf besar) dipakai pada:',
      '',
      '1️⃣ **Awal kalimat.**',
      '> **K**ami pergi ke sekolah.',
      '',
      '2️⃣ **Nama orang.**',
      '> Teman saya bernama **R**aka **P**ratama.',
      '',
      '3️⃣ **Nama tempat** (kota, negara, sungai, gunung).',
      '> Nenek tinggal di **Y**ogyakarta. Kami mendaki **G**unung **B**romo.',
      '',
      '4️⃣ **Nama hari, bulan, dan hari raya.**',
      '> Hari **S**enin bulan **A**gustus. Kami merayakan **I**dulfitri.',
      '',
      '5️⃣ **Kata yang berhubungan dengan Tuhan dan kitab suci.**',
      '> **A**llah Maha Pengasih. Aku membaca **A**l-Qur\'an.',
      '',
      '6️⃣ **Kata ganti "Anda".**',
    ].join('\n'),
    quiz: [
      ['Penulisan yang benar adalah …', ['saya tinggal di bandung.', 'Saya tinggal di Bandung.', 'Saya Tinggal Di Bandung.'], 1, 'Awal kalimat dan nama kota ditulis dengan huruf kapital.'],
      ['Penulisan nama hari yang benar adalah …', ['hari minggu', 'Hari minggu', 'hari Minggu'], 2, 'Nama hari diawali huruf kapital: Minggu.'],
      ['Kata yang harus diawali huruf kapital adalah …', ['sepeda', 'Sumatra', 'kucing'], 1, 'Sumatra adalah nama pulau.'],
    ],
  },
  {
    slug: 'bindo-tanda-baca',
    theme: 'Bahasa Indonesia: Ejaan',
    emoji: '❗',
    title: 'Tanda Baca',
    titleId: 'Titik, koma, tanda tanya, dan tanda seru',
    minutes: 5,
    intro: [
      '**Tanda titik ( . )** — di akhir kalimat berita.',
      '> Adik sedang tidur.',
      '',
      '**Tanda koma ( , )** — untuk memisahkan rincian atau daftar.',
      '> Ibu membeli bayam, wortel, dan tomat.',
      '',
      '**Tanda tanya ( ? )** — di akhir kalimat tanya.',
      '> Siapa nama gurumu?',
      '',
      '**Tanda seru ( ! )** — di akhir kalimat perintah, ajakan, atau seruan.',
      '> Ayo, buang sampah pada tempatnya!',
      '> Wah, indah sekali pelangi itu!',
      '',
      '> Ingat: setelah tanda baca akhir kalimat, kalimat berikutnya diawali huruf kapital.',
    ].join('\n'),
    quiz: [
      ['"Di mana rumahmu__" Tanda baca yang tepat adalah …', ['.', '?', '!'], 1, 'Kalimat tanya diakhiri tanda tanya.'],
      ['Tanda baca untuk memisahkan daftar barang adalah …', ['Titik', 'Koma', 'Tanda seru'], 1, 'Koma memisahkan rincian: bayam, wortel, dan tomat.'],
      ['"Tolong tutup pintunya__" Tanda baca yang tepat adalah …', ['!', '?', ','], 0, 'Kalimat perintah diakhiri tanda seru.'],
    ],
  },
  {
    slug: 'bindo-jenis-kata',
    theme: 'Bahasa Indonesia: Tata Bahasa',
    emoji: '🧩',
    title: 'Kata Benda, Kata Kerja, dan Kata Sifat',
    titleId: 'Mengenal jenis kata',
    minutes: 5,
    intro: [
      '📦 **Kata benda** — nama orang, hewan, tempat, atau benda.',
      'Contoh: *ibu, kucing, sekolah, buku, sepeda*.',
      '',
      '🏃 **Kata kerja** — menunjukkan kegiatan atau perbuatan.',
      'Contoh: *makan, berlari, membaca, menulis, tidur*.',
      '',
      '🌈 **Kata sifat** — menjelaskan keadaan atau sifat sesuatu.',
      'Contoh: *besar, kecil, cantik, rajin, manis, tinggi*.',
      '',
      '**Mari kita uraikan kalimat ini:**',
      '> Kucing **kecil** itu **minum** susu.',
      '• **Kucing**, **susu** → kata benda',
      '• **minum** → kata kerja',
      '• **kecil** → kata sifat',
    ].join('\n'),
    quiz: [
      ['Kata "membaca" termasuk kata …', ['Benda', 'Kerja', 'Sifat'], 1, 'Membaca adalah kegiatan → kata kerja.'],
      ['Kata "rajin" termasuk kata …', ['Benda', 'Kerja', 'Sifat'], 2, 'Rajin menjelaskan sifat → kata sifat.'],
      ['"Adik makan apel merah." Kata benda dalam kalimat itu adalah …', ['makan', 'merah', 'apel'], 2, 'Apel adalah nama benda (adik juga kata benda).'],
    ],
  },
  {
    slug: 'bindo-kata-tanya',
    theme: 'Bahasa Indonesia: Tata Bahasa',
    emoji: '❓',
    title: 'Kata Tanya',
    titleId: 'Apa, siapa, di mana, kapan, mengapa, bagaimana',
    minutes: 5,
    intro: [
      'Kata tanya digunakan untuk membuat kalimat tanya. Ingat rumus **5W + 1H**!',
      '',
      '• **Apa** — menanyakan benda atau kejadian. *Apa yang kamu bawa?*',
      '• **Siapa** — menanyakan orang. *Siapa nama ayahmu?*',
      '• **Di mana** — menanyakan tempat. *Di mana letak perpustakaan?*',
      '• **Kapan** — menanyakan waktu. *Kapan kamu berulang tahun?*',
      '• **Mengapa** — menanyakan alasan. *Mengapa kamu terlambat?*',
      '• **Bagaimana** — menanyakan cara atau keadaan. *Bagaimana cara membuat layang-layang?*',
      '',
      '> Kalimat tanya selalu diakhiri dengan **tanda tanya ( ? )**.',
    ].join('\n'),
    quiz: [
      ['"___ kamu pergi ke sekolah?" Jawabannya: "Pukul tujuh pagi." Kata tanya yang tepat …', ['Di mana', 'Kapan', 'Siapa'], 1, 'Pukul tujuh adalah waktu → kapan.'],
      ['Kata tanya untuk menanyakan alasan adalah …', ['Mengapa', 'Apa', 'Di mana'], 0, 'Mengapa menanyakan alasan.'],
      ['"___ yang memasak nasi goreng ini?" Kata tanya yang tepat …', ['Bagaimana', 'Siapa', 'Kapan'], 1, 'Menanyakan orang → siapa.'],
    ],
  },
  {
    slug: 'bindo-sinonim-antonim',
    theme: 'Bahasa Indonesia: Kosakata',
    emoji: '↔️',
    title: 'Sinonim dan Antonim',
    titleId: 'Persamaan kata dan lawan kata',
    minutes: 5,
    intro: [
      '🤝 **Sinonim** adalah **persamaan kata**, yaitu kata yang artinya sama atau mirip.',
      '• pandai = pintar',
      '• gembira = senang',
      '• indah = cantik',
      '• melihat = memandang',
      '',
      '🔄 **Antonim** adalah **lawan kata**, yaitu kata yang artinya berlawanan.',
      '• besar ↔ kecil',
      '• panas ↔ dingin',
      '• rajin ↔ malas',
      '• datang ↔ pergi',
      '',
      '> Contoh: "Rina anak yang **pandai**." Kata pandai dapat diganti **pintar** (sinonim), dan lawannya adalah **bodoh** (antonim).',
    ].join('\n'),
    quiz: [
      ['Sinonim kata "gembira" adalah …', ['Sedih', 'Senang', 'Marah'], 1, 'Gembira = senang.'],
      ['Antonim kata "tinggi" adalah …', ['Pendek', 'Besar', 'Panjang'], 0, 'Tinggi ↔ pendek.'],
      ['Pasangan kata yang merupakan sinonim adalah …', ['Rajin – malas', 'Pandai – pintar', 'Siang – malam'], 1, 'Pandai dan pintar artinya sama.'],
    ],
  },
  {
    slug: 'bindo-puisi-anak',
    theme: 'Bahasa Indonesia: Sastra',
    emoji: '📝',
    title: 'Mengenal Puisi Anak',
    titleId: 'Bait, baris, dan rima',
    minutes: 5,
    intro: [
      '**Puisi** adalah karya sastra dengan bahasa yang indah dan padat. Puisi terdiri dari **bait** dan **baris (larik)**.',
      '',
      '**Contoh puisi:**',
      '> **Ibu**',
      '> Ibu, engkau bangun paling pagi',
      '> Menyiapkan sarapan penuh cinta',
      '> Ibu, engkau tidur paling akhir',
      '> Menjaga kami sepanjang masa',
      '>',
      '> Terima kasih, Ibu tercinta',
      '> Doaku untukmu setiap waktu',
      '> Semoga Allah menjaga Ibu',
      '> Seperti Ibu menjagaku',
      '',
      '• Puisi di atas terdiri dari **2 bait**.',
      '• Setiap bait terdiri dari **4 baris**.',
      '• **Rima** adalah persamaan bunyi di akhir baris, misalnya *cinta – masa*, *waktu – menjagaku*.',
      '',
      '**Tips membaca puisi:** suara jelas, lafal tepat, ekspresi wajah sesuai isi puisi, dan berhenti sejenak di akhir baris.',
    ].join('\n'),
    quiz: [
      ['Kumpulan beberapa baris dalam puisi disebut …', ['Bait', 'Paragraf', 'Judul'], 0, 'Kumpulan baris disebut bait.'],
      ['Persamaan bunyi di akhir baris puisi disebut …', ['Rima', 'Irama', 'Tema'], 0, 'Persamaan bunyi disebut rima.'],
      ['Puisi "Ibu" di atas terdiri dari … bait.', ['1', '2', '4'], 1, 'Ada 2 bait, masing-masing 4 baris.'],
    ],
  },
];
