// Daily English Reading — Fase A (SD Kelas 1–2), CEFR Pre-A1.
// Kalimat pendek, kosakata konkret, satu pola kalimat per bacaan, kuis 3 soal.

import type { SeedReading } from './types';

export const englishPhaseA: SeedReading[] = [
  {
    slug: 'a-my-cat-milo',
    theme: 'Animals',
    emoji: '🐱',
    title: 'My Cat, Milo',
    titleId: 'Kucingku, Milo',
    minutes: 3,
    sentences: [
      ['I have a cat.', 'Aku punya seekor kucing.'],
      ['His name is Milo.', 'Namanya Milo.'],
      ['Milo is orange.', 'Milo berwarna oranye.'],
      ['He has a long tail.', 'Dia punya ekor yang panjang.'],
      ['Milo likes milk.', 'Milo suka susu.', true],
      ['He sleeps on my bed.', 'Dia tidur di atas kasurku.'],
      ['I love Milo!', 'Aku sayang Milo!'],
    ],
    vocab: [
      ['cat', 'kucing', '🐱', 'noun', ['cats'], 'I have a cat.'],
      ['tail', 'ekor', '🐾', 'noun', ['tails'], 'He has a long tail.'],
      ['milk', 'susu', '🥛', 'noun', [], 'Milo likes milk.'],
      ['sleeps', 'tidur', '😴', 'verb', ['sleep'], 'He sleeps on my bed.'],
      ['bed', 'kasur / tempat tidur', '🛏️', 'noun', ['beds'], 'He sleeps on my bed.'],
    ],
    grammar: [
      {
        title: 'Pola: I have … (Aku punya …)',
        pattern: 'I have + a + benda',
        explanation:
          'Untuk mengatakan "aku punya", kita pakai I have. Untuk dia (laki-laki) atau hewan, kita pakai He has.',
        examples: ['I have a cat.', 'He has a long tail.'],
      },
    ],
    quiz: [
      ['What is the cat\'s name? (Siapa nama kucingnya?)', ['Mimi', 'Milo', 'Max'], 1, 'Namanya Milo: "His name is Milo."'],
      ['What color is Milo? (Apa warna Milo?)', ['Black', 'White', 'Orange'], 2, '"Milo is orange." Oranye = orange.'],
      ['What does Milo like? (Milo suka apa?)', ['Milk', 'Rice', 'Juice'], 0, '"Milo likes milk." Milk artinya susu.'],
    ],
  },
  {
    slug: 'a-my-family',
    theme: 'Family',
    emoji: '👨‍👩‍👧‍👦',
    title: 'My Family',
    titleId: 'Keluargaku',
    minutes: 3,
    sentences: [
      ['This is my family.', 'Ini keluargaku.'],
      ['This is my father.', 'Ini ayahku.'],
      ['He is tall.', 'Dia tinggi.'],
      ['This is my mother.', 'Ini ibuku.'],
      ['She is kind.', 'Dia baik hati.'],
      ['I have a little sister.', 'Aku punya seorang adik perempuan.', true],
      ['Her name is Aisyah.', 'Namanya Aisyah.'],
      ['We are happy together.', 'Kami bahagia bersama.'],
    ],
    vocab: [
      ['family', 'keluarga', '👨‍👩‍👧‍👦', 'noun', [], 'This is my family.'],
      ['father', 'ayah', '👨', 'noun', [], 'This is my father.'],
      ['mother', 'ibu', '👩', 'noun', [], 'This is my mother.'],
      ['sister', 'saudara perempuan', '👧', 'noun', ['sisters'], 'I have a little sister.'],
      ['tall', 'tinggi', '📏', 'adjective', [], 'He is tall.'],
      ['kind', 'baik hati', '💖', 'adjective', [], 'She is kind.'],
    ],
    grammar: [
      {
        title: 'Pola: This is my … (Ini … ku)',
        pattern: 'This is + my + orang/benda',
        explanation:
          'This is artinya "ini adalah". Kita pakai untuk memperkenalkan orang atau benda di dekat kita. He untuk laki-laki, She untuk perempuan.',
        examples: ['This is my father. He is tall.', 'This is my mother. She is kind.'],
      },
    ],
    quiz: [
      ['Who is tall? (Siapa yang tinggi?)', ['Father', 'Mother', 'Sister'], 0, '"This is my father. He is tall."'],
      ['What is the sister\'s name? (Siapa nama adiknya?)', ['Aisyah', 'Ani', 'Ayu'], 0, '"Her name is Aisyah."'],
      ['"Mother" artinya …', ['Ayah', 'Ibu', 'Kakak'], 1, 'Mother = ibu, father = ayah.'],
    ],
  },
  {
    slug: 'a-colors-around-me',
    theme: 'Colors',
    emoji: '🌈',
    title: 'Colors Around Me',
    titleId: 'Warna di Sekitarku',
    minutes: 3,
    sentences: [
      ['Look at the colors!', 'Lihat warna-warnanya!'],
      ['The sky is blue.', 'Langit berwarna biru.'],
      ['The grass is green.', 'Rumput berwarna hijau.'],
      ['The sun is yellow.', 'Matahari berwarna kuning.'],
      ['My bag is red.', 'Tasku berwarna merah.', true],
      ['My shoes are black.', 'Sepatuku berwarna hitam.'],
      ['What is your favorite color?', 'Apa warna kesukaanmu?'],
    ],
    vocab: [
      ['blue', 'biru', '🔵', 'adjective', [], 'The sky is blue.'],
      ['green', 'hijau', '🟢', 'adjective', [], 'The grass is green.'],
      ['yellow', 'kuning', '🟡', 'adjective', [], 'The sun is yellow.'],
      ['red', 'merah', '🔴', 'adjective', [], 'My bag is red.'],
      ['black', 'hitam', '⚫', 'adjective', [], 'My shoes are black.'],
      ['sky', 'langit', '☁️', 'noun', [], 'The sky is blue.'],
    ],
    grammar: [
      {
        title: 'Pola: … is + warna',
        pattern: 'The + benda + is + warna',
        explanation:
          'Untuk menyebut warna satu benda, kita pakai is. Kalau bendanya banyak (seperti shoes, sepasang sepatu), kita pakai are.',
        examples: ['The sky is blue.', 'My shoes are black.'],
      },
    ],
    quiz: [
      ['What color is the sky? (Apa warna langit?)', ['Green', 'Blue', 'Red'], 1, '"The sky is blue."'],
      ['What color is the grass? (Apa warna rumput?)', ['Green', 'Yellow', 'Black'], 0, '"The grass is green."'],
      ['"Yellow" artinya …', ['Merah', 'Kuning', 'Hitam'], 1, 'Yellow = kuning, seperti matahari.'],
    ],
  },
  {
    slug: 'a-breakfast-time',
    theme: 'Food',
    emoji: '🍳',
    title: 'Breakfast Time',
    titleId: 'Waktunya Sarapan',
    minutes: 3,
    sentences: [
      ['It is seven o\'clock.', 'Sekarang jam tujuh.'],
      ['It is breakfast time.', 'Ini waktunya sarapan.'],
      ['I eat fried rice and an egg.', 'Aku makan nasi goreng dan sebutir telur.'],
      ['I drink a glass of water.', 'Aku minum segelas air.'],
      ['My brother eats bread.', 'Kakakku makan roti.', true],
      ['The food is yummy!', 'Makanannya enak!'],
      ['Thank you, Mom!', 'Terima kasih, Ibu!'],
    ],
    vocab: [
      ['breakfast', 'sarapan', '🍳', 'noun', [], 'It is breakfast time.'],
      ['fried rice', 'nasi goreng', '🍛', 'noun', [], 'I eat fried rice.'],
      ['egg', 'telur', '🥚', 'noun', ['eggs'], 'I eat an egg.'],
      ['water', 'air', '💧', 'noun', [], 'I drink a glass of water.'],
      ['bread', 'roti', '🍞', 'noun', [], 'My brother eats bread.'],
      ['yummy', 'enak / lezat', '😋', 'adjective', [], 'The food is yummy!'],
    ],
    grammar: [
      {
        title: 'Pola: I eat … / I drink …',
        pattern: 'I + eat/drink + makanan/minuman',
        explanation:
          'Eat artinya makan, drink artinya minum. Untuk orang lain (dia, kakak), tambahkan huruf s: eats, drinks.',
        examples: ['I eat fried rice.', 'My brother eats bread.'],
      },
    ],
    quiz: [
      ['What time is it? (Jam berapa?)', ['Six o\'clock', 'Seven o\'clock', 'Eight o\'clock'], 1, '"It is seven o\'clock."'],
      ['What does the brother eat? (Kakak makan apa?)', ['Bread', 'Egg', 'Rice'], 0, '"My brother eats bread."'],
      ['"Drink" artinya …', ['Makan', 'Minum', 'Tidur'], 1, 'Drink = minum. Eat = makan.'],
    ],
  },
  {
    slug: 'a-at-school',
    theme: 'School',
    emoji: '🏫',
    title: 'At School',
    titleId: 'Di Sekolah',
    minutes: 3,
    sentences: [
      ['I go to school every day.', 'Aku pergi ke sekolah setiap hari.'],
      ['My school is big.', 'Sekolahku besar.'],
      ['My teacher is Mrs. Rina.', 'Guruku adalah Bu Rina.'],
      ['She is very nice.', 'Beliau sangat baik.'],
      ['I read books in class.', 'Aku membaca buku di kelas.', true],
      ['I write with a pencil.', 'Aku menulis dengan pensil.'],
      ['I like my school.', 'Aku suka sekolahku.'],
    ],
    vocab: [
      ['school', 'sekolah', '🏫', 'noun', [], 'I go to school every day.'],
      ['teacher', 'guru', '👩‍🏫', 'noun', [], 'My teacher is Mrs. Rina.'],
      ['read', 'membaca', '📖', 'verb', [], 'I read books in class.'],
      ['write', 'menulis', '✍️', 'verb', [], 'I write with a pencil.'],
      ['pencil', 'pensil', '✏️', 'noun', [], 'I write with a pencil.'],
      ['book', 'buku', '📚', 'noun', ['books'], 'I read books.'],
    ],
    grammar: [
      {
        title: 'Pola: I + kata kerja',
        pattern: 'I + go / read / write + …',
        explanation:
          'Untuk menceritakan kegiatan kita sehari-hari, pakai I lalu kata kerja. Contoh: I read (aku membaca), I write (aku menulis).',
        examples: ['I go to school every day.', 'I write with a pencil.'],
      },
    ],
    quiz: [
      ['Who is the teacher? (Siapa gurunya?)', ['Mrs. Rina', 'Mrs. Ani', 'Mr. Budi'], 0, '"My teacher is Mrs. Rina."'],
      ['What do I write with? (Aku menulis dengan apa?)', ['A pen', 'A pencil', 'A crayon'], 1, '"I write with a pencil."'],
      ['"Teacher" artinya …', ['Murid', 'Guru', 'Sekolah'], 1, 'Teacher = guru.'],
    ],
  },
  {
    slug: 'a-my-toys',
    theme: 'Toys',
    emoji: '🧸',
    title: 'My Toys',
    titleId: 'Mainanku',
    minutes: 3,
    sentences: [
      ['I have many toys.', 'Aku punya banyak mainan.'],
      ['I have a red ball.', 'Aku punya bola merah.'],
      ['I have a small car.', 'Aku punya mobil kecil.'],
      ['I have a brown teddy bear.', 'Aku punya boneka beruang cokelat.'],
      ['My teddy bear is soft.', 'Boneka beruangku lembut.', true],
      ['I play with my toys after school.', 'Aku bermain dengan mainanku sepulang sekolah.'],
      ['I put them in the box.', 'Aku menaruhnya di dalam kotak.'],
    ],
    vocab: [
      ['toy', 'mainan', '🧸', 'noun', ['toys'], 'I have many toys.'],
      ['ball', 'bola', '⚽', 'noun', ['balls'], 'I have a red ball.'],
      ['car', 'mobil', '🚗', 'noun', ['cars'], 'I have a small car.'],
      ['teddy bear', 'boneka beruang', '🧸', 'noun', [], 'My teddy bear is soft.'],
      ['soft', 'lembut', '☁️', 'adjective', [], 'My teddy bear is soft.'],
      ['box', 'kotak', '📦', 'noun', [], 'I put them in the box.'],
    ],
    grammar: [
      {
        title: 'Pola: a + sifat + benda',
        pattern: 'a + red/small/brown + benda',
        explanation:
          'Dalam bahasa Inggris, kata sifat (warna, ukuran) diletakkan SEBELUM bendanya. "Bola merah" menjadi a red ball, bukan a ball red.',
        examples: ['a red ball', 'a small car', 'a brown teddy bear'],
      },
    ],
    quiz: [
      ['What color is the ball? (Apa warna bolanya?)', ['Blue', 'Red', 'Green'], 1, '"I have a red ball."'],
      ['Which one is soft? (Mana yang lembut?)', ['The car', 'The box', 'The teddy bear'], 2, '"My teddy bear is soft."'],
      ['"Mobil kecil" dalam bahasa Inggris adalah …', ['a car small', 'a small car', 'small a car'], 1, 'Kata sifat di depan benda: a small car.'],
    ],
  },
  {
    slug: 'a-sunny-day',
    theme: 'Weather',
    emoji: '☀️',
    title: 'A Sunny Day',
    titleId: 'Hari yang Cerah',
    minutes: 3,
    sentences: [
      ['Today is a sunny day.', 'Hari ini hari yang cerah.'],
      ['The sun is hot.', 'Mataharinya panas.'],
      ['I wear a hat.', 'Aku memakai topi.'],
      ['I drink cold water.', 'Aku minum air dingin.'],
      ['Look, there are white clouds!', 'Lihat, ada awan putih!', true],
      ['The wind is cool.', 'Anginnya sejuk.'],
      ['I like sunny days.', 'Aku suka hari yang cerah.'],
    ],
    vocab: [
      ['sunny', 'cerah', '☀️', 'adjective', [], 'Today is a sunny day.'],
      ['hot', 'panas', '🔥', 'adjective', [], 'The sun is hot.'],
      ['cold', 'dingin', '🧊', 'adjective', [], 'I drink cold water.'],
      ['hat', 'topi', '👒', 'noun', [], 'I wear a hat.'],
      ['cloud', 'awan', '☁️', 'noun', ['clouds'], 'There are white clouds.'],
      ['wind', 'angin', '🌬️', 'noun', [], 'The wind is cool.'],
    ],
    grammar: [
      {
        title: 'Pola: Today is … / The … is …',
        pattern: 'The + benda + is + sifat',
        explanation:
          'Untuk menjelaskan keadaan sesuatu, pakai is lalu kata sifat. The sun is hot artinya "mataharinya panas".',
        examples: ['The sun is hot.', 'The wind is cool.'],
      },
    ],
    quiz: [
      ['What is the weather today? (Bagaimana cuaca hari ini?)', ['Rainy', 'Sunny', 'Windy'], 1, '"Today is a sunny day."'],
      ['What do I wear? (Aku memakai apa?)', ['A hat', 'A coat', 'Boots'], 0, '"I wear a hat."'],
      ['"Hot" artinya …', ['Dingin', 'Panas', 'Sejuk'], 1, 'Hot = panas, cold = dingin.'],
    ],
  },
  {
    slug: 'a-yummy-fruits',
    theme: 'Food',
    emoji: '🍌',
    title: 'Yummy Fruits',
    titleId: 'Buah-Buahan Lezat',
    minutes: 3,
    sentences: [
      ['I like fruits.', 'Aku suka buah-buahan.'],
      ['A banana is long and yellow.', 'Pisang itu panjang dan kuning.'],
      ['An apple is round and red.', 'Apel itu bulat dan merah.'],
      ['A watermelon is big.', 'Semangka itu besar.'],
      ['It is green outside and red inside.', 'Luarnya hijau dan dalamnya merah.', true],
      ['A mango is sweet.', 'Mangga itu manis.'],
      ['Fruits are good for us.', 'Buah-buahan baik untuk kita.'],
    ],
    vocab: [
      ['fruit', 'buah', '🍓', 'noun', ['fruits'], 'I like fruits.'],
      ['banana', 'pisang', '🍌', 'noun', ['bananas'], 'A banana is long.'],
      ['apple', 'apel', '🍎', 'noun', ['apples'], 'An apple is round.'],
      ['watermelon', 'semangka', '🍉', 'noun', [], 'A watermelon is big.'],
      ['mango', 'mangga', '🥭', 'noun', ['mangoes'], 'A mango is sweet.'],
      ['sweet', 'manis', '🍯', 'adjective', [], 'A mango is sweet.'],
    ],
    grammar: [
      {
        title: 'Pola: a dan an',
        pattern: 'a + huruf mati · an + huruf vokal (a, i, u, e, o)',
        explanation:
          'A dan an artinya "sebuah/seekor". Pakai an jika kata berikutnya diawali bunyi vokal, misalnya an apple. Selain itu pakai a, misalnya a banana.',
        examples: ['A banana is long.', 'An apple is round.', 'A mango is sweet.'],
      },
    ],
    quiz: [
      ['Which fruit is long and yellow? (Buah apa yang panjang dan kuning?)', ['Apple', 'Banana', 'Mango'], 1, '"A banana is long and yellow."'],
      ['What color is a watermelon inside? (Apa warna semangka di dalam?)', ['Red', 'Green', 'Yellow'], 0, '"Green outside and red inside."'],
      ['Pilih yang benar:', ['a apple', 'an apple', 'an banana'], 1, 'Apple diawali vokal a, jadi pakai an: an apple.'],
    ],
  },
  {
    slug: 'a-at-the-park',
    theme: 'Places',
    emoji: '🛝',
    title: 'At the Park',
    titleId: 'Di Taman',
    minutes: 3,
    sentences: [
      ['On Sunday, I go to the park.', 'Pada hari Minggu, aku pergi ke taman.'],
      ['The park has a big tree.', 'Taman itu punya pohon besar.'],
      ['I play on the slide.', 'Aku bermain perosotan.'],
      ['My friend plays on the swing.', 'Temanku bermain ayunan.'],
      ['We see birds in the tree.', 'Kami melihat burung-burung di pohon.', true],
      ['We run and laugh.', 'Kami berlari dan tertawa.'],
      ['The park is fun!', 'Taman itu menyenangkan!'],
    ],
    vocab: [
      ['park', 'taman', '🏞️', 'noun', [], 'I go to the park.'],
      ['tree', 'pohon', '🌳', 'noun', ['trees'], 'The park has a big tree.'],
      ['slide', 'perosotan', '🛝', 'noun', [], 'I play on the slide.'],
      ['swing', 'ayunan', '🎠', 'noun', [], 'My friend plays on the swing.'],
      ['bird', 'burung', '🐦', 'noun', ['birds'], 'We see birds.'],
      ['run', 'berlari', '🏃', 'verb', [], 'We run and laugh.'],
    ],
    grammar: [
      {
        title: 'Pola: We + kata kerja',
        pattern: 'We + run / see / play',
        explanation:
          'We artinya "kami" atau "kita". Setelah we, kata kerjanya tidak ditambah s.',
        examples: ['We see birds in the tree.', 'We run and laugh.'],
      },
    ],
    quiz: [
      ['When do I go to the park? (Kapan aku ke taman?)', ['Monday', 'Friday', 'Sunday'], 2, '"On Sunday, I go to the park."'],
      ['Where are the birds? (Di mana burung-burungnya?)', ['In the tree', 'On the slide', 'In the water'], 0, '"We see birds in the tree."'],
      ['"Swing" artinya …', ['Perosotan', 'Ayunan', 'Pohon'], 1, 'Swing = ayunan, slide = perosotan.'],
    ],
  },
  {
    slug: 'a-my-body',
    theme: 'Body',
    emoji: '🧒',
    title: 'My Body',
    titleId: 'Tubuhku',
    minutes: 3,
    sentences: [
      ['I have two eyes.', 'Aku punya dua mata.'],
      ['I see with my eyes.', 'Aku melihat dengan mataku.'],
      ['I have two ears.', 'Aku punya dua telinga.'],
      ['I hear with my ears.', 'Aku mendengar dengan telingaku.'],
      ['I have one nose.', 'Aku punya satu hidung.', true],
      ['I smell flowers with my nose.', 'Aku mencium bunga dengan hidungku.'],
      ['I have two hands and two feet.', 'Aku punya dua tangan dan dua kaki.'],
    ],
    vocab: [
      ['eye', 'mata', '👁️', 'noun', ['eyes'], 'I see with my eyes.'],
      ['ear', 'telinga', '👂', 'noun', ['ears'], 'I hear with my ears.'],
      ['nose', 'hidung', '👃', 'noun', [], 'I have one nose.'],
      ['hand', 'tangan', '✋', 'noun', ['hands'], 'I have two hands.'],
      ['feet', 'kaki (jamak)', '🦶', 'noun', ['foot'], 'I have two feet.'],
      ['hear', 'mendengar', '🎧', 'verb', [], 'I hear with my ears.'],
    ],
    grammar: [
      {
        title: 'Pola: Kata benda jamak (+s)',
        pattern: 'one eye → two eyes',
        explanation:
          'Kalau bendanya lebih dari satu, biasanya kita tambah s di belakang: eye → eyes, ear → ears. Ada yang berubah bentuk: foot → feet.',
        examples: ['I have two eyes.', 'I have two hands and two feet.'],
      },
    ],
    quiz: [
      ['How many noses do I have? (Berapa hidungku?)', ['One', 'Two', 'Three'], 0, '"I have one nose."'],
      ['I hear with my … (Aku mendengar dengan …)', ['eyes', 'ears', 'hands'], 1, '"I hear with my ears."'],
      ['Bentuk jamak dari "foot" adalah …', ['foots', 'feet', 'feets'], 1, 'Foot → feet, bentuknya berubah.'],
    ],
  },
  {
    slug: 'a-counting-ducks',
    theme: 'Numbers',
    emoji: '🦆',
    title: 'Counting Ducks',
    titleId: 'Menghitung Bebek',
    minutes: 3,
    sentences: [
      ['There is a pond near my house.', 'Ada sebuah kolam di dekat rumahku.'],
      ['I see ducks in the pond.', 'Aku melihat bebek-bebek di kolam.'],
      ['Let\'s count!', 'Ayo kita hitung!'],
      ['One, two, three, four, five.', 'Satu, dua, tiga, empat, lima.'],
      ['There are five ducks.', 'Ada lima ekor bebek.', true],
      ['Two ducks are swimming.', 'Dua bebek sedang berenang.'],
      ['Three ducks are sleeping.', 'Tiga bebek sedang tidur.'],
    ],
    vocab: [
      ['duck', 'bebek', '🦆', 'noun', ['ducks'], 'I see ducks in the pond.'],
      ['pond', 'kolam', '🌊', 'noun', [], 'There is a pond near my house.'],
      ['count', 'menghitung', '🔢', 'verb', [], "Let's count!"],
      ['five', 'lima', '5️⃣', 'number', [], 'There are five ducks.'],
      ['swimming', 'berenang', '🏊', 'verb', ['swim'], 'Two ducks are swimming.'],
      ['house', 'rumah', '🏠', 'noun', [], 'near my house'],
    ],
    grammar: [
      {
        title: 'Pola: There is / There are (Ada …)',
        pattern: 'There is + satu benda · There are + banyak benda',
        explanation:
          'There is dan there are artinya "ada". Pakai there is untuk satu benda dan there are untuk lebih dari satu.',
        examples: ['There is a pond near my house.', 'There are five ducks.'],
      },
    ],
    quiz: [
      ['How many ducks are there? (Ada berapa bebek?)', ['Three', 'Four', 'Five'], 2, '"There are five ducks."'],
      ['How many ducks are sleeping? (Berapa bebek yang tidur?)', ['Two', 'Three', 'Five'], 1, '"Three ducks are sleeping."'],
      ['Pilih yang benar: There ___ a pond.', ['is', 'are', 'am'], 0, 'Satu kolam → there is.'],
    ],
  },
  {
    slug: 'a-on-the-farm',
    theme: 'Animals',
    emoji: '🐄',
    title: 'On the Farm',
    titleId: 'Di Peternakan',
    minutes: 3,
    sentences: [
      ['Grandpa has a farm.', 'Kakek punya sebuah peternakan.'],
      ['There is a cow.', 'Ada seekor sapi.'],
      ['The cow says, "Moo!"', 'Sapi berbunyi, "Moo!"'],
      ['There is a goat.', 'Ada seekor kambing.'],
      ['The goat says, "Baa!"', 'Kambing berbunyi, "Mbee!"'],
      ['There are many chickens.', 'Ada banyak ayam.', true],
      ['The chickens say, "Cluck, cluck!"', 'Ayam-ayam berbunyi, "Petok, petok!"'],
      ['I help Grandpa feed the animals.', 'Aku membantu Kakek memberi makan hewan-hewan.'],
    ],
    vocab: [
      ['farm', 'peternakan / pertanian', '🚜', 'noun', [], 'Grandpa has a farm.'],
      ['cow', 'sapi', '🐄', 'noun', [], 'There is a cow.'],
      ['goat', 'kambing', '🐐', 'noun', [], 'There is a goat.'],
      ['chicken', 'ayam', '🐔', 'noun', ['chickens'], 'There are many chickens.'],
      ['feed', 'memberi makan', '🌾', 'verb', [], 'I help Grandpa feed the animals.'],
      ['Grandpa', 'kakek', '👴', 'noun', [], 'Grandpa has a farm.'],
    ],
    grammar: [
      {
        title: 'Pola: The … says, "…"',
        pattern: 'The + hewan + says + bunyi',
        explanation:
          'Says artinya "berkata" atau "berbunyi". Untuk satu hewan pakai says, untuk banyak hewan pakai say.',
        examples: ['The cow says, "Moo!"', 'The chickens say, "Cluck, cluck!"'],
      },
    ],
    quiz: [
      ['Who has a farm? (Siapa yang punya peternakan?)', ['Grandma', 'Grandpa', 'Father'], 1, '"Grandpa has a farm."'],
      ['Which animal says "Moo"? (Hewan apa yang berbunyi "Moo"?)', ['Goat', 'Chicken', 'Cow'], 2, '"The cow says, Moo!"'],
      ['"Goat" artinya …', ['Kambing', 'Sapi', 'Ayam'], 0, 'Goat = kambing.'],
    ],
  },
  {
    slug: 'a-my-room',
    theme: 'Home',
    emoji: '🛏️',
    title: 'My Room',
    titleId: 'Kamarku',
    minutes: 3,
    sentences: [
      ['This is my room.', 'Ini kamarku.'],
      ['It is small but nice.', 'Kamarku kecil tapi bagus.'],
      ['My bed is next to the window.', 'Kasurku ada di sebelah jendela.'],
      ['My books are on the table.', 'Buku-bukuku ada di atas meja.'],
      ['My cat is under the chair.', 'Kucingku ada di bawah kursi.', true],
      ['My clothes are in the cupboard.', 'Bajuku ada di dalam lemari.'],
      ['I keep my room clean.', 'Aku menjaga kamarku tetap bersih.'],
    ],
    vocab: [
      ['room', 'kamar', '🚪', 'noun', [], 'This is my room.'],
      ['window', 'jendela', '🪟', 'noun', [], 'next to the window'],
      ['table', 'meja', '🪑', 'noun', [], 'on the table'],
      ['chair', 'kursi', '🪑', 'noun', [], 'under the chair'],
      ['cupboard', 'lemari', '🗄️', 'noun', [], 'in the cupboard'],
      ['clean', 'bersih', '✨', 'adjective', [], 'I keep my room clean.'],
    ],
    grammar: [
      {
        title: 'Pola: in, on, under (di dalam, di atas, di bawah)',
        pattern: 'in = di dalam · on = di atas · under = di bawah',
        explanation:
          'Kata-kata ini menunjukkan letak benda. In untuk di dalam, on untuk di atas permukaan, under untuk di bawah.',
        examples: ['My books are on the table.', 'My cat is under the chair.', 'My clothes are in the cupboard.'],
      },
    ],
    quiz: [
      ['Where is the cat? (Di mana kucingnya?)', ['On the bed', 'Under the chair', 'In the cupboard'], 1, '"My cat is under the chair."'],
      ['Where are the books? (Di mana buku-bukunya?)', ['On the table', 'Under the bed', 'In the bag'], 0, '"My books are on the table."'],
      ['"Under" artinya …', ['Di atas', 'Di dalam', 'Di bawah'], 2, 'Under = di bawah.'],
    ],
  },
  {
    slug: 'a-bath-time',
    theme: 'Daily Routine',
    emoji: '🛁',
    title: 'Bath Time',
    titleId: 'Waktunya Mandi',
    minutes: 3,
    sentences: [
      ['I take a bath every morning.', 'Aku mandi setiap pagi.'],
      ['I use soap and water.', 'Aku memakai sabun dan air.'],
      ['I wash my hair with shampoo.', 'Aku mencuci rambutku dengan sampo.'],
      ['Then I brush my teeth.', 'Lalu aku menggosok gigiku.'],
      ['I dry my body with a towel.', 'Aku mengeringkan badanku dengan handuk.', true],
      ['Now I am clean and fresh!', 'Sekarang aku bersih dan segar!'],
    ],
    vocab: [
      ['bath', 'mandi', '🛁', 'noun', [], 'I take a bath.'],
      ['soap', 'sabun', '🧼', 'noun', [], 'I use soap and water.'],
      ['wash', 'mencuci', '🚿', 'verb', [], 'I wash my hair.'],
      ['teeth', 'gigi (jamak)', '🦷', 'noun', ['tooth'], 'I brush my teeth.'],
      ['towel', 'handuk', '🧺', 'noun', [], 'with a towel'],
      ['fresh', 'segar', '🌿', 'adjective', [], 'I am clean and fresh!'],
    ],
    grammar: [
      {
        title: 'Pola: Then … (Lalu …)',
        pattern: 'Kegiatan 1. Then + kegiatan 2.',
        explanation:
          'Then artinya "lalu" atau "kemudian". Kita pakai untuk menceritakan urutan kegiatan.',
        examples: ['I wash my hair. Then I brush my teeth.'],
      },
    ],
    quiz: [
      ['When do I take a bath? (Kapan aku mandi?)', ['Every morning', 'Every night', 'Every Sunday'], 0, '"I take a bath every morning."'],
      ['What do I use to dry my body? (Apa untuk mengeringkan badan?)', ['Soap', 'A towel', 'Shampoo'], 1, '"I dry my body with a towel."'],
      ['"Teeth" artinya …', ['Rambut', 'Gigi', 'Tangan'], 1, 'Teeth = gigi (satu gigi = tooth).'],
    ],
  },
  {
    slug: 'a-my-best-friend',
    theme: 'Friends',
    emoji: '🤝',
    title: 'My Best Friend',
    titleId: 'Sahabatku',
    minutes: 3,
    sentences: [
      ['My best friend is Dimas.', 'Sahabatku adalah Dimas.'],
      ['He is eight years old.', 'Dia berumur delapan tahun.'],
      ['He has short black hair.', 'Rambutnya pendek dan hitam.'],
      ['Dimas is funny.', 'Dimas itu lucu.'],
      ['We play football together.', 'Kami bermain sepak bola bersama.', true],
      ['We share our snacks.', 'Kami berbagi camilan.'],
      ['Dimas is a good friend.', 'Dimas adalah teman yang baik.'],
    ],
    vocab: [
      ['friend', 'teman', '🧑‍🤝‍🧑', 'noun', ['friends'], 'Dimas is a good friend.'],
      ['funny', 'lucu', '😂', 'adjective', [], 'Dimas is funny.'],
      ['hair', 'rambut', '💇', 'noun', [], 'He has short black hair.'],
      ['football', 'sepak bola', '⚽', 'noun', [], 'We play football.'],
      ['share', 'berbagi', '🤲', 'verb', [], 'We share our snacks.'],
      ['snack', 'camilan', '🍪', 'noun', ['snacks'], 'We share our snacks.'],
    ],
    grammar: [
      {
        title: 'Pola: … years old (berumur …)',
        pattern: 'He/She is + angka + years old',
        explanation:
          'Untuk menyebut umur, pakai is/am lalu angka dan years old. Contoh: I am seven years old (aku berumur tujuh tahun).',
        examples: ['He is eight years old.', 'I am seven years old.'],
      },
    ],
    quiz: [
      ['How old is Dimas? (Berapa umur Dimas?)', ['Seven', 'Eight', 'Nine'], 1, '"He is eight years old."'],
      ['What do they play? (Mereka bermain apa?)', ['Football', 'Badminton', 'Chess'], 0, '"We play football together."'],
      ['"Share" artinya …', ['Berbagi', 'Bermain', 'Makan'], 0, 'Share = berbagi.'],
    ],
  },
  {
    slug: 'a-at-the-zoo',
    theme: 'Animals',
    emoji: '🦒',
    title: 'At the Zoo',
    titleId: 'Di Kebun Binatang',
    minutes: 3,
    sentences: [
      ['Today we go to the zoo.', 'Hari ini kami pergi ke kebun binatang.'],
      ['I see a tall giraffe.', 'Aku melihat jerapah yang tinggi.'],
      ['It has a very long neck.', 'Lehernya sangat panjang.'],
      ['I see a big elephant.', 'Aku melihat gajah yang besar.'],
      ['It has big ears.', 'Telinganya besar.'],
      ['The monkeys can jump and climb.', 'Monyet-monyet bisa melompat dan memanjat.', true],
      ['The lion is sleeping.', 'Singanya sedang tidur.'],
      ['The zoo is so much fun!', 'Kebun binatang sangat menyenangkan!'],
    ],
    vocab: [
      ['zoo', 'kebun binatang', '🦁', 'noun', [], 'We go to the zoo.'],
      ['giraffe', 'jerapah', '🦒', 'noun', [], 'I see a tall giraffe.'],
      ['elephant', 'gajah', '🐘', 'noun', [], 'I see a big elephant.'],
      ['monkey', 'monyet', '🐒', 'noun', ['monkeys'], 'The monkeys can jump.'],
      ['lion', 'singa', '🦁', 'noun', [], 'The lion is sleeping.'],
      ['neck', 'leher', '🦒', 'noun', [], 'It has a long neck.'],
    ],
    grammar: [
      {
        title: 'Pola: can (bisa)',
        pattern: 'Subjek + can + kata kerja',
        explanation:
          'Can artinya "bisa" atau "dapat". Setelah can, kata kerjanya tetap bentuk dasar.',
        examples: ['The monkeys can jump and climb.', 'I can swim.'],
      },
    ],
    quiz: [
      ['Which animal has a long neck? (Hewan apa yang lehernya panjang?)', ['Elephant', 'Giraffe', 'Lion'], 1, 'Jerapah: "It has a very long neck."'],
      ['What is the lion doing? (Sedang apa singanya?)', ['Eating', 'Running', 'Sleeping'], 2, '"The lion is sleeping."'],
      ['What can the monkeys do? (Apa yang bisa dilakukan monyet?)', ['Fly', 'Jump and climb', 'Swim'], 1, '"The monkeys can jump and climb."'],
    ],
  },
  {
    slug: 'a-at-the-beach',
    theme: 'Places',
    emoji: '🏖️',
    title: 'At the Beach',
    titleId: 'Di Pantai',
    minutes: 3,
    sentences: [
      ['We are at the beach.', 'Kami ada di pantai.'],
      ['The sea is blue and wide.', 'Lautnya biru dan luas.'],
      ['The sand is soft and warm.', 'Pasirnya lembut dan hangat.'],
      ['I make a sandcastle.', 'Aku membuat istana pasir.'],
      ['My sister finds a shell.', 'Adikku menemukan kerang.', true],
      ['We swim in the sea with Dad.', 'Kami berenang di laut bersama Ayah.'],
      ['I love the beach!', 'Aku suka pantai!'],
    ],
    vocab: [
      ['beach', 'pantai', '🏖️', 'noun', [], 'We are at the beach.'],
      ['sea', 'laut', '🌊', 'noun', [], 'The sea is blue.'],
      ['sand', 'pasir', '⏳', 'noun', [], 'The sand is soft.'],
      ['sandcastle', 'istana pasir', '🏰', 'noun', [], 'I make a sandcastle.'],
      ['shell', 'kerang', '🐚', 'noun', [], 'My sister finds a shell.'],
      ['swim', 'berenang', '🏊', 'verb', [], 'We swim in the sea.'],
    ],
    grammar: [
      {
        title: 'Pola: We are … (Kami sedang/ada …)',
        pattern: 'I am · You are · We are · He/She is',
        explanation:
          'Am, is, are artinya "adalah/ada". Pasangannya: I → am, we/you/they → are, he/she/it → is.',
        examples: ['We are at the beach.', 'The sea is blue.', 'I am happy.'],
      },
    ],
    quiz: [
      ['What does the sister find? (Apa yang ditemukan adik?)', ['A shell', 'A fish', 'A ball'], 0, '"My sister finds a shell."'],
      ['What do I make? (Aku membuat apa?)', ['A boat', 'A sandcastle', 'A kite'], 1, '"I make a sandcastle."'],
      ['Pilih yang benar: We ___ at the beach.', ['is', 'am', 'are'], 2, 'We → are.'],
    ],
  },
  {
    slug: 'a-fun-shapes',
    theme: 'Shapes',
    emoji: '🔺',
    title: 'Fun Shapes',
    titleId: 'Bentuk-Bentuk Seru',
    minutes: 3,
    sentences: [
      ['Shapes are everywhere!', 'Bentuk ada di mana-mana!'],
      ['The clock is a circle.', 'Jam dinding berbentuk lingkaran.'],
      ['The door is a rectangle.', 'Pintu berbentuk persegi panjang.'],
      ['A slice of pizza is a triangle.', 'Sepotong pizza berbentuk segitiga.'],
      ['My picture book is a square.', 'Buku bergambarku berbentuk persegi.', true],
      ['A star has five points.', 'Bintang punya lima sudut.'],
      ['Can you find a circle in your house?', 'Bisakah kamu menemukan lingkaran di rumahmu?'],
    ],
    vocab: [
      ['shape', 'bentuk', '🔷', 'noun', ['shapes'], 'Shapes are everywhere!'],
      ['circle', 'lingkaran', '⚪', 'noun', [], 'The clock is a circle.'],
      ['square', 'persegi', '🟥', 'noun', [], 'My book is a square.'],
      ['triangle', 'segitiga', '🔺', 'noun', [], 'A slice of pizza is a triangle.'],
      ['rectangle', 'persegi panjang', '▭', 'noun', [], 'The door is a rectangle.'],
      ['star', 'bintang', '⭐', 'noun', [], 'A star has five points.'],
    ],
    grammar: [
      {
        title: 'Pola: Can you …? (Bisakah kamu …?)',
        pattern: 'Can + you + kata kerja + …?',
        explanation:
          'Untuk bertanya "bisakah kamu", letakkan can di depan: Can you …? Jawabannya: Yes, I can. / No, I can\'t.',
        examples: ['Can you find a circle?', 'Yes, I can!'],
      },
    ],
    quiz: [
      ['What shape is the clock? (Jam dinding berbentuk apa?)', ['Square', 'Circle', 'Triangle'], 1, '"The clock is a circle."'],
      ['What shape is a slice of pizza? (Pizza sepotong berbentuk?)', ['Triangle', 'Rectangle', 'Star'], 0, '"A slice of pizza is a triangle."'],
      ['How many points does a star have? (Berapa sudut bintang?)', ['Three', 'Four', 'Five'], 2, '"A star has five points."'],
    ],
  },
  {
    slug: 'a-days-of-the-week',
    theme: 'Time',
    emoji: '📅',
    title: 'My Busy Week',
    titleId: 'Mingguku yang Sibuk',
    minutes: 4,
    sentences: [
      ['There are seven days in a week.', 'Ada tujuh hari dalam seminggu.'],
      ['On Monday, I go to school.', 'Pada hari Senin, aku pergi ke sekolah.'],
      ['On Wednesday, I have a drawing class.', 'Pada hari Rabu, aku ikut kelas menggambar.'],
      ['On Friday, I go to the mosque with Dad.', 'Pada hari Jumat, aku pergi ke masjid bersama Ayah.'],
      ['On Saturday, I help Mom at home.', 'Pada hari Sabtu, aku membantu Ibu di rumah.', true],
      ['On Sunday, we visit Grandma.', 'Pada hari Minggu, kami mengunjungi Nenek.'],
      ['What is your favorite day?', 'Hari apa yang paling kamu sukai?'],
    ],
    vocab: [
      ['week', 'minggu (7 hari)', '🗓️', 'noun', [], 'seven days in a week'],
      ['Monday', 'Senin', '1️⃣', 'noun', [], 'On Monday, I go to school.'],
      ['Wednesday', 'Rabu', '3️⃣', 'noun', [], 'On Wednesday, I draw.'],
      ['Friday', 'Jumat', '5️⃣', 'noun', [], 'On Friday, I go to the mosque.'],
      ['mosque', 'masjid', '🕌', 'noun', [], 'I go to the mosque with Dad.'],
      ['visit', 'mengunjungi', '🚶', 'verb', [], 'We visit Grandma.'],
    ],
    grammar: [
      {
        title: 'Pola: On + hari',
        pattern: 'On Monday, … · On Sunday, …',
        explanation:
          'Untuk menyebut hari, pakai kata on. Nama hari dalam bahasa Inggris selalu diawali huruf kapital.',
        examples: ['On Monday, I go to school.', 'On Sunday, we visit Grandma.'],
      },
    ],
    quiz: [
      ['When do I go to the mosque with Dad? (Kapan ke masjid bersama Ayah?)', ['Monday', 'Friday', 'Sunday'], 1, '"On Friday, I go to the mosque with Dad."'],
      ['How many days are in a week? (Ada berapa hari dalam seminggu?)', ['Five', 'Six', 'Seven'], 2, '"There are seven days in a week."'],
      ['"Wednesday" artinya …', ['Selasa', 'Rabu', 'Kamis'], 1, 'Wednesday = Rabu.'],
    ],
  },
  {
    slug: 'a-my-clothes',
    theme: 'Clothes',
    emoji: '👕',
    title: 'What I Wear',
    titleId: 'Yang Aku Pakai',
    minutes: 3,
    sentences: [
      ['It is a school day.', 'Ini hari sekolah.'],
      ['I wear a white shirt.', 'Aku memakai kemeja putih.'],
      ['I wear red trousers.', 'Aku memakai celana panjang merah.'],
      ['I wear socks and black shoes.', 'Aku memakai kaus kaki dan sepatu hitam.'],
      ['When it rains, I wear a raincoat.', 'Saat hujan, aku memakai jas hujan.', true],
      ['At home, I wear a T-shirt and shorts.', 'Di rumah, aku memakai kaus dan celana pendek.'],
    ],
    vocab: [
      ['wear', 'memakai', '👔', 'verb', [], 'I wear a white shirt.'],
      ['shirt', 'kemeja', '👔', 'noun', [], 'a white shirt'],
      ['trousers', 'celana panjang', '👖', 'noun', [], 'red trousers'],
      ['socks', 'kaus kaki', '🧦', 'noun', ['sock'], 'I wear socks.'],
      ['shoes', 'sepatu', '👟', 'noun', ['shoe'], 'black shoes'],
      ['raincoat', 'jas hujan', '🧥', 'noun', [], 'I wear a raincoat.'],
    ],
    grammar: [
      {
        title: 'Pola: I wear … (Aku memakai …)',
        pattern: 'I wear + warna + pakaian',
        explanation:
          'Wear artinya "memakai" untuk pakaian, sepatu, topi, atau kacamata. Ingat, warna diletakkan sebelum nama pakaian.',
        examples: ['I wear a white shirt.', 'I wear black shoes.'],
      },
    ],
    quiz: [
      ['What color is the shirt? (Apa warna kemejanya?)', ['White', 'Red', 'Black'], 0, '"I wear a white shirt."'],
      ['What do I wear when it rains? (Apa yang dipakai saat hujan?)', ['A hat', 'A raincoat', 'Shorts'], 1, '"When it rains, I wear a raincoat."'],
      ['"Socks" artinya …', ['Sepatu', 'Kaus kaki', 'Celana'], 1, 'Socks = kaus kaki.'],
    ],
  },
  {
    slug: 'a-on-the-road',
    theme: 'Transportation',
    emoji: '🚌',
    title: 'On the Road',
    titleId: 'Di Jalan',
    minutes: 3,
    sentences: [
      ['The road is busy.', 'Jalannya ramai.'],
      ['I see a yellow bus.', 'Aku melihat bus kuning.'],
      ['I see many motorbikes.', 'Aku melihat banyak sepeda motor.'],
      ['A train goes fast.', 'Kereta api melaju cepat.'],
      ['An airplane flies in the sky.', 'Pesawat terbang di langit.', true],
      ['I go to school by bicycle.', 'Aku pergi ke sekolah naik sepeda.'],
      ['I stop at the red light.', 'Aku berhenti saat lampu merah.'],
    ],
    vocab: [
      ['road', 'jalan', '🛣️', 'noun', [], 'The road is busy.'],
      ['bus', 'bus', '🚌', 'noun', [], 'I see a yellow bus.'],
      ['motorbike', 'sepeda motor', '🏍️', 'noun', ['motorbikes'], 'many motorbikes'],
      ['train', 'kereta api', '🚆', 'noun', [], 'A train goes fast.'],
      ['airplane', 'pesawat terbang', '✈️', 'noun', [], 'An airplane flies.'],
      ['bicycle', 'sepeda', '🚲', 'noun', [], 'I go by bicycle.'],
    ],
    grammar: [
      {
        title: 'Pola: by + kendaraan (naik …)',
        pattern: 'I go to … by + bus/car/bicycle',
        explanation:
          'Untuk mengatakan "naik" kendaraan, pakai by. Contoh: by bus (naik bus), by car (naik mobil). Khusus jalan kaki: on foot.',
        examples: ['I go to school by bicycle.', 'Dad goes to work by car.'],
      },
    ],
    quiz: [
      ['What color is the bus? (Apa warna busnya?)', ['Red', 'Blue', 'Yellow'], 2, '"I see a yellow bus."'],
      ['How do I go to school? (Aku ke sekolah naik apa?)', ['By bus', 'By bicycle', 'By train'], 1, '"I go to school by bicycle."'],
      ['What flies in the sky? (Apa yang terbang di langit?)', ['A train', 'An airplane', 'A bus'], 1, '"An airplane flies in the sky."'],
    ],
  },
  {
    slug: 'a-happy-birthday',
    theme: 'Celebration',
    emoji: '🎂',
    title: 'Happy Birthday, Nisa!',
    titleId: 'Selamat Ulang Tahun, Nisa!',
    minutes: 3,
    sentences: [
      ['Today is Nisa\'s birthday.', 'Hari ini ulang tahun Nisa.'],
      ['She is eight today.', 'Hari ini dia berumur delapan tahun.'],
      ['There is a big chocolate cake.', 'Ada kue cokelat yang besar.'],
      ['There are eight candles on the cake.', 'Ada delapan lilin di atas kue.'],
      ['Her friends sing a song.', 'Teman-temannya menyanyikan lagu.', true],
      ['Nisa gets a doll and a book.', 'Nisa mendapat boneka dan buku.'],
      ['Nisa says, "Thank you, everyone!"', 'Nisa berkata, "Terima kasih, semuanya!"'],
    ],
    vocab: [
      ['birthday', 'ulang tahun', '🎉', 'noun', [], "Today is Nisa's birthday."],
      ['cake', 'kue', '🎂', 'noun', [], 'a big chocolate cake'],
      ['candle', 'lilin', '🕯️', 'noun', ['candles'], 'eight candles'],
      ['sing', 'menyanyi', '🎤', 'verb', [], 'Her friends sing a song.'],
      ['doll', 'boneka', '🪆', 'noun', [], 'Nisa gets a doll.'],
      ['chocolate', 'cokelat', '🍫', 'noun', [], 'a chocolate cake'],
    ],
    grammar: [
      {
        title: "Pola: 's (milik)",
        pattern: "Nama + 's + benda",
        explanation:
          "Tanda 's setelah nama menunjukkan kepemilikan. Nisa's birthday artinya \"ulang tahun Nisa\".",
        examples: ["Today is Nisa's birthday.", "This is Dad's car."],
      },
    ],
    quiz: [
      ['How old is Nisa today? (Berapa umur Nisa?)', ['Seven', 'Eight', 'Nine'], 1, '"She is eight today."'],
      ['What kind of cake is it? (Kue apa?)', ['Chocolate cake', 'Cheese cake', 'Banana cake'], 0, '"a big chocolate cake"'],
      ['What does Nisa get? (Apa yang Nisa dapat?)', ['A ball and a car', 'A doll and a book', 'A bag'], 1, '"Nisa gets a doll and a book."'],
    ],
  },
  {
    slug: 'a-my-feelings',
    theme: 'Feelings',
    emoji: '😊',
    title: 'How Do I Feel?',
    titleId: 'Bagaimana Perasaanku?',
    minutes: 3,
    sentences: [
      ['I am happy when I play with friends.', 'Aku senang saat bermain dengan teman.'],
      ['I am sad when my toy breaks.', 'Aku sedih saat mainanku rusak.'],
      ['I am angry when my brother takes my pencil.', 'Aku marah saat kakak mengambil pensilku.'],
      ['I am scared of the dark.', 'Aku takut gelap.'],
      ['When I am sad, Mom hugs me.', 'Saat aku sedih, Ibu memelukku.', true],
      ['Then I feel better.', 'Lalu aku merasa lebih baik.'],
      ['How do you feel today?', 'Bagaimana perasaanmu hari ini?'],
    ],
    vocab: [
      ['happy', 'senang', '😊', 'adjective', [], 'I am happy.'],
      ['sad', 'sedih', '😢', 'adjective', [], 'I am sad.'],
      ['angry', 'marah', '😠', 'adjective', [], 'I am angry.'],
      ['scared', 'takut', '😨', 'adjective', [], 'I am scared of the dark.'],
      ['hug', 'memeluk', '🤗', 'verb', ['hugs'], 'Mom hugs me.'],
      ['feel', 'merasa', '💭', 'verb', [], 'I feel better.'],
    ],
    grammar: [
      {
        title: 'Pola: I am … when … (Aku … saat …)',
        pattern: 'I am + perasaan + when + kejadian',
        explanation:
          'When artinya "saat" atau "ketika". Kita bisa menceritakan perasaan dan penyebabnya dengan pola ini.',
        examples: ['I am happy when I play with friends.', 'I am sad when my toy breaks.'],
      },
    ],
    quiz: [
      ['When am I happy? (Kapan aku senang?)', ['When I play with friends', 'When my toy breaks', 'In the dark'], 0, '"I am happy when I play with friends."'],
      ['What does Mom do when I am sad? (Apa yang Ibu lakukan?)', ['She sings', 'She hugs me', 'She cooks'], 1, '"When I am sad, Mom hugs me."'],
      ['"Scared" artinya …', ['Senang', 'Marah', 'Takut'], 2, 'Scared = takut.'],
    ],
  },
  {
    slug: 'a-my-little-garden',
    theme: 'Nature',
    emoji: '🌻',
    title: 'My Little Garden',
    titleId: 'Kebun Kecilku',
    minutes: 3,
    sentences: [
      ['We have a little garden.', 'Kami punya kebun kecil.'],
      ['There are red roses and yellow sunflowers.', 'Ada mawar merah dan bunga matahari kuning.'],
      ['I water the plants every afternoon.', 'Aku menyiram tanaman setiap sore.'],
      ['Plants need water and sunlight.', 'Tanaman butuh air dan sinar matahari.'],
      ['A butterfly sits on a flower.', 'Seekor kupu-kupu hinggap di bunga.', true],
      ['A bee is busy too.', 'Seekor lebah juga sedang sibuk.'],
      ['My garden is beautiful.', 'Kebunku indah.'],
    ],
    vocab: [
      ['garden', 'kebun', '🏡', 'noun', [], 'We have a little garden.'],
      ['flower', 'bunga', '🌸', 'noun', ['flowers'], 'on a flower'],
      ['rose', 'mawar', '🌹', 'noun', ['roses'], 'red roses'],
      ['plant', 'tanaman', '🪴', 'noun', ['plants'], 'I water the plants.'],
      ['butterfly', 'kupu-kupu', '🦋', 'noun', [], 'A butterfly sits on a flower.'],
      ['bee', 'lebah', '🐝', 'noun', [], 'A bee is busy too.'],
    ],
    grammar: [
      {
        title: 'Pola: every + waktu (setiap …)',
        pattern: 'I + kegiatan + every morning/afternoon/day',
        explanation:
          'Every artinya "setiap". Kita pakai untuk kebiasaan yang dilakukan berulang-ulang.',
        examples: ['I water the plants every afternoon.', 'I go to school every day.'],
      },
    ],
    quiz: [
      ['When do I water the plants? (Kapan aku menyiram tanaman?)', ['Every morning', 'Every afternoon', 'Every night'], 1, '"I water the plants every afternoon."'],
      ['What do plants need? (Apa yang dibutuhkan tanaman?)', ['Milk and bread', 'Water and sunlight', 'Sand and stones'], 1, '"Plants need water and sunlight."'],
      ['What sits on a flower? (Apa yang hinggap di bunga?)', ['A bird', 'A cat', 'A butterfly'], 2, '"A butterfly sits on a flower."'],
    ],
  },
  {
    slug: 'a-the-moon-and-stars',
    theme: 'Space',
    emoji: '🌙',
    title: 'The Moon and the Stars',
    titleId: 'Bulan dan Bintang',
    minutes: 3,
    sentences: [
      ['It is night.', 'Sekarang malam hari.'],
      ['The sky is dark.', 'Langitnya gelap.'],
      ['I see the moon.', 'Aku melihat bulan.'],
      ['It is round and bright.', 'Bulannya bulat dan terang.'],
      ['I see many stars.', 'Aku melihat banyak bintang.', true],
      ['They are small and shiny.', 'Bintang-bintang itu kecil dan berkilau.'],
      ['I say, "Good night, Moon!"', 'Aku berkata, "Selamat malam, Bulan!"'],
    ],
    vocab: [
      ['night', 'malam', '🌃', 'noun', [], 'It is night.'],
      ['dark', 'gelap', '🌑', 'adjective', [], 'The sky is dark.'],
      ['moon', 'bulan', '🌕', 'noun', [], 'I see the moon.'],
      ['bright', 'terang', '💡', 'adjective', [], 'It is round and bright.'],
      ['shiny', 'berkilau', '✨', 'adjective', [], 'They are small and shiny.'],
      ['round', 'bulat', '⭕', 'adjective', [], 'It is round.'],
    ],
    grammar: [
      {
        title: 'Pola: It is … / They are …',
        pattern: 'It = satu benda · They = banyak benda',
        explanation:
          'It dipakai untuk satu benda atau hewan (bulan). They dipakai untuk banyak benda (bintang-bintang).',
        examples: ['It is round and bright.', 'They are small and shiny.'],
      },
    ],
    quiz: [
      ['What is the moon like? (Seperti apa bulannya?)', ['Small and dark', 'Round and bright', 'Long and yellow'], 1, '"It is round and bright."'],
      ['What color is the sky at night? (Bagaimana langit malam?)', ['Dark', 'Blue', 'Bright'], 0, '"The sky is dark."'],
      ['"They are shiny." They menunjuk …', ['The moon', 'The stars', 'The sky'], 1, 'They = banyak benda, yaitu the stars.'],
    ],
  },
  {
    slug: 'a-helping-at-home',
    theme: 'Home',
    emoji: '🧹',
    title: 'Helping at Home',
    titleId: 'Membantu di Rumah',
    minutes: 3,
    sentences: [
      ['I like to help my family.', 'Aku suka membantu keluargaku.'],
      ['I sweep the floor.', 'Aku menyapu lantai.'],
      ['I make my bed.', 'Aku merapikan tempat tidurku.'],
      ['I put my shoes on the rack.', 'Aku menaruh sepatuku di rak.'],
      ['I help Mom wash the dishes.', 'Aku membantu Ibu mencuci piring.', true],
      ['Mom smiles and says, "Thank you, dear."', 'Ibu tersenyum dan berkata, "Terima kasih, Nak."'],
      ['Helping makes me happy.', 'Membantu membuatku senang.'],
    ],
    vocab: [
      ['help', 'membantu', '🤝', 'verb', ['helping'], 'I like to help my family.'],
      ['sweep', 'menyapu', '🧹', 'verb', [], 'I sweep the floor.'],
      ['floor', 'lantai', '🟫', 'noun', [], 'I sweep the floor.'],
      ['dishes', 'piring-piring', '🍽️', 'noun', ['dish'], 'wash the dishes'],
      ['rack', 'rak', '🗄️', 'noun', [], 'on the rack'],
      ['smiles', 'tersenyum', '😊', 'verb', ['smile'], 'Mom smiles.'],
    ],
    grammar: [
      {
        title: 'Pola: I like to … (Aku suka …)',
        pattern: 'I like to + kata kerja',
        explanation:
          'Untuk mengatakan suka melakukan sesuatu, pakai I like to lalu kata kerja dasar.',
        examples: ['I like to help my family.', 'I like to read books.'],
      },
    ],
    quiz: [
      ['What do I sweep? (Apa yang aku sapu?)', ['The table', 'The floor', 'The bed'], 1, '"I sweep the floor."'],
      ['Who do I help wash the dishes? (Siapa yang kubantu cuci piring?)', ['Dad', 'Mom', 'Grandpa'], 1, '"I help Mom wash the dishes."'],
      ['"Sweep" artinya …', ['Menyapu', 'Mencuci', 'Memasak'], 0, 'Sweep = menyapu.'],
    ],
  },
  {
    slug: 'a-my-goldfish',
    theme: 'Animals',
    emoji: '🐠',
    title: 'Bubbles the Goldfish',
    titleId: 'Bubbles si Ikan Mas',
    minutes: 3,
    sentences: [
      ['I have a goldfish.', 'Aku punya ikan mas koki.'],
      ['Her name is Bubbles.', 'Namanya Bubbles.'],
      ['She lives in a fish tank.', 'Dia tinggal di akuarium.'],
      ['She is small and gold.', 'Dia kecil dan berwarna emas.'],
      ['Bubbles swims all day.', 'Bubbles berenang sepanjang hari.', true],
      ['I feed her two times a day.', 'Aku memberinya makan dua kali sehari.'],
      ['I clean her tank every week.', 'Aku membersihkan akuariumnya setiap minggu.'],
    ],
    vocab: [
      ['goldfish', 'ikan mas koki', '🐠', 'noun', [], 'I have a goldfish.'],
      ['fish tank', 'akuarium', '🫙', 'noun', ['tank'], 'She lives in a fish tank.'],
      ['lives', 'tinggal / hidup', '🏠', 'verb', ['live'], 'She lives in a tank.'],
      ['gold', 'emas', '🥇', 'adjective', [], 'She is small and gold.'],
      ['swims', 'berenang', '🏊', 'verb', ['swim'], 'Bubbles swims all day.'],
      ['clean', 'membersihkan', '🧽', 'verb', [], 'I clean her tank.'],
    ],
    grammar: [
      {
        title: 'Pola: She + kata kerja + s',
        pattern: 'She lives · She swims',
        explanation:
          'Untuk dia (she/he/it) dalam kalimat kebiasaan, kata kerjanya ditambah s: live → lives, swim → swims.',
        examples: ['She lives in a fish tank.', 'Bubbles swims all day.'],
      },
    ],
    quiz: [
      ['Where does Bubbles live? (Di mana Bubbles tinggal?)', ['In a pond', 'In a fish tank', 'In the sea'], 1, '"She lives in a fish tank."'],
      ['How many times a day do I feed her? (Berapa kali sehari diberi makan?)', ['One time', 'Two times', 'Three times'], 1, '"I feed her two times a day."'],
      ['Pilih yang benar: She ___ all day.', ['swim', 'swims', 'swimming'], 1, 'She → kata kerja + s: swims.'],
    ],
  },
  {
    slug: 'a-rainy-day',
    theme: 'Weather',
    emoji: '🌧️',
    title: 'A Rainy Day',
    titleId: 'Hari Hujan',
    minutes: 3,
    sentences: [
      ['It is raining today.', 'Hari ini sedang hujan.'],
      ['The sky is grey.', 'Langitnya kelabu.'],
      ['I can hear the thunder.', 'Aku bisa mendengar petir.'],
      ['I stay at home.', 'Aku tinggal di rumah.'],
      ['I read a book and drink hot chocolate.', 'Aku membaca buku dan minum cokelat panas.', true],
      ['After the rain, I see a rainbow!', 'Setelah hujan, aku melihat pelangi!'],
      ['It has many colors.', 'Pelanginya punya banyak warna.'],
    ],
    vocab: [
      ['rain', 'hujan', '🌧️', 'noun', ['raining'], 'It is raining today.'],
      ['grey', 'kelabu / abu-abu', '🩶', 'adjective', [], 'The sky is grey.'],
      ['thunder', 'petir / guruh', '⛈️', 'noun', [], 'I can hear the thunder.'],
      ['stay', 'tinggal / tetap', '🏠', 'verb', [], 'I stay at home.'],
      ['rainbow', 'pelangi', '🌈', 'noun', [], 'I see a rainbow!'],
      ['after', 'setelah', '⏭️', 'preposition', [], 'After the rain'],
    ],
    grammar: [
      {
        title: 'Pola: It is …ing (Sedang …)',
        pattern: 'It is + kata kerja-ing',
        explanation:
          'Untuk kejadian yang sedang berlangsung sekarang, pakai is/am/are + kata kerja berakhiran -ing. It is raining = sedang hujan.',
        examples: ['It is raining today.', 'The baby is sleeping.'],
      },
    ],
    quiz: [
      ['What is the weather today? (Bagaimana cuaca hari ini?)', ['Sunny', 'Raining', 'Snowing'], 1, '"It is raining today."'],
      ['What do I see after the rain? (Apa yang terlihat setelah hujan?)', ['A rainbow', 'The moon', 'A plane'], 0, '"After the rain, I see a rainbow!"'],
      ['"Thunder" artinya …', ['Pelangi', 'Petir', 'Awan'], 1, 'Thunder = petir/guruh.'],
    ],
  },
  {
    slug: 'a-friday-at-the-mosque',
    theme: 'Daily Life',
    emoji: '🕌',
    title: 'Friday at the Mosque',
    titleId: 'Hari Jumat di Masjid',
    minutes: 3,
    sentences: [
      ['Today is Friday.', 'Hari ini hari Jumat.'],
      ['Dad and I go to the mosque.', 'Ayah dan aku pergi ke masjid.'],
      ['I wear a white shirt and a cap.', 'Aku memakai baju putih dan peci.'],
      ['We take off our shoes.', 'Kami melepas sepatu.'],
      ['We wash our hands and faces.', 'Kami membasuh tangan dan wajah.', true],
      ['The mosque is quiet and clean.', 'Masjidnya tenang dan bersih.'],
      ['We pray together with many people.', 'Kami salat bersama banyak orang.'],
    ],
    vocab: [
      ['mosque', 'masjid', '🕌', 'noun', [], 'We go to the mosque.'],
      ['cap', 'peci / topi', '🧢', 'noun', [], 'I wear a cap.'],
      ['take off', 'melepas', '👟', 'verb', [], 'We take off our shoes.'],
      ['face', 'wajah', '🙂', 'noun', ['faces'], 'We wash our faces.'],
      ['quiet', 'tenang / sunyi', '🤫', 'adjective', [], 'The mosque is quiet.'],
      ['pray', 'salat / berdoa', '🤲', 'verb', [], 'We pray together.'],
    ],
    grammar: [
      {
        title: 'Pola: our (milik kami)',
        pattern: 'my = milikku · our = milik kami',
        explanation:
          'Our artinya "milik kami/kita". Kita pakai saat bendanya milik beberapa orang termasuk kita.',
        examples: ['We take off our shoes.', 'We wash our hands and faces.'],
      },
    ],
    quiz: [
      ['Who goes to the mosque with me? (Siapa yang ke masjid bersamaku?)', ['Mom', 'Dad', 'Grandma'], 1, '"Dad and I go to the mosque."'],
      ['What do we take off? (Apa yang kami lepas?)', ['Our caps', 'Our shoes', 'Our shirts'], 1, '"We take off our shoes."'],
      ['"Quiet" artinya …', ['Ramai', 'Tenang', 'Kotor'], 1, 'Quiet = tenang/sunyi.'],
    ],
  },
  {
    slug: 'a-at-the-market',
    theme: 'Shopping',
    emoji: '🛒',
    title: 'At the Market',
    titleId: 'Di Pasar',
    minutes: 3,
    sentences: [
      ['Mom and I go to the market.', 'Ibu dan aku pergi ke pasar.'],
      ['The market is crowded.', 'Pasarnya ramai.'],
      ['Mom buys vegetables.', 'Ibu membeli sayur-sayuran.'],
      ['She buys carrots, tomatoes, and spinach.', 'Ibu membeli wortel, tomat, dan bayam.'],
      ['I carry a small basket.', 'Aku membawa keranjang kecil.', true],
      ['Mom asks, "How much is it?"', 'Ibu bertanya, "Berapa harganya?"'],
      ['The seller says, "Ten thousand rupiah."', 'Penjual berkata, "Sepuluh ribu rupiah."'],
    ],
    vocab: [
      ['market', 'pasar', '🏪', 'noun', [], 'We go to the market.'],
      ['buy', 'membeli', '🛍️', 'verb', ['buys'], 'Mom buys vegetables.'],
      ['vegetable', 'sayuran', '🥦', 'noun', ['vegetables'], 'Mom buys vegetables.'],
      ['carrot', 'wortel', '🥕', 'noun', ['carrots'], 'She buys carrots.'],
      ['tomato', 'tomat', '🍅', 'noun', ['tomatoes'], 'She buys tomatoes.'],
      ['basket', 'keranjang', '🧺', 'noun', [], 'I carry a small basket.'],
    ],
    grammar: [
      {
        title: 'Pola: How much is it? (Berapa harganya?)',
        pattern: 'How much is + benda?',
        explanation:
          'Untuk menanyakan harga, pakai How much is it? atau How much is this? Jawabannya berupa jumlah uang.',
        examples: ['How much is it?', 'It is ten thousand rupiah.'],
      },
    ],
    quiz: [
      ['What does Mom buy? (Ibu membeli apa?)', ['Fruits', 'Vegetables', 'Clothes'], 1, '"Mom buys vegetables."'],
      ['What do I carry? (Aku membawa apa?)', ['A bag', 'A box', 'A basket'], 2, '"I carry a small basket."'],
      ['Untuk menanyakan harga, kita berkata …', ['How old are you?', 'How much is it?', 'What is your name?'], 1, 'How much is it? = Berapa harganya?'],
    ],
  },
];
