// Daily English Reading Fase A — tahun pertama, bagian 2 (minggu 8–14).

import { P } from './english-phase-a-patterns';
import type { SeedReading } from './types';

export const englishPhaseAYear2: SeedReading[] = [
  // ── Minggu 8: Pakaian ────────────────────────────────────────────────────
  {
    slug: 'a2-my-school-uniform', theme: 'Clothes', emoji: '👕', title: 'My School Uniform', titleId: 'Seragam Sekolahku', minutes: 3,
    sentences: [
      ['On Monday, I wear my school uniform.', 'Pada hari Senin, aku memakai seragam sekolah.'],
      ['My shirt is white.', 'Kemejaku putih.'],
      ['My shorts are red.', 'Celana pendekku merah.'],
      ['I wear a red tie and a belt.', 'Aku memakai dasi merah dan ikat pinggang.'],
      ['I wear black shoes and white socks.', 'Aku memakai sepatu hitam dan kaus kaki putih.', true],
      ['I look neat and smart!', 'Aku terlihat rapi dan keren!'],
    ],
    vocab: [
      ['uniform', 'seragam', '🧑‍🎓', 'noun', ['uniforms'], 'my school uniform'],
      ['shirt', 'kemeja / baju', '👔', 'noun', ['shirts'], 'My shirt is white.'],
      ['shorts', 'celana pendek', '🩳', 'noun', [], 'My shorts are red.'],
      ['tie', 'dasi', '👔', 'noun', ['ties'], 'a red tie'],
      ['shoes', 'sepatu', '👞', 'noun', ['shoe'], 'black shoes'],
      ['socks', 'kaus kaki', '🧦', 'noun', ['sock'], 'white socks'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What color is the shirt? (Apa warna kemejanya?)', ['White', 'Red', 'Blue'], 0, '"My shirt is white."'],
      ['What color are the shoes? (Apa warna sepatunya?)', ['White', 'Black', 'Brown'], 1, '"I wear black shoes."'],
      ['"Socks" artinya …', ['Sepatu', 'Kaus kaki', 'Dasi'], 1, 'Socks = kaus kaki.'],
    ],
  },
  {
    slug: 'a2-batik-friday', theme: 'Clothes', emoji: '🎨', title: 'Batik Friday', titleId: 'Jumat Batik', minutes: 3,
    sentences: [
      ['Today is Friday.', 'Hari ini hari Jumat.'],
      ['On Friday, we wear batik to school.', 'Pada hari Jumat, kami memakai batik ke sekolah.'],
      ['My batik shirt is brown and gold.', 'Kemeja batikku cokelat dan keemasan.'],
      ['Dina\'s batik dress has flowers on it.', 'Gaun batik Dina bermotif bunga.'],
      ['Mrs. Sari wears batik too.', 'Bu Sari juga memakai batik.', true],
      ['Batik is a special cloth from Indonesia.', 'Batik adalah kain istimewa dari Indonesia.'],
      ['I am proud of batik!', 'Aku bangga dengan batik!'],
    ],
    vocab: [
      ['batik', 'batik', '🎨', 'noun', [], 'we wear batik'],
      ['gold', 'emas / keemasan', '🟡', 'adjective', [], 'brown and gold'],
      ['dress', 'gaun', '👗', 'noun', ['dresses'], 'Dina\'s batik dress'],
      ['special', 'istimewa', '🌟', 'adjective', [], 'a special cloth'],
      ['cloth', 'kain', '🧵', 'noun', [], 'a special cloth'],
      ['proud', 'bangga', '🏅', 'adjective', [], 'I am proud of batik!'],
    ],
    grammar: [P.daysOfWeek],
    quiz: [
      ['When do they wear batik? (Kapan mereka memakai batik?)', ['On Monday', 'On Friday', 'On Sunday'], 1, '"On Friday, we wear batik to school."'],
      ['What is on Dina\'s dress? (Apa motif gaun Dina?)', ['Flowers', 'Stars', 'Cars'], 0, '"Dina\'s batik dress has flowers on it."'],
      ['Batik comes from … (Batik berasal dari …)', ['Japan', 'Indonesia', 'India'], 1, '"Batik is a special cloth from Indonesia."'],
    ],
  },
  {
    slug: 'a2-my-yellow-raincoat', theme: 'Clothes', emoji: '🧥', title: 'My Yellow Raincoat', titleId: 'Jas Hujan Kuningku', minutes: 3,
    sentences: [
      ['It is raining outside.', 'Di luar sedang hujan.'],
      ['I put on my yellow raincoat.', 'Aku memakai jas hujan kuningku.'],
      ['I put on my rain boots too.', 'Aku juga memakai sepatu bot hujan.'],
      ['Splash, splash! I walk in the puddles.', 'Cipratan, cipratan! Aku berjalan di genangan air.'],
      ['My clothes stay dry.', 'Pakaianku tetap kering.', true],
      ['I love rainy days!', 'Aku suka hari hujan!'],
    ],
    vocab: [
      ['raining', 'sedang hujan', '🌧️', 'verb', ['rain'], 'It is raining outside.'],
      ['put on', 'memakai (pakaian)', '🧥', 'verb', ['puts on'], 'I put on my raincoat.'],
      ['raincoat', 'jas hujan', '🧥', 'noun', ['raincoats'], 'my yellow raincoat'],
      ['boots', 'sepatu bot', '🥾', 'noun', ['boot'], 'my rain boots'],
      ['puddles', 'genangan air', '💧', 'noun', ['puddle'], 'I walk in the puddles.'],
      ['dry', 'kering', '☀️', 'adjective', [], 'My clothes stay dry.'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What color is the raincoat? (Apa warna jas hujannya?)', ['Red', 'Yellow', 'Green'], 1, '"my yellow raincoat"'],
      ['Where does Rafi walk? (Rafi berjalan di mana?)', ['In the puddles', 'On the roof', 'In the pool'], 0, '"I walk in the puddles."'],
      ['"Dry" artinya …', ['Basah', 'Kering', 'Kotor'], 1, 'Dry = kering, wet = basah.'],
    ],
  },
  {
    slug: 'a2-dad-s-hat', theme: 'Clothes', emoji: '🧢', title: 'Where Is Dad\'s Hat?', titleId: 'Di Mana Topi Ayah?', minutes: 3,
    sentences: [
      ['Dad wants to go out.', 'Ayah ingin pergi keluar.'],
      ['"Where is my hat?" he asks.', '"Di mana topiku?" tanyanya.'],
      ['Is it on the table? No.', 'Apakah di atas meja? Tidak.'],
      ['Is it in the car? No.', 'Apakah di dalam mobil? Tidak.'],
      ['Aisyah laughs. "Dad, it is on your head!"', 'Aisyah tertawa. "Ayah, topinya ada di kepala Ayah!"', true],
      ['Dad touches his head. "Oh, silly me!"', 'Ayah menyentuh kepalanya. "Oh, Ayah konyol!"'],
    ],
    vocab: [
      ['go out', 'pergi keluar', '🚶', 'verb', [], 'Dad wants to go out.'],
      ['hat', 'topi', '🧢', 'noun', ['hats'], 'Where is my hat?'],
      ['car', 'mobil', '🚗', 'noun', ['cars'], 'in the car'],
      ['head', 'kepala', '🙆', 'noun', [], 'it is on your head'],
      ['silly', 'konyol', '🤪', 'adjective', [], 'Oh, silly me!'],
    ],
    grammar: [P.prepositions],
    quiz: [
      ['What is Dad looking for? (Ayah mencari apa?)', ['His shoes', 'His hat', 'His bag'], 1, '"Where is my hat?"'],
      ['Where is the hat? (Di mana topinya?)', ['On the table', 'In the car', 'On Dad\'s head'], 2, '"it is on your head!"'],
      ['Who finds the hat? (Siapa yang menemukan topi?)', ['Aisyah', 'Mom', 'Rafi'], 0, 'Aisyah tertawa dan berkata topinya di kepala Ayah.'],
    ],
  },
  {
    slug: 'a2-hot-and-cold-clothes', theme: 'Clothes', emoji: '🧣', title: 'Clothes for Hot and Cold', titleId: 'Pakaian untuk Panas dan Dingin', minutes: 3,
    sentences: [
      ['When it is hot, I wear a T-shirt.', 'Saat panas, aku memakai kaus.'],
      ['I wear shorts and sandals.', 'Aku memakai celana pendek dan sandal.'],
      ['I wear a cap to cover my head from the sun.', 'Aku memakai topi untuk melindungi kepalaku dari matahari.'],
      ['When it is cold, I wear a jacket.', 'Saat dingin, aku memakai jaket.', true],
      ['I wear long pants and a scarf.', 'Aku memakai celana panjang dan syal.'],
      ['The right clothes keep us comfortable.', 'Pakaian yang tepat membuat kita nyaman.'],
    ],
    vocab: [
      ['T-shirt', 'kaus', '👕', 'noun', ['T-shirts'], 'I wear a T-shirt.'],
      ['sandals', 'sandal', '🩴', 'noun', ['sandal'], 'shorts and sandals'],
      ['cap', 'topi (pet)', '🧢', 'noun', ['caps'], 'I wear a cap.'],
      ['jacket', 'jaket', '🧥', 'noun', ['jackets'], 'I wear a jacket.'],
      ['pants', 'celana panjang', '👖', 'noun', [], 'long pants'],
      ['scarf', 'syal', '🧣', 'noun', ['scarves'], 'a scarf'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What do I wear when it is cold? (Apa yang kupakai saat dingin?)', ['A jacket', 'Sandals', 'Shorts'], 0, '"When it is cold, I wear a jacket."'],
      ['Why do I wear a cap? (Mengapa aku memakai topi?)', ['To cover my head from the sun', 'To sleep', 'To swim'], 0, '"to cover my head from the sun"'],
      ['"Scarf" artinya …', ['Sarung tangan', 'Syal', 'Sandal'], 1, 'Scarf = syal.'],
    ],
  },
  {
    slug: 'a2-pajama-time', theme: 'Clothes', emoji: '🌙', title: 'Pajama Time', titleId: 'Waktunya Piyama', minutes: 3,
    sentences: [
      ['It is eight o\'clock at night.', 'Sekarang pukul delapan malam.'],
      ['Aisyah takes off her dress.', 'Aisyah melepas gaunnya.'],
      ['She puts on her pajamas.', 'Dia memakai piyamanya.'],
      ['Her pajamas are pink with little stars.', 'Piyamanya merah muda dengan bintang-bintang kecil.'],
      ['Rafi\'s pajamas are blue with rockets.', 'Piyama Rafi biru dengan gambar roket.', true],
      ['They say their prayers.', 'Mereka berdoa.'],
      ['Then they go to bed.', 'Lalu mereka pergi tidur.'],
    ],
    vocab: [
      ['take off', 'melepas (pakaian)', '👚', 'verb', ['takes off'], 'Aisyah takes off her dress.'],
      ['pajamas', 'piyama', '🛌', 'noun', [], 'She puts on her pajamas.'],
      ['pink', 'merah muda', '🩷', 'adjective', [], 'pink with little stars'],
      ['rockets', 'roket', '🚀', 'noun', ['rocket'], 'blue with rockets'],
      ['prayers', 'doa', '🤲', 'noun', ['prayer'], 'They say their prayers.'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What color are Aisyah\'s pajamas? (Apa warna piyama Aisyah?)', ['Blue', 'Pink', 'Green'], 1, '"Her pajamas are pink."'],
      ['What is on Rafi\'s pajamas? (Gambar apa di piyama Rafi?)', ['Stars', 'Cars', 'Rockets'], 2, '"Rafi\'s pajamas are blue with rockets."'],
      ['What do they do before bed? (Apa yang mereka lakukan sebelum tidur?)', ['They say their prayers', 'They eat', 'They swim'], 0, '"They say their prayers."'],
    ],
  },
  {
    slug: 'a2-getting-dressed', theme: 'Clothes', emoji: '🧦', title: 'Aisyah Gets Dressed', titleId: 'Aisyah Berpakaian', minutes: 3,
    sentences: [
      ['Aisyah is five years old.', 'Aisyah berumur lima tahun.'],
      ['Today she gets dressed by herself.', 'Hari ini dia berpakaian sendiri.'],
      ['She puts on her blouse.', 'Dia memakai blusnya.'],
      ['She puts on her skirt.', 'Dia memakai roknya.'],
      ['Oops! Her socks are different colors.', 'Ups! Kaus kakinya berbeda warna.', true],
      ['One is red and one is green.', 'Satu merah dan satu hijau.'],
      ['Mom smiles. "Good try, Aisyah!"', 'Ibu tersenyum. "Usaha yang bagus, Aisyah!"'],
    ],
    vocab: [
      ['gets dressed', 'berpakaian', '👗', 'verb', ['get dressed'], 'she gets dressed'],
      ['by herself', 'sendiri', '🙋‍♀️', 'phrase', [], 'by herself'],
      ['blouse', 'blus', '👚', 'noun', ['blouses'], 'her blouse'],
      ['skirt', 'rok', '👗', 'noun', ['skirts'], 'her skirt'],
      ['different', 'berbeda', '🔀', 'adjective', [], 'different colors'],
      ['try', 'usaha / mencoba', '💪', 'noun', ['tries'], 'Good try, Aisyah!'],
    ],
    grammar: [P.heShe],
    quiz: [
      ['How old is Aisyah? (Berapa umur Aisyah?)', ['Five', 'Six', 'Eight'], 0, '"Aisyah is five years old."'],
      ['What is funny about her socks? (Apa yang lucu dari kaus kakinya?)', ['They are big', 'They are different colors', 'They are wet'], 1, '"Her socks are different colors."'],
      ['"Skirt" artinya …', ['Rok', 'Blus', 'Topi'], 0, 'Skirt = rok.'],
    ],
  },

  // ── Minggu 9: Makanan & Minuman ──────────────────────────────────────────
  {
    slug: 'a2-rice-every-day', theme: 'Food', emoji: '🍚', title: 'Rice Every Day', titleId: 'Nasi Setiap Hari', minutes: 3,
    sentences: [
      ['In Indonesia, we eat rice every day.', 'Di Indonesia, kami makan nasi setiap hari.'],
      ['Rice comes from rice plants.', 'Nasi berasal dari tanaman padi.'],
      ['Farmers grow rice in the rice fields.', 'Petani menanam padi di sawah.'],
      ['Mom cooks the rice in a rice cooker.', 'Ibu memasak nasi di penanak nasi.'],
      ['I eat rice with egg and vegetables.', 'Aku makan nasi dengan telur dan sayur.', true],
      ['Thank you, farmers!', 'Terima kasih, para petani!'],
    ],
    vocab: [
      ['rice', 'nasi / beras / padi', '🍚', 'noun', [], 'we eat rice'],
      ['grow', 'menanam', '🌱', 'verb', ['grows'], 'Farmers grow rice.'],
      ['rice fields', 'sawah', '🌾', 'noun', ['rice field'], 'in the rice fields'],
      ['rice cooker', 'penanak nasi', '🍲', 'noun', [], 'in a rice cooker'],
      ['egg', 'telur', '🍳', 'noun', ['eggs'], 'rice with egg'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Where do farmers grow rice? (Di mana petani menanam padi?)', ['In the rice fields', 'In the sea', 'In the city'], 0, '"Farmers grow rice in the rice fields."'],
      ['What does Mom use to cook rice? (Ibu memakai apa untuk memasak nasi?)', ['A rice cooker', 'A fridge', 'A fan'], 0, '"in a rice cooker"'],
      ['"Rice fields" artinya …', ['Kebun', 'Sawah', 'Hutan'], 1, 'Rice fields = sawah.'],
    ],
  },
  {
    slug: 'a2-fried-rice-for-dinner', theme: 'Food', emoji: '🍛', title: 'Fried Rice for Dinner', titleId: 'Nasi Goreng untuk Makan Malam', minutes: 3,
    sentences: [
      ['Tonight Dad cooks dinner.', 'Malam ini Ayah memasak makan malam.'],
      ['He makes fried rice.', 'Dia membuat nasi goreng.'],
      ['He puts rice, eggs, and onions in the pan.', 'Dia memasukkan nasi, telur, dan bawang ke wajan.'],
      ['He adds sweet soy sauce.', 'Dia menambahkan kecap manis.'],
      ['The fried rice smells so good!', 'Nasi gorengnya harum sekali!', true],
      ['We eat together at the table.', 'Kami makan bersama di meja.'],
      ['"Dad, this is the best fried rice!"', '"Ayah, ini nasi goreng terenak!"'],
    ],
    vocab: [
      ['tonight', 'malam ini', '🌃', 'adverb', [], 'Tonight Dad cooks dinner.'],
      ['fried rice', 'nasi goreng', '🍛', 'noun', [], 'He makes fried rice.'],
      ['onions', 'bawang', '🧅', 'noun', ['onion'], 'eggs, and onions'],
      ['pan', 'wajan', '🍳', 'noun', ['pans'], 'in the pan'],
      ['adds', 'menambahkan', '➕', 'verb', ['add'], 'He adds sweet soy sauce.'],
      ['best', 'terbaik / terenak', '🏆', 'adjective', [], 'the best fried rice'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Who cooks dinner tonight? (Siapa yang memasak makan malam?)', ['Mom', 'Dad', 'Grandma'], 1, '"Tonight Dad cooks dinner."'],
      ['What does Dad make? (Ayah membuat apa?)', ['Soup', 'Fried rice', 'Noodles'], 1, '"He makes fried rice."'],
      ['"Pan" artinya …', ['Wajan', 'Piring', 'Gelas'], 0, 'Pan = wajan.'],
    ],
  },
  {
    slug: 'a2-a-glass-of-water', theme: 'Food', emoji: '💧', title: 'Drink More Water', titleId: 'Minumlah Lebih Banyak Air', minutes: 3,
    sentences: [
      ['After football, Budi is thirsty.', 'Setelah bermain sepak bola, Budi haus.'],
      ['He wants a sweet soda.', 'Dia ingin minuman soda yang manis.'],
      ['"Water is better," says his mom.', '"Air putih lebih baik," kata ibunya.'],
      ['Budi drinks a big glass of water.', 'Budi minum segelas besar air putih.'],
      ['He feels fresh again.', 'Dia merasa segar lagi.', true],
      ['Our body needs water every day.', 'Tubuh kita butuh air setiap hari.'],
    ],
    vocab: [
      ['thirsty', 'haus', '🥵', 'adjective', [], 'Budi is thirsty.'],
      ['soda', 'minuman bersoda', '🥤', 'noun', [], 'a sweet soda'],
      ['better', 'lebih baik', '👍', 'adjective', ['good'], 'Water is better.'],
      ['drinks', 'minum', '🥛', 'verb', ['drink'], 'Budi drinks a big glass of water.'],
      ['fresh', 'segar', '🌿', 'adjective', [], 'He feels fresh again.'],
      ['needs', 'membutuhkan', '🙏', 'verb', ['need'], 'Our body needs water.'],
    ],
    grammar: [P.wantTo],
    quiz: [
      ['Why is Budi thirsty? (Mengapa Budi haus?)', ['After football', 'After sleeping', 'After reading'], 0, '"After football, Budi is thirsty."'],
      ['What does Budi drink? (Apa yang Budi minum?)', ['Soda', 'Water', 'Coffee'], 1, '"Budi drinks a big glass of water."'],
      ['"Thirsty" artinya …', ['Lapar', 'Haus', 'Lelah'], 1, 'Thirsty = haus, hungry = lapar.'],
    ],
  },
  {
    slug: 'a2-chicken-noodle-soup', theme: 'Food', emoji: '🍜', title: 'Hot Noodle Soup', titleId: 'Sup Mi Hangat', minutes: 3,
    sentences: [
      ['It is a cold, rainy evening.', 'Sore ini dingin dan hujan.'],
      ['Mom makes chicken noodle soup.', 'Ibu membuat sup mi ayam.'],
      ['The soup is hot. Steam comes up.', 'Supnya panas. Uapnya naik.'],
      ['I blow on my spoon. Phew, phew!', 'Aku meniup sendokku. Fuh, fuh!'],
      ['The noodles are long and soft.', 'Mi-nya panjang dan lembut.', true],
      ['The warm soup makes my tummy happy.', 'Sup hangat membuat perutku senang.'],
    ],
    vocab: [
      ['evening', 'sore / petang', '🌆', 'noun', [], 'a cold, rainy evening'],
      ['noodle', 'mi', '🍜', 'noun', ['noodles'], 'chicken noodle soup'],
      ['soup', 'sup', '🥣', 'noun', [], 'The soup is hot.'],
      ['steam', 'uap', '♨️', 'noun', [], 'Steam comes up.'],
      ['blow', 'meniup', '🌬️', 'verb', ['blows'], 'I blow on my spoon.'],
      ['tummy', 'perut', '🤰', 'noun', [], 'my tummy'],
    ],
    grammar: [P.itIs],
    quiz: [
      ['What does Mom make? (Ibu membuat apa?)', ['Fried rice', 'Chicken noodle soup', 'Cake'], 1, '"Mom makes chicken noodle soup."'],
      ['Why does Rafi blow on his spoon? (Mengapa Rafi meniup sendok?)', ['The soup is hot', 'The soup is cold', 'He is sleepy'], 0, '"The soup is hot."'],
      ['What is the weather like? (Bagaimana cuacanya?)', ['Hot and sunny', 'Cold and rainy', 'Windy and dry'], 1, '"It is a cold, rainy evening."'],
    ],
  },
  {
    slug: 'a2-healthy-snacks', theme: 'Food', emoji: '🥕', title: 'Healthy Snacks', titleId: 'Camilan Sehat', minutes: 3,
    sentences: [
      ['Rafi is hungry after school.', 'Rafi lapar setelah pulang sekolah.'],
      ['"Can I have candy, Mom?"', '"Boleh aku makan permen, Bu?"'],
      ['"How about a healthy snack?" asks Mom.', '"Bagaimana kalau camilan sehat?" tanya Ibu.'],
      ['She gives him carrot sticks and a boiled egg.', 'Ibu memberinya potongan wortel dan telur rebus.'],
      ['There is a glass of milk too.', 'Ada juga segelas susu.', true],
      ['Too much candy is bad for our teeth.', 'Terlalu banyak permen tidak baik untuk gigi kita.'],
    ],
    vocab: [
      ['hungry', 'lapar', '😋', 'adjective', [], 'Rafi is hungry.'],
      ['candy', 'permen', '🍬', 'noun', ['candies'], 'Can I have candy?'],
      ['snack', 'camilan', '🥨', 'noun', ['snacks'], 'a healthy snack'],
      ['sticks', 'potongan panjang', '🥕', 'noun', ['stick'], 'carrot sticks'],
      ['boiled', 'direbus', '🥚', 'adjective', ['boil'], 'a boiled egg'],
      ['bad for', 'tidak baik untuk', '👎', 'phrase', [], 'bad for our teeth'],
    ],
    grammar: [P.canIQuestion],
    quiz: [
      ['What does Rafi want? (Apa yang Rafi inginkan?)', ['Candy', 'Rice', 'Soup'], 0, '"Can I have candy, Mom?"'],
      ['What does Mom give him? (Ibu memberinya apa?)', ['Carrot sticks and a boiled egg', 'Ice cream', 'Chips'], 0, '"carrot sticks and a boiled egg"'],
      ['Too much candy is bad for our … (Terlalu banyak permen tidak baik untuk …)', ['Eyes', 'Teeth', 'Hair'], 1, '"bad for our teeth"'],
    ],
  },
  {
    slug: 'a2-tea-with-grandpa', theme: 'Food', emoji: '🍵', title: 'Tea with Grandpa', titleId: 'Minum Teh Bersama Kakek', minutes: 3,
    sentences: [
      ['Every afternoon, Grandpa drinks tea.', 'Setiap sore, Kakek minum teh.'],
      ['He sits on the front porch.', 'Dia duduk di teras depan.'],
      ['He eats fried bananas with his tea.', 'Dia makan pisang goreng bersama tehnya.'],
      ['I sit next to Grandpa.', 'Aku duduk di sebelah Kakek.'],
      ['I drink warm milk and eat a fried banana too.', 'Aku minum susu hangat dan makan pisang goreng juga.', true],
      ['Grandpa tells me funny stories.', 'Kakek menceritakan cerita lucu kepadaku.'],
      ['I love afternoons with Grandpa.', 'Aku suka sore hari bersama Kakek.'],
    ],
    vocab: [
      ['afternoon', 'sore hari', '🌇', 'noun', ['afternoons'], 'Every afternoon'],
      ['tea', 'teh', '🍵', 'noun', [], 'Grandpa drinks tea.'],
      ['porch', 'teras', '🏡', 'noun', [], 'on the front porch'],
      ['fried bananas', 'pisang goreng', '🍌', 'noun', ['fried banana'], 'He eats fried bananas.'],
      ['tells', 'menceritakan', '🗣️', 'verb', ['tell'], 'Grandpa tells me funny stories.'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What does Grandpa drink? (Kakek minum apa?)', ['Coffee', 'Tea', 'Juice'], 1, '"Grandpa drinks tea."'],
      ['Where does Grandpa sit? (Di mana Kakek duduk?)', ['On the front porch', 'In the kitchen', 'In the car'], 0, '"He sits on the front porch."'],
      ['What does Rafi drink? (Rafi minum apa?)', ['Warm milk', 'Tea', 'Soda'], 0, '"I drink warm milk."'],
    ],
  },
  {
    slug: 'a2-sate-night', theme: 'Food', emoji: '🍢', title: 'Satay Night', titleId: 'Malam Sate', minutes: 3,
    sentences: [
      ['Listen! "Satay, satay!"', 'Dengar! "Sate, sate!"'],
      ['The satay seller comes by at night.', 'Penjual sate lewat pada malam hari.'],
      ['Dad buys twenty sticks of chicken satay.', 'Ayah membeli dua puluh tusuk sate ayam.'],
      ['The seller grills the satay on the fire.', 'Penjual membakar sate di atas api.'],
      ['He puts peanut sauce on it.', 'Dia menuangkan bumbu kacang di atasnya.', true],
      ['We eat it with rice cakes.', 'Kami memakannya dengan lontong.'],
      ['Satay is my favorite food!', 'Sate adalah makanan favoritku!'],
    ],
    vocab: [
      ['satay', 'sate', '🍢', 'noun', [], 'chicken satay'],
      ['seller', 'penjual', '🧑‍🍳', 'noun', ['sellers'], 'The satay seller'],
      ['grills', 'membakar / memanggang', '🔥', 'verb', ['grill'], 'The seller grills the satay.'],
      ['peanut', 'kacang tanah', '🥜', 'noun', ['peanuts'], 'peanut sauce'],
      ['sauce', 'saus / bumbu', '🥣', 'noun', ['sauces'], 'peanut sauce'],
      ['favorite', 'kesukaan / favorit', '❤️', 'adjective', [], 'my favorite food'],
    ],
    grammar: [P.iLike],
    quiz: [
      ['How many sticks does Dad buy? (Ayah membeli berapa tusuk?)', ['Ten', 'Fifteen', 'Twenty'], 2, '"Dad buys twenty sticks."'],
      ['What sauce is on the satay? (Bumbu apa yang ada di sate?)', ['Peanut sauce', 'Tomato sauce', 'Chocolate sauce'], 0, '"He puts peanut sauce on it."'],
      ['"Favorite" artinya …', ['Kesukaan', 'Termahal', 'Terpanas'], 0, 'Favorite = kesukaan.'],
    ],
  },

  // ── Minggu 10: Perasaan ──────────────────────────────────────────────────
  {
    slug: 'a2-happy-and-sad', theme: 'Feelings', emoji: '😊', title: 'Happy and Sad', titleId: 'Senang dan Sedih', minutes: 3,
    sentences: [
      ['Aisyah has a red balloon.', 'Aisyah punya balon merah.'],
      ['She is happy. She smiles.', 'Dia senang. Dia tersenyum.'],
      ['Oh no! The wind blows the balloon away.', 'Oh tidak! Angin menerbangkan balonnya.'],
      ['Now Aisyah is sad. She cries.', 'Sekarang Aisyah sedih. Dia menangis.', true],
      ['Rafi gives her his blue balloon.', 'Rafi memberinya balon birunya.'],
      ['Aisyah is happy again!', 'Aisyah senang lagi!'],
    ],
    vocab: [
      ['balloon', 'balon', '🎈', 'noun', ['balloons'], 'a red balloon'],
      ['happy', 'senang', '😊', 'adjective', [], 'She is happy.'],
      ['wind', 'angin', '🌬️', 'noun', [], 'The wind blows the balloon away.'],
      ['sad', 'sedih', '😢', 'adjective', [], 'Aisyah is sad.'],
      ['cries', 'menangis', '😭', 'verb', ['cry'], 'She cries.'],
    ],
    grammar: [P.feelings],
    quiz: [
      ['Why is Aisyah sad? (Mengapa Aisyah sedih?)', ['Her balloon flies away', 'She is sick', 'She is hungry'], 0, 'Angin menerbangkan balonnya.'],
      ['What does Rafi give her? (Rafi memberinya apa?)', ['A doll', 'His blue balloon', 'A cake'], 1, '"Rafi gives her his blue balloon."'],
      ['"Cries" artinya …', ['Tertawa', 'Menangis', 'Tidur'], 1, 'Cries = menangis.'],
    ],
  },
  {
    slug: 'a2-i-am-angry', theme: 'Feelings', emoji: '😠', title: 'When I Am Angry', titleId: 'Saat Aku Marah', minutes: 3,
    sentences: [
      ['Budi takes my toy car.', 'Budi mengambil mobil-mobilanku.'],
      ['I feel angry. My face is red.', 'Aku merasa marah. Wajahku merah.'],
      ['I want to shout.', 'Aku ingin berteriak.'],
      ['But I stop and take a deep breath.', 'Tapi aku berhenti dan menarik napas dalam-dalam.', true],
      ['I count to five.', 'Aku menghitung sampai lima.'],
      ['Then I say, "Budi, please give it back."', 'Lalu aku berkata, "Budi, tolong kembalikan."'],
      ['Budi says sorry. We play together.', 'Budi minta maaf. Kami bermain bersama.'],
    ],
    vocab: [
      ['angry', 'marah', '😠', 'adjective', [], 'I feel angry.'],
      ['shout', 'berteriak', '📢', 'verb', ['shouts'], 'I want to shout.'],
      ['stop', 'berhenti', '✋', 'verb', ['stops'], 'I stop.'],
      ['deep', 'dalam', '🌊', 'adjective', [], 'a deep breath'],
      ['breath', 'napas', '😮‍💨', 'noun', [], 'take a deep breath'],
    ],
    grammar: [P.feelings],
    quiz: [
      ['What does Budi take? (Apa yang diambil Budi?)', ['A toy car', 'A book', 'A ball'], 0, '"Budi takes my toy car."'],
      ['What does Rafi do when he is angry? (Apa yang Rafi lakukan saat marah?)', ['He hits Budi', 'He takes a deep breath', 'He runs away'], 1, '"I stop and take a deep breath."'],
      ['"Angry" artinya …', ['Marah', 'Takut', 'Senang'], 0, 'Angry = marah.'],
    ],
  },
  {
    slug: 'a2-scared-of-the-dark', theme: 'Feelings', emoji: '🌑', title: 'Scared of the Dark', titleId: 'Takut Gelap', minutes: 3,
    sentences: [
      ['The lights go out.', 'Lampunya padam.'],
      ['It is very dark.', 'Gelap sekali.'],
      ['Aisyah is scared.', 'Aisyah takut.'],
      ['"Rafi, where are you?" she asks.', '"Rafi, kamu di mana?" tanyanya.'],
      ['Rafi holds her hand. "I am here."', 'Rafi memegang tangannya. "Aku di sini."', true],
      ['Dad brings a flashlight.', 'Ayah membawa senter.'],
      ['Now Aisyah is not scared anymore.', 'Sekarang Aisyah tidak takut lagi.'],
    ],
    vocab: [
      ['lights', 'lampu', '💡', 'noun', ['light'], 'The lights go out.'],
      ['dark', 'gelap', '🌑', 'adjective', [], 'It is very dark.'],
      ['scared', 'takut', '😨', 'adjective', [], 'Aisyah is scared.'],
      ['holds', 'memegang', '🤝', 'verb', ['hold'], 'Rafi holds her hand.'],
      ['flashlight', 'senter', '🔦', 'noun', ['flashlights'], 'Dad brings a flashlight.'],
    ],
    grammar: [P.feelings],
    quiz: [
      ['Why is it dark? (Mengapa gelap?)', ['The lights go out', 'It is noon', 'The TV is on'], 0, '"The lights go out."'],
      ['What does Dad bring? (Ayah membawa apa?)', ['A candle', 'A flashlight', 'A book'], 1, '"Dad brings a flashlight."'],
      ['"Scared" artinya …', ['Takut', 'Marah', 'Lapar'], 0, 'Scared = takut.'],
    ],
  },
  {
    slug: 'a2-so-tired', theme: 'Feelings', emoji: '🥱', title: 'So Tired!', titleId: 'Lelah Sekali!', minutes: 3,
    sentences: [
      ['Today Rafi has a busy day.', 'Hari ini Rafi sangat sibuk.'],
      ['He goes to school.', 'Dia pergi ke sekolah.'],
      ['He plays football in the afternoon.', 'Dia bermain sepak bola pada sore hari.'],
      ['He helps Dad wash the car.', 'Dia membantu Ayah mencuci mobil.'],
      ['At night, he yawns. "I am so tired."', 'Pada malam hari, dia menguap. "Aku lelah sekali."', true],
      ['He falls asleep on the sofa!', 'Dia tertidur di sofa!'],
      ['Dad carries him to bed.', 'Ayah menggendongnya ke tempat tidur.'],
    ],
    vocab: [
      ['busy', 'sibuk', '🏃', 'adjective', [], 'a busy day'],
      ['yawns', 'menguap', '🥱', 'verb', ['yawn'], 'he yawns'],
      ['tired', 'lelah', '😩', 'adjective', [], 'I am so tired.'],
      ['falls asleep', 'tertidur', '😴', 'verb', ['fall asleep'], 'He falls asleep on the sofa!'],
      ['carries', 'menggendong / membawa', '🤱', 'verb', ['carry'], 'Dad carries him to bed.'],
    ],
    grammar: [P.feelings],
    quiz: [
      ['What does Rafi do in the afternoon? (Apa yang Rafi lakukan sore hari?)', ['He plays football', 'He sleeps', 'He cooks'], 0, '"He plays football in the afternoon."'],
      ['Where does Rafi fall asleep? (Di mana Rafi tertidur?)', ['On the sofa', 'In the car', 'At school'], 0, '"He falls asleep on the sofa!"'],
      ['"Tired" artinya …', ['Lelah', 'Haus', 'Sedih'], 0, 'Tired = lelah.'],
    ],
  },
  {
    slug: 'a2-a-surprise-for-mom', theme: 'Feelings', emoji: '💐', title: 'A Surprise for Mom', titleId: 'Kejutan untuk Ibu', minutes: 3,
    sentences: [
      ['Today is Mother\'s Day.', 'Hari ini Hari Ibu.'],
      ['Rafi and Aisyah make a card.', 'Rafi dan Aisyah membuat kartu.'],
      ['They draw a big heart on it.', 'Mereka menggambar hati besar di kartu itu.'],
      ['They write, "We love you, Mom!"', 'Mereka menulis, "Kami sayang Ibu!"'],
      ['It is a surprise for Mom.', 'Ini kejutan untuk Ibu.'],
      ['They give Mom the card and some flowers.', 'Mereka memberi Ibu kartu dan beberapa bunga.', true],
      ['Mom is surprised.', 'Ibu terkejut.'],
      ['She hugs them. She is very happy.', 'Ibu memeluk mereka. Dia sangat senang.'],
    ],
    vocab: [
      ['surprise', 'kejutan', '🎁', 'noun', [], 'A Surprise for Mom'],
      ['card', 'kartu', '💌', 'noun', ['cards'], 'They make a card.'],
      ['heart', 'hati / bentuk hati', '❤️', 'noun', ['hearts'], 'a big heart'],
      ['surprised', 'terkejut', '😲', 'adjective', [], 'Mom is surprised.'],
      ['hugs', 'memeluk', '🤗', 'verb', ['hug'], 'She hugs them.'],
    ],
    grammar: [P.feelings],
    quiz: [
      ['What do Rafi and Aisyah make? (Apa yang dibuat Rafi dan Aisyah?)', ['A cake', 'A card', 'A kite'], 1, '"Rafi and Aisyah make a card."'],
      ['What do they draw? (Apa yang mereka gambar?)', ['A star', 'A big heart', 'A car'], 1, '"They draw a big heart on it."'],
      ['How does Mom feel? (Bagaimana perasaan Ibu?)', ['Angry', 'Very happy', 'Scared'], 1, '"She is very happy."'],
    ],
  },
  {
    slug: 'a2-feeling-nervous', theme: 'Feelings', emoji: '😬', title: 'Feeling Nervous', titleId: 'Merasa Gugup', minutes: 3,
    sentences: [
      ['Tomorrow Dina sings in front of the class.', 'Besok Dina bernyanyi di depan kelas.'],
      ['She feels nervous.', 'Dia merasa gugup.'],
      ['Her hands are cold.', 'Tangannya dingin.'],
      ['Mom says, "Practice at home first."', 'Ibu berkata, "Berlatihlah di rumah dulu."'],
      ['Dina sings for her family many times.', 'Dina bernyanyi untuk keluarganya berkali-kali.', true],
      ['The next day, she sings well.', 'Keesokan harinya, dia bernyanyi dengan baik.'],
      ['Everyone claps. Dina feels proud.', 'Semua bertepuk tangan. Dina merasa bangga.'],
    ],
    vocab: [
      ['nervous', 'gugup', '😬', 'adjective', [], 'She feels nervous.'],
      ['cold', 'dingin', '🥶', 'adjective', [], 'Her hands are cold.'],
      ['practice', 'berlatih', '🎯', 'verb', ['practices'], 'Practice at home first.'],
      ['many times', 'berkali-kali', '🔁', 'phrase', [], 'many times'],
      ['claps', 'bertepuk tangan', '👏', 'verb', ['clap'], 'Everyone claps.'],
    ],
    grammar: [P.feelings],
    quiz: [
      ['Why is Dina nervous? (Mengapa Dina gugup?)', ['She sings in front of the class', 'She is sick', 'She lost her bag'], 0, 'Dina akan bernyanyi di depan kelas.'],
      ['What does Mom tell her? (Apa kata Ibu?)', ['Practice at home first', 'Go to sleep', 'Don\'t sing'], 0, '"Practice at home first."'],
      ['How does Dina feel at the end? (Bagaimana perasaan Dina di akhir?)', ['Proud', 'Sad', 'Angry'], 0, '"Dina feels proud."'],
    ],
  },
  {
    slug: 'a2-kind-words-help', theme: 'Feelings', emoji: '🤗', title: 'Kind Words Help', titleId: 'Kata-kata Baik Menolong', minutes: 3,
    sentences: [
      ['Budi falls down in the playground.', 'Budi jatuh di taman bermain.'],
      ['His knee hurts. He is sad.', 'Lututnya sakit. Dia sedih.'],
      ['Rafi runs to him.', 'Rafi berlari menghampirinya.'],
      ['"Are you okay, Budi?"', '"Kamu baik-baik saja, Budi?"'],
      ['Rafi helps him stand up.', 'Rafi membantunya berdiri.', true],
      ['They walk to Mrs. Sari together.', 'Mereka berjalan bersama menemui Bu Sari.'],
      ['Budi smiles. "Thank you, Rafi. You are a good friend."', 'Budi tersenyum. "Terima kasih, Rafi. Kamu teman yang baik."'],
    ],
    vocab: [
      ['falls down', 'jatuh', '🤕', 'verb', ['fall down'], 'Budi falls down.'],
      ['playground', 'taman bermain', '🛝', 'noun', ['playgrounds'], 'in the playground'],
      ['hurts', 'sakit', '🩹', 'verb', ['hurt'], 'His knee hurts.'],
      ['okay', 'baik-baik saja', '👌', 'adjective', [], 'Are you okay?'],
      ['stand up', 'berdiri', '🧍', 'verb', [], 'Rafi helps him stand up.'],
    ],
    grammar: [P.howAreYou],
    quiz: [
      ['What happens to Budi? (Apa yang terjadi pada Budi?)', ['He falls down', 'He sings', 'He sleeps'], 0, '"Budi falls down in the playground."'],
      ['What hurts? (Apa yang sakit?)', ['His head', 'His knee', 'His hand'], 1, '"His knee hurts."'],
      ['Who do they walk to? (Mereka menemui siapa?)', ['Dad', 'Mrs. Sari', 'Dina'], 1, '"They walk to Mrs. Sari together."'],
    ],
  },

  // ── Minggu 11: Cuaca & Musim Hujan ───────────────────────────────────────
  {
    slug: 'a2-whats-the-weather-like', theme: 'Weather', emoji: '🌤️', title: 'What Is the Weather Like?', titleId: 'Bagaimana Cuacanya?', minutes: 3,
    sentences: [
      ['Every morning, Rafi looks out of the window.', 'Setiap pagi, Rafi melihat keluar jendela.'],
      ['On Monday, it is sunny.', 'Pada hari Senin, cuacanya cerah.'],
      ['On Tuesday, it is cloudy.', 'Pada hari Selasa, cuacanya berawan.'],
      ['On Wednesday, it is rainy.', 'Pada hari Rabu, cuacanya hujan.'],
      ['On Thursday, it is windy.', 'Pada hari Kamis, cuacanya berangin.', true],
      ['"What is the weather like today?" asks Mom.', '"Bagaimana cuaca hari ini?" tanya Ibu.'],
      ['"It is sunny again!" says Rafi.', '"Cerah lagi!" kata Rafi.'],
    ],
    vocab: [
      ['window', 'jendela', '🪟', 'noun', ['windows'], 'out of the window'],
      ['weather', 'cuaca', '🌦️', 'noun', [], 'What is the weather like?'],
      ['sunny', 'cerah', '☀️', 'adjective', [], 'it is sunny'],
      ['cloudy', 'berawan', '☁️', 'adjective', [], 'it is cloudy'],
      ['rainy', 'hujan', '🌧️', 'adjective', [], 'it is rainy'],
      ['windy', 'berangin', '🌬️', 'adjective', [], 'it is windy'],
    ],
    grammar: [P.weather],
    quiz: [
      ['What is the weather like on Wednesday? (Bagaimana cuaca pada hari Rabu?)', ['Sunny', 'Rainy', 'Windy'], 1, '"On Wednesday, it is rainy."'],
      ['"Cloudy" artinya …', ['Berawan', 'Berangin', 'Cerah'], 0, 'Cloudy = berawan.'],
      ['What is the weather like on Thursday? (Bagaimana cuaca pada hari Kamis?)', ['Windy', 'Cloudy', 'Snowy'], 0, '"On Thursday, it is windy."'],
    ],
  },
  {
    slug: 'a2-dark-clouds', theme: 'Weather', emoji: '⛈️', title: 'Dark Clouds', titleId: 'Awan Gelap', minutes: 3,
    sentences: [
      ['Rafi and Budi play in the field.', 'Rafi dan Budi bermain di lapangan.'],
      ['Suddenly, the sky is gray.', 'Tiba-tiba, langit menjadi kelabu.'],
      ['There are big, dark clouds.', 'Ada awan besar yang gelap.'],
      ['Boom! They hear thunder.', 'Duar! Mereka mendengar guntur.'],
      ['They see lightning in the sky.', 'Mereka melihat kilat di langit.', true],
      ['"Let us go home!" says Rafi.', '"Ayo pulang!" kata Rafi.'],
      ['They run home before the rain comes.', 'Mereka berlari pulang sebelum hujan turun.'],
    ],
    vocab: [
      ['field', 'lapangan', '🏟️', 'noun', ['fields'], 'in the field'],
      ['suddenly', 'tiba-tiba', '⚡', 'adverb', [], 'Suddenly, the sky is gray.'],
      ['gray', 'abu-abu / kelabu', '🩶', 'adjective', [], 'the sky is gray'],
      ['clouds', 'awan', '☁️', 'noun', ['cloud'], 'big, dark clouds'],
      ['thunder', 'guntur', '🌩️', 'noun', [], 'They hear thunder.'],
      ['lightning', 'kilat', '⚡', 'noun', [], 'They see lightning.'],
    ],
    grammar: [P.weather],
    quiz: [
      ['Where do Rafi and Budi play? (Di mana Rafi dan Budi bermain?)', ['In the field', 'At home', 'In the pool'], 0, '"Rafi and Budi play in the field."'],
      ['What do they hear? (Apa yang mereka dengar?)', ['Music', 'Thunder', 'A dog'], 1, '"They hear thunder."'],
      ['What do they do? (Apa yang mereka lakukan?)', ['They run home', 'They swim', 'They sleep'], 0, '"They run home before the rain comes."'],
    ],
  },
  {
    slug: 'a2-rainbow-after-the-rain', theme: 'Weather', emoji: '🌈', title: 'Rainbow After the Rain', titleId: 'Pelangi Setelah Hujan', minutes: 3,
    sentences: [
      ['The rain stops.', 'Hujan berhenti.'],
      ['The sun comes out again.', 'Matahari muncul lagi.'],
      ['"Look, a rainbow!" shouts Aisyah.', '"Lihat, pelangi!" seru Aisyah.'],
      ['The rainbow has seven colors.', 'Pelangi punya tujuh warna.'],
      ['Red, orange, yellow, green, blue, indigo, and violet.', 'Merah, jingga, kuning, hijau, biru, nila, dan ungu.', true],
      ['It is so beautiful.', 'Indah sekali.'],
      ['Soon the rainbow is gone.', 'Tak lama pelanginya hilang.'],
    ],
    vocab: [
      ['stops', 'berhenti', '🛑', 'verb', ['stop'], 'The rain stops.'],
      ['comes out', 'muncul / keluar', '🌤️', 'verb', ['come out'], 'The sun comes out again.'],
      ['rainbow', 'pelangi', '🌈', 'noun', ['rainbows'], 'Look, a rainbow!'],
      ['orange', 'jingga / oranye', '🟠', 'adjective', [], 'Red, orange, yellow'],
      ['violet', 'ungu', '🟣', 'adjective', [], 'indigo, and violet'],
      ['gone', 'hilang', '💨', 'adjective', [], 'the rainbow is gone'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['How many colors does a rainbow have? (Pelangi punya berapa warna?)', ['Five', 'Six', 'Seven'], 2, '"The rainbow has seven colors."'],
      ['Who sees the rainbow first? (Siapa yang pertama melihat pelangi?)', ['Rafi', 'Aisyah', 'Dad'], 1, '"Look, a rainbow!" shouts Aisyah.'],
      ['When can we see a rainbow? (Kapan kita bisa melihat pelangi?)', ['After the rain', 'At midnight', 'In the dark'], 0, 'Pelangi muncul setelah hujan saat matahari keluar.'],
    ],
  },
  {
    slug: 'a2-a-windy-day', theme: 'Weather', emoji: '🪁', title: 'A Windy Day', titleId: 'Hari yang Berangin', minutes: 3,
    sentences: [
      ['Today it is windy.', 'Hari ini berangin.'],
      ['The trees move left and right.', 'Pohon-pohon bergoyang ke kiri dan ke kanan.'],
      ['The clothes on the line fly up.', 'Pakaian di jemuran berkibar.'],
      ['Grandpa\'s hat flies off!', 'Topi Kakek terbang!'],
      ['Rafi runs and catches it.', 'Rafi berlari dan menangkapnya.', true],
      ['It is a good day to fly a kite.', 'Ini hari yang bagus untuk menerbangkan layang-layang.'],
    ],
    vocab: [
      ['move', 'bergerak', '↔️', 'verb', ['moves'], 'The trees move.'],
      ['left', 'kiri', '⬅️', 'noun', [], 'left and right'],
      ['right', 'kanan', '➡️', 'noun', [], 'left and right'],
      ['clothes line', 'tali jemuran', '👕', 'noun', ['line'], 'The clothes on the line'],
      ['catches', 'menangkap', '🫴', 'verb', ['catch'], 'Rafi runs and catches it.'],
      ['kite', 'layang-layang', '🪁', 'noun', ['kites'], 'fly a kite'],
    ],
    grammar: [P.weather],
    quiz: [
      ['What flies off? (Apa yang terbang?)', ['Grandpa\'s hat', 'Rafi\'s shoe', 'A bird'], 0, '"Grandpa\'s hat flies off!"'],
      ['Who catches it? (Siapa yang menangkapnya?)', ['Grandpa', 'Rafi', 'Aisyah'], 1, '"Rafi runs and catches it."'],
      ['A windy day is good for … (Hari berangin cocok untuk …)', ['Flying a kite', 'Swimming', 'Sleeping'], 0, '"a good day to fly a kite"'],
    ],
  },
  {
    slug: 'a2-hot-sunny-day', theme: 'Weather', emoji: '🥵', title: 'A Very Hot Day', titleId: 'Hari yang Sangat Panas', minutes: 3,
    sentences: [
      ['It is very hot today.', 'Hari ini sangat panas.'],
      ['The sun is bright.', 'Mataharinya terik.'],
      ['Rafi sweats a lot.', 'Rafi banyak berkeringat.'],
      ['He drinks cold water.', 'Dia minum air dingin.'],
      ['He sits under a big tree.', 'Dia duduk di bawah pohon besar.', true],
      ['The shade is cool.', 'Tempat teduhnya sejuk.'],
      ['Milo sleeps in the shade too.', 'Milo juga tidur di tempat teduh.'],
    ],
    vocab: [
      ['bright', 'terang / terik', '🔆', 'adjective', [], 'The sun is bright.'],
      ['sweats', 'berkeringat', '💦', 'verb', ['sweat'], 'Rafi sweats a lot.'],
      ['a lot', 'banyak', '➕', 'phrase', [], 'Rafi sweats a lot.'],
      ['shade', 'tempat teduh', '🌳', 'noun', [], 'The shade is cool.'],
      ['cool', 'sejuk', '😎', 'adjective', [], 'The shade is cool.'],
    ],
    grammar: [P.weather],
    quiz: [
      ['What is the weather like? (Bagaimana cuacanya?)', ['Very hot', 'Very cold', 'Rainy'], 0, '"It is very hot today."'],
      ['Where does Rafi sit? (Di mana Rafi duduk?)', ['Under a big tree', 'In the sun', 'On the roof'], 0, '"He sits under a big tree."'],
      ['"Shade" artinya …', ['Tempat teduh', 'Kolam', 'Matahari'], 0, 'Shade = tempat teduh.'],
    ],
  },
  {
    slug: 'a2-two-seasons-for-kids', theme: 'Weather', emoji: '🌦️', title: 'Rainy Season, Dry Season', titleId: 'Musim Hujan, Musim Kemarau', minutes: 3,
    sentences: [
      ['Indonesia has two seasons.', 'Indonesia punya dua musim.'],
      ['In the rainy season, it rains a lot.', 'Pada musim hujan, sering turun hujan.'],
      ['The rice fields are green.', 'Sawah-sawah berwarna hijau.'],
      ['In the dry season, it is hot and sunny.', 'Pada musim kemarau, cuacanya panas dan cerah.', true],
      ['The ground is dry.', 'Tanahnya kering.'],
      ['Which season do you like?', 'Kamu suka musim apa?'],
    ],
    vocab: [
      ['seasons', 'musim', '📆', 'noun', ['season'], 'two seasons'],
      ['rainy season', 'musim hujan', '🌧️', 'noun', [], 'In the rainy season'],
      ['dry season', 'musim kemarau', '☀️', 'noun', [], 'In the dry season'],
      ['green', 'hijau', '🟢', 'adjective', [], 'The rice fields are green.'],
      ['ground', 'tanah', '🟫', 'noun', [], 'The ground is dry.'],
    ],
    grammar: [P.weather],
    quiz: [
      ['How many seasons does Indonesia have? (Indonesia punya berapa musim?)', ['Two', 'Three', 'Four'], 0, '"Indonesia has two seasons."'],
      ['When is it hot and sunny? (Kapan cuacanya panas dan cerah?)', ['In the rainy season', 'In the dry season', 'At night'], 1, '"In the dry season, it is hot and sunny."'],
      ['"Dry season" artinya …', ['Musim hujan', 'Musim kemarau', 'Musim dingin'], 1, 'Dry season = musim kemarau.'],
    ],
  },
  {
    slug: 'a2-the-umbrella-friends', theme: 'Weather', emoji: '☂️', title: 'One Umbrella, Two Friends', titleId: 'Satu Payung, Dua Sahabat', minutes: 3,
    sentences: [
      ['School is over and it is raining.', 'Sekolah selesai dan hari hujan.'],
      ['Dina has an umbrella.', 'Dina punya payung.'],
      ['Tari does not have an umbrella.', 'Tari tidak punya payung.'],
      ['"Let us share!" says Dina.', '"Ayo kita berbagi!" kata Dina.'],
      ['They walk home under one umbrella.', 'Mereka berjalan pulang di bawah satu payung.', true],
      ['Their shoes are wet, but they laugh.', 'Sepatu mereka basah, tapi mereka tertawa.'],
      ['Sharing is fun!', 'Berbagi itu menyenangkan!'],
    ],
    vocab: [
      ['umbrella', 'payung', '☂️', 'noun', ['umbrellas'], 'Dina has an umbrella.'],
      ['does not', 'tidak', '🚫', 'verb', [], 'Tari does not have an umbrella.'],
      ['walk', 'berjalan', '🚶', 'verb', ['walks'], 'They walk home.'],
      ['wet', 'basah', '💧', 'adjective', [], 'Their shoes are wet.'],
      ['sharing', 'berbagi', '🤝', 'noun', ['share'], 'Sharing is fun!'],
    ],
    grammar: [P.iHave],
    quiz: [
      ['Who has an umbrella? (Siapa yang punya payung?)', ['Dina', 'Tari', 'Rafi'], 0, '"Dina has an umbrella."'],
      ['How do they walk home? (Bagaimana mereka berjalan pulang?)', ['Under one umbrella', 'In a car', 'Very fast'], 0, '"They walk home under one umbrella."'],
      ['"Wet" artinya …', ['Kering', 'Basah', 'Panas'], 1, 'Wet = basah.'],
    ],
  },

  // ── Minggu 12: Mainan & Bermain ──────────────────────────────────────────
  {
    slug: 'a2-flying-a-kite', theme: 'Toys', emoji: '🪁', title: 'Flying a Kite', titleId: 'Menerbangkan Layang-layang', minutes: 3,
    sentences: [
      ['Dad makes a kite for Rafi.', 'Ayah membuat layang-layang untuk Rafi.'],
      ['It is made of paper and bamboo.', 'Layang-layangnya terbuat dari kertas dan bambu.'],
      ['They go to the field.', 'Mereka pergi ke lapangan.'],
      ['The wind is strong.', 'Anginnya kencang.'],
      ['Rafi runs and the kite goes up.', 'Rafi berlari dan layang-layangnya naik.', true],
      ['Up, up, up! It flies high in the sky.', 'Naik, naik, naik! Ia terbang tinggi di langit.'],
      ['"I can fly a kite!" Rafi shouts.', '"Aku bisa menerbangkan layang-layang!" seru Rafi.'],
    ],
    vocab: [
      ['made of', 'terbuat dari', '🧩', 'phrase', [], 'It is made of paper and bamboo.'],
      ['paper', 'kertas', '📄', 'noun', [], 'paper and bamboo'],
      ['bamboo', 'bambu', '🎋', 'noun', [], 'paper and bamboo'],
      ['goes up', 'naik', '⬆️', 'verb', ['go up'], 'the kite goes up'],
      ['high', 'tinggi', '🔝', 'adverb', [], 'It flies high in the sky.'],
    ],
    grammar: [P.iCan],
    quiz: [
      ['Who makes the kite? (Siapa yang membuat layang-layang?)', ['Rafi', 'Dad', 'Grandpa'], 1, '"Dad makes a kite for Rafi."'],
      ['What is the kite made of? (Layang-layang terbuat dari apa?)', ['Paper and bamboo', 'Plastic and metal', 'Cloth and wood'], 0, '"It is made of paper and bamboo."'],
      ['Where do they go? (Mereka pergi ke mana?)', ['To the beach', 'To the field', 'To the mall'], 1, '"They go to the field."'],
    ],
  },
  {
    slug: 'a2-building-blocks', theme: 'Toys', emoji: '🧱', title: 'The Tall Tower', titleId: 'Menara yang Tinggi', minutes: 3,
    sentences: [
      ['Aisyah has many building blocks.', 'Aisyah punya banyak balok susun.'],
      ['They are red, blue, and yellow.', 'Warnanya merah, biru, dan kuning.'],
      ['She builds a tall tower.', 'Dia membangun menara yang tinggi.'],
      ['One block, two blocks, ten blocks!', 'Satu balok, dua balok, sepuluh balok!'],
      ['Milo jumps on the table.', 'Milo melompat ke atas meja.', true],
      ['Crash! The tower falls down.', 'Brak! Menaranya runtuh.'],
      ['Aisyah laughs. "Let us build it again!"', 'Aisyah tertawa. "Ayo kita bangun lagi!"'],
    ],
    vocab: [
      ['blocks', 'balok', '🧱', 'noun', ['block'], 'building blocks'],
      ['builds', 'membangun', '🏗️', 'verb', ['build'], 'She builds a tall tower.'],
      ['tower', 'menara', '🗼', 'noun', ['towers'], 'a tall tower'],
      ['crash', 'brak (bunyi jatuh)', '💥', 'noun', [], 'Crash!'],
      ['falls down', 'runtuh / jatuh', '⬇️', 'verb', ['fall down'], 'The tower falls down.'],
    ],
    grammar: [P.plural],
    quiz: [
      ['What does Aisyah build? (Apa yang Aisyah bangun?)', ['A house', 'A tall tower', 'A bridge'], 1, '"She builds a tall tower."'],
      ['Who makes the tower fall? (Siapa yang membuat menara runtuh?)', ['Rafi', 'Milo', 'Mom'], 1, 'Milo melompat ke atas meja.'],
      ['How does Aisyah feel? (Bagaimana perasaan Aisyah?)', ['She laughs', 'She cries', 'She is angry'], 0, '"Aisyah laughs."'],
    ],
  },
  {
    slug: 'a2-hide-and-seek', theme: 'Toys', emoji: '🙈', title: 'Hide and Seek', titleId: 'Petak Umpet', minutes: 3,
    sentences: [
      ['Let us play hide and seek!', 'Ayo bermain petak umpet!'],
      ['Budi closes his eyes and counts to ten.', 'Budi menutup mata dan menghitung sampai sepuluh.'],
      ['Rafi hides behind the tree.', 'Rafi bersembunyi di balik pohon.'],
      ['Dina hides under the slide.', 'Dina bersembunyi di bawah perosotan.'],
      ['"Ready or not, here I come!" says Budi.', '"Siap atau tidak, aku datang!" kata Budi.', true],
      ['He finds Dina first.', 'Dia menemukan Dina lebih dulu.'],
      ['Now it is Dina\'s turn to count.', 'Sekarang giliran Dina menghitung.'],
    ],
    vocab: [
      ['hide and seek', 'petak umpet', '🙈', 'noun', [], 'play hide and seek'],
      ['closes', 'menutup', '😑', 'verb', ['close'], 'Budi closes his eyes.'],
      ['hides', 'bersembunyi', '🫣', 'verb', ['hide'], 'Rafi hides behind the tree.'],
      ['slide', 'perosotan', '🛝', 'noun', ['slides'], 'under the slide'],
      ['finds', 'menemukan', '🔍', 'verb', ['find'], 'He finds Dina first.'],
      ['turn', 'giliran', '🔄', 'noun', ['turns'], 'it is Dina\'s turn'],
    ],
    grammar: [P.prepositions],
    quiz: [
      ['Who counts first? (Siapa yang menghitung pertama?)', ['Rafi', 'Budi', 'Dina'], 1, '"Budi closes his eyes and counts to ten."'],
      ['Where does Rafi hide? (Di mana Rafi bersembunyi?)', ['Behind the tree', 'Under the slide', 'In the car'], 0, '"Rafi hides behind the tree."'],
      ['Who does Budi find first? (Siapa yang ditemukan Budi pertama?)', ['Rafi', 'Dina', 'Tari'], 1, '"He finds Dina first."'],
    ],
  },
  {
    slug: 'a2-my-new-bike', theme: 'Toys', emoji: '🚲', title: 'My New Bike', titleId: 'Sepeda Baruku', minutes: 3,
    sentences: [
      ['Rafi has a new bike.', 'Rafi punya sepeda baru.'],
      ['It is green and has a bell.', 'Warnanya hijau dan ada belnya.'],
      ['Ring, ring! goes the bell.', 'Kring, kring! bunyi belnya.'],
      ['Rafi wears a helmet.', 'Rafi memakai helm.'],
      ['Dad holds the bike at first.', 'Pada awalnya Ayah memegangi sepedanya.', true],
      ['Then Dad lets go.', 'Lalu Ayah melepaskannya.'],
      ['Rafi rides by himself! "I can do it!"', 'Rafi bersepeda sendiri! "Aku bisa!"'],
    ],
    vocab: [
      ['bike', 'sepeda', '🚲', 'noun', ['bikes'], 'a new bike'],
      ['helmet', 'helm', '⛑️', 'noun', ['helmets'], 'Rafi wears a helmet.'],
      ['at first', 'pada awalnya', '1️⃣', 'phrase', [], 'Dad holds the bike at first.'],
      ['lets go', 'melepaskan', '👐', 'verb', ['let go'], 'Dad lets go.'],
      ['rides', 'mengendarai', '🚴', 'verb', ['ride'], 'Rafi rides by himself!'],
    ],
    grammar: [P.iCan],
    quiz: [
      ['What color is the bike? (Apa warna sepedanya?)', ['Red', 'Green', 'Blue'], 1, '"It is green."'],
      ['What does Rafi wear? (Apa yang Rafi pakai?)', ['A helmet', 'A raincoat', 'A tie'], 0, '"Rafi wears a helmet."'],
      ['"Rafi rides by himself" artinya Rafi bersepeda …', ['Bersama Ayah', 'Sendiri', 'Dengan Dina'], 1, 'By himself = sendiri.'],
    ],
  },
  {
    slug: 'a2-the-ball-game', theme: 'Toys', emoji: '⚽', title: 'Kick the Ball!', titleId: 'Tendang Bolanya!', minutes: 3,
    sentences: [
      ['Rafi and his friends play football.', 'Rafi dan teman-temannya bermain sepak bola.'],
      ['Budi kicks the ball to Rafi.', 'Budi menendang bola ke Rafi.'],
      ['Rafi runs fast with the ball.', 'Rafi berlari cepat membawa bola.'],
      ['He kicks the ball hard.', 'Dia menendang bola dengan kuat.'],
      ['Goal! The ball is in the net.', 'Gol! Bolanya masuk ke jaring.', true],
      ['Everyone cheers. "Yay!"', 'Semua bersorak. "Hore!"'],
    ],
    vocab: [
      ['football', 'sepak bola', '⚽', 'noun', [], 'play football'],
      ['kicks', 'menendang', '🦵', 'verb', ['kick'], 'Budi kicks the ball.'],
      ['ball', 'bola', '⚽', 'noun', ['balls'], 'the ball'],
      ['hard', 'kuat / keras', '💥', 'adverb', [], 'He kicks the ball hard.'],
      ['goal', 'gol', '🥅', 'noun', ['goals'], 'Goal!'],
      ['cheers', 'bersorak', '🙌', 'verb', ['cheer'], 'Everyone cheers.'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Who kicks the ball to Rafi? (Siapa yang menendang bola ke Rafi?)', ['Dina', 'Budi', 'Tari'], 1, '"Budi kicks the ball to Rafi."'],
      ['Where is the ball at the end? (Di mana bola pada akhirnya?)', ['In the net', 'On the roof', 'In the river'], 0, '"The ball is in the net."'],
      ['"Cheers" artinya …', ['Menangis', 'Bersorak', 'Tidur'], 1, 'Cheers = bersorak.'],
    ],
  },
  {
    slug: 'a2-dolls-tea-party', theme: 'Toys', emoji: '🫖', title: 'A Tea Party for Dolls', titleId: 'Pesta Teh Boneka', minutes: 3,
    sentences: [
      ['Aisyah has three dolls.', 'Aisyah punya tiga boneka.'],
      ['Today they have a tea party.', 'Hari ini mereka mengadakan pesta teh.'],
      ['Aisyah puts small cups on the mat.', 'Aisyah menaruh cangkir kecil di atas tikar.'],
      ['She pours pretend tea for each doll.', 'Dia menuangkan teh pura-pura untuk setiap boneka.'],
      ['"Would you like some cake?" she asks.', '"Mau kue?" tanyanya.', true],
      ['Milo comes to the party too.', 'Milo juga datang ke pesta.'],
      ['It is a fun party!', 'Pestanya menyenangkan!'],
    ],
    vocab: [
      ['party', 'pesta', '🎉', 'noun', ['parties'], 'a tea party'],
      ['mat', 'tikar / alas', '🟫', 'noun', ['mats'], 'on the mat'],
      ['pours', 'menuangkan', '🫖', 'verb', ['pour'], 'She pours tea.'],
      ['pretend', 'pura-pura', '🎭', 'adjective', [], 'pretend tea'],
      ['each', 'setiap', '☝️', 'determiner', [], 'for each doll'],
      ['would like', 'ingin / mau (sopan)', '🙂', 'verb', ['would you like'], 'Would you like some cake?'],
    ],
    grammar: [P.politeWords],
    quiz: [
      ['How many dolls does Aisyah have? (Aisyah punya berapa boneka?)', ['Two', 'Three', 'Four'], 1, '"Aisyah has three dolls."'],
      ['What kind of party is it? (Pesta apa itu?)', ['A tea party', 'A birthday party', 'A pool party'], 0, '"they have a tea party"'],
      ['Who comes to the party too? (Siapa yang juga datang?)', ['Milo', 'Budi', 'Grandpa'], 0, '"Milo comes to the party too."'],
    ],
  },
  {
    slug: 'a2-sharing-toys', theme: 'Toys', emoji: '🤝', title: 'Sharing Toys', titleId: 'Berbagi Mainan', minutes: 3,
    sentences: [
      ['Budi visits Rafi\'s house.', 'Budi berkunjung ke rumah Rafi.'],
      ['Rafi has a toy train.', 'Rafi punya kereta mainan.'],
      ['Budi wants to play with it too.', 'Budi juga ingin memainkannya.'],
      ['At first, Rafi says, "No, it is mine!"', 'Awalnya Rafi berkata, "Tidak, ini punyaku!"'],
      ['Then he sees Budi\'s sad face.', 'Lalu dia melihat wajah Budi yang sedih.', true],
      ['"Okay, let us play together," says Rafi.', '"Baiklah, ayo kita main bersama," kata Rafi.'],
      ['Playing together is more fun!', 'Bermain bersama lebih menyenangkan!'],
    ],
    vocab: [
      ['visits', 'mengunjungi', '🚪', 'verb', ['visit'], 'Budi visits Rafi\'s house.'],
      ['train', 'kereta', '🚂', 'noun', ['trains'], 'a toy train'],
      ['mine', 'milikku', '🙋', 'pronoun', [], 'it is mine!'],
      ['face', 'wajah', '😟', 'noun', ['faces'], 'Budi\'s sad face'],
      ['more fun', 'lebih menyenangkan', '🎉', 'phrase', [], 'Playing together is more fun!'],
    ],
    grammar: [P.wantTo],
    quiz: [
      ['What toy does Rafi have? (Mainan apa yang Rafi punya?)', ['A toy train', 'A doll', 'A kite'], 0, '"Rafi has a toy train."'],
      ['What does Rafi say at first? (Apa kata Rafi pada awalnya?)', ['No, it is mine!', 'Here you are', 'Let us go'], 0, '"No, it is mine!"'],
      ['What is the lesson? (Apa pesannya?)', ['Playing together is more fun', 'Never share', 'Toys are bad'], 0, '"Playing together is more fun!"'],
    ],
  },

  // ── Minggu 13: Nama-nama Hari ────────────────────────────────────────────
  {
    slug: 'a2-monday-flag-ceremony', theme: 'Days', emoji: '🇮🇩', title: 'Monday Morning', titleId: 'Senin Pagi', minutes: 3,
    sentences: [
      ['Today is Monday.', 'Hari ini hari Senin.'],
      ['Every Monday, we have a flag ceremony.', 'Setiap Senin, kami mengadakan upacara bendera.'],
      ['We stand in lines in the schoolyard.', 'Kami berdiri berbaris di halaman sekolah.'],
      ['The red and white flag goes up.', 'Bendera merah putih dinaikkan.'],
      ['We sing "Indonesia Raya".', 'Kami menyanyikan "Indonesia Raya".', true],
      ['We stand still and respect the flag.', 'Kami berdiri diam dan menghormati bendera.'],
    ],
    vocab: [
      ['Monday', 'Senin', '1️⃣', 'noun', [], 'Today is Monday.'],
      ['flag', 'bendera', '🇮🇩', 'noun', ['flags'], 'a flag ceremony'],
      ['ceremony', 'upacara', '🎖️', 'noun', [], 'a flag ceremony'],
      ['schoolyard', 'halaman sekolah', '🏫', 'noun', [], 'in the schoolyard'],
      ['still', 'diam / tidak bergerak', '🧍', 'adjective', [], 'We stand still.'],
      ['respect', 'menghormati', '🫡', 'verb', ['respects'], 'respect the flag'],
    ],
    grammar: [P.daysOfWeek],
    quiz: [
      ['What happens every Monday? (Apa yang ada setiap Senin?)', ['A flag ceremony', 'A party', 'A test'], 0, '"Every Monday, we have a flag ceremony."'],
      ['What song do they sing? (Lagu apa yang mereka nyanyikan?)', ['Indonesia Raya', 'Happy Birthday', 'Twinkle Twinkle'], 0, '"We sing Indonesia Raya."'],
      ['"Flag" artinya …', ['Bendera', 'Bunga', 'Buku'], 0, 'Flag = bendera.'],
    ],
  },
  {
    slug: 'a2-tuesday-library-day', theme: 'Days', emoji: '📚', title: 'Tuesday Is Library Day', titleId: 'Selasa Hari Perpustakaan', minutes: 3,
    sentences: [
      ['On Tuesday, our class goes to the library.', 'Pada hari Selasa, kelas kami pergi ke perpustakaan.'],
      ['The library is quiet.', 'Perpustakaannya tenang.'],
      ['There are many books on the shelves.', 'Ada banyak buku di rak-rak.'],
      ['Rafi chooses a book about dinosaurs.', 'Rafi memilih buku tentang dinosaurus.'],
      ['Dina chooses a book about princesses.', 'Dina memilih buku tentang putri raja.', true],
      ['They borrow the books for one week.', 'Mereka meminjam buku itu selama satu minggu.'],
    ],
    vocab: [
      ['Tuesday', 'Selasa', '2️⃣', 'noun', [], 'On Tuesday'],
      ['library', 'perpustakaan', '📚', 'noun', ['libraries'], 'to the library'],
      ['quiet', 'tenang / sunyi', '🤫', 'adjective', [], 'The library is quiet.'],
      ['chooses', 'memilih', '👆', 'verb', ['choose'], 'Rafi chooses a book.'],
      ['dinosaurs', 'dinosaurus', '🦕', 'noun', ['dinosaur'], 'a book about dinosaurs'],
      ['week', 'minggu (7 hari)', '📅', 'noun', ['weeks'], 'for one week'],
    ],
    grammar: [P.daysOfWeek],
    quiz: [
      ['When does the class go to the library? (Kapan kelas pergi ke perpustakaan?)', ['On Monday', 'On Tuesday', 'On Friday'], 1, '"On Tuesday, our class goes to the library."'],
      ['What is Rafi\'s book about? (Buku Rafi tentang apa?)', ['Dinosaurs', 'Princesses', 'Cars'], 0, '"a book about dinosaurs"'],
      ['How long can they borrow the books? (Berapa lama mereka boleh meminjam?)', ['One day', 'One week', 'One year'], 1, '"for one week"'],
    ],
  },
  {
    slug: 'a2-wednesday-swimming', theme: 'Days', emoji: '🏊', title: 'Swimming on Wednesday', titleId: 'Berenang pada Hari Rabu', minutes: 3,
    sentences: [
      ['On Wednesday, we have a swimming lesson.', 'Pada hari Rabu, kami ada pelajaran renang.'],
      ['We go to the pool by bus.', 'Kami pergi ke kolam renang naik bus.'],
      ['The coach says, "Kick your legs!"', 'Pelatih berkata, "Gerakkan kakimu!"'],
      ['Rafi kicks and moves his arms.', 'Rafi menendang dan menggerakkan lengannya.'],
      ['Splash! He can swim a little.', 'Byur! Dia bisa sedikit berenang.', true],
      ['Swimming is good exercise.', 'Berenang adalah olahraga yang baik.'],
    ],
    vocab: [
      ['Wednesday', 'Rabu', '3️⃣', 'noun', [], 'On Wednesday'],
      ['lesson', 'pelajaran', '📘', 'noun', ['lessons'], 'a swimming lesson'],
      ['pool', 'kolam renang', '🏊', 'noun', ['pools'], 'to the pool'],
      ['coach', 'pelatih', '🧑‍🏫', 'noun', ['coaches'], 'The coach says'],
      ['arms', 'lengan', '💪', 'noun', ['arm'], 'moves his arms'],
      ['exercise', 'olahraga', '🏋️', 'noun', [], 'good exercise'],
    ],
    grammar: [P.daysOfWeek],
    quiz: [
      ['When is the swimming lesson? (Kapan pelajaran renang?)', ['On Wednesday', 'On Thursday', 'On Sunday'], 0, '"On Wednesday, we have a swimming lesson."'],
      ['How do they go to the pool? (Bagaimana mereka pergi ke kolam?)', ['By bus', 'By train', 'On foot'], 0, '"We go to the pool by bus."'],
      ['"Coach" artinya …', ['Pelatih', 'Kepala sekolah', 'Sopir'], 0, 'Coach = pelatih.'],
    ],
  },
  {
    slug: 'a2-thursday-cooking-class', theme: 'Days', emoji: '🧁', title: 'Thursday Cooking Class', titleId: 'Kelas Memasak Hari Kamis', minutes: 3,
    sentences: [
      ['On Thursday, Mrs. Sari has a surprise.', 'Pada hari Kamis, Bu Sari punya kejutan.'],
      ['"Today we make sandwiches!"', '"Hari ini kita membuat roti lapis!"'],
      ['We wash our hands first.', 'Kami mencuci tangan dulu.'],
      ['We put cheese and tomato on the bread.', 'Kami menaruh keju dan tomat di atas roti.'],
      ['Then we put another bread on top.', 'Lalu kami menaruh roti lain di atasnya.', true],
      ['We eat our sandwiches together.', 'Kami makan roti lapis kami bersama.'],
      ['Thursday is fun!', 'Hari Kamis menyenangkan!'],
    ],
    vocab: [
      ['Thursday', 'Kamis', '4️⃣', 'noun', [], 'On Thursday'],
      ['sandwiches', 'roti lapis', '🥪', 'noun', ['sandwich'], 'we make sandwiches'],
      ['cheese', 'keju', '🧀', 'noun', [], 'cheese and tomato'],
      ['tomato', 'tomat', '🍅', 'noun', ['tomatoes'], 'cheese and tomato'],
      ['bread', 'roti', '🍞', 'noun', [], 'on the bread'],
      ['on top', 'di atasnya', '⬆️', 'phrase', [], 'another bread on top'],
    ],
    grammar: [P.daysOfWeek],
    quiz: [
      ['What do they make? (Apa yang mereka buat?)', ['Sandwiches', 'Cakes', 'Soup'], 0, '"Today we make sandwiches!"'],
      ['What do they do first? (Apa yang mereka lakukan pertama?)', ['Wash their hands', 'Eat the bread', 'Go home'], 0, '"We wash our hands first."'],
      ['"Cheese" artinya …', ['Keju', 'Mentega', 'Selai'], 0, 'Cheese = keju.'],
    ],
  },
  {
    slug: 'a2-friday-jumat-prayer', theme: 'Days', emoji: '🕌', title: 'Friday with Dad', titleId: 'Jumat Bersama Ayah', minutes: 3,
    sentences: [
      ['On Friday, school ends early.', 'Pada hari Jumat, sekolah selesai lebih awal.'],
      ['Rafi goes home and takes a bath.', 'Rafi pulang dan mandi.'],
      ['He wears a white shirt and a cap.', 'Dia memakai baju putih dan peci.'],
      ['He walks to the mosque with Dad.', 'Dia berjalan ke masjid bersama Ayah.'],
      ['Many people pray together.', 'Banyak orang salat bersama.', true],
      ['After that, they buy ice cream.', 'Setelah itu, mereka membeli es krim.'],
      ['Rafi loves Fridays!', 'Rafi suka hari Jumat!'],
    ],
    vocab: [
      ['Friday', 'Jumat', '5️⃣', 'noun', ['Fridays'], 'On Friday'],
      ['ends', 'berakhir / selesai', '🏁', 'verb', ['end'], 'school ends early'],
      ['takes a bath', 'mandi', '🛁', 'verb', ['take a bath'], 'takes a bath'],
      ['mosque', 'masjid', '🕌', 'noun', ['mosques'], 'to the mosque'],
      ['pray', 'salat / berdoa', '🤲', 'verb', ['prays'], 'Many people pray together.'],
      ['ice cream', 'es krim', '🍦', 'noun', [], 'they buy ice cream'],
    ],
    grammar: [P.daysOfWeek],
    quiz: [
      ['Where do Rafi and Dad go? (Rafi dan Ayah pergi ke mana?)', ['To the mosque', 'To the market', 'To the zoo'], 0, '"He walks to the mosque with Dad."'],
      ['What color is Rafi\'s shirt? (Apa warna baju Rafi?)', ['White', 'Red', 'Black'], 0, '"He wears a white shirt."'],
      ['What do they buy after that? (Apa yang mereka beli setelah itu?)', ['Ice cream', 'A book', 'Shoes'], 0, '"they buy ice cream"'],
    ],
  },
  {
    slug: 'a2-saturday-at-the-farm-market', theme: 'Days', emoji: '🧺', title: 'Saturday Morning', titleId: 'Sabtu Pagi', minutes: 3,
    sentences: [
      ['On Saturday, there is no school.', 'Pada hari Sabtu, tidak ada sekolah.'],
      ['Rafi wakes up late.', 'Rafi bangun siang.'],
      ['He rides his bike around the village.', 'Dia bersepeda keliling desa.'],
      ['He sees Mr. Joni washing his car.', 'Dia melihat Pak Joni sedang mencuci mobil.'],
      ['He waves to Mrs. Ani at her shop.', 'Dia melambai kepada Bu Ani di tokonya.', true],
      ['In the afternoon, he reads comics.', 'Pada siang hari, dia membaca komik.'],
      ['Saturday is a relaxing day.', 'Hari Sabtu adalah hari yang santai.'],
    ],
    vocab: [
      ['Saturday', 'Sabtu', '6️⃣', 'noun', [], 'On Saturday'],
      ['late', 'terlambat / siang', '⏰', 'adverb', [], 'Rafi wakes up late.'],
      ['around', 'berkeliling', '🔄', 'preposition', [], 'around the village'],
      ['comics', 'komik', '📖', 'noun', ['comic'], 'he reads comics'],
      ['relaxing', 'santai', '😌', 'adjective', [], 'a relaxing day'],
    ],
    grammar: [P.daysOfWeek],
    quiz: [
      ['Is there school on Saturday? (Apakah ada sekolah hari Sabtu?)', ['Yes', 'No', 'Only in the morning'], 1, '"On Saturday, there is no school."'],
      ['What does Rafi read? (Rafi membaca apa?)', ['Comics', 'The newspaper', 'A letter'], 0, '"he reads comics"'],
      ['Who is washing his car? (Siapa yang mencuci mobil?)', ['Mr. Joni', 'Dad', 'Budi'], 0, '"Mr. Joni washing his car"'],
    ],
  },
  {
    slug: 'a2-sunday-family-day', theme: 'Days', emoji: '👨‍👩‍👧‍👦', title: 'Sunday Is Family Day', titleId: 'Minggu Hari Keluarga', minutes: 3,
    sentences: [
      ['On Sunday, the whole family is at home.', 'Pada hari Minggu, seluruh keluarga ada di rumah.'],
      ['In the morning, we jog in the park.', 'Pada pagi hari, kami jogging di taman.'],
      ['Then we eat chicken porridge.', 'Lalu kami makan bubur ayam.'],
      ['In the afternoon, we visit Grandma.', 'Pada sore hari, kami mengunjungi Nenek.'],
      ['At night, we play board games.', 'Pada malam hari, kami bermain permainan papan.', true],
      ['I love Sundays with my family.', 'Aku suka hari Minggu bersama keluargaku.'],
    ],
    vocab: [
      ['Sunday', 'Minggu', '7️⃣', 'noun', ['Sundays'], 'On Sunday'],
      ['whole', 'seluruh', '🌐', 'adjective', [], 'the whole family'],
      ['jog', 'jogging / lari santai', '🏃', 'verb', ['jogs'], 'we jog in the park'],
      ['porridge', 'bubur', '🥣', 'noun', [], 'chicken porridge'],
      ['board games', 'permainan papan', '🎲', 'noun', ['board game'], 'we play board games'],
    ],
    grammar: [P.daysOfWeek],
    quiz: [
      ['What do they eat on Sunday morning? (Apa yang mereka makan Minggu pagi?)', ['Chicken porridge', 'Satay', 'Pizza'], 0, '"we eat chicken porridge"'],
      ['Who do they visit in the afternoon? (Siapa yang mereka kunjungi sore hari?)', ['Grandma', 'Mrs. Sari', 'Uncle Joko'], 0, '"we visit Grandma"'],
      ['How many days are there in a week? (Ada berapa hari dalam seminggu?)', ['Five', 'Six', 'Seven'], 2, 'Monday sampai Sunday = tujuh hari.'],
    ],
  },

  // ── Minggu 14: Sedang apa? (-ing) ────────────────────────────────────────
  {
    slug: 'a2-what-are-you-doing', theme: 'Daily Life', emoji: '❓', title: 'What Are You Doing?', titleId: 'Kamu Sedang Apa?', minutes: 3,
    sentences: [
      ['Mom calls Rafi on the phone.', 'Ibu menelepon Rafi.'],
      ['"Rafi, what are you doing?"', '"Rafi, kamu sedang apa?"'],
      ['"I am doing my homework, Mom."', '"Aku sedang mengerjakan PR, Bu."'],
      ['"What is Aisyah doing?"', '"Aisyah sedang apa?"'],
      ['"She is drawing a cat."', '"Dia sedang menggambar kucing."', true],
      ['"And Milo?"', '"Lalu Milo?"'],
      ['"Milo is sleeping, of course!"', '"Milo sedang tidur, tentu saja!"'],
    ],
    vocab: [
      ['calls', 'menelepon / memanggil', '📞', 'verb', ['call'], 'Mom calls Rafi.'],
      ['phone', 'telepon', '📱', 'noun', ['phones'], 'on the phone'],
      ['doing', 'sedang melakukan', '🛠️', 'verb', ['do'], 'What are you doing?'],
      ['drawing', 'sedang menggambar', '🖍️', 'verb', ['draw'], 'She is drawing a cat.'],
      ['of course', 'tentu saja', '✔️', 'phrase', [], 'of course!'],
    ],
    grammar: [P.ingNow],
    quiz: [
      ['What is Rafi doing? (Rafi sedang apa?)', ['His homework', 'Sleeping', 'Cooking'], 0, '"I am doing my homework, Mom."'],
      ['What is Aisyah drawing? (Aisyah sedang menggambar apa?)', ['A dog', 'A cat', 'A house'], 1, '"She is drawing a cat."'],
      ['"Milo is sleeping" artinya Milo …', ['Akan tidur', 'Sedang tidur', 'Suka tidur'], 1, 'Is sleeping = sedang tidur.'],
    ],
  },
  {
    slug: 'a2-at-the-park-now', theme: 'Daily Life', emoji: '🌳', title: 'Busy in the Park', titleId: 'Ramai di Taman', minutes: 3,
    sentences: [
      ['Look at the park!', 'Lihat taman itu!'],
      ['Some children are running.', 'Beberapa anak sedang berlari.'],
      ['A girl is riding a bike.', 'Seorang anak perempuan sedang bersepeda.'],
      ['Two boys are playing football.', 'Dua anak laki-laki sedang bermain sepak bola.'],
      ['A grandpa is reading under a tree.', 'Seorang kakek sedang membaca di bawah pohon.', true],
      ['Birds are singing.', 'Burung-burung sedang berkicau.'],
      ['Everyone is enjoying the sunny day.', 'Semua orang sedang menikmati hari yang cerah.'],
    ],
    vocab: [
      ['park', 'taman', '🌳', 'noun', ['parks'], 'Look at the park!'],
      ['running', 'sedang berlari', '🏃', 'verb', ['run'], 'Some children are running.'],
      ['riding', 'sedang mengendarai', '🚴', 'verb', ['ride'], 'A girl is riding a bike.'],
      ['reading', 'sedang membaca', '📖', 'verb', ['read'], 'A grandpa is reading.'],
      ['enjoying', 'sedang menikmati', '😊', 'verb', ['enjoy'], 'Everyone is enjoying the sunny day.'],
    ],
    grammar: [P.ingNow],
    quiz: [
      ['What is the girl doing? (Anak perempuan itu sedang apa?)', ['Riding a bike', 'Swimming', 'Sleeping'], 0, '"A girl is riding a bike."'],
      ['Where is the grandpa reading? (Di mana kakek itu membaca?)', ['Under a tree', 'In the pool', 'On the bike'], 0, '"A grandpa is reading under a tree."'],
      ['What are the birds doing? (Burung-burung sedang apa?)', ['Singing', 'Swimming', 'Eating rice'], 0, '"Birds are singing."'],
    ],
  },
  {
    slug: 'a2-mom-is-cooking', theme: 'Daily Life', emoji: '👩‍🍳', title: 'Everyone Is Helping', titleId: 'Semua Membantu', minutes: 3,
    sentences: [
      ['Grandma is coming for lunch.', 'Nenek akan datang untuk makan siang.'],
      ['Mom is cooking chicken curry.', 'Ibu sedang memasak kari ayam.'],
      ['Dad is cleaning the table.', 'Ayah sedang membersihkan meja.'],
      ['Rafi is putting the plates on the table.', 'Rafi sedang menaruh piring di meja.'],
      ['Aisyah is putting flowers in a vase.', 'Aisyah sedang menaruh bunga di vas.', true],
      ['Ding dong! Grandma is here!', 'Ting tong! Nenek sudah datang!'],
    ],
    vocab: [
      ['lunch', 'makan siang', '🍱', 'noun', [], 'for lunch'],
      ['cooking', 'sedang memasak', '🍳', 'verb', ['cook'], 'Mom is cooking.'],
      ['curry', 'kari', '🍛', 'noun', [], 'chicken curry'],
      ['cleaning', 'sedang membersihkan', '🧽', 'verb', ['clean'], 'Dad is cleaning the table.'],
      ['vase', 'vas bunga', '🏺', 'noun', ['vases'], 'in a vase'],
    ],
    grammar: [P.ingNow],
    quiz: [
      ['Who is coming for lunch? (Siapa yang datang untuk makan siang?)', ['Grandma', 'Mrs. Sari', 'Budi'], 0, '"Grandma is coming for lunch."'],
      ['What is Mom cooking? (Ibu sedang memasak apa?)', ['Fried rice', 'Chicken curry', 'Soup'], 1, '"Mom is cooking chicken curry."'],
      ['What is Aisyah doing? (Aisyah sedang apa?)', ['Putting flowers in a vase', 'Sleeping', 'Washing the car'], 0, '"Aisyah is putting flowers in a vase."'],
    ],
  },
  {
    slug: 'a2-milo-is-chasing', theme: 'Animals', emoji: '🐈', title: 'Milo Is Chasing a Butterfly', titleId: 'Milo Mengejar Kupu-kupu', minutes: 3,
    sentences: [
      ['Milo is in the garden.', 'Milo ada di kebun.'],
      ['A yellow butterfly is flying near him.', 'Seekor kupu-kupu kuning sedang terbang di dekatnya.'],
      ['Milo is watching it.', 'Milo sedang mengamatinya.'],
      ['Now Milo is chasing the butterfly!', 'Sekarang Milo sedang mengejar kupu-kupu itu!'],
      ['He is jumping!', 'Dia sedang melompat!'],
      ['The butterfly is flying higher.', 'Kupu-kupu itu terbang lebih tinggi.', true],
      ['Milo is sitting on the grass.', 'Milo sedang duduk di rumput.'],
      ['He is looking at the sky. Goodbye, butterfly!', 'Dia sedang menatap langit. Dadah, kupu-kupu!'],
    ],
    vocab: [
      ['chasing', 'sedang mengejar', '🐈', 'verb', ['chase'], 'Milo Is Chasing a Butterfly'],
      ['near', 'dekat', '📍', 'preposition', [], 'near him'],
      ['watching', 'sedang mengamati', '👀', 'verb', ['watch'], 'Milo is watching it.'],
      ['jumping', 'sedang melompat', '🤸', 'verb', ['jump'], 'He is jumping!'],
      ['higher', 'lebih tinggi', '⬆️', 'adverb', ['high'], 'flying higher'],
    ],
    grammar: [P.ingNow],
    quiz: [
      ['What color is the butterfly? (Apa warna kupu-kupunya?)', ['Yellow', 'Blue', 'White'], 0, '"A yellow butterfly"'],
      ['Does Milo catch the butterfly? (Apakah Milo menangkap kupu-kupu?)', ['Yes', 'No'], 1, 'Kupu-kupu terbang lebih tinggi, Milo duduk di rumput.'],
      ['"Is jumping" artinya …', ['Sedang melompat', 'Akan berlari', 'Sudah tidur'], 0, 'Is jumping = sedang melompat.'],
    ],
  },
  {
    slug: 'a2-on-the-video-call', theme: 'Family', emoji: '📱', title: 'A Video Call with Grandma', titleId: 'Panggilan Video dengan Nenek', minutes: 3,
    sentences: [
      ['Grandma lives in a village far away.', 'Nenek tinggal di desa yang jauh.'],
      ['Today we make a video call.', 'Hari ini kami melakukan panggilan video.'],
      ['"Hello, Grandma! I can see you!"', '"Halo, Nek! Aku bisa melihat Nenek!"'],
      ['Grandma is sitting in her garden.', 'Nenek sedang duduk di kebunnya.'],
      ['Grandpa is feeding the chickens.', 'Kakek sedang memberi makan ayam.', true],
      ['"We miss you," says Grandma.', '"Kami rindu kalian," kata Nenek.'],
      ['"We miss you too! See you soon!"', '"Kami juga rindu! Sampai jumpa!"'],
    ],
    vocab: [
      ['far away', 'jauh', '🗺️', 'phrase', [], 'a village far away'],
      ['video call', 'panggilan video', '📱', 'noun', [], 'a video call'],
      ['sitting', 'sedang duduk', '🪑', 'verb', ['sit'], 'Grandma is sitting.'],
      ['feeding', 'sedang memberi makan', '🐔', 'verb', ['feed'], 'Grandpa is feeding the chickens.'],
      ['miss', 'rindu', '💞', 'verb', ['misses'], 'We miss you.'],
    ],
    grammar: [P.ingNow],
    quiz: [
      ['Where does Grandma live? (Di mana Nenek tinggal?)', ['In a village far away', 'Next door', 'In Bandung'], 0, '"Grandma lives in a village far away."'],
      ['What is Grandpa doing? (Kakek sedang apa?)', ['Feeding the chickens', 'Cooking', 'Sleeping'], 0, '"Grandpa is feeding the chickens."'],
      ['"We miss you" artinya …', ['Kami rindu kalian', 'Kami pergi', 'Kami lapar'], 0, 'Miss = rindu.'],
    ],
  },
  {
    slug: 'a2-whats-the-noise', theme: 'Daily Life', emoji: '🔊', title: 'What Is That Noise?', titleId: 'Suara Apa Itu?', minutes: 3,
    sentences: [
      ['Rafi is reading in his room.', 'Rafi sedang membaca di kamarnya.'],
      ['Bang, bang! What is that noise?', 'Duk, duk! Suara apa itu?'],
      ['He goes to the yard.', 'Dia pergi ke halaman.'],
      ['Dad is fixing the fence.', 'Ayah sedang memperbaiki pagar.'],
      ['He is using a hammer and nails.', 'Dia sedang memakai palu dan paku.', true],
      ['"Can I help, Dad?"', '"Boleh aku bantu, Yah?"'],
      ['"Yes! Please hold this board."', '"Boleh! Tolong pegang papan ini."'],
    ],
    vocab: [
      ['noise', 'suara / bunyi', '🔊', 'noun', ['noises'], 'What is that noise?'],
      ['fixing', 'sedang memperbaiki', '🔧', 'verb', ['fix'], 'Dad is fixing the fence.'],
      ['fence', 'pagar', '🚧', 'noun', ['fences'], 'the fence'],
      ['hammer', 'palu', '🔨', 'noun', ['hammers'], 'a hammer and nails'],
      ['nails', 'paku', '📌', 'noun', ['nail'], 'a hammer and nails'],
      ['board', 'papan', '🪵', 'noun', ['boards'], 'hold this board'],
    ],
    grammar: [P.ingNow],
    quiz: [
      ['What is Dad fixing? (Ayah sedang memperbaiki apa?)', ['The car', 'The fence', 'The TV'], 1, '"Dad is fixing the fence."'],
      ['What is Dad using? (Ayah memakai apa?)', ['A hammer and nails', 'A spoon', 'A brush'], 0, '"a hammer and nails"'],
      ['What does Rafi hold? (Apa yang Rafi pegang?)', ['A board', 'A cat', 'A cup'], 0, '"Please hold this board."'],
    ],
  },
  {
    slug: 'a2-a-busy-street', theme: 'Places', emoji: '🚦', title: 'A Busy Street', titleId: 'Jalan yang Ramai', minutes: 3,
    sentences: [
      ['Rafi and Mom are waiting at the traffic light.', 'Rafi dan Ibu sedang menunggu di lampu lalu lintas.'],
      ['Cars and motorbikes are stopping.', 'Mobil dan motor sedang berhenti.'],
      ['A policeman is helping people cross.', 'Seorang polisi sedang membantu orang menyeberang.'],
      ['A man is selling newspapers.', 'Seorang pria sedang menjual koran.'],
      ['The light is green for walkers now.', 'Sekarang lampu hijau untuk pejalan kaki.', true],
      ['Rafi holds Mom\'s hand. They cross the street.', 'Rafi memegang tangan Ibu. Mereka menyeberang jalan.'],
    ],
    vocab: [
      ['waiting', 'sedang menunggu', '⏳', 'verb', ['wait'], 'are waiting'],
      ['traffic light', 'lampu lalu lintas', '🚦', 'noun', [], 'at the traffic light'],
      ['motorbikes', 'sepeda motor', '🏍️', 'noun', ['motorbike'], 'Cars and motorbikes'],
      ['policeman', 'polisi (laki-laki)', '👮', 'noun', [], 'A policeman is helping'],
      ['cross', 'menyeberang', '🚸', 'verb', ['crosses'], 'They cross the street.'],
      ['street', 'jalan', '🛣️', 'noun', ['streets'], 'the street'],
    ],
    grammar: [P.ingNow],
    quiz: [
      ['Where are Rafi and Mom waiting? (Di mana Rafi dan Ibu menunggu?)', ['At the traffic light', 'At school', 'At home'], 0, '"waiting at the traffic light"'],
      ['Who is helping people cross? (Siapa yang membantu orang menyeberang?)', ['A teacher', 'A policeman', 'A doctor'], 1, '"A policeman is helping people cross."'],
      ['When can walkers cross? (Kapan pejalan kaki boleh menyeberang?)', ['When the light is green for walkers', 'When it is red for walkers', 'Any time'], 0, '"The light is green for walkers now."'],
    ],
  },
];
