// Daily English Reading Fase A — tahun pertama, bagian 4 (minggu 22–28).

import { P } from './english-phase-a-patterns';
import type { SeedReading } from './types';

export const englishPhaseAYear4: SeedReading[] = [
  // ── Minggu 22: Tanaman ───────────────────────────────────────────────────
  {
    slug: 'a4-planting-a-seed', theme: 'Plants', emoji: '🌱', title: 'Planting a Seed', titleId: 'Menanam Biji', minutes: 3,
    sentences: [
      ['Rafi has a bean seed.', 'Rafi punya sebutir biji kacang.'],
      ['He puts soil in a small pot.', 'Dia memasukkan tanah ke pot kecil.'],
      ['He makes a hole and puts the seed in.', 'Dia membuat lubang dan memasukkan bijinya.'],
      ['He covers it with soil and waters it.', 'Dia menutupnya dengan tanah dan menyiramnya.'],
      ['He puts the pot in the sun.', 'Dia menaruh pot itu di bawah sinar matahari.', true],
      ['After five days, a tiny green shoot comes up!', 'Setelah lima hari, tunas hijau kecil muncul!'],
    ],
    vocab: [
      ['bean', 'kacang', '🫘', 'noun', ['beans'], 'a bean seed'],
      ['soil', 'tanah', '🟫', 'noun', [], 'He puts soil in a small pot.'],
      ['pot', 'pot', '🪴', 'noun', ['pots'], 'a small pot'],
      ['covers', 'menutup', '🫳', 'verb', ['cover'], 'He covers it with soil.'],
      ['shoot', 'tunas', '🌱', 'noun', ['shoots'], 'a tiny green shoot'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What seed does Rafi have? (Biji apa yang Rafi punya?)', ['A bean seed', 'A mango seed', 'A rice seed'], 0, '"Rafi has a bean seed."'],
      ['Where does he put the pot? (Di mana dia menaruh pot?)', ['In the sun', 'In the fridge', 'Under the bed'], 0, '"He puts the pot in the sun."'],
      ['When does the shoot come up? (Kapan tunasnya muncul?)', ['After five days', 'After one hour', 'After one year'], 0, '"After five days"'],
    ],
  },
  {
    slug: 'a4-what-plants-need', theme: 'Plants', emoji: '☀️', title: 'What Plants Need', titleId: 'Kebutuhan Tanaman', minutes: 3,
    sentences: [
      ['Plants are living things.', 'Tanaman adalah makhluk hidup.'],
      ['They need water to drink.', 'Mereka butuh air untuk minum.'],
      ['They need sunlight to make food.', 'Mereka butuh sinar matahari untuk membuat makanan.'],
      ['They need air and good soil.', 'Mereka butuh udara dan tanah yang baik.'],
      ['Without water, plants die.', 'Tanpa air, tanaman akan mati.', true],
      ['Let us take care of our plants!', 'Ayo rawat tanaman kita!'],
    ],
    vocab: [
      ['living things', 'makhluk hidup', '🌿', 'noun', ['living thing'], 'Plants are living things.'],
      ['sunlight', 'sinar matahari', '☀️', 'noun', [], 'They need sunlight.'],
      ['food', 'makanan', '🍽️', 'noun', [], 'to make food'],
      ['without', 'tanpa', '🚫', 'preposition', [], 'Without water'],
      ['die', 'mati', '🥀', 'verb', ['dies'], 'plants die'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What do plants need to make food? (Tanaman butuh apa untuk membuat makanan?)', ['Sunlight', 'Milk', 'Toys'], 0, '"They need sunlight to make food."'],
      ['What happens without water? (Apa yang terjadi tanpa air?)', ['Plants die', 'Plants grow fast', 'Plants sing'], 0, '"Without water, plants die."'],
      ['Are plants living things? (Apakah tanaman makhluk hidup?)', ['Yes', 'No'], 0, '"Plants are living things."'],
    ],
  },
  {
    slug: 'a4-parts-of-a-plant', theme: 'Plants', emoji: '🌻', title: 'Parts of a Plant', titleId: 'Bagian-bagian Tanaman', minutes: 3,
    sentences: [
      ['A plant has many parts.', 'Tanaman punya banyak bagian.'],
      ['The roots are under the ground.', 'Akar ada di bawah tanah.'],
      ['The roots drink water from the soil.', 'Akar menyerap air dari tanah.'],
      ['The stem holds the plant up.', 'Batang menopang tanaman agar tegak.'],
      ['The leaves make food from sunlight.', 'Daun membuat makanan dari sinar matahari.', true],
      ['The flowers make seeds for new plants.', 'Bunga menghasilkan biji untuk tanaman baru.'],
    ],
    vocab: [
      ['parts', 'bagian', '🧩', 'noun', ['part'], 'many parts'],
      ['roots', 'akar', '🌳', 'noun', ['root'], 'The roots are under the ground.'],
      ['stem', 'batang', '🌿', 'noun', ['stems'], 'The stem holds the plant up.'],
      ['holds up', 'menopang', '🏋️', 'verb', ['holds'], 'holds the plant up'],
      ['new', 'baru', '✨', 'adjective', [], 'new plants'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Where are the roots? (Di mana akar?)', ['Under the ground', 'On the flower', 'In the sky'], 0, '"The roots are under the ground."'],
      ['What do the leaves do? (Apa tugas daun?)', ['Make food from sunlight', 'Hold the plant up', 'Drink milk'], 0, '"The leaves make food from sunlight."'],
      ['"Stem" artinya …', ['Akar', 'Batang', 'Bunga'], 1, 'Stem = batang.'],
    ],
  },
  {
    slug: 'a4-the-sunflower-race', theme: 'Plants', emoji: '🌻', title: 'The Sunflower Race', titleId: 'Lomba Bunga Matahari', minutes: 3,
    sentences: [
      ['Rafi and Dina plant sunflowers.', 'Rafi dan Dina menanam bunga matahari.'],
      ['"Let us see whose sunflower is taller!"', '"Ayo lihat bunga matahari siapa yang lebih tinggi!"'],
      ['They water their plants every day.', 'Mereka menyiram tanaman setiap hari.'],
      ['After two months, the sunflowers are very tall.', 'Setelah dua bulan, bunga mataharinya sangat tinggi.'],
      ['Rafi\'s sunflower is taller than Rafi!', 'Bunga matahari Rafi lebih tinggi daripada Rafi!', true],
      ['Dina\'s sunflower is taller than Dad!', 'Bunga matahari Dina lebih tinggi daripada Ayah!'],
      ['Dina wins the race. They laugh together.', 'Dina memenangkan lomba. Mereka tertawa bersama.'],
    ],
    vocab: [
      ['sunflowers', 'bunga matahari', '🌻', 'noun', ['sunflower'], 'plant sunflowers'],
      ['whose', 'milik siapa', '❓', 'pronoun', [], 'whose sunflower'],
      ['months', 'bulan', '🗓️', 'noun', ['month'], 'After two months'],
      ['than', 'daripada', '⚖️', 'conjunction', [], 'taller than Rafi'],
      ['wins', 'menang', '🏆', 'verb', ['win'], 'Dina wins the race.'],
      ['race', 'lomba', '🏁', 'noun', ['races'], 'the race'],
    ],
    grammar: [P.comparison],
    quiz: [
      ['What do they plant? (Apa yang mereka tanam?)', ['Sunflowers', 'Roses', 'Rice'], 0, '"Rafi and Dina plant sunflowers."'],
      ['Whose sunflower is the tallest? (Bunga matahari siapa yang paling tinggi?)', ['Rafi\'s', 'Dina\'s'], 1, 'Bunga Dina lebih tinggi dari Ayah.'],
      ['"Taller than" artinya …', ['Lebih tinggi daripada', 'Lebih pendek daripada', 'Sama tinggi'], 0, 'Taller than = lebih tinggi daripada.'],
    ],
  },
  {
    slug: 'a4-the-big-banyan-tree', theme: 'Plants', emoji: '🌳', title: 'The Old Banyan Tree', titleId: 'Pohon Beringin Tua', minutes: 3,
    sentences: [
      ['In the town square, there is a banyan tree.', 'Di alun-alun kota, ada pohon beringin.'],
      ['It is very old and very big.', 'Pohon itu sangat tua dan sangat besar.'],
      ['Its roots hang down from the branches.', 'Akarnya menggantung dari dahan-dahan.'],
      ['Birds build nests in it.', 'Burung-burung membuat sarang di sana.'],
      ['People sit in its shade.', 'Orang-orang duduk di bawah keteduhannya.', true],
      ['Trees give us shade and clean air.', 'Pohon memberi kita keteduhan dan udara bersih.'],
    ],
    vocab: [
      ['town square', 'alun-alun', '🏛️', 'noun', [], 'In the town square'],
      ['banyan tree', 'pohon beringin', '🌳', 'noun', [], 'a banyan tree'],
      ['hang down', 'menggantung', '🧶', 'verb', [], 'Its roots hang down.'],
      ['branches', 'dahan', '🌿', 'noun', ['branch'], 'from the branches'],
      ['clean air', 'udara bersih', '🍃', 'noun', [], 'shade and clean air'],
    ],
    grammar: [P.thereIsAre],
    quiz: [
      ['Where is the banyan tree? (Di mana pohon beringin itu?)', ['In the town square', 'In the school', 'In the sea'], 0, '"In the town square, there is a banyan tree."'],
      ['What hangs down from the branches? (Apa yang menggantung dari dahan?)', ['Its roots', 'Its fruit', 'Lamps'], 0, '"Its roots hang down from the branches."'],
      ['What do trees give us? (Pohon memberi kita apa?)', ['Shade and clean air', 'Money', 'Toys'], 0, '"Trees give us shade and clean air."'],
    ],
  },
  {
    slug: 'a4-vegetable-garden', theme: 'Plants', emoji: '🥬', title: 'Mom\'s Vegetable Garden', titleId: 'Kebun Sayur Ibu', minutes: 3,
    sentences: [
      ['Behind our house, Mom has a vegetable garden.', 'Di belakang rumah kami, Ibu punya kebun sayur.'],
      ['She grows spinach, long beans, and chilies.', 'Dia menanam bayam, kacang panjang, dan cabai.'],
      ['She uses no chemicals.', 'Dia tidak memakai bahan kimia.'],
      ['Today we pick the long beans.', 'Hari ini kami memetik kacang panjang.'],
      ['Mom cooks them for dinner.', 'Ibu memasaknya untuk makan malam.', true],
      ['Food from our garden tastes the best!', 'Makanan dari kebun kami rasanya paling enak!'],
    ],
    vocab: [
      ['behind', 'di belakang', '🔙', 'preposition', [], 'Behind our house'],
      ['grows', 'menanam', '🌱', 'verb', ['grow'], 'She grows spinach.'],
      ['long beans', 'kacang panjang', '🫛', 'noun', [], 'long beans'],
      ['chemicals', 'bahan kimia', '🧪', 'noun', ['chemical'], 'no chemicals'],
      ['pick', 'memetik', '🤏', 'verb', ['picks'], 'we pick the long beans'],
      ['tastes', 'rasanya', '😋', 'verb', ['taste'], 'tastes the best'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Where is the vegetable garden? (Di mana kebun sayurnya?)', ['Behind the house', 'At school', 'On the roof'], 0, '"Behind our house"'],
      ['What do they pick today? (Apa yang mereka petik hari ini?)', ['Long beans', 'Mangoes', 'Flowers'], 0, '"Today we pick the long beans."'],
      ['"Pick" artinya …', ['Memetik', 'Menanam', 'Menyiram'], 0, 'Pick = memetik.'],
    ],
  },
  {
    slug: 'a4-the-cactus', theme: 'Plants', emoji: '🌵', title: 'The Thirsty Cactus?', titleId: 'Kaktus yang Kehausan?', minutes: 3,
    sentences: [
      ['Aisyah has a small cactus.', 'Aisyah punya kaktus kecil.'],
      ['She waters it every day.', 'Dia menyiramnya setiap hari.'],
      ['Oh no! The cactus looks sick.', 'Oh tidak! Kaktusnya terlihat sakit.'],
      ['Grandpa says, "A cactus doesn\'t need much water."', 'Kakek berkata, "Kaktus tidak butuh banyak air."'],
      ['"It stores water inside its body."', '"Ia menyimpan air di dalam tubuhnya."', true],
      ['Now Aisyah waters it once a week.', 'Sekarang Aisyah menyiramnya seminggu sekali.'],
      ['The cactus is healthy again!', 'Kaktusnya sehat lagi!'],
    ],
    vocab: [
      ['cactus', 'kaktus', '🌵', 'noun', [], 'a small cactus'],
      ['looks', 'terlihat', '👀', 'verb', ['look'], 'The cactus looks sick.'],
      ['much', 'banyak', '💧', 'adjective', [], 'much water'],
      ['stores', 'menyimpan', '🫙', 'verb', ['store'], 'It stores water.'],
      ['once a week', 'seminggu sekali', '📅', 'phrase', [], 'once a week'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What is wrong at first? (Apa masalahnya awalnya?)', ['Aisyah gives it too much water', 'The cactus is too small', 'Milo eats it'], 0, 'Aisyah menyiramnya setiap hari, padahal kaktus tidak butuh banyak air.'],
      ['Where does a cactus store water? (Di mana kaktus menyimpan air?)', ['Inside its body', 'In its flowers', 'In the pot'], 0, '"It stores water inside its body."'],
      ['How often does Aisyah water it now? (Seberapa sering sekarang?)', ['Once a week', 'Every hour', 'Never'], 0, '"once a week"'],
    ],
  },

  // ── Minggu 23: Ramadan ───────────────────────────────────────────────────
  {
    slug: 'a4-ramadan-is-here', theme: 'Ramadan', emoji: '🌙', title: 'Ramadan Is Here', titleId: 'Ramadan Telah Tiba', minutes: 3,
    sentences: [
      ['Ramadan is a special month for Muslims.', 'Ramadan adalah bulan istimewa bagi umat Islam.'],
      ['In Ramadan, we fast.', 'Di bulan Ramadan, kami berpuasa.'],
      ['We don\'t eat or drink from dawn to sunset.', 'Kami tidak makan dan minum dari subuh sampai matahari terbenam.'],
      ['We pray more and read the Quran.', 'Kami lebih banyak salat dan membaca Al-Qur\'an.'],
      ['We also share food with others.', 'Kami juga berbagi makanan dengan orang lain.', true],
      ['Ramadan teaches us to be patient and kind.', 'Ramadan mengajari kita untuk sabar dan baik hati.'],
    ],
    vocab: [
      ['month', 'bulan', '🌙', 'noun', ['months'], 'a special month'],
      ['fast', 'berpuasa', '🍽️', 'verb', ['fasts', 'fasting'], 'we fast'],
      ['dawn', 'subuh / fajar', '🌅', 'noun', [], 'from dawn'],
      ['sunset', 'matahari terbenam', '🌇', 'noun', [], 'to sunset'],
      ['others', 'orang lain', '👥', 'pronoun', [], 'share food with others'],
      ['teaches', 'mengajari', '📘', 'verb', ['teach'], 'Ramadan teaches us'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What do we do in Ramadan? (Apa yang kita lakukan di bulan Ramadan?)', ['We fast', 'We go to the beach every day', 'We sleep all day'], 0, '"In Ramadan, we fast."'],
      ['When do we stop eating and drinking? (Kapan kita berhenti makan dan minum?)', ['From dawn to sunset', 'From sunset to dawn', 'Only at lunch'], 0, '"from dawn to sunset"'],
      ['Ramadan teaches us to be … (Ramadan mengajari kita untuk …)', ['Patient and kind', 'Lazy', 'Angry'], 0, '"patient and kind"'],
    ],
  },
  {
    slug: 'a4-sahur-time', theme: 'Ramadan', emoji: '⏰', title: 'Wake Up for Sahur!', titleId: 'Bangun Sahur!', minutes: 3,
    sentences: [
      ['It is three o\'clock in the morning.', 'Sekarang pukul tiga pagi.'],
      ['"Sahur! Sahur!" The children shout in the street.', '"Sahur! Sahur!" Anak-anak berteriak di jalan.'],
      ['Mom wakes Rafi up.', 'Ibu membangunkan Rafi.'],
      ['Rafi is sleepy, but he gets up.', 'Rafi mengantuk, tapi dia bangun.'],
      ['The family eats rice, eggs, and dates.', 'Keluarga makan nasi, telur, dan kurma.', true],
      ['They drink a lot of water.', 'Mereka minum banyak air.'],
      ['Now Rafi is ready to fast all day!', 'Sekarang Rafi siap berpuasa seharian!'],
    ],
    vocab: [
      ['sahur', 'makan sahur', '🍚', 'noun', [], 'Sahur! Sahur!'],
      ['shout', 'berteriak', '📢', 'verb', ['shouts'], 'The children shout.'],
      ['wakes up', 'membangunkan', '⏰', 'verb', ['wake up'], 'Mom wakes Rafi up.'],
      ['dates', 'kurma', '🌴', 'noun', ['date'], 'rice, eggs, and dates'],
      ['all day', 'seharian', '☀️', 'phrase', [], 'fast all day'],
    ],
    grammar: [P.timeClock],
    quiz: [
      ['What time is it? (Jam berapa sekarang?)', ['Three o\'clock in the morning', 'Seven o\'clock at night', 'Noon'], 0, '"It is three o\'clock in the morning."'],
      ['What does the family eat? (Apa yang dimakan keluarga itu?)', ['Rice, eggs, and dates', 'Pizza', 'Ice cream'], 0, '"rice, eggs, and dates"'],
      ['"Dates" dalam cerita ini artinya …', ['Tanggal', 'Kurma', 'Teman'], 1, 'Di sini dates = kurma (buah).'],
    ],
  },
  {
    slug: 'a4-breaking-the-fast', theme: 'Ramadan', emoji: '🍹', title: 'Breaking the Fast', titleId: 'Berbuka Puasa', minutes: 3,
    sentences: [
      ['The sun is going down.', 'Matahari mulai terbenam.'],
      ['The family sits around the table.', 'Keluarga duduk mengelilingi meja.'],
      ['There is sweet iced tea and fried snacks.', 'Ada es teh manis dan gorengan.'],
      ['There is also kolak with bananas.', 'Ada juga kolak pisang.'],
      ['Allahu akbar! We hear the call to prayer.', 'Allahu akbar! Kami mendengar azan.', true],
      ['We say a prayer and break our fast.', 'Kami berdoa dan berbuka puasa.'],
      ['The first sip of tea is so sweet!', 'Tegukan teh pertama terasa sangat manis!'],
    ],
    vocab: [
      ['going down', 'terbenam / turun', '🌇', 'verb', ['go down'], 'The sun is going down.'],
      ['around', 'mengelilingi', '⭕', 'preposition', [], 'around the table'],
      ['iced tea', 'es teh', '🧋', 'noun', [], 'sweet iced tea'],
      ['break our fast', 'berbuka puasa', '🍽️', 'verb', ['break the fast'], 'break our fast'],
      ['sip', 'tegukan', '🥤', 'noun', ['sips'], 'The first sip'],
    ],
    grammar: [P.thereIsAre],
    quiz: [
      ['What is on the table? (Apa yang ada di meja?)', ['Iced tea, fried snacks, and kolak', 'Only water', 'Nothing'], 0, '"sweet iced tea and fried snacks … kolak"'],
      ['When do they break their fast? (Kapan mereka berbuka?)', ['When they hear the call to prayer', 'At noon', 'In the morning'], 0, '"We hear the call to prayer … break our fast."'],
      ['"Break our fast" artinya …', ['Berbuka puasa', 'Mulai puasa', 'Makan sahur'], 0, 'Break our fast = berbuka puasa.'],
    ],
  },
  {
    slug: 'a4-tarawih-prayer', theme: 'Ramadan', emoji: '🕌', title: 'Tarawih at the Mosque', titleId: 'Tarawih di Masjid', minutes: 3,
    sentences: [
      ['After dinner, Rafi goes to the mosque.', 'Setelah makan malam, Rafi pergi ke masjid.'],
      ['He prays tarawih with Dad.', 'Dia salat tarawih bersama Ayah.'],
      ['The mosque is full of people.', 'Masjidnya penuh orang.'],
      ['Some children are sleepy.', 'Beberapa anak mengantuk.'],
      ['Rafi tries his best to stay awake.', 'Rafi berusaha sebaik mungkin agar tetap terjaga.', true],
      ['After tarawih, he writes in his Ramadan book.', 'Setelah tarawih, dia menulis di buku Ramadannya.'],
    ],
    vocab: [
      ['tarawih', 'salat tarawih', '🕌', 'noun', [], 'He prays tarawih.'],
      ['full of', 'penuh dengan', '🈵', 'phrase', [], 'full of people'],
      ['tries his best', 'berusaha sebaik mungkin', '💪', 'verb', ['try my best'], 'Rafi tries his best.'],
      ['awake', 'terjaga / tidak tidur', '👁️', 'adjective', [], 'to stay awake'],
      ['writes', 'menulis', '✍️', 'verb', ['write'], 'he writes in his Ramadan book'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Who does Rafi pray with? (Rafi salat bersama siapa?)', ['Dad', 'Dina', 'Grandma'], 0, '"He prays tarawih with Dad."'],
      ['How is the mosque? (Bagaimana masjidnya?)', ['Full of people', 'Empty', 'Closed'], 0, '"The mosque is full of people."'],
      ['What does Rafi do after tarawih? (Apa yang Rafi lakukan setelah tarawih?)', ['He writes in his Ramadan book', 'He eats candy', 'He plays football'], 0, '"he writes in his Ramadan book"'],
    ],
  },
  {
    slug: 'a4-sharing-iftar', theme: 'Ramadan', emoji: '🤲', title: 'Sharing Food', titleId: 'Berbagi Takjil', minutes: 3,
    sentences: [
      ['Rafi\'s mosque gives free food for iftar.', 'Masjid Rafi membagikan takjil gratis.'],
      ['Rafi and his friends help.', 'Rafi dan teman-temannya membantu.'],
      ['They put dates and water in small bags.', 'Mereka memasukkan kurma dan air ke kantong kecil.'],
      ['They give the bags to people on the street.', 'Mereka memberikan kantong itu kepada orang di jalan.'],
      ['A motorcycle taxi driver smiles. "Thank you, kids!"', 'Seorang pengemudi ojek tersenyum. "Terima kasih, anak-anak!"', true],
      ['Giving makes Rafi\'s heart happy.', 'Memberi membuat hati Rafi bahagia.'],
    ],
    vocab: [
      ['free', 'gratis', '🆓', 'adjective', [], 'free food'],
      ['iftar', 'buka puasa', '🍽️', 'noun', [], 'for iftar'],
      ['bags', 'kantong / tas', '👜', 'noun', ['bag'], 'small bags'],
      ['driver', 'pengemudi', '🛵', 'noun', ['drivers'], 'A motorcycle taxi driver'],
      ['giving', 'memberi', '🎁', 'noun', ['give'], 'Giving makes Rafi\'s heart happy.'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What do they put in the bags? (Apa yang mereka masukkan ke kantong?)', ['Dates and water', 'Toys', 'Books'], 0, '"They put dates and water in small bags."'],
      ['Who do they give the bags to? (Kepada siapa kantong itu diberikan?)', ['People on the street', 'Their teacher', 'Their cat'], 0, '"to people on the street"'],
      ['How does giving make Rafi feel? (Bagaimana perasaan Rafi saat memberi?)', ['Happy', 'Sad', 'Angry'], 0, '"Giving makes Rafi\'s heart happy."'],
    ],
  },
  {
    slug: 'a4-my-first-full-fast', theme: 'Ramadan', emoji: '🏅', title: 'My First Full Fast', titleId: 'Puasa Penuh Pertamaku', minutes: 3,
    sentences: [
      ['Aisyah is five years old.', 'Aisyah berumur lima tahun.'],
      ['She wants to fast like Rafi.', 'Dia ingin berpuasa seperti Rafi.'],
      ['At noon, she is hungry and thirsty.', 'Pada siang hari, dia lapar dan haus.'],
      ['"Can I eat now?" she asks.', '"Boleh aku makan sekarang?" tanyanya.'],
      ['Mom says, "You can fast half a day."', 'Ibu berkata, "Kamu boleh puasa setengah hari."', true],
      ['Aisyah eats lunch, then fasts again until sunset.', 'Aisyah makan siang, lalu berpuasa lagi sampai magrib.'],
      ['Everyone is proud of her.', 'Semua bangga padanya.'],
    ],
    vocab: [
      ['noon', 'tengah hari / siang', '🕛', 'noun', [], 'At noon'],
      ['half', 'setengah', '½', 'noun', [], 'half a day'],
      ['until', 'sampai', '⏳', 'preposition', [], 'until sunset'],
      ['proud of', 'bangga pada', '🏅', 'phrase', [], 'proud of her'],
      ['like', 'seperti', '🟰', 'preposition', [], 'like Rafi'],
    ],
    grammar: [P.canIQuestion],
    quiz: [
      ['How old is Aisyah? (Berapa umur Aisyah?)', ['Five', 'Eight', 'Ten'], 0, '"Aisyah is five years old."'],
      ['How long can Aisyah fast? (Berapa lama Aisyah boleh puasa?)', ['Half a day', 'Two days', 'One hour'], 0, '"You can fast half a day."'],
      ['How does everyone feel? (Bagaimana perasaan semua orang?)', ['Proud', 'Angry', 'Scared'], 0, '"Everyone is proud of her."'],
    ],
  },
  {
    slug: 'a4-zakat-and-charity', theme: 'Ramadan', emoji: '💝', title: 'Helping Others', titleId: 'Menolong Sesama', minutes: 3,
    sentences: [
      ['At the end of Ramadan, Muslims give zakat.', 'Di akhir Ramadan, umat Islam membayar zakat.'],
      ['Dad gives rice to the mosque.', 'Ayah memberikan beras ke masjid.'],
      ['The mosque gives the rice to poor families.', 'Masjid memberikan beras itu kepada keluarga yang kurang mampu.'],
      ['Rafi gives some of his savings too.', 'Rafi juga memberikan sebagian tabungannya.'],
      ['Now everyone can celebrate Eid.', 'Sekarang semua orang bisa merayakan Lebaran.', true],
      ['Helping others is beautiful.', 'Menolong sesama itu indah.'],
    ],
    vocab: [
      ['end', 'akhir', '🔚', 'noun', [], 'At the end of Ramadan'],
      ['zakat', 'zakat', '💝', 'noun', [], 'Muslims give zakat.'],
      ['poor', 'miskin / kurang mampu', '🫶', 'adjective', [], 'poor families'],
      ['savings', 'tabungan', '🐷', 'noun', [], 'his savings'],
      ['celebrate', 'merayakan', '🎉', 'verb', ['celebrates'], 'celebrate Eid'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What does Dad give to the mosque? (Apa yang Ayah berikan ke masjid?)', ['Rice', 'Toys', 'Clothes'], 0, '"Dad gives rice to the mosque."'],
      ['Who gets the rice? (Siapa yang menerima beras?)', ['Poor families', 'Rich people', 'Animals'], 0, '"to poor families"'],
      ['When do Muslims give zakat? (Kapan umat Islam membayar zakat?)', ['At the end of Ramadan', 'On New Year', 'On birthdays'], 0, '"At the end of Ramadan"'],
    ],
  },

  // ── Minggu 24: Idulfitri / Lebaran ───────────────────────────────────────
  {
    slug: 'a4-takbir-night', theme: 'Eid', emoji: '🏮', title: 'Takbir Night', titleId: 'Malam Takbiran', minutes: 3,
    sentences: [
      ['Tonight is the last night of Ramadan.', 'Malam ini malam terakhir Ramadan.'],
      ['We hear "Allahu akbar" from the mosques.', 'Kami mendengar "Allahu akbar" dari masjid-masjid.'],
      ['Children walk around with lanterns.', 'Anak-anak berkeliling membawa lampion.'],
      ['Some people beat drums.', 'Sebagian orang menabuh bedug.'],
      ['Rafi carries a star-shaped lantern.', 'Rafi membawa lampion berbentuk bintang.', true],
      ['Tomorrow is Eid. Everyone is excited!', 'Besok Lebaran. Semua orang bersemangat!'],
    ],
    vocab: [
      ['last', 'terakhir', '🔚', 'adjective', [], 'the last night'],
      ['lanterns', 'lampion', '🏮', 'noun', ['lantern'], 'with lanterns'],
      ['beat', 'menabuh / memukul', '🥁', 'verb', ['beats'], 'Some people beat drums.'],
      ['drums', 'bedug / drum', '🥁', 'noun', ['drum'], 'beat drums'],
      ['star-shaped', 'berbentuk bintang', '⭐', 'adjective', [], 'a star-shaped lantern'],
      ['excited', 'bersemangat', '🤩', 'adjective', [], 'Everyone is excited!'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What do children carry? (Apa yang dibawa anak-anak?)', ['Lanterns', 'Umbrellas', 'Books'], 0, '"Children walk around with lanterns."'],
      ['What shape is Rafi\'s lantern? (Apa bentuk lampion Rafi?)', ['A star', 'A moon', 'A fish'], 0, '"a star-shaped lantern"'],
      ['What is tomorrow? (Besok hari apa?)', ['Eid', 'Monday', 'Independence Day'], 0, '"Tomorrow is Eid."'],
    ],
  },
  {
    slug: 'a4-eid-morning', theme: 'Eid', emoji: '🕌', title: 'Eid Morning', titleId: 'Pagi Lebaran', minutes: 3,
    sentences: [
      ['It is Eid al-Fitr!', 'Hari ini Idulfitri!'],
      ['Everyone wears new clothes.', 'Semua memakai baju baru.'],
      ['We go to the field to pray Eid prayer.', 'Kami pergi ke lapangan untuk salat Id.'],
      ['After praying, we shake hands with everyone.', 'Setelah salat, kami bersalaman dengan semua orang.'],
      ['We say, "Mohon maaf lahir dan batin."', 'Kami mengucapkan, "Mohon maaf lahir dan batin."', true],
      ['It means, "Please forgive me."', 'Artinya, "Tolong maafkan aku."'],
    ],
    vocab: [
      ['Eid', 'Lebaran / hari raya', '🌙', 'noun', [], 'It is Eid al-Fitr!'],
      ['new clothes', 'baju baru', '👘', 'noun', [], 'Everyone wears new clothes.'],
      ['praying', 'salat / berdoa', '🤲', 'verb', ['pray'], 'After praying'],
      ['shake hands', 'bersalaman', '🤝', 'verb', ['shake hand'], 'we shake hands with everyone'],
      ['forgive', 'memaafkan', '💞', 'verb', ['forgives'], 'Please forgive me.'],
    ],
    grammar: [P.politeWords],
    quiz: [
      ['Where do they pray Eid prayer? (Di mana mereka salat Id?)', ['In the field', 'At home', 'At school'], 0, '"We go to the field to pray Eid prayer."'],
      ['What do they do after praying? (Apa yang dilakukan setelah salat?)', ['Shake hands with everyone', 'Go to sleep', 'Go swimming'], 0, '"we shake hands with everyone"'],
      ['"Please forgive me" artinya …', ['Tolong maafkan aku', 'Terima kasih', 'Sampai jumpa'], 0, 'Forgive = memaafkan.'],
    ],
  },
  {
    slug: 'a4-going-home-to-the-village', theme: 'Eid', emoji: '🚗', title: 'Going Home for Eid', titleId: 'Mudik Lebaran', minutes: 3,
    sentences: [
      ['Every Eid, we go back to Grandma\'s village.', 'Setiap Lebaran, kami pulang ke desa Nenek.'],
      ['Many people do the same. It is called mudik.', 'Banyak orang melakukan hal yang sama. Namanya mudik.'],
      ['The roads are full of cars and motorbikes.', 'Jalan-jalan penuh dengan mobil dan motor.'],
      ['The trip takes ten hours!', 'Perjalanannya sepuluh jam!'],
      ['We sing songs and play games in the car.', 'Kami bernyanyi dan bermain di dalam mobil.', true],
      ['At last, we see Grandma at the door.', 'Akhirnya, kami melihat Nenek di depan pintu.'],
    ],
    vocab: [
      ['go back', 'pulang / kembali', '🔙', 'verb', [], 'we go back'],
      ['the same', 'hal yang sama', '🟰', 'phrase', [], 'Many people do the same.'],
      ['roads', 'jalan raya', '🛣️', 'noun', ['road'], 'The roads are full of cars.'],
      ['trip', 'perjalanan', '🧳', 'noun', ['trips'], 'The trip takes ten hours!'],
      ['at last', 'akhirnya', '🎉', 'phrase', [], 'At last, we see Grandma.'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Where do they go every Eid? (Ke mana mereka setiap Lebaran?)', ['Grandma\'s village', 'The beach', 'Japan'], 0, '"we go back to Grandma\'s village"'],
      ['How long is the trip? (Berapa lama perjalanannya?)', ['Ten hours', 'One hour', 'Ten days'], 0, '"The trip takes ten hours!"'],
      ['"At last" artinya …', ['Akhirnya', 'Pertama', 'Kemarin'], 0, 'At last = akhirnya.'],
    ],
  },
  {
    slug: 'a4-ketupat-and-opor', theme: 'Eid', emoji: '🍙', title: 'Ketupat and Opor', titleId: 'Ketupat dan Opor', minutes: 3,
    sentences: [
      ['Grandma cooks special food for Eid.', 'Nenek memasak makanan istimewa untuk Lebaran.'],
      ['She makes ketupat from rice and coconut leaves.', 'Dia membuat ketupat dari beras dan janur.'],
      ['She cooks chicken opor with coconut milk.', 'Dia memasak opor ayam dengan santan.'],
      ['There is also beef rendang and crackers.', 'Ada juga rendang sapi dan kerupuk.'],
      ['The whole family eats together.', 'Seluruh keluarga makan bersama.', true],
      ['Grandma\'s food is the best!', 'Masakan Nenek paling enak!'],
    ],
    vocab: [
      ['ketupat', 'ketupat', '🍙', 'noun', [], 'She makes ketupat.'],
      ['coconut', 'kelapa', '🥥', 'noun', ['coconuts'], 'coconut leaves'],
      ['coconut milk', 'santan', '🥥', 'noun', [], 'with coconut milk'],
      ['beef', 'daging sapi', '🥩', 'noun', [], 'beef rendang'],
      ['crackers', 'kerupuk', '🍘', 'noun', ['cracker'], 'and crackers'],
    ],
    grammar: [P.thereIsAre],
    quiz: [
      ['What is ketupat made from? (Ketupat dibuat dari apa?)', ['Rice and coconut leaves', 'Bread', 'Noodles'], 0, '"from rice and coconut leaves"'],
      ['What does Grandma cook opor with? (Opor dimasak dengan apa?)', ['Coconut milk', 'Milk tea', 'Soy sauce'], 0, '"chicken opor with coconut milk"'],
      ['"Crackers" artinya …', ['Kerupuk', 'Kue', 'Permen'], 0, 'Crackers = kerupuk.'],
    ],
  },
  {
    slug: 'a4-visiting-relatives', theme: 'Eid', emoji: '🏘️', title: 'Visiting Relatives', titleId: 'Bersilaturahmi', minutes: 3,
    sentences: [
      ['During Eid, we visit our relatives.', 'Selama Lebaran, kami mengunjungi saudara-saudara.'],
      ['We visit Uncle Joko and Aunt Rina.', 'Kami mengunjungi Paman Joko dan Bibi Rina.'],
      ['We meet our cousins too.', 'Kami juga bertemu sepupu-sepupu kami.'],
      ['Every house has cookies on the table.', 'Setiap rumah menyajikan kue kering di meja.'],
      ['Rafi eats too many pineapple tarts!', 'Rafi makan terlalu banyak kue nastar!', true],
      ['Visiting family makes our bond strong.', 'Mengunjungi keluarga membuat hubungan kami erat.'],
    ],
    vocab: [
      ['during', 'selama', '⏳', 'preposition', [], 'During Eid'],
      ['relatives', 'saudara / kerabat', '👨‍👩‍👧‍👦', 'noun', ['relative'], 'we visit our relatives'],
      ['cousins', 'sepupu', '🧒', 'noun', ['cousin'], 'our cousins'],
      ['cookies', 'kue kering', '🍪', 'noun', ['cookie'], 'cookies on the table'],
      ['pineapple tarts', 'kue nastar', '🥧', 'noun', ['pineapple tart'], 'too many pineapple tarts'],
      ['bond', 'ikatan / hubungan', '🔗', 'noun', [], 'our bond strong'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Who do they visit? (Siapa yang mereka kunjungi?)', ['Their relatives', 'Their teacher', 'A doctor'], 0, '"we visit our relatives"'],
      ['What does Rafi eat too many of? (Rafi makan terlalu banyak apa?)', ['Pineapple tarts', 'Apples', 'Noodles'], 0, '"Rafi eats too many pineapple tarts!"'],
      ['"Cousins" artinya …', ['Sepupu', 'Kakak', 'Paman'], 0, 'Cousins = sepupu.'],
    ],
  },
  {
    slug: 'a4-eid-money', theme: 'Eid', emoji: '✉️', title: 'Little Envelopes', titleId: 'Amplop Kecil', minutes: 3,
    sentences: [
      ['At Eid, Grandpa gives the children little envelopes.', 'Saat Lebaran, Kakek memberi anak-anak amplop kecil.'],
      ['There is some money inside.', 'Di dalamnya ada sedikit uang.'],
      ['Aisyah wants to buy candy.', 'Aisyah ingin membeli permen.'],
      ['Rafi says, "I am going to save my money."', 'Rafi berkata, "Aku akan menabung uangku."'],
      ['He puts half in his piggy bank.', 'Dia memasukkan setengahnya ke celengan.', true],
      ['He gives the other half to the mosque.', 'Setengah lagi dia berikan ke masjid.'],
    ],
    vocab: [
      ['envelopes', 'amplop', '✉️', 'noun', ['envelope'], 'little envelopes'],
      ['inside', 'di dalam', '📥', 'adverb', [], 'There is some money inside.'],
      ['candy', 'permen', '🍬', 'noun', [], 'buy candy'],
      ['going to', 'akan', '🔜', 'phrase', [], 'I am going to save my money.'],
      ['other', 'yang lain', '🔀', 'adjective', [], 'the other half'],
    ],
    grammar: [P.willFuture],
    quiz: [
      ['Who gives the envelopes? (Siapa yang memberi amplop?)', ['Grandpa', 'Mrs. Sari', 'Budi'], 0, '"Grandpa gives the children little envelopes."'],
      ['What does Rafi do with half his money? (Apa yang Rafi lakukan dengan setengah uangnya?)', ['He saves it', 'He loses it', 'He eats it'], 0, '"He puts half in his piggy bank."'],
      ['What does Aisyah want to buy? (Aisyah ingin membeli apa?)', ['Candy', 'A bike', 'A book'], 0, '"Aisyah wants to buy candy."'],
    ],
  },
  {
    slug: 'a4-back-to-the-city', theme: 'Eid', emoji: '👋', title: 'Goodbye, Grandma', titleId: 'Sampai Jumpa, Nenek', minutes: 3,
    sentences: [
      ['The Eid holiday is over.', 'Libur Lebaran sudah selesai.'],
      ['It is time to go back to the city.', 'Sudah waktunya kembali ke kota.'],
      ['Grandma gives us bananas and cassava chips.', 'Nenek memberi kami pisang dan keripik singkong.'],
      ['She hugs Rafi and Aisyah tightly.', 'Dia memeluk Rafi dan Aisyah erat-erat.'],
      ['"Study hard and be good," she says.', '"Belajar yang rajin dan jadilah anak baik," katanya.', true],
      ['Aisyah cries a little. She will miss Grandma.', 'Aisyah menangis sedikit. Dia akan rindu Nenek.'],
      ['"See you next holiday, Grandma!"', '"Sampai jumpa liburan depan, Nek!"'],
    ],
    vocab: [
      ['holiday', 'liburan', '🏖️', 'noun', ['holidays'], 'The Eid holiday'],
      ['city', 'kota', '🏙️', 'noun', ['cities'], 'back to the city'],
      ['cassava chips', 'keripik singkong', '🥔', 'noun', [], 'cassava chips'],
      ['tightly', 'erat-erat', '🤗', 'adverb', [], 'She hugs them tightly.'],
      ['next', 'berikutnya / depan', '⏭️', 'adjective', [], 'next holiday'],
    ],
    grammar: [P.willFuture],
    quiz: [
      ['What does Grandma give them? (Apa yang Nenek berikan?)', ['Bananas and cassava chips', 'Toys', 'Money only'], 0, '"bananas and cassava chips"'],
      ['What does Grandma say? (Apa kata Nenek?)', ['Study hard and be good', 'Don\'t come back', 'Go to sleep'], 0, '"Study hard and be good."'],
      ['Why does Aisyah cry? (Mengapa Aisyah menangis?)', ['She will miss Grandma', 'She is hungry', 'She is sick'], 0, '"She will miss Grandma."'],
    ],
  },

  // ── Minggu 25: Bentuk & Ukuran ───────────────────────────────────────────
  {
    slug: 'a4-shapes-in-my-house', theme: 'Shapes', emoji: '🔷', title: 'Shapes in My House', titleId: 'Bentuk-bentuk di Rumahku', minutes: 3,
    sentences: [
      ['I look for shapes in my house.', 'Aku mencari bentuk-bentuk di rumahku.'],
      ['The clock is a circle.', 'Jam dinding berbentuk lingkaran.'],
      ['The window is a square.', 'Jendela berbentuk persegi.'],
      ['The door is a rectangle.', 'Pintu berbentuk persegi panjang.'],
      ['The roof looks like a triangle.', 'Atap terlihat seperti segitiga.', true],
      ['Shapes are everywhere!', 'Bentuk ada di mana-mana!'],
    ],
    vocab: [
      ['shapes', 'bentuk', '🔷', 'noun', ['shape'], 'I look for shapes.'],
      ['circle', 'lingkaran', '⭕', 'noun', ['circles'], 'The clock is a circle.'],
      ['square', 'persegi', '🟥', 'noun', ['squares'], 'The window is a square.'],
      ['rectangle', 'persegi panjang', '▭', 'noun', ['rectangles'], 'The door is a rectangle.'],
      ['triangle', 'segitiga', '🔺', 'noun', ['triangles'], 'like a triangle'],
      ['everywhere', 'di mana-mana', '🌍', 'adverb', [], 'Shapes are everywhere!'],
    ],
    grammar: [P.itIs],
    quiz: [
      ['What shape is the clock? (Jam berbentuk apa?)', ['A circle', 'A square', 'A triangle'], 0, '"The clock is a circle."'],
      ['What shape is the door? (Pintu berbentuk apa?)', ['A rectangle', 'A circle', 'A star'], 0, '"The door is a rectangle."'],
      ['"Triangle" artinya …', ['Segitiga', 'Lingkaran', 'Persegi'], 0, 'Triangle = segitiga.'],
    ],
  },
  {
    slug: 'a4-big-and-small', theme: 'Shapes', emoji: '🐘', title: 'Big and Small', titleId: 'Besar dan Kecil', minutes: 3,
    sentences: [
      ['An elephant is big. A mouse is small.', 'Gajah itu besar. Tikus itu kecil.'],
      ['A giraffe is tall. A turtle is short.', 'Jerapah itu tinggi. Kura-kura itu pendek.'],
      ['A snake is long. A worm is short.', 'Ular itu panjang. Cacing itu pendek.'],
      ['A rock is heavy. A feather is light.', 'Batu itu berat. Bulu itu ringan.'],
      ['Big and small are opposites.', 'Besar dan kecil adalah lawan kata.', true],
      ['Can you find more opposites?', 'Bisakah kamu menemukan lawan kata lainnya?'],
    ],
    vocab: [
      ['mouse', 'tikus', '🐭', 'noun', ['mice'], 'A mouse is small.'],
      ['worm', 'cacing', '🪱', 'noun', ['worms'], 'A worm is short.'],
      ['feather', 'bulu (burung)', '🪶', 'noun', ['feathers'], 'A feather is light.'],
      ['light', 'ringan', '🎈', 'adjective', [], 'A feather is light.'],
      ['opposites', 'lawan kata', '↔️', 'noun', ['opposite'], 'Big and small are opposites.'],
    ],
    grammar: [{
      title: 'Lawan kata (opposites)',
      pattern: 'big ↔ small • tall ↔ short • heavy ↔ light',
      explanation: 'Banyak kata sifat punya pasangan yang artinya berlawanan. Menghafalnya berpasangan membuat kita lebih mudah ingat.',
      examples: ['An elephant is big. A mouse is small.', 'A rock is heavy. A feather is light.'],
    }],
    quiz: [
      ['The opposite of "heavy" is … (Lawan kata "heavy" adalah …)', ['Light', 'Big', 'Tall'], 0, 'Heavy ↔ light.'],
      ['Which animal is tall? (Hewan apa yang tinggi?)', ['Giraffe', 'Turtle', 'Mouse'], 0, '"A giraffe is tall."'],
      ['"Feather" artinya …', ['Bulu', 'Batu', 'Daun'], 0, 'Feather = bulu.'],
    ],
  },
  {
    slug: 'a4-bigger-and-smaller', theme: 'Shapes', emoji: '⚖️', title: 'Which Is Bigger?', titleId: 'Mana yang Lebih Besar?', minutes: 3,
    sentences: [
      ['Rafi has two balls.', 'Rafi punya dua bola.'],
      ['The football is bigger than the tennis ball.', 'Bola sepak lebih besar daripada bola tenis.'],
      ['The tennis ball is smaller than the football.', 'Bola tenis lebih kecil daripada bola sepak.'],
      ['Dad is taller than Rafi.', 'Ayah lebih tinggi daripada Rafi.'],
      ['Rafi is taller than Aisyah.', 'Rafi lebih tinggi daripada Aisyah.', true],
      ['So Dad is the tallest!', 'Jadi Ayah yang paling tinggi!'],
    ],
    vocab: [
      ['bigger', 'lebih besar', '⬆️', 'adjective', ['big'], 'bigger than the tennis ball'],
      ['tennis ball', 'bola tenis', '🎾', 'noun', [], 'the tennis ball'],
      ['smaller', 'lebih kecil', '⬇️', 'adjective', ['small'], 'smaller than the football'],
      ['taller', 'lebih tinggi', '📏', 'adjective', ['tall'], 'Dad is taller than Rafi.'],
      ['the tallest', 'paling tinggi', '🏆', 'adjective', [], 'Dad is the tallest!'],
    ],
    grammar: [P.comparison],
    quiz: [
      ['Which ball is bigger? (Bola mana yang lebih besar?)', ['The football', 'The tennis ball'], 0, '"The football is bigger than the tennis ball."'],
      ['Who is the tallest? (Siapa yang paling tinggi?)', ['Dad', 'Rafi', 'Aisyah'], 0, '"So Dad is the tallest!"'],
      ['Who is taller, Rafi or Aisyah? (Siapa lebih tinggi?)', ['Rafi', 'Aisyah'], 0, '"Rafi is taller than Aisyah."'],
    ],
  },
  {
    slug: 'a4-the-star-cookie', theme: 'Shapes', emoji: '⭐', title: 'Shape Cookies', titleId: 'Kue Berbentuk', minutes: 3,
    sentences: [
      ['Mom and Aisyah make cookies.', 'Ibu dan Aisyah membuat kue kering.'],
      ['They use cookie cutters.', 'Mereka memakai cetakan kue.'],
      ['Aisyah makes star cookies and heart cookies.', 'Aisyah membuat kue bintang dan kue hati.'],
      ['Mom makes circle cookies.', 'Ibu membuat kue bulat.'],
      ['They bake the cookies in the oven.', 'Mereka memanggang kue di oven.', true],
      ['"Which shape do you like?" asks Mom.', '"Kamu suka bentuk yang mana?" tanya Ibu.'],
      ['"I like the star!" says Aisyah.', '"Aku suka yang bintang!" kata Aisyah.'],
    ],
    vocab: [
      ['cookie cutters', 'cetakan kue', '⭐', 'noun', ['cookie cutter'], 'They use cookie cutters.'],
      ['star', 'bintang', '⭐', 'noun', ['stars'], 'star cookies'],
      ['bake', 'memanggang', '🍪', 'verb', ['bakes'], 'They bake the cookies.'],
      ['oven', 'oven', '🔥', 'noun', ['ovens'], 'in the oven'],
      ['which', 'yang mana', '❓', 'determiner', [], 'Which shape do you like?'],
    ],
    grammar: [P.iLike],
    quiz: [
      ['What do they make? (Apa yang mereka buat?)', ['Cookies', 'Bread', 'Soup'], 0, '"Mom and Aisyah make cookies."'],
      ['What shape does Mom make? (Ibu membuat bentuk apa?)', ['Circles', 'Stars', 'Hearts'], 0, '"Mom makes circle cookies."'],
      ['Which shape does Aisyah like? (Aisyah suka bentuk apa?)', ['The star', 'The circle', 'The square'], 0, '"I like the star!"'],
    ],
  },
  {
    slug: 'a4-the-long-and-short-pencil', theme: 'Shapes', emoji: '✏️', title: 'Long and Short', titleId: 'Panjang dan Pendek', minutes: 3,
    sentences: [
      ['Mrs. Sari gives us a ruler.', 'Bu Sari memberi kami penggaris.'],
      ['"Let us measure things!"', '"Ayo kita mengukur benda-benda!"'],
      ['Rafi\'s pencil is fifteen centimeters long.', 'Pensil Rafi panjangnya lima belas sentimeter.'],
      ['Dina\'s pencil is eight centimeters long.', 'Pensil Dina panjangnya delapan sentimeter.'],
      ['Rafi\'s pencil is longer.', 'Pensil Rafi lebih panjang.', true],
      ['Dina\'s pencil is shorter, because she uses it a lot!', 'Pensil Dina lebih pendek, karena dia sering memakainya!'],
    ],
    vocab: [
      ['measure', 'mengukur', '📏', 'verb', ['measures'], 'Let us measure things!'],
      ['things', 'benda-benda', '📦', 'noun', ['thing'], 'measure things'],
      ['centimeters', 'sentimeter', '📐', 'noun', ['centimeter'], 'fifteen centimeters'],
      ['longer', 'lebih panjang', '➡️', 'adjective', ['long'], 'Rafi\'s pencil is longer.'],
      ['shorter', 'lebih pendek', '⬅️', 'adjective', ['short'], 'Dina\'s pencil is shorter.'],
    ],
    grammar: [P.comparison],
    quiz: [
      ['How long is Rafi\'s pencil? (Berapa panjang pensil Rafi?)', ['Eight centimeters', 'Fifteen centimeters', 'Twenty centimeters'], 1, '"fifteen centimeters long"'],
      ['Whose pencil is shorter? (Pensil siapa yang lebih pendek?)', ['Rafi\'s', 'Dina\'s'], 1, '"Dina\'s pencil is shorter."'],
      ['Why is Dina\'s pencil short? (Mengapa pensil Dina pendek?)', ['She uses it a lot', 'It is broken', 'It is new'], 0, '"because she uses it a lot"'],
    ],
  },
  {
    slug: 'a4-heavy-or-light', theme: 'Shapes', emoji: '🪶', title: 'Heavy or Light?', titleId: 'Berat atau Ringan?', minutes: 3,
    sentences: [
      ['Rafi has a balance scale.', 'Rafi punya timbangan.'],
      ['He puts an apple on one side.', 'Dia menaruh apel di satu sisi.'],
      ['He puts a feather on the other side.', 'Dia menaruh bulu di sisi lain.'],
      ['The apple side goes down.', 'Sisi apel turun.'],
      ['The apple is heavier than the feather.', 'Apel lebih berat daripada bulu.', true],
      ['The feather is lighter than the apple.', 'Bulu lebih ringan daripada apel.'],
    ],
    vocab: [
      ['balance scale', 'timbangan', '⚖️', 'noun', [], 'a balance scale'],
      ['side', 'sisi', '↔️', 'noun', ['sides'], 'on one side'],
      ['goes down', 'turun', '⬇️', 'verb', ['go down'], 'The apple side goes down.'],
      ['heavier', 'lebih berat', '🏋️', 'adjective', ['heavy'], 'heavier than the feather'],
      ['lighter', 'lebih ringan', '🎈', 'adjective', ['light'], 'lighter than the apple'],
    ],
    grammar: [P.comparison],
    quiz: [
      ['Which side goes down? (Sisi mana yang turun?)', ['The apple side', 'The feather side'], 0, '"The apple side goes down."'],
      ['Which is heavier? (Mana yang lebih berat?)', ['The apple', 'The feather'], 0, '"The apple is heavier than the feather."'],
      ['"Lighter" artinya …', ['Lebih ringan', 'Lebih terang', 'Lebih besar'], 0, 'Di sini lighter = lebih ringan.'],
    ],
  },
  {
    slug: 'a4-my-shape-robot', theme: 'Shapes', emoji: '🤖', title: 'My Shape Robot', titleId: 'Robot Bentukku', minutes: 3,
    sentences: [
      ['Rafi draws a robot with shapes.', 'Rafi menggambar robot dari bentuk-bentuk.'],
      ['Its head is a square.', 'Kepalanya persegi.'],
      ['Its eyes are two small circles.', 'Matanya dua lingkaran kecil.'],
      ['Its body is a big rectangle.', 'Badannya persegi panjang besar.'],
      ['Its hat is a triangle.', 'Topinya segitiga.', true],
      ['Its name is Bolt. Beep, beep!', 'Namanya Bolt. Bip, bip!'],
    ],
    vocab: [
      ['robot', 'robot', '🤖', 'noun', ['robots'], 'a robot'],
      ['its', 'miliknya (benda/hewan)', '👉', 'determiner', [], 'Its head is a square.'],
      ['body', 'badan / tubuh', '🧍', 'noun', ['bodies'], 'Its body is a big rectangle.'],
      ['big', 'besar', '🐘', 'adjective', [], 'a big rectangle'],
      ['beep', 'bip (bunyi robot)', '🔊', 'noun', [], 'Beep, beep!'],
    ],
    grammar: [P.itIs],
    quiz: [
      ['What shape is the robot\'s head? (Kepala robot berbentuk apa?)', ['A square', 'A triangle', 'A circle'], 0, '"Its head is a square."'],
      ['What shape is its hat? (Topinya berbentuk apa?)', ['A triangle', 'A square', 'A star'], 0, '"Its hat is a triangle."'],
      ['What is the robot\'s name? (Siapa nama robot itu?)', ['Bolt', 'Milo', 'Bruno'], 0, '"Its name is Bolt."'],
    ],
  },

  // ── Minggu 26: Memasak & Rencana ─────────────────────────────────────────
  {
    slug: 'a4-we-are-going-to-make-a-cake', theme: 'Cooking', emoji: '🎂', title: 'We Are Going to Make a Cake', titleId: 'Kami Akan Membuat Kue', minutes: 3,
    sentences: [
      ['Tomorrow is Dad\'s birthday.', 'Besok ulang tahun Ayah.'],
      ['Mom, Rafi, and Aisyah are going to make a cake.', 'Ibu, Rafi, dan Aisyah akan membuat kue.'],
      ['First, they are going to buy flour and eggs.', 'Pertama, mereka akan membeli tepung dan telur.'],
      ['Then they are going to mix everything.', 'Lalu mereka akan mencampur semuanya.'],
      ['Aisyah is going to put chocolate on top.', 'Aisyah akan menaruh cokelat di atasnya.', true],
      ['It is a secret! Shh, don\'t tell Dad!', 'Ini rahasia! Ssst, jangan beri tahu Ayah!'],
    ],
    vocab: [
      ['birthday', 'ulang tahun', '🎂', 'noun', ['birthdays'], 'Dad\'s birthday'],
      ['flour', 'tepung', '🌾', 'noun', [], 'flour and eggs'],
      ['everything', 'semuanya', '🌐', 'pronoun', [], 'mix everything'],
      ['chocolate', 'cokelat', '🍫', 'noun', [], 'put chocolate on top'],
      ['secret', 'rahasia', '🤫', 'noun', ['secrets'], 'It is a secret!'],
    ],
    grammar: [P.willFuture],
    quiz: [
      ['Whose birthday is tomorrow? (Besok ulang tahun siapa?)', ['Dad\'s', 'Mom\'s', 'Aisyah\'s'], 0, '"Tomorrow is Dad\'s birthday."'],
      ['What are they going to buy first? (Apa yang akan mereka beli pertama?)', ['Flour and eggs', 'Candles', 'A gift'], 0, '"buy flour and eggs"'],
      ['What is Aisyah going to put on top? (Apa yang akan Aisyah taruh di atas?)', ['Chocolate', 'Cheese', 'Rice'], 0, '"Aisyah is going to put chocolate on top."'],
    ],
  },
  {
    slug: 'a4-making-pancakes', theme: 'Cooking', emoji: '🥞', title: 'Pancakes for Breakfast', titleId: 'Panekuk untuk Sarapan', minutes: 3,
    sentences: [
      ['It is Sunday morning.', 'Ini Minggu pagi.'],
      ['Dad makes pancakes.', 'Ayah membuat panekuk.'],
      ['He mixes flour, milk, and eggs in a bowl.', 'Dia mencampur tepung, susu, dan telur di mangkuk.'],
      ['He pours the mixture into a hot pan.', 'Dia menuang adonan ke wajan panas.'],
      ['He flips the pancake. Whoosh!', 'Dia membalik panekuknya. Wuss!', true],
      ['We eat pancakes with honey and bananas.', 'Kami makan panekuk dengan madu dan pisang.'],
    ],
    vocab: [
      ['pancakes', 'panekuk', '🥞', 'noun', ['pancake'], 'Dad makes pancakes.'],
      ['mixes', 'mencampur', '🥣', 'verb', ['mix'], 'He mixes flour, milk, and eggs.'],
      ['mixture', 'adonan / campuran', '🫗', 'noun', [], 'the mixture'],
      ['flips', 'membalik', '🔄', 'verb', ['flip'], 'He flips the pancake.'],
      ['honey', 'madu', '🍯', 'noun', [], 'with honey and bananas'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Who makes pancakes? (Siapa yang membuat panekuk?)', ['Dad', 'Mom', 'Grandma'], 0, '"Dad makes pancakes."'],
      ['What does he mix? (Apa yang dia campur?)', ['Flour, milk, and eggs', 'Rice and water', 'Sugar and salt'], 0, '"flour, milk, and eggs"'],
      ['What do they eat the pancakes with? (Panekuk dimakan dengan apa?)', ['Honey and bananas', 'Soy sauce', 'Chili'], 0, '"with honey and bananas"'],
    ],
  },
  {
    slug: 'a4-kitchen-safety', theme: 'Cooking', emoji: '⚠️', title: 'Be Safe in the Kitchen', titleId: 'Aman di Dapur', minutes: 3,
    sentences: [
      ['The kitchen is a fun place.', 'Dapur adalah tempat yang menyenangkan.'],
      ['But we must be careful there.', 'Tapi kita harus berhati-hati di sana.'],
      ['Don\'t touch the hot stove.', 'Jangan sentuh kompor yang panas.'],
      ['Don\'t play with sharp knives.', 'Jangan bermain dengan pisau tajam.'],
      ['Ask an adult to help you.', 'Minta orang dewasa membantumu.', true],
      ['Wash your hands before cooking.', 'Cuci tanganmu sebelum memasak.'],
    ],
    vocab: [
      ['must', 'harus', '❗', 'verb', [], 'we must be careful'],
      ['touch', 'menyentuh', '✋', 'verb', ['touches'], 'Don\'t touch the hot stove.'],
      ['knives', 'pisau (banyak)', '🔪', 'noun', ['knife'], 'sharp knives'],
      ['adult', 'orang dewasa', '🧑', 'noun', ['adults'], 'Ask an adult.'],
      ['before', 'sebelum', '⏪', 'preposition', [], 'before cooking'],
    ],
    grammar: [P.commands],
    quiz: [
      ['What must we not touch? (Apa yang tidak boleh kita sentuh?)', ['The hot stove', 'The table', 'The plate'], 0, '"Don\'t touch the hot stove."'],
      ['Who should help us? (Siapa yang sebaiknya membantu kita?)', ['An adult', 'A cat', 'Nobody'], 0, '"Ask an adult to help you."'],
      ['"Knives" adalah bentuk banyak dari …', ['Knife', 'Knive', 'Knifes'], 0, 'One knife → two knives.'],
    ],
  },
  {
    slug: 'a4-the-picnic-plan', theme: 'Cooking', emoji: '🧺', title: 'The Picnic Plan', titleId: 'Rencana Piknik', minutes: 3,
    sentences: [
      ['On Saturday, we will have a picnic.', 'Pada hari Sabtu, kami akan berpiknik.'],
      ['We will go to the botanical garden.', 'Kami akan pergi ke kebun raya.'],
      ['Mom will make sandwiches and fried chicken.', 'Ibu akan membuat roti lapis dan ayam goreng.'],
      ['Rafi will bring his ball.', 'Rafi akan membawa bolanya.'],
      ['Aisyah will bring a picnic mat.', 'Aisyah akan membawa tikar piknik.', true],
      ['We hope it will be sunny!', 'Kami berharap cuacanya akan cerah!'],
    ],
    vocab: [
      ['picnic', 'piknik', '🧺', 'noun', ['picnics'], 'a picnic'],
      ['botanical garden', 'kebun raya', '🌺', 'noun', [], 'the botanical garden'],
      ['fried chicken', 'ayam goreng', '🍗', 'noun', [], 'fried chicken'],
      ['bring', 'membawa', '👜', 'verb', ['brings'], 'Rafi will bring his ball.'],
      ['hope', 'berharap', '🙏', 'verb', ['hopes'], 'We hope it will be sunny!'],
    ],
    grammar: [P.willFuture],
    quiz: [
      ['Where will they have a picnic? (Di mana mereka akan berpiknik?)', ['At the botanical garden', 'At school', 'At the mall'], 0, '"We will go to the botanical garden."'],
      ['What will Rafi bring? (Rafi akan membawa apa?)', ['His ball', 'A mat', 'Sandwiches'], 0, '"Rafi will bring his ball."'],
      ['"Will" artinya …', ['Akan', 'Sudah', 'Sedang'], 0, 'Will = akan.'],
    ],
  },
  {
    slug: 'a4-the-lemonade-stand', theme: 'Cooking', emoji: '🍋', title: 'The Lemonade Stand', titleId: 'Kios Limun', minutes: 3,
    sentences: [
      ['Rafi and Dina have an idea.', 'Rafi dan Dina punya ide.'],
      ['They are going to sell lemonade.', 'Mereka akan menjual limun.'],
      ['They squeeze lemons and add sugar and water.', 'Mereka memeras lemon dan menambahkan gula dan air.'],
      ['They make a sign: "Lemonade, 2,000 rupiah".', 'Mereka membuat papan: "Limun, 2.000 rupiah".'],
      ['Neighbors buy many cups.', 'Para tetangga membeli banyak gelas.', true],
      ['They give the money to the school library.', 'Mereka memberikan uangnya ke perpustakaan sekolah.'],
    ],
    vocab: [
      ['idea', 'ide', '💡', 'noun', ['ideas'], 'an idea'],
      ['sell', 'menjual', '🏷️', 'verb', ['sells'], 'They are going to sell lemonade.'],
      ['lemonade', 'limun / air lemon', '🍋', 'noun', [], 'sell lemonade'],
      ['squeeze', 'memeras', '✊', 'verb', ['squeezes'], 'They squeeze lemons.'],
      ['sugar', 'gula', '🍬', 'noun', [], 'add sugar and water'],
      ['sign', 'papan tanda', '🪧', 'noun', ['signs'], 'They make a sign.'],
    ],
    grammar: [P.willFuture],
    quiz: [
      ['What are they going to sell? (Apa yang akan mereka jual?)', ['Lemonade', 'Cookies', 'Toys'], 0, '"They are going to sell lemonade."'],
      ['How much is one cup? (Berapa harga satu gelas?)', ['2,000 rupiah', '5,000 rupiah', '10,000 rupiah'], 0, '"Lemonade, 2,000 rupiah"'],
      ['Where does the money go? (Uangnya untuk apa?)', ['The school library', 'New toys', 'Candy'], 0, '"to the school library"'],
    ],
  },
  {
    slug: 'a4-grandmas-recipe', theme: 'Cooking', emoji: '📜', title: 'Grandma\'s Recipe', titleId: 'Resep Nenek', minutes: 3,
    sentences: [
      ['Grandma has an old recipe book.', 'Nenek punya buku resep tua.'],
      ['Today she teaches Mom to make klepon.', 'Hari ini dia mengajari Ibu membuat klepon.'],
      ['Klepon are green rice balls.', 'Klepon adalah bola-bola tepung beras berwarna hijau.'],
      ['Inside, there is palm sugar.', 'Di dalamnya ada gula merah.'],
      ['They roll the balls in grated coconut.', 'Mereka menggulingkan bola-bola itu di kelapa parut.', true],
      ['When you bite one, sweet syrup comes out!', 'Saat kamu menggigitnya, sirup manis keluar!'],
    ],
    vocab: [
      ['recipe', 'resep', '📜', 'noun', ['recipes'], 'an old recipe book'],
      ['rice balls', 'bola tepung beras', '🟢', 'noun', [], 'green rice balls'],
      ['palm sugar', 'gula merah', '🟤', 'noun', [], 'there is palm sugar'],
      ['grated coconut', 'kelapa parut', '🥥', 'noun', [], 'in grated coconut'],
      ['syrup', 'sirup / cairan manis', '🍯', 'noun', [], 'sweet syrup'],
    ],
    grammar: [P.thereIsAre],
    quiz: [
      ['What do they make? (Apa yang mereka buat?)', ['Klepon', 'Rendang', 'Satay'], 0, '"to make klepon"'],
      ['What color are klepon? (Apa warna klepon?)', ['Green', 'Red', 'White'], 0, '"Klepon are green rice balls."'],
      ['What is inside? (Apa isinya?)', ['Palm sugar', 'Chicken', 'Chocolate'], 0, '"Inside, there is palm sugar."'],
    ],
  },
  {
    slug: 'a4-washing-the-dishes', theme: 'Cooking', emoji: '🧽', title: 'After Dinner', titleId: 'Setelah Makan Malam', minutes: 3,
    sentences: [
      ['Dinner is finished.', 'Makan malam selesai.'],
      ['Everyone helps to clean up.', 'Semua membantu membereskan.'],
      ['Aisyah puts the cups in the sink.', 'Aisyah menaruh cangkir di bak cuci.'],
      ['Rafi washes the plates with soap.', 'Rafi mencuci piring dengan sabun.'],
      ['Dad dries the plates with a cloth.', 'Ayah mengeringkan piring dengan lap.', true],
      ['Mom puts them back on the shelf.', 'Ibu menaruhnya kembali di rak.'],
      ['Many hands make work easy!', 'Banyak tangan membuat pekerjaan mudah!'],
    ],
    vocab: [
      ['finished', 'selesai', '✅', 'adjective', [], 'Dinner is finished.'],
      ['clean up', 'membereskan', '🧹', 'verb', [], 'helps to clean up'],
      ['sink', 'bak cuci', '🚰', 'noun', ['sinks'], 'in the sink'],
      ['dries', 'mengeringkan', '🌬️', 'verb', ['dry'], 'Dad dries the plates.'],
      ['easy', 'mudah', '👌', 'adjective', [], 'make work easy'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Who washes the plates? (Siapa yang mencuci piring?)', ['Rafi', 'Dad', 'Mom'], 0, '"Rafi washes the plates with soap."'],
      ['What does Dad do? (Apa yang Ayah lakukan?)', ['He dries the plates', 'He cooks', 'He sleeps'], 0, '"Dad dries the plates with a cloth."'],
      ['"Many hands make work easy" artinya …', ['Banyak tangan membuat pekerjaan mudah', 'Tangan harus bersih', 'Kerja itu sulit'], 0, 'Kalau bekerja bersama, pekerjaan jadi ringan.'],
    ],
  },

  // ── Minggu 27: Hobi ──────────────────────────────────────────────────────
  {
    slug: 'a4-dinas-drawings', theme: 'Hobbies', emoji: '🖍️', title: 'Dina Loves Drawing', titleId: 'Dina Suka Menggambar', minutes: 3,
    sentences: [
      ['Dina\'s hobby is drawing.', 'Hobi Dina adalah menggambar.'],
      ['She draws every day after school.', 'Dia menggambar setiap hari sepulang sekolah.'],
      ['She draws animals, flowers, and people.', 'Dia menggambar hewan, bunga, dan orang.'],
      ['She uses colored pencils and crayons.', 'Dia memakai pensil warna dan krayon.'],
      ['Her drawings are on the wall of her room.', 'Gambar-gambarnya ada di dinding kamarnya.', true],
      ['One day, she wants to be an artist.', 'Suatu hari nanti, dia ingin menjadi seniman.'],
    ],
    vocab: [
      ['hobby', 'hobi', '🎯', 'noun', ['hobbies'], 'Dina\'s hobby is drawing.'],
      ['drawing', 'menggambar', '🖍️', 'noun', ['draw', 'draws'], 'Dina\'s hobby is drawing.'],
      ['colored pencils', 'pensil warna', '🖍️', 'noun', [], 'colored pencils'],
      ['crayons', 'krayon', '🖍️', 'noun', ['crayon'], 'and crayons'],
      ['drawings', 'gambar-gambar', '🖼️', 'noun', [], 'Her drawings are on the wall.'],
    ],
    grammar: [P.iLike],
    quiz: [
      ['What is Dina\'s hobby? (Apa hobi Dina?)', ['Drawing', 'Swimming', 'Cooking'], 0, '"Dina\'s hobby is drawing."'],
      ['What does she use? (Apa yang dia pakai?)', ['Colored pencils and crayons', 'A camera', 'A guitar'], 0, '"colored pencils and crayons"'],
      ['Where are her drawings? (Di mana gambar-gambarnya?)', ['On the wall of her room', 'In the garbage', 'At the bank'], 0, '"on the wall of her room"'],
    ],
  },
  {
    slug: 'a4-budi-plays-badminton', theme: 'Hobbies', emoji: '🏸', title: 'Budi Plays Badminton', titleId: 'Budi Bermain Bulu Tangkis', minutes: 3,
    sentences: [
      ['Budi loves badminton.', 'Budi sangat suka bulu tangkis.'],
      ['He plays with his father every evening.', 'Dia bermain dengan ayahnya setiap sore.'],
      ['He has a racket and many shuttlecocks.', 'Dia punya raket dan banyak kok.'],
      ['He hits the shuttlecock over the net.', 'Dia memukul kok melewati net.'],
      ['Indonesia has many badminton champions.', 'Indonesia punya banyak juara bulu tangkis.', true],
      ['Budi wants to be a champion too!', 'Budi juga ingin menjadi juara!'],
    ],
    vocab: [
      ['badminton', 'bulu tangkis', '🏸', 'noun', [], 'Budi loves badminton.'],
      ['racket', 'raket', '🏸', 'noun', ['rackets'], 'a racket'],
      ['shuttlecocks', 'kok', '🏸', 'noun', ['shuttlecock'], 'many shuttlecocks'],
      ['hits', 'memukul', '💥', 'verb', ['hit'], 'He hits the shuttlecock.'],
      ['net', 'net / jaring', '🥅', 'noun', [], 'over the net'],
      ['champions', 'juara', '🏆', 'noun', ['champion'], 'badminton champions'],
    ],
    grammar: [P.wantTo],
    quiz: [
      ['Who does Budi play with? (Budi bermain dengan siapa?)', ['His father', 'His teacher', 'His cat'], 0, '"He plays with his father every evening."'],
      ['What does he hit? (Apa yang dia pukul?)', ['The shuttlecock', 'A football', 'A drum'], 0, '"He hits the shuttlecock over the net."'],
      ['What does Budi want to be? (Budi ingin menjadi apa?)', ['A champion', 'A chef', 'A pilot'], 0, '"Budi wants to be a champion too!"'],
    ],
  },
  {
    slug: 'a4-tari-sings', theme: 'Hobbies', emoji: '🎤', title: 'Tari\'s Beautiful Voice', titleId: 'Suara Indah Tari', minutes: 3,
    sentences: [
      ['Tari likes singing.', 'Tari suka bernyanyi.'],
      ['She sings in the school choir.', 'Dia bernyanyi di paduan suara sekolah.'],
      ['She practices every Thursday.', 'Dia berlatih setiap hari Kamis.'],
      ['Her voice is clear and sweet.', 'Suaranya jernih dan merdu.'],
      ['Next month, the choir will sing on stage.', 'Bulan depan, paduan suara akan tampil di panggung.', true],
      ['Tari is excited and a little nervous.', 'Tari bersemangat dan sedikit gugup.'],
    ],
    vocab: [
      ['choir', 'paduan suara', '🎶', 'noun', ['choirs'], 'the school choir'],
      ['practices', 'berlatih', '🎯', 'verb', ['practice'], 'She practices every Thursday.'],
      ['voice', 'suara', '🗣️', 'noun', ['voices'], 'Her voice is clear.'],
      ['clear', 'jernih', '💎', 'adjective', [], 'clear and sweet'],
      ['stage', 'panggung', '🎭', 'noun', ['stages'], 'on stage'],
    ],
    grammar: [P.iLike],
    quiz: [
      ['Where does Tari sing? (Di mana Tari bernyanyi?)', ['In the school choir', 'In the kitchen', 'At the market'], 0, '"She sings in the school choir."'],
      ['When does she practice? (Kapan dia berlatih?)', ['Every Thursday', 'Every Monday', 'Every day'], 0, '"She practices every Thursday."'],
      ['"Choir" artinya …', ['Paduan suara', 'Panggung', 'Gitar'], 0, 'Choir = paduan suara.'],
    ],
  },
  {
    slug: 'a4-collecting-stamps', theme: 'Hobbies', emoji: '📮', title: 'Grandpa\'s Stamps', titleId: 'Perangko Kakek', minutes: 3,
    sentences: [
      ['Grandpa has an interesting hobby.', 'Kakek punya hobi yang menarik.'],
      ['He collects stamps.', 'Dia mengoleksi perangko.'],
      ['He has stamps from many countries.', 'Dia punya perangko dari banyak negara.'],
      ['Some stamps have pictures of animals.', 'Beberapa perangko bergambar hewan.'],
      ['Some are very old.', 'Beberapa sangat tua.', true],
      ['Grandpa keeps them in a special book.', 'Kakek menyimpannya di buku khusus.'],
      ['Rafi wants to start collecting too.', 'Rafi juga ingin mulai mengoleksi.'],
    ],
    vocab: [
      ['interesting', 'menarik', '🤩', 'adjective', [], 'an interesting hobby'],
      ['collects', 'mengoleksi', '🗃️', 'verb', ['collect', 'collecting'], 'He collects stamps.'],
      ['stamps', 'perangko', '📮', 'noun', ['stamp'], 'He collects stamps.'],
      ['countries', 'negara', '🌍', 'noun', ['country'], 'many countries'],
      ['keeps', 'menyimpan', '📥', 'verb', ['keep'], 'Grandpa keeps them.'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What does Grandpa collect? (Apa yang Kakek koleksi?)', ['Stamps', 'Coins', 'Rocks'], 0, '"He collects stamps."'],
      ['Where does he keep them? (Di mana dia menyimpannya?)', ['In a special book', 'In the fridge', 'In his shoes'], 0, '"in a special book"'],
      ['"Interesting" artinya …', ['Membosankan', 'Menarik', 'Menakutkan'], 1, 'Interesting = menarik.'],
    ],
  },
  {
    slug: 'a4-reading-is-my-hobby', theme: 'Hobbies', emoji: '📚', title: 'I Love Reading', titleId: 'Aku Suka Membaca', minutes: 3,
    sentences: [
      ['My hobby is reading.', 'Hobiku membaca.'],
      ['I read comics and storybooks.', 'Aku membaca komik dan buku cerita.'],
      ['I read before I go to sleep.', 'Aku membaca sebelum tidur.'],
      ['Books take me to many places.', 'Buku membawaku ke banyak tempat.'],
      ['I can travel to space or to the bottom of the sea!', 'Aku bisa pergi ke luar angkasa atau ke dasar laut!', true],
      ['Reading makes me smart and happy.', 'Membaca membuatku pintar dan senang.'],
    ],
    vocab: [
      ['reading', 'membaca', '📖', 'noun', ['read'], 'My hobby is reading.'],
      ['go to sleep', 'pergi tidur', '😴', 'verb', [], 'before I go to sleep'],
      ['travel', 'bepergian', '🧳', 'verb', ['travels'], 'I can travel to space.'],
      ['space', 'luar angkasa', '🚀', 'noun', [], 'to space'],
      ['bottom', 'dasar / bagian bawah', '⬇️', 'noun', [], 'the bottom of the sea'],
    ],
    grammar: [P.iCan],
    quiz: [
      ['What does Rafi read? (Apa yang Rafi baca?)', ['Comics and storybooks', 'Newspapers', 'Letters'], 0, '"I read comics and storybooks."'],
      ['When does he read? (Kapan dia membaca?)', ['Before he goes to sleep', 'While he eats', 'At the pool'], 0, '"I read before I go to sleep."'],
      ['How does reading make him feel? (Membaca membuatnya …)', ['Smart and happy', 'Tired and sad', 'Angry'], 0, '"Reading makes me smart and happy."'],
    ],
  },
  {
    slug: 'a4-fishing-with-grandpa', theme: 'Hobbies', emoji: '🎣', title: 'Fishing with Grandpa', titleId: 'Memancing Bersama Kakek', minutes: 3,
    sentences: [
      ['Grandpa likes fishing.', 'Kakek suka memancing.'],
      ['He takes Rafi to the lake.', 'Dia mengajak Rafi ke danau.'],
      ['They sit quietly with their fishing rods.', 'Mereka duduk dengan tenang memegang joran.'],
      ['They wait and wait.', 'Mereka menunggu dan menunggu.'],
      ['Suddenly, Rafi\'s rod moves! He pulls hard.', 'Tiba-tiba, joran Rafi bergerak! Dia menariknya kuat-kuat.', true],
      ['He catches a big fish!', 'Dia menangkap ikan besar!'],
      ['Fishing teaches us to be patient.', 'Memancing mengajari kita untuk sabar.'],
    ],
    vocab: [
      ['fishing', 'memancing', '🎣', 'noun', [], 'Grandpa likes fishing.'],
      ['lake', 'danau', '🏞️', 'noun', ['lakes'], 'to the lake'],
      ['quietly', 'dengan tenang', '🤫', 'adverb', [], 'They sit quietly.'],
      ['fishing rods', 'joran / pancing', '🎣', 'noun', ['fishing rod', 'rod'], 'their fishing rods'],
      ['pulls', 'menarik', '💪', 'verb', ['pull'], 'He pulls hard.'],
    ],
    grammar: [P.iLike],
    quiz: [
      ['Where do they go? (Mereka pergi ke mana?)', ['To the lake', 'To the sea', 'To the market'], 0, '"He takes Rafi to the lake."'],
      ['What does Rafi catch? (Apa yang Rafi tangkap?)', ['A big fish', 'A frog', 'A shoe'], 0, '"He catches a big fish!"'],
      ['Fishing teaches us to be … (Memancing mengajari kita untuk …)', ['Patient', 'Noisy', 'Fast'], 0, '"Fishing teaches us to be patient."'],
    ],
  },
  {
    slug: 'a4-aisyahs-hobby-dancing', theme: 'Hobbies', emoji: '💃', title: 'Aisyah Dances', titleId: 'Aisyah Menari', minutes: 3,
    sentences: [
      ['Aisyah likes dancing.', 'Aisyah suka menari.'],
      ['She takes a traditional dance class.', 'Dia ikut kelas tari tradisional.'],
      ['She learns the Saman dance from Aceh.', 'Dia belajar tari Saman dari Aceh.'],
      ['The dancers sit in a line.', 'Para penari duduk berbaris.'],
      ['They clap and move fast together.', 'Mereka bertepuk dan bergerak cepat bersama.', true],
      ['Aisyah practices at home every day.', 'Aisyah berlatih di rumah setiap hari.'],
    ],
    vocab: [
      ['dancing', 'menari', '💃', 'noun', ['dance'], 'Aisyah likes dancing.'],
      ['traditional', 'tradisional', '🪘', 'adjective', [], 'a traditional dance class'],
      ['learns', 'belajar', '📚', 'verb', ['learn'], 'She learns the Saman dance.'],
      ['dancers', 'penari', '🕺', 'noun', ['dancer'], 'The dancers sit in a line.'],
      ['move', 'bergerak', '↔️', 'verb', ['moves'], 'move fast together'],
    ],
    grammar: [P.iLike],
    quiz: [
      ['What dance does Aisyah learn? (Tari apa yang Aisyah pelajari?)', ['Saman', 'Ballet', 'Hip hop'], 0, '"She learns the Saman dance."'],
      ['Where is the Saman dance from? (Tari Saman berasal dari mana?)', ['Aceh', 'Bali', 'Papua'], 0, '"from Aceh"'],
      ['How do the dancers sit? (Bagaimana para penari duduk?)', ['In a line', 'In a circle', 'On chairs'], 0, '"The dancers sit in a line."'],
    ],
  },

  // ── Minggu 28: Kesehatan ─────────────────────────────────────────────────
  {
    slug: 'a4-i-have-a-cold', theme: 'Health', emoji: '🤧', title: 'I Have a Cold', titleId: 'Aku Pilek', minutes: 3,
    sentences: [
      ['Achoo! Rafi sneezes.', 'Hatsyi! Rafi bersin.'],
      ['He has a cold.', 'Dia pilek.'],
      ['His nose is runny and his throat hurts.', 'Hidungnya meler dan tenggorokannya sakit.'],
      ['Mom makes him warm ginger tea.', 'Ibu membuatkannya teh jahe hangat.'],
      ['He stays home and rests in bed.', 'Dia tinggal di rumah dan beristirahat di tempat tidur.', true],
      ['He covers his mouth when he sneezes.', 'Dia menutup mulutnya saat bersin.'],
      ['After three days, he feels better.', 'Setelah tiga hari, dia merasa lebih baik.'],
    ],
    vocab: [
      ['sneezes', 'bersin', '🤧', 'verb', ['sneeze'], 'Rafi sneezes.'],
      ['cold', 'pilek / flu', '🤒', 'noun', [], 'He has a cold.'],
      ['runny', 'meler', '💧', 'adjective', [], 'His nose is runny.'],
      ['throat', 'tenggorokan', '🗣️', 'noun', [], 'his throat hurts'],
      ['ginger', 'jahe', '🫚', 'noun', [], 'warm ginger tea'],
      ['rests', 'beristirahat', '🛌', 'verb', ['rest'], 'He rests in bed.'],
    ],
    grammar: [P.iHave],
    quiz: [
      ['What does Mom make for Rafi? (Ibu membuatkan Rafi apa?)', ['Ginger tea', 'Ice cream', 'Soda'], 0, '"warm ginger tea"'],
      ['What does Rafi do when he sneezes? (Apa yang Rafi lakukan saat bersin?)', ['He covers his mouth', 'He laughs', 'He runs'], 0, '"He covers his mouth when he sneezes."'],
      ['When does he feel better? (Kapan dia merasa lebih baik?)', ['After three days', 'After one hour', 'After one month'], 0, '"After three days"'],
    ],
  },
  {
    slug: 'a4-visiting-the-dentist', theme: 'Health', emoji: '🦷', title: 'Visiting the Dentist', titleId: 'Ke Dokter Gigi', minutes: 3,
    sentences: [
      ['Aisyah has a toothache.', 'Aisyah sakit gigi.'],
      ['Mom takes her to the dentist.', 'Ibu membawanya ke dokter gigi.'],
      ['The dentist is friendly.', 'Dokter giginya ramah.'],
      ['"Open your mouth wide, please."', '"Tolong buka mulutmu lebar-lebar."'],
      ['She finds a small hole in one tooth.', 'Dia menemukan lubang kecil di satu gigi.', true],
      ['She fixes it. It does not hurt much.', 'Dia memperbaikinya. Tidak terlalu sakit.'],
      ['"Eat less candy and brush your teeth!"', '"Kurangi permen dan sikat gigimu!"'],
    ],
    vocab: [
      ['toothache', 'sakit gigi', '🦷', 'noun', [], 'Aisyah has a toothache.'],
      ['dentist', 'dokter gigi', '🧑‍⚕️', 'noun', ['dentists'], 'to the dentist'],
      ['friendly', 'ramah', '😊', 'adjective', [], 'The dentist is friendly.'],
      ['wide', 'lebar', '↔️', 'adverb', [], 'Open your mouth wide.'],
      ['less', 'lebih sedikit', '➖', 'adjective', [], 'Eat less candy.'],
    ],
    grammar: [P.commands],
    quiz: [
      ['What is wrong with Aisyah? (Apa yang dialami Aisyah?)', ['A toothache', 'A fever', 'A broken leg'], 0, '"Aisyah has a toothache."'],
      ['What does the dentist find? (Apa yang ditemukan dokter gigi?)', ['A small hole in one tooth', 'A candy', 'A coin'], 0, '"a small hole in one tooth"'],
      ['What advice does the dentist give? (Apa nasihat dokter gigi?)', ['Eat less candy and brush your teeth', 'Eat more candy', 'Don\'t go to school'], 0, '"Eat less candy and brush your teeth!"'],
    ],
  },
  {
    slug: 'a4-sleep-is-important', theme: 'Health', emoji: '😴', title: 'Why We Sleep', titleId: 'Mengapa Kita Tidur', minutes: 3,
    sentences: [
      ['Every night, our body needs sleep.', 'Setiap malam, tubuh kita butuh tidur.'],
      ['Children need about ten hours of sleep.', 'Anak-anak butuh tidur sekitar sepuluh jam.'],
      ['When we sleep, our body grows and gets strong.', 'Saat kita tidur, tubuh kita tumbuh dan menjadi kuat.'],
      ['Our brain rests too.', 'Otak kita juga beristirahat.'],
      ['Without sleep, we feel tired and grumpy.', 'Tanpa tidur, kita merasa lelah dan rewel.', true],
      ['So turn off the TV and go to bed early!', 'Jadi matikan TV dan tidurlah lebih awal!'],
    ],
    vocab: [
      ['sleep', 'tidur', '😴', 'noun', [], 'our body needs sleep'],
      ['about', 'sekitar', '≈', 'adverb', [], 'about ten hours'],
      ['hours', 'jam', '⏰', 'noun', ['hour'], 'ten hours of sleep'],
      ['grumpy', 'rewel / mudah marah', '😤', 'adjective', [], 'tired and grumpy'],
      ['turn off', 'mematikan', '📴', 'verb', [], 'turn off the TV'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['How many hours of sleep do children need? (Anak butuh tidur berapa jam?)', ['About five', 'About ten', 'About twenty'], 1, '"about ten hours of sleep"'],
      ['What happens without sleep? (Apa yang terjadi tanpa tidur?)', ['We feel tired and grumpy', 'We grow taller', 'We are happy'], 0, '"we feel tired and grumpy"'],
      ['"Turn off" artinya …', ['Menyalakan', 'Mematikan', 'Membuka'], 1, 'Turn off = mematikan.'],
    ],
  },
  {
    slug: 'a4-eat-your-vegetables', theme: 'Health', emoji: '🥦', title: 'Eat Your Vegetables!', titleId: 'Makan Sayurmu!', minutes: 3,
    sentences: [
      ['Budi doesn\'t like vegetables.', 'Budi tidak suka sayur.'],
      ['He only eats rice and fried chicken.', 'Dia hanya makan nasi dan ayam goreng.'],
      ['One day, he feels weak and tired.', 'Suatu hari, dia merasa lemas dan lelah.'],
      ['His mom says, "Vegetables give you energy."', 'Ibunya berkata, "Sayur memberimu tenaga."'],
      ['Budi tries carrots and broccoli.', 'Budi mencoba wortel dan brokoli.', true],
      ['"Hmm, not bad!" he says.', '"Hmm, lumayan!" katanya.'],
      ['Now he eats vegetables every day.', 'Sekarang dia makan sayur setiap hari.'],
    ],
    vocab: [
      ['only', 'hanya', '☝️', 'adverb', [], 'He only eats rice.'],
      ['weak', 'lemas / lemah', '😩', 'adjective', [], 'he feels weak'],
      ['energy', 'tenaga / energi', '⚡', 'noun', [], 'Vegetables give you energy.'],
      ['tries', 'mencoba', '🥄', 'verb', ['try'], 'Budi tries carrots.'],
      ['broccoli', 'brokoli', '🥦', 'noun', [], 'carrots and broccoli'],
    ],
    grammar: [P.iLike],
    quiz: [
      ['What does Budi eat at first? (Apa yang Budi makan awalnya?)', ['Only rice and fried chicken', 'Only vegetables', 'Only fruit'], 0, '"He only eats rice and fried chicken."'],
      ['What do vegetables give us? (Sayur memberi kita apa?)', ['Energy', 'Toothache', 'Sleep'], 0, '"Vegetables give you energy."'],
      ['What does Budi try? (Apa yang Budi coba?)', ['Carrots and broccoli', 'Durian', 'Candy'], 0, '"Budi tries carrots and broccoli."'],
    ],
  },
  {
    slug: 'a4-morning-exercise', theme: 'Health', emoji: '🤸', title: 'Morning Exercise', titleId: 'Senam Pagi', minutes: 3,
    sentences: [
      ['Every Friday, our school has morning exercise.', 'Setiap Jumat, sekolah kami mengadakan senam pagi.'],
      ['We stand in the schoolyard.', 'Kami berdiri di halaman sekolah.'],
      ['The music starts. One, two, three, four!', 'Musik dimulai. Satu, dua, tiga, empat!'],
      ['We jump, bend, and turn.', 'Kami melompat, membungkuk, dan berputar.'],
      ['We swing our arms up and down.', 'Kami mengayunkan tangan ke atas dan ke bawah.', true],
      ['Exercise makes our bodies healthy and strong.', 'Olahraga membuat tubuh kita sehat dan kuat.'],
    ],
    vocab: [
      ['exercise', 'senam / olahraga', '🤸', 'noun', [], 'morning exercise'],
      ['music', 'musik', '🎵', 'noun', [], 'The music starts.'],
      ['bend', 'membungkuk', '🙇', 'verb', ['bends'], 'We jump, bend, and turn.'],
      ['turn', 'berputar', '🔄', 'verb', ['turns'], 'bend, and turn'],
      ['swing', 'mengayunkan', '🙆', 'verb', ['swings'], 'We swing our arms.'],
    ],
    grammar: [P.daysOfWeek],
    quiz: [
      ['When is morning exercise? (Kapan senam pagi?)', ['Every Friday', 'Every Monday', 'Every Sunday'], 0, '"Every Friday"'],
      ['Where do they stand? (Di mana mereka berdiri?)', ['In the schoolyard', 'In the library', 'At home'], 0, '"We stand in the schoolyard."'],
      ['What does exercise do? (Apa manfaat olahraga?)', ['Makes our bodies healthy and strong', 'Makes us sleepy', 'Makes us hungry only'], 0, '"Exercise makes our bodies healthy and strong."'],
    ],
  },
  {
    slug: 'a4-a-scraped-knee', theme: 'Health', emoji: '🩹', title: 'A Scraped Knee', titleId: 'Lutut Lecet', minutes: 3,
    sentences: [
      ['Rafi falls off his bike.', 'Rafi jatuh dari sepedanya.'],
      ['He scrapes his knee. It is bleeding a little.', 'Lututnya lecet. Sedikit berdarah.'],
      ['Mom cleans the wound with clean water.', 'Ibu membersihkan lukanya dengan air bersih.'],
      ['She puts on some medicine.', 'Dia mengoleskan sedikit obat.'],
      ['Then she covers it with a bandage.', 'Lalu dia menutupnya dengan plester.', true],
      ['"You are brave," says Mom.', '"Kamu pemberani," kata Ibu.'],
      ['Next time, Rafi will ride more carefully.', 'Lain kali, Rafi akan bersepeda lebih hati-hati.'],
    ],
    vocab: [
      ['falls off', 'jatuh dari', '🚲', 'verb', ['fall off'], 'Rafi falls off his bike.'],
      ['scrapes', 'tergores / lecet', '🩹', 'verb', ['scrape'], 'He scrapes his knee.'],
      ['bleeding', 'berdarah', '🩸', 'verb', ['bleed'], 'It is bleeding a little.'],
      ['wound', 'luka', '🤕', 'noun', ['wounds'], 'the wound'],
      ['bandage', 'plester / perban', '🩹', 'noun', ['bandages'], 'with a bandage'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What happens to Rafi? (Apa yang terjadi pada Rafi?)', ['He falls off his bike', 'He gets a cold', 'He loses his bag'], 0, '"Rafi falls off his bike."'],
      ['What does Mom use to clean the wound? (Ibu membersihkan luka dengan apa?)', ['Clean water', 'Juice', 'Sand'], 0, '"with clean water"'],
      ['"Bandage" artinya …', ['Plester / perban', 'Obat', 'Air'], 0, 'Bandage = plester / perban.'],
    ],
  },
  {
    slug: 'a4-my-healthy-day', theme: 'Health', emoji: '💚', title: 'My Healthy Day', titleId: 'Hari Sehatku', minutes: 3,
    sentences: [
      ['I wake up early and drink a glass of water.', 'Aku bangun pagi dan minum segelas air.'],
      ['I eat a good breakfast.', 'Aku sarapan dengan baik.'],
      ['I walk to school and play outside.', 'Aku berjalan ke sekolah dan bermain di luar.'],
      ['I eat fruit and vegetables.', 'Aku makan buah dan sayur.'],
      ['I wash my hands often.', 'Aku sering mencuci tangan.', true],
      ['I go to bed early.', 'Aku tidur lebih awal.'],
      ['A healthy day makes a happy me!', 'Hari yang sehat membuatku bahagia!'],
    ],
    vocab: [
      ['early', 'pagi-pagi / lebih awal', '🌅', 'adverb', [], 'I wake up early.'],
      ['good', 'baik / bagus', '👍', 'adjective', [], 'a good breakfast'],
      ['outside', 'di luar', '🌳', 'adverb', [], 'play outside'],
      ['often', 'sering', '🔁', 'adverb', [], 'I wash my hands often.'],
      ['healthy', 'sehat', '💚', 'adjective', [], 'A healthy day'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What does Rafi drink when he wakes up? (Apa yang Rafi minum saat bangun?)', ['A glass of water', 'Coffee', 'Soda'], 0, '"drink a glass of water"'],
      ['How often does he wash his hands? (Seberapa sering dia mencuci tangan?)', ['Often', 'Never', 'Once a year'], 0, '"I wash my hands often."'],
      ['"Often" artinya …', ['Sering', 'Jarang', 'Tidak pernah'], 0, 'Often = sering.'],
    ],
  },
];
