// Daily English Reading — Fase B (SD Kelas 3–4), CEFR Pre-A1 → A1.
// 8–11 kalimat, mulai mengenal simple past, comparative, "going to", dan "should"; kuis 4 soal.

import type { SeedReading } from './types';

export const englishPhaseB: SeedReading[] = [
  {
    slug: 'b-my-daily-routine',
    theme: 'Daily Routine',
    emoji: '⏰',
    title: 'My Daily Routine',
    titleId: 'Kegiatan Harianku',
    minutes: 4,
    sentences: [
      ['My name is Fajar and I am nine years old.', 'Namaku Fajar dan aku berumur sembilan tahun.'],
      ['I wake up at five o\'clock every morning.', 'Aku bangun jam lima setiap pagi.'],
      ['I pray Subuh with my father.', 'Aku salat Subuh bersama ayahku.'],
      ['Then I take a shower and put on my uniform.', 'Lalu aku mandi dan memakai seragam.'],
      ['At half past six, I have breakfast with my family.', 'Pukul setengah tujuh, aku sarapan bersama keluargaku.', true],
      ['I go to school by bicycle.', 'Aku pergi ke sekolah naik sepeda.'],
      ['School starts at seven o\'clock and finishes at twelve.', 'Sekolah dimulai jam tujuh dan selesai jam dua belas.'],
      ['In the afternoon, I do my homework and play football.', 'Pada sore hari, aku mengerjakan PR dan bermain sepak bola.', true],
      ['I usually go to bed at nine o\'clock.', 'Aku biasanya tidur jam sembilan.'],
    ],
    vocab: [
      ['wake up', 'bangun tidur', '⏰', 'verb', [], 'I wake up at five o\'clock.'],
      ['uniform', 'seragam', '👔', 'noun', [], 'I put on my uniform.'],
      ['shower', 'mandi (pancuran)', '🚿', 'noun', [], 'I take a shower.'],
      ['homework', 'pekerjaan rumah (PR)', '📝', 'noun', [], 'I do my homework.'],
      ['usually', 'biasanya', '🔁', 'adverb', [], 'I usually go to bed at nine.'],
      ['finishes', 'selesai', '🏁', 'verb', ['finish'], 'School finishes at twelve.'],
    ],
    grammar: [
      {
        title: 'Pola: Kebiasaan sehari-hari (Simple Present)',
        pattern: 'I + kata kerja · He/She + kata kerja + s',
        explanation:
          'Untuk kebiasaan yang dilakukan setiap hari, pakai kata kerja bentuk dasar. Jika subjeknya he/she/it, tambahkan -s atau -es (start → starts, finish → finishes).',
        examples: ['I wake up at five o\'clock.', 'School starts at seven o\'clock.'],
      },
      {
        title: 'Kata keterangan frekuensi',
        pattern: 'always · usually · sometimes · never',
        explanation: 'Kata ini menunjukkan seberapa sering kita melakukan sesuatu, diletakkan sebelum kata kerja.',
        examples: ['I usually go to bed at nine o\'clock.'],
      },
    ],
    quiz: [
      ['What time does Fajar wake up?', ['At five o\'clock', 'At six o\'clock', 'At seven o\'clock'], 0, '"I wake up at five o\'clock every morning."'],
      ['How does Fajar go to school?', ['By bus', 'By bicycle', 'On foot'], 1, '"I go to school by bicycle."'],
      ['What does Fajar do in the afternoon?', ['He sleeps', 'He does homework and plays football', 'He goes to the market'], 1, '"I do my homework and play football."'],
      ['"School ___ at seven o\'clock." Pilih kata yang tepat.', ['start', 'starts', 'starting'], 1, 'Subjek "school" = it, jadi starts.'],
    ],
  },
  {
    slug: 'b-grandmas-village',
    theme: 'Holiday',
    emoji: '🏡',
    title: 'A Visit to Grandma\'s Village',
    titleId: 'Berkunjung ke Desa Nenek',
    minutes: 4,
    sentences: [
      ['Last holiday, my family visited Grandma\'s village.', 'Liburan lalu, keluargaku mengunjungi desa Nenek.'],
      ['We went there by train.', 'Kami pergi ke sana naik kereta api.'],
      ['The trip took five hours.', 'Perjalanannya memakan waktu lima jam.'],
      ['Grandma\'s house was small, but the garden was very big.', 'Rumah Nenek kecil, tetapi kebunnya sangat besar.', true],
      ['There were many chickens and two goats.', 'Ada banyak ayam dan dua ekor kambing.'],
      ['Every morning, I helped Grandma collect eggs.', 'Setiap pagi, aku membantu Nenek mengumpulkan telur.'],
      ['In the afternoon, we played in the rice field and flew kites.', 'Sore harinya, kami bermain di sawah dan menerbangkan layang-layang.', true],
      ['The air in the village was fresh and cool.', 'Udara di desa segar dan sejuk.'],
      ['I was sad when the holiday ended.', 'Aku sedih ketika liburan berakhir.'],
    ],
    vocab: [
      ['village', 'desa', '🏘️', 'noun', [], 'Grandma\'s village'],
      ['visited', 'mengunjungi', '🚶', 'verb', ['visit'], 'My family visited Grandma.'],
      ['trip', 'perjalanan', '🧳', 'noun', [], 'The trip took five hours.'],
      ['collect', 'mengumpulkan', '🧺', 'verb', [], 'collect eggs'],
      ['rice field', 'sawah', '🌾', 'noun', [], 'We played in the rice field.'],
      ['kite', 'layang-layang', '🪁', 'noun', ['kites'], 'We flew kites.'],
    ],
    grammar: [
      {
        title: 'Pola: Cerita masa lalu (Simple Past)',
        pattern: 'Kata kerja + ed · atau bentuk khusus (go → went, fly → flew)',
        explanation:
          'Untuk menceritakan kejadian yang sudah lewat, kata kerja berubah. Kebanyakan ditambah -ed (visit → visited, help → helped). Ada juga yang berubah bentuk: go → went, take → took, fly → flew.',
        examples: ['We went there by train.', 'I helped Grandma collect eggs.'],
      },
      {
        title: 'was / were (am, is, are di masa lalu)',
        pattern: 'I/he/she/it + was · we/you/they + were',
        explanation: 'Is dan am berubah menjadi was; are berubah menjadi were.',
        examples: ['Grandma\'s house was small.', 'There were many chickens.'],
      },
    ],
    quiz: [
      ['How did the family go to the village?', ['By car', 'By train', 'By plane'], 1, '"We went there by train."'],
      ['What did the writer help Grandma do?', ['Cook rice', 'Collect eggs', 'Feed the goats'], 1, '"I helped Grandma collect eggs."'],
      ['How was the air in the village?', ['Hot and dusty', 'Fresh and cool', 'Smoky'], 1, '"The air in the village was fresh and cool."'],
      ['Bentuk lampau dari "go" adalah …', ['goed', 'went', 'gone'], 1, 'Go → went (bentuk khusus).'],
    ],
  },
  {
    slug: 'b-our-class-hamster',
    theme: 'Animals',
    emoji: '🐹',
    title: 'Our Class Hamster',
    titleId: 'Hamster Kelas Kami',
    minutes: 4,
    sentences: [
      ['Our class has a pet hamster.', 'Kelas kami punya hamster peliharaan.'],
      ['His name is Kiko.', 'Namanya Kiko.'],
      ['Kiko is small, round, and brown.', 'Kiko kecil, bulat, dan berwarna cokelat.'],
      ['He lives in a cage near the window.', 'Dia tinggal di kandang dekat jendela.'],
      ['Every day, two students take care of Kiko.', 'Setiap hari, dua murid merawat Kiko.', true],
      ['They give him seeds, vegetables, and fresh water.', 'Mereka memberinya biji-bijian, sayuran, dan air bersih.'],
      ['Kiko sleeps during the day and runs on his wheel at night.', 'Kiko tidur pada siang hari dan berlari di rodanya pada malam hari.'],
      ['He keeps food in his cheeks.', 'Dia menyimpan makanan di pipinya.', true],
      ['We love Kiko because he is cute and funny.', 'Kami sayang Kiko karena dia lucu dan menggemaskan.'],
    ],
    vocab: [
      ['pet', 'hewan peliharaan', '🐾', 'noun', [], 'a pet hamster'],
      ['cage', 'kandang', '🪺', 'noun', [], 'He lives in a cage.'],
      ['take care of', 'merawat', '🤲', 'verb', [], 'take care of Kiko'],
      ['seeds', 'biji-bijian', '🌻', 'noun', ['seed'], 'They give him seeds.'],
      ['wheel', 'roda', '🎡', 'noun', [], 'runs on his wheel'],
      ['cheeks', 'pipi', '😊', 'noun', ['cheek'], 'food in his cheeks'],
    ],
    grammar: [
      {
        title: 'Pola: because (karena)',
        pattern: 'Kalimat + because + alasan',
        explanation: 'Because artinya "karena". Kita memakainya untuk memberi alasan.',
        examples: ['We love Kiko because he is cute and funny.'],
      },
    ],
    quiz: [
      ['What is the hamster\'s name?', ['Kiki', 'Kiko', 'Koko'], 1, '"His name is Kiko."'],
      ['Where does Kiko live?', ['In a box under the table', 'In a cage near the window', 'In the garden'], 1, '"He lives in a cage near the window."'],
      ['When does Kiko run on his wheel?', ['In the morning', 'During the day', 'At night'], 2, '"Kiko … runs on his wheel at night."'],
      ['Where does Kiko keep food?', ['In his cheeks', 'Under his bed', 'In his tail'], 0, '"He keeps food in his cheeks."'],
    ],
  },
  {
    slug: 'b-the-school-canteen',
    theme: 'Food',
    emoji: '🍱',
    title: 'At the School Canteen',
    titleId: 'Di Kantin Sekolah',
    minutes: 4,
    sentences: [
      ['It is break time.', 'Sekarang waktu istirahat.'],
      ['Nadia and Bima go to the school canteen.', 'Nadia dan Bima pergi ke kantin sekolah.'],
      ['"What would you like?" asks Mrs. Wati, the seller.', '"Mau pesan apa?" tanya Bu Wati, si penjual.'],
      ['"I would like chicken porridge, please," says Nadia.', '"Saya mau bubur ayam," kata Nadia.', true],
      ['"How much is it?"', '"Berapa harganya?"'],
      ['"It is eight thousand rupiah."', '"Delapan ribu rupiah."'],
      ['Bima wants fried noodles and orange juice.', 'Bima mau mi goreng dan jus jeruk.', true],
      ['They sit together and eat their food.', 'Mereka duduk bersama dan makan.'],
      ['After eating, they throw the rubbish in the bin.', 'Setelah makan, mereka membuang sampah ke tempat sampah.'],
    ],
    vocab: [
      ['break time', 'waktu istirahat', '🔔', 'noun', [], 'It is break time.'],
      ['canteen', 'kantin', '🏪', 'noun', [], 'the school canteen'],
      ['seller', 'penjual', '🧑‍🍳', 'noun', [], 'Mrs. Wati, the seller'],
      ['porridge', 'bubur', '🥣', 'noun', [], 'chicken porridge'],
      ['noodles', 'mi', '🍜', 'noun', [], 'fried noodles'],
      ['bin', 'tempat sampah', '🗑️', 'noun', [], 'in the bin'],
    ],
    grammar: [
      {
        title: 'Pola: Memesan dengan sopan',
        pattern: 'What would you like? · I would like …, please.',
        explanation:
          '"Would like" adalah cara sopan untuk mengatakan "mau/ingin". Tambahkan please supaya lebih santun.',
        examples: ['What would you like?', 'I would like chicken porridge, please.'],
      },
    ],
    quiz: [
      ['Who is Mrs. Wati?', ['A teacher', 'The seller', 'Nadia\'s mother'], 1, '"Mrs. Wati, the seller."'],
      ['What does Nadia order?', ['Fried noodles', 'Chicken porridge', 'Orange juice'], 1, '"I would like chicken porridge, please."'],
      ['How much is Nadia\'s food?', ['Five thousand rupiah', 'Eight thousand rupiah', 'Ten thousand rupiah'], 1, '"It is eight thousand rupiah."'],
      ['What do they do after eating?', ['Go home', 'Throw the rubbish in the bin', 'Buy more food'], 1, '"They throw the rubbish in the bin."'],
    ],
  },
  {
    slug: 'b-sports-day',
    theme: 'Sports',
    emoji: '🏃',
    title: 'Sports Day',
    titleId: 'Hari Olahraga',
    minutes: 4,
    sentences: [
      ['Yesterday was Sports Day at my school.', 'Kemarin adalah Hari Olahraga di sekolahku.'],
      ['There were many races and games.', 'Ada banyak lomba dan permainan.'],
      ['I joined the running race with Doni and Rara.', 'Aku ikut lomba lari bersama Doni dan Rara.'],
      ['Doni is taller than me, so his legs are longer.', 'Doni lebih tinggi dariku, jadi kakinya lebih panjang.', true],
      ['But I ran faster than Doni!', 'Tapi aku berlari lebih cepat daripada Doni!'],
      ['Rara was the fastest runner of all.', 'Rara adalah pelari tercepat dari semuanya.'],
      ['She won the gold medal.', 'Dia memenangkan medali emas.'],
      ['I got the silver medal.', 'Aku mendapat medali perak.', true],
      ['It was a happy day for everyone.', 'Itu hari yang menyenangkan bagi semua orang.'],
    ],
    vocab: [
      ['race', 'lomba (adu cepat)', '🏁', 'noun', ['races'], 'the running race'],
      ['joined', 'ikut', '🙋', 'verb', ['join'], 'I joined the race.'],
      ['faster', 'lebih cepat', '💨', 'adjective', ['fast', 'fastest'], 'I ran faster than Doni.'],
      ['taller', 'lebih tinggi', '📏', 'adjective', ['tall'], 'Doni is taller than me.'],
      ['won', 'memenangkan', '🏆', 'verb', ['win'], 'She won the gold medal.'],
      ['medal', 'medali', '🥇', 'noun', [], 'the gold medal'],
    ],
    grammar: [
      {
        title: 'Membandingkan (Comparative & Superlative)',
        pattern: 'tall → taller than → the tallest',
        explanation:
          'Untuk membandingkan dua hal, tambahkan -er dan than ("lebih … daripada"). Untuk yang paling, pakai the + -est.',
        examples: ['Doni is taller than me.', 'I ran faster than Doni.', 'Rara was the fastest runner of all.'],
      },
    ],
    quiz: [
      ['Who is taller, Doni or the writer?', ['Doni', 'The writer', 'They are the same'], 0, '"Doni is taller than me."'],
      ['Who won the gold medal?', ['Doni', 'Rara', 'The writer'], 1, '"Rara was the fastest… She won the gold medal."'],
      ['What medal did the writer get?', ['Gold', 'Silver', 'Bronze'], 1, '"I got the silver medal."'],
      ['"An elephant is ___ than a cat."', ['big', 'bigger', 'biggest'], 1, 'Membandingkan dua hal → bigger than.'],
    ],
  },
  {
    slug: 'b-my-hobby',
    theme: 'Hobbies',
    emoji: '🎨',
    title: 'My Favorite Hobby',
    titleId: 'Hobi Favoritku',
    minutes: 4,
    sentences: [
      ['I have many hobbies, but my favorite is drawing.', 'Aku punya banyak hobi, tapi favoritku adalah menggambar.'],
      ['I like drawing animals and cartoon characters.', 'Aku suka menggambar hewan dan tokoh kartun.'],
      ['I use pencils, crayons, and watercolors.', 'Aku memakai pensil, krayon, dan cat air.'],
      ['My brother likes reading comics.', 'Kakakku suka membaca komik.', true],
      ['My sister enjoys singing and dancing.', 'Adik perempuanku senang menyanyi dan menari.'],
      ['My father likes fishing on Sunday mornings.', 'Ayahku suka memancing pada Minggu pagi.'],
      ['Last month, I joined a drawing competition.', 'Bulan lalu, aku ikut lomba menggambar.', true],
      ['I drew a picture of a big tiger.', 'Aku menggambar seekor harimau besar.'],
      ['I didn\'t win, but I was very proud.', 'Aku tidak menang, tapi aku sangat bangga.'],
    ],
    vocab: [
      ['hobby', 'hobi / kegemaran', '🎯', 'noun', ['hobbies'], 'my favorite hobby'],
      ['drawing', 'menggambar', '✏️', 'verb', ['draw', 'drew'], 'I like drawing animals.'],
      ['watercolors', 'cat air', '🎨', 'noun', [], 'I use watercolors.'],
      ['enjoys', 'menikmati / senang', '😄', 'verb', ['enjoy'], 'She enjoys singing.'],
      ['fishing', 'memancing', '🎣', 'verb', [], 'My father likes fishing.'],
      ['proud', 'bangga', '🥲', 'adjective', [], 'I was very proud.'],
    ],
    grammar: [
      {
        title: 'Pola: like / enjoy + kata kerja-ing',
        pattern: 'like/enjoy + verb-ing',
        explanation: 'Untuk mengatakan suka melakukan sesuatu, kata kerjanya ditambah -ing setelah like atau enjoy.',
        examples: ['I like drawing animals.', 'My sister enjoys singing and dancing.'],
      },
    ],
    quiz: [
      ['What is the writer\'s favorite hobby?', ['Singing', 'Drawing', 'Fishing'], 1, '"My favorite is drawing."'],
      ['Who likes reading comics?', ['The brother', 'The sister', 'The father'], 0, '"My brother likes reading comics."'],
      ['What did the writer draw for the competition?', ['A cat', 'A big tiger', 'A house'], 1, '"I drew a picture of a big tiger."'],
      ['"She enjoys ___."', ['dance', 'dancing', 'danced'], 1, 'Enjoy + verb-ing → enjoys dancing.'],
    ],
  },
  {
    slug: 'b-the-lost-kitten',
    theme: 'Story',
    emoji: '🐈',
    title: 'The Lost Kitten',
    titleId: 'Anak Kucing yang Tersesat',
    minutes: 4,
    sentences: [
      ['One rainy afternoon, Salsa heard a small sound.', 'Suatu sore yang hujan, Salsa mendengar suara kecil.'],
      ['"Meow… meow…"', '"Meong… meong…"'],
      ['She looked under the car and found a tiny kitten.', 'Dia melihat ke bawah mobil dan menemukan anak kucing yang mungil.'],
      ['The kitten was lost, wet, and hungry.', 'Anak kucing itu tersesat, basah, dan lapar.', true],
      ['Salsa took the kitten inside and dried it with a towel.', 'Salsa membawa anak kucing itu masuk dan mengeringkannya dengan handuk.'],
      ['Her mother gave it some warm milk.', 'Ibunya memberinya susu hangat.'],
      ['The next day, Salsa and her mother made a poster: "Found a Kitten!"', 'Keesokan harinya, Salsa dan ibunya membuat poster: "Ditemukan Anak Kucing!"', true],
      ['A boy from the next street came to their house.', 'Seorang anak laki-laki dari jalan sebelah datang ke rumah mereka.'],
      ['"That is my kitten! Thank you so much!" he said happily.', '"Itu anak kucingku! Terima kasih banyak!" katanya dengan gembira.'],
    ],
    vocab: [
      ['lost', 'tersesat / hilang', '❓', 'adjective', [], 'The Lost Kitten'],
      ['kitten', 'anak kucing', '🐈', 'noun', [], 'a tiny kitten'],
      ['tiny', 'sangat kecil / mungil', '🤏', 'adjective', [], 'a tiny kitten'],
      ['wet', 'basah', '💦', 'adjective', [], 'The kitten was wet.'],
      ['poster', 'poster / selebaran', '📄', 'noun', [], 'made a poster'],
      ['happily', 'dengan gembira', '😃', 'adverb', [], 'he said happily'],
    ],
    grammar: [
      {
        title: 'Simple Past dalam cerita',
        pattern: 'hear → heard · find → found · take → took · give → gave · make → made',
        explanation:
          'Cerita biasanya ditulis dalam bentuk lampau. Banyak kata kerja penting yang berubah bentuk, jadi perlu dihafal sedikit demi sedikit.',
        examples: ['Salsa heard a small sound.', 'She found a tiny kitten.'],
      },
    ],
    quiz: [
      ['Where did Salsa find the kitten?', ['In the garden', 'Under the car', 'On the roof'], 1, '"She looked under the car and found a tiny kitten."'],
      ['How was the kitten?', ['Lost, wet, and hungry', 'Big and strong', 'Happy and dry'], 0, '"The kitten was lost, wet, and hungry."'],
      ['What did Salsa and her mother make?', ['A cake', 'A poster', 'A cage'], 1, 'They made a poster: "Found a Kitten!"'],
      ['Who was the owner of the kitten?', ['A boy from the next street', 'Salsa\'s teacher', 'Salsa\'s brother'], 0, 'A boy from the next street said, "That is my kitten!"'],
    ],
  },
  {
    slug: 'b-trip-to-the-museum',
    theme: 'History & Culture',
    emoji: '🏛️',
    title: 'A Trip to the Museum',
    titleId: 'Darmawisata ke Museum',
    minutes: 5,
    sentences: [
      ['Last Friday, my class went to the National Museum in Jakarta.', 'Jumat lalu, kelasku pergi ke Museum Nasional di Jakarta.'],
      ['People also call it "Museum Gajah" because there is an elephant statue in front of it.', 'Orang juga menyebutnya "Museum Gajah" karena ada patung gajah di depannya.'],
      ['Inside the museum, we saw old statues, ancient tools, and traditional clothes.', 'Di dalam museum, kami melihat arca kuno, peralatan kuno, dan pakaian adat.', true],
      ['Our guide told us stories about the old kingdoms of Indonesia.', 'Pemandu kami menceritakan kisah kerajaan-kerajaan kuno di Indonesia.'],
      ['We were not allowed to touch the objects.', 'Kami tidak boleh menyentuh benda-benda itu.'],
      ['My favorite part was the room full of golden jewelry.', 'Bagian favoritku adalah ruangan yang penuh perhiasan emas.', true],
      ['I wrote notes in my small notebook.', 'Aku menulis catatan di buku catatan kecilku.'],
      ['It was a fun and interesting trip.', 'Itu darmawisata yang menyenangkan dan menarik.'],
    ],
    vocab: [
      ['museum', 'museum', '🏛️', 'noun', [], 'the National Museum'],
      ['statue', 'patung / arca', '🗿', 'noun', ['statues'], 'an elephant statue'],
      ['ancient', 'kuno / sangat tua', '📜', 'adjective', [], 'ancient tools'],
      ['guide', 'pemandu', '🧑‍🏫', 'noun', [], 'Our guide told us stories.'],
      ['kingdom', 'kerajaan', '👑', 'noun', ['kingdoms'], 'the old kingdoms'],
      ['allowed', 'diizinkan / boleh', '✅', 'adjective', [], 'We were not allowed to touch.'],
    ],
    grammar: [
      {
        title: 'Pola: not allowed to (tidak boleh)',
        pattern: 'Subjek + was/were/is/are + not allowed to + kata kerja',
        explanation: 'Ungkapan ini dipakai untuk aturan atau larangan.',
        examples: ['We were not allowed to touch the objects.', 'You are not allowed to run in the library.'],
      },
    ],
    quiz: [
      ['Why do people call it "Museum Gajah"?', ['It has many elephants inside', 'There is an elephant statue in front of it', 'It is very big'], 1, '"… because there is an elephant statue in front of it."'],
      ['Who told stories about old kingdoms?', ['The teacher', 'The guide', 'A friend'], 1, '"Our guide told us stories…"'],
      ['What was the writer\'s favorite part?', ['The statues', 'The room of golden jewelry', 'The canteen'], 1, '"My favorite part was the room full of golden jewelry."'],
      ['Apa yang tidak boleh dilakukan di museum menurut bacaan?', ['Menulis catatan', 'Menyentuh benda', 'Mendengarkan pemandu'], 1, '"We were not allowed to touch the objects."'],
    ],
  },
  {
    slug: 'b-healthy-food',
    theme: 'Health',
    emoji: '🥦',
    title: 'Healthy Food, Strong Body',
    titleId: 'Makanan Sehat, Tubuh Kuat',
    minutes: 4,
    sentences: [
      ['We need healthy food to grow strong and smart.', 'Kita butuh makanan sehat agar tumbuh kuat dan pintar.'],
      ['Rice and bread give us energy.', 'Nasi dan roti memberi kita tenaga.'],
      ['Fish, eggs, and tofu help our muscles grow.', 'Ikan, telur, dan tahu membantu otot kita tumbuh.'],
      ['Vegetables and fruits have many vitamins.', 'Sayur dan buah mengandung banyak vitamin.'],
      ['We should drink water every day, not too many sweet drinks.', 'Kita sebaiknya minum air setiap hari, jangan terlalu banyak minuman manis.', true],
      ['We should not eat too many snacks or fried food.', 'Kita sebaiknya tidak makan terlalu banyak camilan atau gorengan.'],
      ['Before eating, we should always wash our hands.', 'Sebelum makan, kita sebaiknya selalu mencuci tangan.'],
      ['Healthy food makes us happy and full of energy!', 'Makanan sehat membuat kita bahagia dan penuh tenaga!'],
    ],
    vocab: [
      ['healthy', 'sehat', '💪', 'adjective', [], 'healthy food'],
      ['energy', 'tenaga / energi', '⚡', 'noun', [], 'give us energy'],
      ['muscles', 'otot', '🦵', 'noun', ['muscle'], 'help our muscles grow'],
      ['tofu', 'tahu', '🧈', 'noun', [], 'Fish, eggs, and tofu'],
      ['vitamins', 'vitamin', '🍊', 'noun', ['vitamin'], 'many vitamins'],
      ['fried food', 'gorengan', '🍤', 'noun', [], 'too many fried food'],
    ],
    grammar: [
      {
        title: 'Pola: should / should not (sebaiknya)',
        pattern: 'We should + kata kerja · We should not + kata kerja',
        explanation: 'Should dipakai untuk memberi nasihat. Should not (shouldn\'t) berarti sebaiknya tidak dilakukan.',
        examples: ['We should drink water every day.', 'We should not eat too many snacks.'],
      },
    ],
    quiz: [
      ['Which food gives us energy?', ['Rice and bread', 'Water', 'Candy'], 0, '"Rice and bread give us energy."'],
      ['Which food helps our muscles grow?', ['Fish, eggs, and tofu', 'Sweet drinks', 'Fried snacks'], 0, '"Fish, eggs, and tofu help our muscles grow."'],
      ['What should we do before eating?', ['Play games', 'Wash our hands', 'Drink soda'], 1, '"We should always wash our hands."'],
      ['Mana nasihat yang benar?', ['We should eat many snacks.', 'We should drink water every day.', 'We should not eat vegetables.'], 1, 'Minum air setiap hari adalah nasihat yang baik.'],
    ],
  },
  {
    slug: 'b-independence-day',
    theme: 'Indonesia',
    emoji: '🇮🇩',
    title: 'Independence Day Fun',
    titleId: 'Serunya Hari Kemerdekaan',
    minutes: 5,
    sentences: [
      ['Indonesia became independent on 17 August 1945.', 'Indonesia merdeka pada tanggal 17 Agustus 1945.'],
      ['Every year, we celebrate Independence Day with a flag ceremony.', 'Setiap tahun, kita merayakan Hari Kemerdekaan dengan upacara bendera.'],
      ['Our flag is red and white.', 'Bendera kita berwarna merah putih.'],
      ['After the ceremony, there are many fun competitions in my neighborhood.', 'Setelah upacara, ada banyak lomba seru di lingkunganku.', true],
      ['I joined the cracker-eating race.', 'Aku ikut lomba makan kerupuk.'],
      ['My friends joined the sack race.', 'Teman-temanku ikut lomba balap karung.'],
      ['The adults climbed a tall greased pole to get prizes at the top.', 'Orang-orang dewasa memanjat tiang yang licin untuk mendapatkan hadiah di puncaknya.'],
      ['Everyone laughed and cheered.', 'Semua orang tertawa dan bersorak.', true],
      ['I am proud to be Indonesian!', 'Aku bangga menjadi orang Indonesia!'],
    ],
    vocab: [
      ['independent', 'merdeka', '🕊️', 'adjective', ['independence'], 'Indonesia became independent.'],
      ['celebrate', 'merayakan', '🎉', 'verb', [], 'we celebrate Independence Day'],
      ['ceremony', 'upacara', '🎌', 'noun', [], 'a flag ceremony'],
      ['competitions', 'lomba', '🏅', 'noun', ['competition'], 'many fun competitions'],
      ['sack race', 'balap karung', '🛍️', 'noun', [], 'the sack race'],
      ['greased pole', 'tiang licin (panjat pinang)', '🪵', 'noun', [], 'a tall greased pole'],
    ],
    grammar: [
      {
        title: 'Menulis tanggal dalam bahasa Inggris',
        pattern: 'on + tanggal · in + tahun',
        explanation:
          'Untuk tanggal lengkap pakai on (on 17 August 1945). Untuk tahun saja pakai in (in 1945). Untuk bulan saja juga pakai in (in August).',
        examples: ['Indonesia became independent on 17 August 1945.', 'My birthday is in May.'],
      },
    ],
    quiz: [
      ['When did Indonesia become independent?', ['17 August 1945', '17 August 1950', '1 June 1945'], 0, '"Indonesia became independent on 17 August 1945."'],
      ['What are the colors of the Indonesian flag?', ['Red and white', 'Red and blue', 'White and green'], 0, '"Our flag is red and white."'],
      ['Which race did the writer join?', ['The sack race', 'The cracker-eating race', 'The greased pole'], 1, '"I joined the cracker-eating race."'],
      ['"Sack race" dalam bahasa Indonesia adalah …', ['Lomba makan kerupuk', 'Balap karung', 'Panjat pinang'], 1, 'Sack = karung, race = lomba balap.'],
    ],
  },
  {
    slug: 'b-at-the-library',
    theme: 'School',
    emoji: '📚',
    title: 'At the Library',
    titleId: 'Di Perpustakaan',
    minutes: 4,
    sentences: [
      ['Our school library is my favorite place.', 'Perpustakaan sekolah adalah tempat favoritku.'],
      ['It has hundreds of books on many shelves.', 'Di sana ada ratusan buku di banyak rak.'],
      ['There are storybooks, science books, and comics.', 'Ada buku cerita, buku sains, dan komik.'],
      ['In the library, we must be quiet.', 'Di perpustakaan, kita harus tenang.', true],
      ['We can read at the tables or on the soft carpet.', 'Kita bisa membaca di meja atau di atas karpet yang empuk.'],
      ['We can borrow two books for one week.', 'Kita bisa meminjam dua buku selama satu minggu.'],
      ['We must return the books on time and keep them clean.', 'Kita harus mengembalikan buku tepat waktu dan menjaganya tetap bersih.'],
      ['This week, I borrowed a book about dinosaurs.', 'Minggu ini, aku meminjam buku tentang dinosaurus.', true],
    ],
    vocab: [
      ['library', 'perpustakaan', '🏫', 'noun', [], 'Our school library'],
      ['shelves', 'rak-rak', '🗄️', 'noun', ['shelf'], 'many shelves'],
      ['quiet', 'tenang', '🤫', 'adjective', [], 'we must be quiet'],
      ['borrow', 'meminjam', '📖', 'verb', ['borrowed'], 'We can borrow two books.'],
      ['return', 'mengembalikan', '↩️', 'verb', [], 'return the books on time'],
      ['on time', 'tepat waktu', '⏱️', 'phrase', [], 'return the books on time'],
    ],
    grammar: [
      {
        title: 'Pola: can (boleh/bisa) dan must (harus)',
        pattern: 'We can + kata kerja · We must + kata kerja',
        explanation: 'Can menunjukkan hal yang boleh atau bisa dilakukan. Must menunjukkan aturan yang wajib diikuti.',
        examples: ['We can borrow two books for one week.', 'We must be quiet.'],
      },
    ],
    quiz: [
      ['How many books can students borrow?', ['One book', 'Two books', 'Five books'], 1, '"We can borrow two books for one week."'],
      ['What must students do in the library?', ['Be quiet', 'Eat snacks', 'Run around'], 0, '"In the library, we must be quiet."'],
      ['What book did the writer borrow this week?', ['A comic', 'A book about dinosaurs', 'A cookbook'], 1, '"I borrowed a book about dinosaurs."'],
      ['"Borrow" artinya …', ['Membeli', 'Meminjam', 'Mengembalikan'], 1, 'Borrow = meminjam, return = mengembalikan.'],
    ],
  },
  {
    slug: 'b-my-dream-job',
    theme: 'Future',
    emoji: '👩‍⚕️',
    title: 'My Dream Job',
    titleId: 'Cita-Citaku',
    minutes: 4,
    sentences: [
      ['When I grow up, I want to be a doctor.', 'Kalau sudah besar, aku ingin menjadi dokter.'],
      ['Doctors help sick people get better.', 'Dokter membantu orang sakit agar sembuh.'],
      ['My aunt is a doctor at a hospital.', 'Bibiku adalah dokter di rumah sakit.'],
      ['She works very hard every day.', 'Dia bekerja sangat keras setiap hari.'],
      ['To become a doctor, I am going to study hard.', 'Untuk menjadi dokter, aku akan belajar dengan giat.', true],
      ['I am going to read many science books.', 'Aku akan membaca banyak buku sains.'],
      ['My best friend Tari wants to be a pilot.', 'Sahabatku Tari ingin menjadi pilot.'],
      ['She is going to fly airplanes around the world.', 'Dia akan menerbangkan pesawat keliling dunia.'],
      ['What do you want to be?', 'Kamu ingin menjadi apa?', true],
    ],
    vocab: [
      ['grow up', 'tumbuh dewasa', '🌱', 'verb', [], 'When I grow up'],
      ['doctor', 'dokter', '👩‍⚕️', 'noun', ['doctors'], 'I want to be a doctor.'],
      ['hospital', 'rumah sakit', '🏥', 'noun', [], 'a doctor at a hospital'],
      ['sick', 'sakit', '🤒', 'adjective', [], 'sick people'],
      ['pilot', 'pilot', '🧑‍✈️', 'noun', [], 'Tari wants to be a pilot.'],
      ['study', 'belajar', '📖', 'verb', [], 'study hard'],
    ],
    grammar: [
      {
        title: 'Rencana masa depan (be going to)',
        pattern: 'I am / She is + going to + kata kerja',
        explanation: 'Going to dipakai untuk rencana yang akan dilakukan di masa depan.',
        examples: ['I am going to study hard.', 'She is going to fly airplanes.'],
      },
      {
        title: 'Cita-cita: want to be',
        pattern: 'I want to be + a/an + pekerjaan',
        explanation: 'Untuk menyebut cita-cita, pakai want to be (ingin menjadi).',
        examples: ['I want to be a doctor.', 'Tari wants to be a pilot.'],
      },
    ],
    quiz: [
      ['What does the writer want to be?', ['A pilot', 'A doctor', 'A teacher'], 1, '"I want to be a doctor."'],
      ['Where does the aunt work?', ['At a school', 'At a hospital', 'At an airport'], 1, '"My aunt is a doctor at a hospital."'],
      ['What does Tari want to be?', ['A pilot', 'A nurse', 'A singer'], 0, '"Tari wants to be a pilot."'],
      ['"I am ___ to study hard."', ['go', 'going', 'went'], 1, 'Pola be going to + kata kerja.'],
    ],
  },
  {
    slug: 'b-two-seasons',
    theme: 'Nature',
    emoji: '🌦️',
    title: 'Two Seasons in Indonesia',
    titleId: 'Dua Musim di Indonesia',
    minutes: 4,
    sentences: [
      ['Some countries have four seasons, but Indonesia has only two.', 'Beberapa negara punya empat musim, tetapi Indonesia hanya punya dua.'],
      ['They are the dry season and the rainy season.', 'Yaitu musim kemarau dan musim hujan.'],
      ['In the dry season, it rarely rains.', 'Pada musim kemarau, hujan jarang turun.', true],
      ['The weather is hot and the ground is dry.', 'Cuaca panas dan tanahnya kering.'],
      ['Farmers must water their plants more often.', 'Petani harus lebih sering menyiram tanamannya.'],
      ['In the rainy season, it rains almost every day.', 'Pada musim hujan, hujan turun hampir setiap hari.', true],
      ['Rivers become full, and the plants grow green.', 'Sungai-sungai menjadi penuh, dan tanaman tumbuh hijau.'],
      ['We should bring an umbrella or a raincoat.', 'Kita sebaiknya membawa payung atau jas hujan.'],
      ['Which season do you like better?', 'Musim mana yang lebih kamu sukai?'],
    ],
    vocab: [
      ['season', 'musim', '📆', 'noun', ['seasons'], 'two seasons'],
      ['dry', 'kering', '🏜️', 'adjective', [], 'the dry season'],
      ['rarely', 'jarang', '🔅', 'adverb', [], 'it rarely rains'],
      ['ground', 'tanah', '🟫', 'noun', [], 'the ground is dry'],
      ['farmers', 'petani', '👨‍🌾', 'noun', ['farmer'], 'Farmers must water their plants.'],
      ['umbrella', 'payung', '☂️', 'noun', [], 'bring an umbrella'],
    ],
    grammar: [
      {
        title: 'Pola: but (tetapi)',
        pattern: 'Kalimat 1, but kalimat 2',
        explanation: 'But artinya "tetapi". Kita memakainya untuk menghubungkan dua hal yang berbeda.',
        examples: ['Some countries have four seasons, but Indonesia has only two.'],
      },
    ],
    quiz: [
      ['How many seasons does Indonesia have?', ['Two', 'Three', 'Four'], 0, '"Indonesia has only two."'],
      ['How is the weather in the dry season?', ['Cold and wet', 'Hot and dry', 'Snowy'], 1, '"The weather is hot and the ground is dry."'],
      ['What should we bring in the rainy season?', ['Sunglasses', 'An umbrella or a raincoat', 'A kite'], 1, '"We should bring an umbrella or a raincoat."'],
      ['"Rarely" artinya …', ['Sering', 'Jarang', 'Selalu'], 1, 'Rarely = jarang.'],
    ],
  },
  {
    slug: 'b-ramadan-at-home',
    theme: 'Daily Life',
    emoji: '🌙',
    title: 'Ramadan at Home',
    titleId: 'Ramadan di Rumah',
    minutes: 4,
    sentences: [
      ['Ramadan is a special month for Muslims.', 'Ramadan adalah bulan istimewa bagi umat Islam.'],
      ['During Ramadan, we fast from dawn until sunset.', 'Selama Ramadan, kami berpuasa dari fajar sampai matahari terbenam.'],
      ['Every morning before dawn, my mother wakes us up for sahur.', 'Setiap pagi sebelum fajar, ibuku membangunkan kami untuk sahur.', true],
      ['We eat rice, eggs, and vegetables, and we drink a lot of water.', 'Kami makan nasi, telur, dan sayur, dan banyak minum air.'],
      ['In the evening, we break our fast with dates and sweet tea.', 'Pada sore hari, kami berbuka puasa dengan kurma dan teh manis.', true],
      ['After that, we pray Maghrib together.', 'Setelah itu, kami salat Magrib bersama.'],
      ['At night, my father and I go to the mosque for tarawih prayers.', 'Pada malam hari, ayah dan aku pergi ke masjid untuk salat tarawih.'],
      ['At the end of Ramadan, we celebrate Eid al-Fitr with our big family.', 'Di akhir Ramadan, kami merayakan Idulfitri bersama keluarga besar.', true],
    ],
    vocab: [
      ['special', 'istimewa', '✨', 'adjective', [], 'a special month'],
      ['fast', 'berpuasa', '🌙', 'verb', [], 'we fast from dawn until sunset'],
      ['dawn', 'fajar', '🌅', 'noun', [], 'before dawn'],
      ['sunset', 'matahari terbenam', '🌇', 'noun', [], 'until sunset'],
      ['break our fast', 'berbuka puasa', '🍵', 'phrase', [], 'we break our fast with dates'],
      ['dates', 'kurma', '🌴', 'noun', [], 'dates and sweet tea'],
    ],
    grammar: [
      {
        title: 'Kata keterangan waktu: during, before, after',
        pattern: 'during = selama · before = sebelum · after = sesudah',
        explanation: 'Kata-kata ini membantu kita menceritakan urutan waktu kegiatan.',
        examples: ['During Ramadan, we fast.', 'before dawn', 'After that, we pray Maghrib together.'],
      },
    ],
    quiz: [
      ['When do Muslims fast during Ramadan?', ['From dawn until sunset', 'From sunset until dawn', 'All day and night'], 0, '"We fast from dawn until sunset."'],
      ['What do they eat to break the fast?', ['Bread and milk', 'Dates and sweet tea', 'Noodles'], 1, '"We break our fast with dates and sweet tea."'],
      ['Where do the father and the writer go at night?', ['To the market', 'To the mosque', 'To the park'], 1, '"… go to the mosque for tarawih prayers."'],
      ['"Dawn" artinya …', ['Fajar', 'Senja', 'Tengah malam'], 0, 'Dawn = fajar, sunset = matahari terbenam.'],
    ],
  },
  {
    slug: 'b-letter-to-pen-pal',
    theme: 'Friends',
    emoji: '✉️',
    title: 'A Letter to My Pen Pal',
    titleId: 'Surat untuk Sahabat Pena',
    minutes: 4,
    sentences: [
      ['Dear Emma,', 'Emma yang baik,'],
      ['Hello from Bandung, Indonesia!', 'Halo dari Bandung, Indonesia!', true],
      ['I am so happy to be your pen pal.', 'Aku senang sekali menjadi sahabat penamu.'],
      ['My name is Laila and I am in the fourth grade.', 'Namaku Laila dan aku kelas empat.'],
      ['Bandung is a city in the mountains, so the weather is cool.', 'Bandung adalah kota di pegunungan, jadi cuacanya sejuk.'],
      ['My favorite food is batagor, a fried fish dumpling with peanut sauce.', 'Makanan favoritku adalah batagor, pangsit ikan goreng dengan saus kacang.'],
      ['I like playing badminton and reading books.', 'Aku suka bermain bulu tangkis dan membaca buku.', true],
      ['What is your city like?', 'Seperti apa kotamu?'],
      ['What do you like to do after school?', 'Apa yang kamu suka lakukan sepulang sekolah?'],
      ['Please write back soon!', 'Tolong segera balas, ya!', true],
      ['Your friend, Laila', 'Temanmu, Laila'],
    ],
    vocab: [
      ['pen pal', 'sahabat pena', '✉️', 'noun', [], 'a letter to my pen pal'],
      ['grade', 'kelas (tingkat)', '🏫', 'noun', [], 'the fourth grade'],
      ['mountains', 'pegunungan', '⛰️', 'noun', ['mountain'], 'a city in the mountains'],
      ['dumpling', 'pangsit', '🥟', 'noun', [], 'a fried fish dumpling'],
      ['peanut sauce', 'saus kacang', '🥜', 'noun', [], 'with peanut sauce'],
      ['badminton', 'bulu tangkis', '🏸', 'noun', [], 'playing badminton'],
    ],
    grammar: [
      {
        title: 'Struktur surat pribadi',
        pattern: 'Dear … (salam) → isi surat → Your friend, … (penutup)',
        explanation:
          'Surat pribadi diawali sapaan "Dear + nama", dilanjutkan isi surat (perkenalan, cerita, pertanyaan), lalu ditutup dengan salam penutup dan nama pengirim.',
        examples: ['Dear Emma,', 'Please write back soon!', 'Your friend, Laila'],
      },
      {
        title: 'Bertanya: What … like?',
        pattern: 'What is + benda + like?',
        explanation: '"What is your city like?" artinya "Seperti apa kotamu?", untuk menanyakan gambaran sesuatu.',
        examples: ['What is your city like?', 'What is your school like?'],
      },
    ],
    quiz: [
      ['Who wrote the letter?', ['Emma', 'Laila', 'Laila\'s teacher'], 1, 'The letter is from Laila: "Your friend, Laila".'],
      ['Why is the weather in Bandung cool?', ['It is near the sea', 'It is in the mountains', 'It rains every day'], 1, '"Bandung is a city in the mountains, so the weather is cool."'],
      ['What is batagor?', ['A fried fish dumpling with peanut sauce', 'A kind of cake', 'A sweet drink'], 0, '"batagor, a fried fish dumpling with peanut sauce."'],
      ['Sapaan pembuka surat dalam bahasa Inggris adalah …', ['Dear …', 'Goodbye …', 'Thank you …'], 0, 'Surat diawali dengan "Dear + nama".'],
    ],
  },
];
