// Daily English Reading Fase A — tahun pertama, bagian 3 (minggu 15–21).

import { P } from './english-phase-a-patterns';
import type { SeedReading } from './types';

export const englishPhaseAYear3: SeedReading[] = [
  // ── Minggu 15: Kegiatan di Sekolah ───────────────────────────────────────
  {
    slug: 'a3-going-to-school', theme: 'School', emoji: '🚸', title: 'Going to School', titleId: 'Berangkat ke Sekolah', minutes: 3,
    sentences: [
      ['School starts at seven o\'clock.', 'Sekolah dimulai pukul tujuh.'],
      ['Rafi leaves home at half past six.', 'Rafi berangkat dari rumah pukul setengah tujuh.'],
      ['He goes to school on foot with Budi.', 'Dia berjalan kaki ke sekolah bersama Budi.'],
      ['They walk on the sidewalk.', 'Mereka berjalan di trotoar.'],
      ['They say hello to the security guard.', 'Mereka menyapa satpam.', true],
      ['They are never late.', 'Mereka tidak pernah terlambat.'],
    ],
    vocab: [
      ['starts', 'dimulai', '▶️', 'verb', ['start'], 'School starts at seven.'],
      ['leaves', 'berangkat / meninggalkan', '🚪', 'verb', ['leave'], 'Rafi leaves home.'],
      ['on foot', 'berjalan kaki', '🚶', 'phrase', [], 'on foot'],
      ['sidewalk', 'trotoar', '🛣️', 'noun', [], 'on the sidewalk'],
      ['security guard', 'satpam', '💂', 'noun', [], 'the security guard'],
      ['never', 'tidak pernah', '🚫', 'adverb', [], 'They are never late.'],
    ],
    grammar: [P.timeClock],
    quiz: [
      ['What time does school start? (Jam berapa sekolah dimulai?)', ['Six o\'clock', 'Seven o\'clock', 'Eight o\'clock'], 1, '"School starts at seven o\'clock."'],
      ['How does Rafi go to school? (Bagaimana Rafi pergi ke sekolah?)', ['On foot', 'By car', 'By bus'], 0, '"He goes to school on foot."'],
      ['"Never late" artinya …', ['Selalu terlambat', 'Tidak pernah terlambat', 'Kadang terlambat'], 1, 'Never = tidak pernah.'],
    ],
  },
  {
    slug: 'a3-math-is-fun', theme: 'School', emoji: '➕', title: 'Math Is Fun', titleId: 'Matematika Itu Menyenangkan', minutes: 3,
    sentences: [
      ['Now we have math.', 'Sekarang pelajaran matematika.'],
      ['Mrs. Sari shows us six marbles.', 'Bu Sari menunjukkan enam kelereng.'],
      ['She adds four more marbles.', 'Dia menambahkan empat kelereng lagi.'],
      ['"How many marbles are there?" she asks.', '"Ada berapa kelereng?" tanyanya.'],
      ['Dina raises her hand. "Ten!"', 'Dina mengangkat tangan. "Sepuluh!"', true],
      ['"Correct!" says Mrs. Sari.', '"Benar!" kata Bu Sari.'],
      ['Six plus four is ten.', 'Enam tambah empat sama dengan sepuluh.'],
    ],
    vocab: [
      ['math', 'matematika', '🔢', 'noun', [], 'we have math'],
      ['shows', 'menunjukkan', '👉', 'verb', ['show'], 'Mrs. Sari shows us six marbles.'],
      ['marbles', 'kelereng', '🔮', 'noun', ['marble'], 'six marbles'],
      ['correct', 'benar', '✅', 'adjective', [], 'Correct!'],
      ['plus', 'tambah', '➕', 'preposition', [], 'Six plus four is ten.'],
    ],
    grammar: [P.howMany],
    quiz: [
      ['How many marbles are there at first? (Ada berapa kelereng pada awalnya?)', ['Four', 'Six', 'Ten'], 1, '"six marbles"'],
      ['Who answers the question? (Siapa yang menjawab?)', ['Rafi', 'Dina', 'Budi'], 1, '"Dina raises her hand. Ten!"'],
      ['6 + 4 = ?', ['Nine', 'Ten', 'Eleven'], 1, 'Six plus four is ten.'],
    ],
  },
  {
    slug: 'a3-sports-class', theme: 'School', emoji: '🏃', title: 'PE Class', titleId: 'Pelajaran Olahraga', minutes: 3,
    sentences: [
      ['On Wednesday morning, we have PE.', 'Pada Rabu pagi, kami ada pelajaran olahraga.'],
      ['We wear our sports clothes.', 'Kami memakai baju olahraga.'],
      ['First, we warm up.', 'Pertama, kami pemanasan.'],
      ['We stretch our arms and legs.', 'Kami meregangkan tangan dan kaki.'],
      ['Then we run around the field two times.', 'Lalu kami berlari mengelilingi lapangan dua kali.', true],
      ['After PE, we are hot and thirsty.', 'Setelah olahraga, kami kepanasan dan haus.'],
    ],
    vocab: [
      ['PE', 'pendidikan jasmani / olahraga', '🤸', 'noun', [], 'we have PE'],
      ['sports clothes', 'baju olahraga', '🎽', 'noun', [], 'our sports clothes'],
      ['warm up', 'pemanasan', '🔥', 'verb', [], 'we warm up'],
      ['stretch', 'meregangkan', '🙆', 'verb', ['stretches'], 'We stretch our arms.'],
      ['two times', 'dua kali', '2️⃣', 'phrase', [], 'two times'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What do they do first? (Apa yang mereka lakukan pertama?)', ['Warm up', 'Eat', 'Swim'], 0, '"First, we warm up."'],
      ['How many times do they run around the field? (Berapa kali mereka berlari mengelilingi lapangan?)', ['One', 'Two', 'Three'], 1, '"two times"'],
      ['How do they feel after PE? (Bagaimana perasaan mereka setelah olahraga?)', ['Hot and thirsty', 'Cold and sleepy', 'Sad'], 0, '"we are hot and thirsty"'],
    ],
  },
  {
    slug: 'a3-the-school-garden', theme: 'School', emoji: '🌱', title: 'Our School Garden', titleId: 'Kebun Sekolah Kami', minutes: 3,
    sentences: [
      ['Our school has a small garden.', 'Sekolah kami punya kebun kecil.'],
      ['Each class takes care of one plant.', 'Setiap kelas merawat satu tanaman.'],
      ['Our class has a chili plant.', 'Kelas kami punya tanaman cabai.'],
      ['We water it every morning.', 'Kami menyiramnya setiap pagi.'],
      ['Now it has small white flowers.', 'Sekarang tanamannya punya bunga putih kecil.', true],
      ['Soon it will have red chilies!', 'Sebentar lagi akan ada cabai merah!'],
    ],
    vocab: [
      ['takes care of', 'merawat', '🤲', 'verb', ['take care of'], 'Each class takes care of one plant.'],
      ['chili', 'cabai', '🌶️', 'noun', ['chilies'], 'a chili plant'],
      ['water', 'menyiram', '💧', 'verb', ['waters'], 'We water it every morning.'],
      ['soon', 'sebentar lagi', '⏳', 'adverb', [], 'Soon it will have red chilies!'],
      ['will', 'akan', '🔮', 'verb', [], 'it will have red chilies'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What plant does the class have? (Tanaman apa yang dimiliki kelas?)', ['A tomato plant', 'A chili plant', 'A mango tree'], 1, '"Our class has a chili plant."'],
      ['When do they water it? (Kapan mereka menyiramnya?)', ['Every morning', 'Every night', 'Every week'], 0, '"We water it every morning."'],
      ['What color are the flowers? (Apa warna bunganya?)', ['Red', 'White', 'Yellow'], 1, '"small white flowers"'],
    ],
  },
  {
    slug: 'a3-test-day', theme: 'School', emoji: '📝', title: 'Test Day', titleId: 'Hari Ulangan', minutes: 3,
    sentences: [
      ['Today there is a spelling test.', 'Hari ini ada ulangan mengeja.'],
      ['Rafi studied last night, so he is ready.', 'Rafi belajar tadi malam, jadi dia siap.'],
      ['Mrs. Sari says a word: "elephant".', 'Bu Sari menyebutkan kata: "elephant".'],
      ['Rafi writes E-L-E-P-H-A-N-T.', 'Rafi menulis E-L-E-P-H-A-N-T.'],
      ['He checks his answers.', 'Dia memeriksa jawabannya.', true],
      ['He gets ten out of ten!', 'Dia mendapat nilai sepuluh dari sepuluh!'],
    ],
    vocab: [
      ['spelling', 'mengeja', '🔤', 'noun', [], 'a spelling test'],
      ['test', 'ulangan / tes', '📝', 'noun', ['tests'], 'a spelling test'],
      ['word', 'kata', '💬', 'noun', ['words'], 'Mrs. Sari says a word.'],
      ['checks', 'memeriksa', '🔍', 'verb', ['check'], 'He checks his answers.'],
      ['answers', 'jawaban', '✅', 'noun', ['answer'], 'his answers'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What kind of test is it? (Ulangan apa itu?)', ['Math', 'Spelling', 'Swimming'], 1, '"a spelling test"'],
      ['What word does Mrs. Sari say? (Kata apa yang disebutkan Bu Sari?)', ['Elephant', 'Tiger', 'Apple'], 0, '"elephant"'],
      ['What is Rafi\'s score? (Berapa nilai Rafi?)', ['Five out of ten', 'Eight out of ten', 'Ten out of ten'], 2, '"ten out of ten"'],
    ],
  },
  {
    slug: 'a3-a-new-pencil-case', theme: 'School', emoji: '✏️', title: 'The Lost Pencil Case', titleId: 'Kotak Pensil yang Hilang', minutes: 3,
    sentences: [
      ['Tari can\'t find her pencil case.', 'Tari tidak bisa menemukan kotak pensilnya.'],
      ['It is purple with a star on it.', 'Warnanya ungu dengan gambar bintang.'],
      ['"Is it in your bag?" asks Dina.', '"Apakah ada di tasmu?" tanya Dina.'],
      ['"No, it isn\'t."', '"Tidak ada."'],
      ['Rafi looks under the desks.', 'Rafi mencari di bawah meja-meja.', true],
      ['"Here it is!" he says.', '"Ini dia!" katanya.'],
      ['Tari is happy. "Thank you, Rafi!"', 'Tari senang. "Terima kasih, Rafi!"'],
    ],
    vocab: [
      ['find', 'menemukan', '🔎', 'verb', ['finds'], 'Tari can\'t find her pencil case.'],
      ['pencil case', 'kotak pensil', '🖊️', 'noun', [], 'her pencil case'],
      ['purple', 'ungu', '🟣', 'adjective', [], 'It is purple.'],
      ['looks under', 'mencari di bawah', '🔍', 'verb', ['look under'], 'Rafi looks under the desks.'],
      ['here it is', 'ini dia', '🙌', 'phrase', [], 'Here it is!'],
    ],
    grammar: [P.whatIs],
    quiz: [
      ['What color is the pencil case? (Apa warna kotak pensilnya?)', ['Purple', 'Blue', 'Red'], 0, '"It is purple with a star on it."'],
      ['Who finds it? (Siapa yang menemukannya?)', ['Dina', 'Rafi', 'Mrs. Sari'], 1, '"Here it is!" kata Rafi.'],
      ['Where is it? (Di mana kotak pensilnya?)', ['Under the desks', 'In the bag', 'On the roof'], 0, '"Rafi looks under the desks."'],
    ],
  },
  {
    slug: 'a3-reading-corner', theme: 'School', emoji: '📖', title: 'The Reading Corner', titleId: 'Pojok Baca', minutes: 3,
    sentences: [
      ['Our classroom has a reading corner.', 'Kelas kami punya pojok baca.'],
      ['There is a soft carpet and some pillows.', 'Ada karpet lembut dan beberapa bantal.'],
      ['There are storybooks and picture books.', 'Ada buku cerita dan buku bergambar.'],
      ['After lunch, we read for fifteen minutes.', 'Setelah makan siang, kami membaca selama lima belas menit.'],
      ['Rafi reads about the ocean.', 'Rafi membaca tentang samudra.', true],
      ['Reading takes him on many adventures!', 'Membaca membawanya ke banyak petualangan!'],
    ],
    vocab: [
      ['corner', 'pojok / sudut', '📐', 'noun', ['corners'], 'a reading corner'],
      ['carpet', 'karpet', '🟥', 'noun', ['carpets'], 'a soft carpet'],
      ['storybooks', 'buku cerita', '📚', 'noun', ['storybook'], 'There are storybooks.'],
      ['minutes', 'menit', '⏱️', 'noun', ['minute'], 'fifteen minutes'],
      ['ocean', 'samudra / lautan', '🌊', 'noun', ['oceans'], 'about the ocean'],
      ['adventures', 'petualangan', '🗺️', 'noun', ['adventure'], 'many adventures'],
    ],
    grammar: [P.thereIsAre],
    quiz: [
      ['How long do they read? (Berapa lama mereka membaca?)', ['Five minutes', 'Fifteen minutes', 'One hour'], 1, '"fifteen minutes"'],
      ['What does Rafi read about? (Rafi membaca tentang apa?)', ['The ocean', 'Cars', 'Food'], 0, '"Rafi reads about the ocean."'],
      ['"Corner" artinya …', ['Pojok', 'Pintu', 'Lantai'], 0, 'Corner = pojok / sudut.'],
    ],
  },

  // ── Minggu 16: Pekerjaan ─────────────────────────────────────────────────
  {
    slug: 'a3-the-doctor', theme: 'Jobs', emoji: '🧑‍⚕️', title: 'Dr. Lina Helps Sick People', titleId: 'Dokter Lina Menolong Orang Sakit', minutes: 3,
    sentences: [
      ['Dr. Lina is a doctor.', 'Dokter Lina adalah seorang dokter.'],
      ['She works at a hospital.', 'Dia bekerja di rumah sakit.'],
      ['She wears a white coat.', 'Dia memakai jas putih.'],
      ['She listens to your heart.', 'Dia mendengarkan detak jantungmu.'],
      ['She gives medicine to sick people.', 'Dia memberi obat kepada orang sakit.', true],
      ['She helps them get better.', 'Dia membantu mereka sembuh.'],
    ],
    vocab: [
      ['works', 'bekerja', '💼', 'verb', ['work'], 'She works at a hospital.'],
      ['hospital', 'rumah sakit', '🏥', 'noun', ['hospitals'], 'at a hospital'],
      ['coat', 'jas / mantel', '🥼', 'noun', ['coats'], 'a white coat'],
      ['heart', 'jantung / hati', '❤️', 'noun', ['hearts'], 'She listens to your heart.'],
      ['medicine', 'obat', '💊', 'noun', [], 'She gives medicine.'],
      ['get better', 'sembuh', '💪', 'verb', [], 'get better'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Where does Dr. Lina work? (Di mana Dokter Lina bekerja?)', ['At a school', 'At a hospital', 'At a shop'], 1, '"She works at a hospital."'],
      ['What does she wear? (Apa yang dia pakai?)', ['A white coat', 'A red hat', 'A uniform'], 0, '"She wears a white coat."'],
      ['"Medicine" artinya …', ['Makanan', 'Obat', 'Minuman'], 1, 'Medicine = obat.'],
    ],
  },
  {
    slug: 'a3-the-farmer', theme: 'Jobs', emoji: '👨‍🌾', title: 'Pak Tono the Farmer', titleId: 'Pak Tono si Petani', minutes: 3,
    sentences: [
      ['Pak Tono is a farmer.', 'Pak Tono adalah seorang petani.'],
      ['He gets up very early.', 'Dia bangun sangat pagi.'],
      ['He works in the rice field all day.', 'Dia bekerja di sawah sepanjang hari.'],
      ['He plants rice and pulls out weeds.', 'Dia menanam padi dan mencabut rumput liar.'],
      ['He wears a big straw hat.', 'Dia memakai caping besar.', true],
      ['Farmers give us food. They are heroes!', 'Petani memberi kita makanan. Mereka pahlawan!'],
    ],
    vocab: [
      ['gets up', 'bangun', '🌅', 'verb', ['get up'], 'He gets up very early.'],
      ['plants', 'menanam', '🌾', 'verb', ['plant'], 'He plants rice.'],
      ['pulls out', 'mencabut', '🤏', 'verb', ['pull out'], 'pulls out weeds'],
      ['weeds', 'rumput liar', '🌿', 'noun', ['weed'], 'weeds'],
      ['straw hat', 'caping / topi jerami', '👒', 'noun', [], 'a big straw hat'],
      ['heroes', 'pahlawan', '🦸', 'noun', ['hero'], 'They are heroes!'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What is Pak Tono\'s job? (Apa pekerjaan Pak Tono?)', ['A teacher', 'A farmer', 'A pilot'], 1, '"Pak Tono is a farmer."'],
      ['Where does he work? (Di mana dia bekerja?)', ['In the rice field', 'In a hospital', 'In a bank'], 0, '"He works in the rice field."'],
      ['What does he wear? (Apa yang dia pakai?)', ['A straw hat', 'A helmet', 'A tie'], 0, '"He wears a big straw hat."'],
    ],
  },
  {
    slug: 'a3-the-firefighter', theme: 'Jobs', emoji: '🧑‍🚒', title: 'Brave Firefighters', titleId: 'Pemadam Kebakaran yang Berani', minutes: 3,
    sentences: [
      ['Firefighters put out fires.', 'Pemadam kebakaran memadamkan api.'],
      ['They drive a big red fire truck.', 'Mereka mengendarai truk pemadam merah yang besar.'],
      ['Nee-naw, nee-naw! The truck is coming.', 'Nguing, nguing! Truknya datang.'],
      ['They spray water on the fire.', 'Mereka menyemprotkan air ke api.'],
      ['They also save cats from tall trees!', 'Mereka juga menolong kucing dari pohon tinggi!', true],
      ['Firefighters are very brave.', 'Pemadam kebakaran sangat berani.'],
    ],
    vocab: [
      ['firefighters', 'pemadam kebakaran', '🧑‍🚒', 'noun', ['firefighter'], 'Firefighters put out fires.'],
      ['put out', 'memadamkan', '🧯', 'verb', [], 'put out fires'],
      ['fire truck', 'truk pemadam kebakaran', '🚒', 'noun', [], 'a big red fire truck'],
      ['spray', 'menyemprot', '💦', 'verb', ['sprays'], 'They spray water.'],
      ['save', 'menyelamatkan', '🛟', 'verb', ['saves'], 'They also save cats.'],
      ['brave', 'berani', '🦁', 'adjective', [], 'very brave'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What color is the fire truck? (Apa warna truk pemadam?)', ['Red', 'Blue', 'White'], 0, '"a big red fire truck"'],
      ['What do firefighters spray? (Apa yang mereka semprotkan?)', ['Water', 'Sand', 'Milk'], 0, '"They spray water on the fire."'],
      ['"Brave" artinya …', ['Berani', 'Takut', 'Malas'], 0, 'Brave = berani.'],
    ],
  },
  {
    slug: 'a3-the-chef', theme: 'Jobs', emoji: '👨‍🍳', title: 'Chef Andi\'s Kitchen', titleId: 'Dapur Koki Andi', minutes: 3,
    sentences: [
      ['Uncle Andi is a chef.', 'Paman Andi adalah seorang koki.'],
      ['He works in a restaurant.', 'Dia bekerja di sebuah restoran.'],
      ['He wears a tall white hat.', 'Dia memakai topi putih yang tinggi.'],
      ['He cooks rendang, soto, and gado-gado.', 'Dia memasak rendang, soto, dan gado-gado.'],
      ['People come from far away to eat his food.', 'Orang datang dari jauh untuk makan masakannya.', true],
      ['One day, I want to be a chef too.', 'Suatu hari nanti, aku juga ingin menjadi koki.'],
    ],
    vocab: [
      ['chef', 'koki', '👨‍🍳', 'noun', ['chefs'], 'Uncle Andi is a chef.'],
      ['restaurant', 'restoran', '🍽️', 'noun', ['restaurants'], 'in a restaurant'],
      ['tall', 'tinggi', '📏', 'adjective', [], 'a tall white hat'],
      ['people', 'orang-orang', '👥', 'noun', [], 'People come from far away.'],
      ['one day', 'suatu hari nanti', '🔮', 'phrase', [], 'One day, I want to be a chef.'],
    ],
    grammar: [P.wantTo],
    quiz: [
      ['Where does Uncle Andi work? (Di mana Paman Andi bekerja?)', ['In a restaurant', 'In a hospital', 'On a farm'], 0, '"He works in a restaurant."'],
      ['What does he wear? (Apa yang dia pakai?)', ['A tall white hat', 'A helmet', 'A raincoat'], 0, '"He wears a tall white hat."'],
      ['What does Rafi want to be? (Rafi ingin menjadi apa?)', ['A pilot', 'A chef', 'A doctor'], 1, '"I want to be a chef too."'],
    ],
  },
  {
    slug: 'a3-the-pilot', theme: 'Jobs', emoji: '🧑‍✈️', title: 'Captain Rina Flies a Plane', titleId: 'Kapten Rina Menerbangkan Pesawat', minutes: 3,
    sentences: [
      ['Captain Rina is a pilot.', 'Kapten Rina adalah seorang pilot.'],
      ['She flies a big plane.', 'Dia menerbangkan pesawat besar.'],
      ['She flies from Jakarta to Bali.', 'Dia terbang dari Jakarta ke Bali.'],
      ['She sits in the cockpit.', 'Dia duduk di kokpit.'],
      ['She talks to the passengers.', 'Dia berbicara kepada para penumpang.', true],
      ['"Welcome on board! Enjoy the flight!"', '"Selamat datang di pesawat! Selamat menikmati penerbangan!"'],
    ],
    vocab: [
      ['pilot', 'pilot', '🧑‍✈️', 'noun', ['pilots'], 'Captain Rina is a pilot.'],
      ['plane', 'pesawat terbang', '✈️', 'noun', ['planes'], 'a big plane'],
      ['cockpit', 'kokpit (ruang pilot)', '🎛️', 'noun', [], 'in the cockpit'],
      ['passengers', 'penumpang', '🧳', 'noun', ['passenger'], 'the passengers'],
      ['flight', 'penerbangan', '🛫', 'noun', ['flights'], 'Enjoy the flight!'],
    ],
    grammar: [P.heShe],
    quiz: [
      ['Where does Captain Rina fly to? (Kapten Rina terbang ke mana?)', ['Bali', 'Medan', 'Japan'], 0, '"from Jakarta to Bali"'],
      ['Where does she sit? (Di mana dia duduk?)', ['In the cockpit', 'In the kitchen', 'On the wing'], 0, '"She sits in the cockpit."'],
      ['"Passengers" artinya …', ['Penumpang', 'Pilot', 'Koper'], 0, 'Passengers = penumpang.'],
    ],
  },
  {
    slug: 'a3-the-postman', theme: 'Jobs', emoji: '📮', title: 'A Letter from Grandma', titleId: 'Surat dari Nenek', minutes: 3,
    sentences: [
      ['Pak Hadi is a postman.', 'Pak Hadi adalah seorang tukang pos.'],
      ['He rides an orange motorbike.', 'Dia mengendarai motor oranye.'],
      ['He brings letters and packages.', 'Dia mengantarkan surat dan paket.'],
      ['Today he stops at our house.', 'Hari ini dia berhenti di rumah kami.'],
      ['"A letter for Rafi!" he says.', '"Ada surat untuk Rafi!" katanya.', true],
      ['It is from Grandma. Rafi is so happy!', 'Suratnya dari Nenek. Rafi sangat senang!'],
    ],
    vocab: [
      ['postman', 'tukang pos', '📮', 'noun', [], 'Pak Hadi is a postman.'],
      ['brings', 'membawa / mengantar', '📦', 'verb', ['bring'], 'He brings letters.'],
      ['letters', 'surat', '✉️', 'noun', ['letter'], 'letters and packages'],
      ['packages', 'paket', '📦', 'noun', ['package'], 'letters and packages'],
      ['stops', 'berhenti', '🛑', 'verb', ['stop'], 'he stops at our house'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What color is the postman\'s motorbike? (Apa warna motor tukang pos?)', ['Orange', 'Black', 'Green'], 0, '"an orange motorbike"'],
      ['Who is the letter from? (Surat itu dari siapa?)', ['Grandma', 'Mrs. Sari', 'Dina'], 0, '"It is from Grandma."'],
      ['"Packages" artinya …', ['Paket', 'Prangko', 'Pos'], 0, 'Packages = paket.'],
    ],
  },
  {
    slug: 'a3-when-i-grow-up', theme: 'Jobs', emoji: '🌟', title: 'When I Grow Up', titleId: 'Kalau Aku Besar Nanti', minutes: 3,
    sentences: [
      ['Mrs. Sari asks, "What do you want to be when you grow up?"', 'Bu Sari bertanya, "Kalau sudah besar nanti, kamu ingin menjadi apa?"'],
      ['Budi wants to be a police officer.', 'Budi ingin menjadi polisi.'],
      ['Dina wants to be an artist.', 'Dina ingin menjadi seniman.'],
      ['Tari wants to be a singer.', 'Tari ingin menjadi penyanyi.'],
      ['Rafi wants to be an astronaut.', 'Rafi ingin menjadi astronaut.', true],
      ['"Study hard and you can be anything!" says Mrs. Sari.', '"Belajar yang rajin dan kalian bisa menjadi apa saja!" kata Bu Sari.'],
    ],
    vocab: [
      ['grow up', 'tumbuh besar / dewasa', '🌱', 'verb', [], 'when you grow up'],
      ['police officer', 'polisi', '👮', 'noun', [], 'a police officer'],
      ['artist', 'seniman / pelukis', '🎨', 'noun', ['artists'], 'an artist'],
      ['singer', 'penyanyi', '🎤', 'noun', ['singers'], 'a singer'],
      ['astronaut', 'astronaut', '👩‍🚀', 'noun', ['astronauts'], 'an astronaut'],
      ['anything', 'apa saja', '✨', 'pronoun', [], 'you can be anything'],
    ],
    grammar: [P.wantTo],
    quiz: [
      ['What does Rafi want to be? (Rafi ingin menjadi apa?)', ['A singer', 'An astronaut', 'A farmer'], 1, '"Rafi wants to be an astronaut."'],
      ['Who wants to be an artist? (Siapa yang ingin menjadi seniman?)', ['Dina', 'Tari', 'Budi'], 0, '"Dina wants to be an artist."'],
      ['What does Mrs. Sari say? (Apa kata Bu Sari?)', ['Study hard and you can be anything', 'Go home', 'Don\'t dream'], 0, '"Study hard and you can be anything!"'],
    ],
  },

  // ── Minggu 17: Transportasi ──────────────────────────────────────────────
  {
    slug: 'a3-by-train', theme: 'Transportation', emoji: '🚆', title: 'A Trip by Train', titleId: 'Perjalanan Naik Kereta', minutes: 3,
    sentences: [
      ['We are going to Yogyakarta by train.', 'Kami akan pergi ke Yogyakarta naik kereta.'],
      ['We wait at the station.', 'Kami menunggu di stasiun.'],
      ['The train arrives. Choo choo!', 'Keretanya datang. Tut tut!'],
      ['We find our seats by the window.', 'Kami menemukan tempat duduk kami di dekat jendela.'],
      ['I see rice fields and mountains outside.', 'Aku melihat sawah dan gunung di luar.', true],
      ['The train is fast and comfortable.', 'Keretanya cepat dan nyaman.'],
    ],
    vocab: [
      ['station', 'stasiun', '🚉', 'noun', ['stations'], 'at the station'],
      ['arrives', 'tiba', '🛬', 'verb', ['arrive'], 'The train arrives.'],
      ['seats', 'tempat duduk', '💺', 'noun', ['seat'], 'our seats'],
      ['mountains', 'gunung', '⛰️', 'noun', ['mountain'], 'rice fields and mountains'],
      ['comfortable', 'nyaman', '🛋️', 'adjective', [], 'fast and comfortable'],
    ],
    grammar: [P.ingNow],
    quiz: [
      ['Where are they going? (Mereka akan pergi ke mana?)', ['Yogyakarta', 'Bali', 'Medan'], 0, '"We are going to Yogyakarta."'],
      ['Where do they wait? (Di mana mereka menunggu?)', ['At the station', 'At the airport', 'At the harbor'], 0, '"We wait at the station."'],
      ['What does Rafi see outside? (Apa yang Rafi lihat di luar?)', ['Rice fields and mountains', 'The sea', 'Snow'], 0, '"I see rice fields and mountains outside."'],
    ],
  },
  {
    slug: 'a3-the-school-bus', theme: 'Transportation', emoji: '🚌', title: 'The Yellow School Bus', titleId: 'Bus Sekolah Kuning', minutes: 3,
    sentences: [
      ['Dina goes to school by bus.', 'Dina pergi ke sekolah naik bus.'],
      ['The school bus is yellow.', 'Bus sekolahnya kuning.'],
      ['It stops in front of her house at six thirty.', 'Bus berhenti di depan rumahnya pukul enam tiga puluh.'],
      ['The driver is Pak Udin.', 'Sopirnya Pak Udin.'],
      ['He always smiles and says, "Good morning!"', 'Dia selalu tersenyum dan berkata, "Selamat pagi!"', true],
      ['Dina sits with her friends and sings songs.', 'Dina duduk bersama teman-temannya dan bernyanyi.'],
    ],
    vocab: [
      ['bus', 'bus', '🚌', 'noun', ['buses'], 'by bus'],
      ['in front of', 'di depan', '⬆️', 'preposition', [], 'in front of her house'],
      ['driver', 'sopir / pengemudi', '🧑‍✈️', 'noun', ['drivers'], 'The driver is Pak Udin.'],
      ['always', 'selalu', '♾️', 'adverb', [], 'He always smiles.'],
      ['songs', 'lagu', '🎵', 'noun', ['song'], 'sings songs'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['How does Dina go to school? (Bagaimana Dina pergi ke sekolah?)', ['By bus', 'By bike', 'On foot'], 0, '"Dina goes to school by bus."'],
      ['Who is the driver? (Siapa sopirnya?)', ['Pak Udin', 'Pak Tono', 'Pak Hadi'], 0, '"The driver is Pak Udin."'],
      ['"Always" artinya …', ['Kadang-kadang', 'Selalu', 'Tidak pernah'], 1, 'Always = selalu.'],
    ],
  },
  {
    slug: 'a3-on-a-boat', theme: 'Transportation', emoji: '⛴️', title: 'Crossing the Sea', titleId: 'Menyeberangi Laut', minutes: 3,
    sentences: [
      ['We are going to Bali.', 'Kami akan pergi ke Bali.'],
      ['We take a ferry from Java.', 'Kami naik kapal feri dari Jawa.'],
      ['Our car goes inside the big ferry.', 'Mobil kami masuk ke dalam kapal feri yang besar.'],
      ['We go up to the deck.', 'Kami naik ke dek kapal.'],
      ['The wind is cool. The sea is blue.', 'Anginnya sejuk. Lautnya biru.', true],
      ['I see small fishing boats.', 'Aku melihat perahu-perahu nelayan kecil.'],
      ['After one hour, we are in Bali!', 'Setelah satu jam, kami sampai di Bali!'],
    ],
    vocab: [
      ['ferry', 'kapal feri', '⛴️', 'noun', ['ferries'], 'a ferry'],
      ['deck', 'dek (lantai atas kapal)', '🚢', 'noun', [], 'up to the deck'],
      ['sea', 'laut', '🌊', 'noun', ['seas'], 'The sea is blue.'],
      ['fishing boats', 'perahu nelayan', '🛶', 'noun', ['fishing boat'], 'small fishing boats'],
      ['hour', 'jam (60 menit)', '⏰', 'noun', ['hours'], 'After one hour'],
    ],
    grammar: [P.ingNow],
    quiz: [
      ['How do they go to Bali? (Bagaimana mereka pergi ke Bali?)', ['By ferry', 'By train', 'By plane'], 0, '"We take a ferry from Java."'],
      ['What color is the sea? (Apa warna lautnya?)', ['Blue', 'Green', 'Brown'], 0, '"The sea is blue."'],
      ['How long is the trip on the ferry? (Berapa lama di kapal feri?)', ['One hour', 'Two hours', 'One day'], 0, '"After one hour, we are in Bali!"'],
    ],
  },
  {
    slug: 'a3-at-the-airport', theme: 'Transportation', emoji: '🛫', title: 'At the Airport', titleId: 'Di Bandara', minutes: 3,
    sentences: [
      ['Tante Mira is flying to Makassar.', 'Tante Mira akan terbang ke Makassar.'],
      ['We take her to the airport.', 'Kami mengantarnya ke bandara.'],
      ['The airport is big and busy.', 'Bandaranya besar dan ramai.'],
      ['People are pulling suitcases.', 'Orang-orang sedang menarik koper.'],
      ['We see planes taking off.', 'Kami melihat pesawat lepas landas.', true],
      ['Tante Mira waves goodbye.', 'Tante Mira melambaikan tangan.'],
      ['"Have a safe flight!" we say.', '"Selamat jalan, hati-hati!" kata kami.'],
    ],
    vocab: [
      ['airport', 'bandara', '🛫', 'noun', ['airports'], 'to the airport'],
      ['pulling', 'sedang menarik', '🧳', 'verb', ['pull'], 'People are pulling suitcases.'],
      ['suitcases', 'koper', '🧳', 'noun', ['suitcase'], 'pulling suitcases'],
      ['taking off', 'lepas landas', '🛫', 'verb', ['take off'], 'planes taking off'],
      ['safe', 'aman / selamat', '🛡️', 'adjective', [], 'Have a safe flight!'],
    ],
    grammar: [P.ingNow],
    quiz: [
      ['Where is Tante Mira flying to? (Tante Mira terbang ke mana?)', ['Makassar', 'Bali', 'Jakarta'], 0, '"Tante Mira is flying to Makassar."'],
      ['What are people pulling? (Orang-orang menarik apa?)', ['Suitcases', 'Carts of fruit', 'Kites'], 0, '"People are pulling suitcases."'],
      ['"Airport" artinya …', ['Pelabuhan', 'Bandara', 'Stasiun'], 1, 'Airport = bandara.'],
    ],
  },
  {
    slug: 'a3-riding-the-ojek', theme: 'Transportation', emoji: '🛵', title: 'A Ride with Dad', titleId: 'Dibonceng Ayah', minutes: 3,
    sentences: [
      ['Dad takes me to the barber by motorbike.', 'Ayah mengantarku ke tukang cukur naik motor.'],
      ['First, I put on my helmet.', 'Pertama, aku memakai helmku.'],
      ['I sit behind Dad and hold him tight.', 'Aku duduk di belakang Ayah dan memeluknya erat.'],
      ['Dad drives slowly and carefully.', 'Ayah menyetir pelan dan hati-hati.'],
      ['We stop at the red light.', 'Kami berhenti di lampu merah.', true],
      ['Safety first!', 'Utamakan keselamatan!'],
    ],
    vocab: [
      ['barber', 'tukang cukur', '💈', 'noun', ['barbers'], 'to the barber'],
      ['tight', 'erat', '🤗', 'adverb', [], 'hold him tight'],
      ['slowly', 'pelan-pelan', '🐢', 'adverb', [], 'Dad drives slowly.'],
      ['carefully', 'dengan hati-hati', '⚠️', 'adverb', [], 'slowly and carefully'],
      ['safety', 'keselamatan', '⛑️', 'noun', [], 'Safety first!'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Where are they going? (Mereka pergi ke mana?)', ['To the barber', 'To school', 'To the zoo'], 0, '"Dad takes me to the barber."'],
      ['What does Rafi put on first? (Apa yang Rafi pakai pertama?)', ['His helmet', 'His shoes', 'His jacket'], 0, '"First, I put on my helmet."'],
      ['How does Dad drive? (Bagaimana Ayah menyetir?)', ['Fast', 'Slowly and carefully', 'With one hand'], 1, '"Dad drives slowly and carefully."'],
    ],
  },
  {
    slug: 'a3-big-trucks', theme: 'Transportation', emoji: '🚚', title: 'Big Trucks', titleId: 'Truk-truk Besar', minutes: 3,
    sentences: [
      ['Trucks are big and strong.', 'Truk itu besar dan kuat.'],
      ['Some trucks carry sand and stones.', 'Ada truk yang mengangkut pasir dan batu.'],
      ['Some trucks carry fruit and vegetables.', 'Ada truk yang mengangkut buah dan sayur.'],
      ['A tanker truck carries fuel.', 'Truk tangki mengangkut bahan bakar.'],
      ['A garbage truck takes away trash.', 'Truk sampah mengangkut sampah.', true],
      ['Trucks help our town every day.', 'Truk membantu kota kami setiap hari.'],
    ],
    vocab: [
      ['trucks', 'truk', '🚚', 'noun', ['truck'], 'Trucks are big.'],
      ['carry', 'mengangkut / membawa', '📦', 'verb', ['carries'], 'Some trucks carry sand.'],
      ['sand', 'pasir', '🏖️', 'noun', [], 'sand and stones'],
      ['stones', 'batu', '🪨', 'noun', ['stone'], 'sand and stones'],
      ['fuel', 'bahan bakar', '⛽', 'noun', [], 'carries fuel'],
      ['trash', 'sampah', '🗑️', 'noun', [], 'takes away trash'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What does a garbage truck take away? (Truk sampah mengangkut apa?)', ['Trash', 'Fuel', 'Fruit'], 0, '"A garbage truck takes away trash."'],
      ['What does a tanker truck carry? (Truk tangki mengangkut apa?)', ['Sand', 'Fuel', 'People'], 1, '"A tanker truck carries fuel."'],
      ['"Stones" artinya …', ['Pasir', 'Batu', 'Kayu'], 1, 'Stones = batu.'],
    ],
  },
  {
    slug: 'a3-how-do-you-go', theme: 'Transportation', emoji: '🗺️', title: 'How Do You Go?', titleId: 'Kamu Naik Apa?', minutes: 3,
    sentences: [
      ['We go to many places.', 'Kita pergi ke banyak tempat.'],
      ['We go by car, by bus, or by train.', 'Kita pergi naik mobil, bus, atau kereta.'],
      ['We cross the sea by boat or ship.', 'Kita menyeberangi laut dengan perahu atau kapal.'],
      ['We fly to far places by plane.', 'Kita terbang ke tempat jauh naik pesawat.'],
      ['Some people go on foot.', 'Sebagian orang berjalan kaki.', true],
      ['How do you go to school?', 'Kamu ke sekolah naik apa?'],
    ],
    vocab: [
      ['places', 'tempat', '📍', 'noun', ['place'], 'many places'],
      ['by car', 'naik mobil', '🚗', 'phrase', [], 'by car'],
      ['boat', 'perahu', '🛶', 'noun', ['boats'], 'by boat'],
      ['ship', 'kapal', '🚢', 'noun', ['ships'], 'by boat or ship'],
      ['fly', 'terbang', '✈️', 'verb', ['flies'], 'We fly to far places.'],
    ],
    grammar: [{
      title: 'Naik apa? by + kendaraan',
      pattern: 'by car • by bus • by train • by plane • on foot',
      explanation: 'Untuk mengatakan "naik …", pakai by lalu nama kendaraan tanpa a/the. Khusus berjalan kaki memakai on foot.',
      examples: ['I go to school by bus.', 'Budi goes to school on foot.'],
    }],
    quiz: [
      ['How do we cross the sea? (Bagaimana kita menyeberangi laut?)', ['By boat or ship', 'By bike', 'On foot'], 0, '"We cross the sea by boat or ship."'],
      ['"By plane" artinya …', ['Naik pesawat', 'Naik kereta', 'Jalan kaki'], 0, 'Plane = pesawat.'],
      ['"On foot" artinya …', ['Naik motor', 'Berjalan kaki', 'Naik bus'], 1, 'On foot = berjalan kaki.'],
    ],
  },

  // ── Minggu 18: Tempat di Kota ────────────────────────────────────────────
  {
    slug: 'a3-the-traditional-market', theme: 'Places', emoji: '🧺', title: 'The Morning Market', titleId: 'Pasar Pagi', minutes: 3,
    sentences: [
      ['Mom and I go to the market early.', 'Ibu dan aku pergi ke pasar pagi-pagi.'],
      ['The market is crowded and noisy.', 'Pasarnya ramai dan bising.'],
      ['Sellers sell fish, meat, and vegetables.', 'Para penjual menjual ikan, daging, dan sayur.'],
      ['Mom buys tofu, tempeh, and spinach.', 'Ibu membeli tahu, tempe, dan bayam.'],
      ['I carry the shopping bag.', 'Aku membawa tas belanja.', true],
      ['The vegetables here are fresh and cheap.', 'Sayur di sini segar dan murah.'],
    ],
    vocab: [
      ['crowded', 'ramai / penuh orang', '👥', 'adjective', [], 'The market is crowded.'],
      ['meat', 'daging', '🥩', 'noun', [], 'fish, meat, and vegetables'],
      ['tofu', 'tahu', '🧈', 'noun', [], 'Mom buys tofu.'],
      ['spinach', 'bayam', '🥬', 'noun', [], 'and spinach'],
      ['shopping bag', 'tas belanja', '🛍️', 'noun', [], 'the shopping bag'],
      ['cheap', 'murah', '💲', 'adjective', [], 'fresh and cheap'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What does Mom buy? (Ibu membeli apa?)', ['Tofu, tempeh, and spinach', 'Shoes', 'Toys'], 0, '"Mom buys tofu, tempeh, and spinach."'],
      ['What does Rafi carry? (Rafi membawa apa?)', ['The shopping bag', 'A fish', 'A book'], 0, '"I carry the shopping bag."'],
      ['"Cheap" artinya …', ['Mahal', 'Murah', 'Mewah'], 1, 'Cheap = murah, expensive = mahal.'],
    ],
  },
  {
    slug: 'a3-the-hospital-visit', theme: 'Places', emoji: '🏥', title: 'Visiting Budi', titleId: 'Menjenguk Budi', minutes: 3,
    sentences: [
      ['Budi is in the hospital.', 'Budi sedang dirawat di rumah sakit.'],
      ['He has a fever.', 'Dia demam.'],
      ['Rafi and Mom visit him.', 'Rafi dan Ibu menjenguknya.'],
      ['They bring oranges and a comic book.', 'Mereka membawa jeruk dan buku komik.'],
      ['Budi is lying in bed.', 'Budi sedang berbaring di tempat tidur.', true],
      ['"Thank you for coming," he says.', '"Terima kasih sudah datang," katanya.'],
      ['"Get well soon, Budi!"', '"Cepat sembuh, Budi!"'],
    ],
    vocab: [
      ['fever', 'demam', '🤒', 'noun', [], 'He has a fever.'],
      ['visit', 'menjenguk / mengunjungi', '🚶', 'verb', ['visits'], 'Rafi and Mom visit him.'],
      ['oranges', 'jeruk', '🍊', 'noun', ['orange'], 'oranges and a comic book'],
      ['lying', 'sedang berbaring', '🛏️', 'verb', ['lie'], 'Budi is lying in bed.'],
      ['coming', 'datang', '🚪', 'verb', ['come'], 'Thank you for coming.'],
    ],
    grammar: [P.ingNow],
    quiz: [
      ['Why is Budi in the hospital? (Mengapa Budi di rumah sakit?)', ['He has a fever', 'He works there', 'He visits a friend'], 0, '"He has a fever."'],
      ['What do they bring? (Apa yang mereka bawa?)', ['Oranges and a comic book', 'A cake', 'Flowers'], 0, '"They bring oranges and a comic book."'],
      ['"Fever" artinya …', ['Batuk', 'Demam', 'Pilek'], 1, 'Fever = demam.'],
    ],
  },
  {
    slug: 'a3-the-post-office', theme: 'Places', emoji: '🏤', title: 'At the Post Office', titleId: 'Di Kantor Pos', minutes: 3,
    sentences: [
      ['Rafi writes a letter to Grandma.', 'Rafi menulis surat untuk Nenek.'],
      ['He puts it in an envelope.', 'Dia memasukkannya ke dalam amplop.'],
      ['He writes Grandma\'s address on it.', 'Dia menulis alamat Nenek di amplop itu.'],
      ['Mom takes him to the post office.', 'Ibu mengantarnya ke kantor pos.'],
      ['He buys a stamp and sticks it on.', 'Dia membeli prangko dan menempelkannya.', true],
      ['He drops the letter in the mailbox.', 'Dia memasukkan surat ke kotak pos.'],
    ],
    vocab: [
      ['envelope', 'amplop', '✉️', 'noun', ['envelopes'], 'in an envelope'],
      ['address', 'alamat', '🏷️', 'noun', [], 'Grandma\'s address'],
      ['post office', 'kantor pos', '🏤', 'noun', [], 'to the post office'],
      ['stamp', 'prangko', '📮', 'noun', ['stamps'], 'He buys a stamp.'],
      ['sticks', 'menempelkan', '🩹', 'verb', ['stick'], 'sticks it on'],
      ['mailbox', 'kotak pos', '📫', 'noun', [], 'in the mailbox'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Who is the letter for? (Surat itu untuk siapa?)', ['Grandma', 'Dina', 'Dad'], 0, '"Rafi writes a letter to Grandma."'],
      ['What does Rafi buy? (Apa yang Rafi beli?)', ['A stamp', 'A pen', 'A cake'], 0, '"He buys a stamp."'],
      ['"Address" artinya …', ['Alamat', 'Nama', 'Surat'], 0, 'Address = alamat.'],
    ],
  },
  {
    slug: 'a3-the-bookshop', theme: 'Places', emoji: '📚', title: 'At the Bookshop', titleId: 'Di Toko Buku', minutes: 3,
    sentences: [
      ['It is Aisyah\'s birthday soon.', 'Sebentar lagi ulang tahun Aisyah.'],
      ['Rafi and Dad go to the bookshop.', 'Rafi dan Ayah pergi ke toko buku.'],
      ['There are thousands of books!', 'Ada ribuan buku!'],
      ['Rafi finds a book about a little princess.', 'Rafi menemukan buku tentang seorang putri kecil.'],
      ['It has big, colorful pictures.', 'Buku itu punya gambar besar warna-warni.', true],
      ['"Aisyah will love this!" he says.', '"Aisyah pasti suka ini!" katanya.'],
      ['Dad pays for the book at the cashier.', 'Ayah membayar buku itu di kasir.'],
    ],
    vocab: [
      ['bookshop', 'toko buku', '📚', 'noun', ['bookshops'], 'to the bookshop'],
      ['thousands', 'ribuan', '🔢', 'noun', ['thousand'], 'thousands of books'],
      ['princess', 'putri raja', '👸', 'noun', ['princesses'], 'a little princess'],
      ['pays', 'membayar', '💳', 'verb', ['pay'], 'Dad pays for the book.'],
      ['cashier', 'kasir', '🧾', 'noun', ['cashiers'], 'at the cashier'],
    ],
    grammar: [P.willFuture],
    quiz: [
      ['Why do they go to the bookshop? (Mengapa mereka ke toko buku?)', ['For Aisyah\'s birthday', 'For school', 'To read'], 0, '"It is Aisyah\'s birthday soon."'],
      ['What is the book about? (Buku itu tentang apa?)', ['A little princess', 'A big truck', 'Space'], 0, '"a book about a little princess"'],
      ['Where does Dad pay? (Di mana Ayah membayar?)', ['At the cashier', 'At the door', 'At home'], 0, '"at the cashier"'],
    ],
  },
  {
    slug: 'a3-the-bank', theme: 'Places', emoji: '🏦', title: 'My Savings', titleId: 'Tabunganku', minutes: 3,
    sentences: [
      ['Rafi has a piggy bank.', 'Rafi punya celengan.'],
      ['He puts coins in it every day.', 'Dia memasukkan koin ke dalamnya setiap hari.'],
      ['Now the piggy bank is full.', 'Sekarang celengannya penuh.'],
      ['Dad takes Rafi to the bank.', 'Ayah mengantar Rafi ke bank.'],
      ['Rafi gives his money to the bank teller.', 'Rafi menyerahkan uangnya kepada petugas bank.', true],
      ['Now he has a savings book!', 'Sekarang dia punya buku tabungan!'],
      ['"I want to save for a new bike," he says.', '"Aku ingin menabung untuk sepeda baru," katanya.'],
    ],
    vocab: [
      ['piggy bank', 'celengan', '🐷', 'noun', [], 'a piggy bank'],
      ['coins', 'koin / uang logam', '🪙', 'noun', ['coin'], 'He puts coins in it.'],
      ['full', 'penuh', '🈵', 'adjective', [], 'the piggy bank is full'],
      ['bank', 'bank', '🏦', 'noun', ['banks'], 'to the bank'],
      ['money', 'uang', '💰', 'noun', [], 'his money'],
      ['save', 'menabung', '💵', 'verb', ['saves'], 'I want to save for a new bike.'],
    ],
    grammar: [P.wantTo],
    quiz: [
      ['What does Rafi put in his piggy bank? (Apa yang Rafi masukkan ke celengan?)', ['Coins', 'Candy', 'Stones'], 0, '"He puts coins in it every day."'],
      ['Where does Dad take Rafi? (Ayah mengantar Rafi ke mana?)', ['To the bank', 'To the market', 'To school'], 0, '"Dad takes Rafi to the bank."'],
      ['What does Rafi want to save for? (Rafi ingin menabung untuk apa?)', ['A new bike', 'A phone', 'A cat'], 0, '"I want to save for a new bike."'],
    ],
  },
  {
    slug: 'a3-the-fire-station', theme: 'Places', emoji: '🚒', title: 'A Trip to the Fire Station', titleId: 'Kunjungan ke Pos Pemadam Kebakaran', minutes: 3,
    sentences: [
      ['Our class visits the fire station.', 'Kelas kami berkunjung ke pos pemadam kebakaran.'],
      ['A firefighter shows us the fire truck.', 'Seorang petugas menunjukkan truk pemadam kepada kami.'],
      ['It has a long ladder and a big hose.', 'Truk itu punya tangga panjang dan selang besar.'],
      ['We try on the heavy helmets.', 'Kami mencoba memakai helm yang berat.'],
      ['We learn what to do in a fire.', 'Kami belajar apa yang harus dilakukan saat kebakaran.', true],
      ['Stay calm and get out fast!', 'Tetap tenang dan segera keluar!'],
    ],
    vocab: [
      ['fire station', 'pos pemadam kebakaran', '🚒', 'noun', [], 'the fire station'],
      ['ladder', 'tangga', '🪜', 'noun', ['ladders'], 'a long ladder'],
      ['hose', 'selang', '🧯', 'noun', ['hoses'], 'a big hose'],
      ['try on', 'mencoba memakai', '⛑️', 'verb', [], 'We try on the heavy helmets.'],
      ['calm', 'tenang', '😌', 'adjective', [], 'Stay calm.'],
    ],
    grammar: [P.commands],
    quiz: [
      ['Where does the class go? (Kelas pergi ke mana?)', ['To the fire station', 'To the zoo', 'To the bank'], 0, '"Our class visits the fire station."'],
      ['What does the truck have? (Apa yang dimiliki truk itu?)', ['A long ladder and a big hose', 'A kitchen', 'Wings'], 0, '"a long ladder and a big hose"'],
      ['What should we do in a fire? (Apa yang harus kita lakukan saat kebakaran?)', ['Stay calm and get out fast', 'Hide under the bed', 'Go to sleep'], 0, '"Stay calm and get out fast!"'],
    ],
  },
  {
    slug: 'a3-the-mosque-near-my-house', theme: 'Places', emoji: '🕌', title: 'The Mosque Near My House', titleId: 'Masjid Dekat Rumahku', minutes: 3,
    sentences: [
      ['There is a mosque near my house.', 'Ada masjid di dekat rumahku.'],
      ['It has a green dome and a tall tower.', 'Masjid itu punya kubah hijau dan menara tinggi.'],
      ['Five times a day, we hear the call to prayer.', 'Lima kali sehari, kami mendengar azan.'],
      ['In the afternoon, I study the Quran there.', 'Pada sore hari, aku mengaji di sana.'],
      ['My teacher is Ustazah Nur.', 'Guruku Ustazah Nur.', true],
      ['She is patient and kind.', 'Dia sabar dan baik hati.'],
    ],
    vocab: [
      ['near', 'dekat', '📍', 'preposition', [], 'near my house'],
      ['dome', 'kubah', '🕌', 'noun', ['domes'], 'a green dome'],
      ['call to prayer', 'azan', '📢', 'noun', [], 'the call to prayer'],
      ['study', 'belajar / mengaji', '📖', 'verb', ['studies'], 'I study the Quran there.'],
      ['patient', 'sabar', '🧘', 'adjective', [], 'She is patient.'],
    ],
    grammar: [P.thereIsAre],
    quiz: [
      ['What color is the dome? (Apa warna kubahnya?)', ['Green', 'Gold', 'White'], 0, '"a green dome"'],
      ['How many times a day do we hear the call to prayer? (Berapa kali sehari terdengar azan?)', ['Three', 'Five', 'Seven'], 1, '"Five times a day"'],
      ['"Patient" artinya …', ['Sabar', 'Galak', 'Sibuk'], 0, 'Patient = sabar.'],
    ],
  },

  // ── Minggu 19: Hewan Liar ────────────────────────────────────────────────
  {
    slug: 'a3-the-elephant', theme: 'Wild Animals', emoji: '🐘', title: 'The Gentle Elephant', titleId: 'Gajah yang Lembut', minutes: 3,
    sentences: [
      ['The elephant is a very big animal.', 'Gajah adalah hewan yang sangat besar.'],
      ['It has big ears and a long trunk.', 'Telinganya besar dan belalainya panjang.'],
      ['It uses its trunk to drink water.', 'Gajah memakai belalainya untuk minum.'],
      ['It eats leaves, grass, and fruit.', 'Gajah makan daun, rumput, dan buah.'],
      ['There are elephants in Sumatra.', 'Ada gajah di Sumatra.', true],
      ['Elephants are big, but they are gentle.', 'Gajah itu besar, tapi lembut.'],
    ],
    vocab: [
      ['elephant', 'gajah', '🐘', 'noun', ['elephants'], 'The elephant is a very big animal.'],
      ['animal', 'hewan', '🐾', 'noun', ['animals'], 'a very big animal'],
      ['trunk', 'belalai', '🐘', 'noun', [], 'a long trunk'],
      ['uses', 'memakai / menggunakan', '🛠️', 'verb', ['use'], 'It uses its trunk.'],
      ['leaves', 'daun-daun', '🍃', 'noun', ['leaf'], 'It eats leaves.'],
      ['gentle', 'lembut', '🕊️', 'adjective', [], 'they are gentle'],
    ],
    grammar: [P.iHave],
    quiz: [
      ['What does the elephant use to drink? (Gajah memakai apa untuk minum?)', ['Its trunk', 'Its tail', 'Its ears'], 0, '"It uses its trunk to drink water."'],
      ['Where are there elephants in Indonesia? (Di mana ada gajah di Indonesia?)', ['Sumatra', 'Bali', 'Jakarta'], 0, '"There are elephants in Sumatra."'],
      ['"Trunk" artinya …', ['Gading', 'Belalai', 'Ekor'], 1, 'Trunk = belalai.'],
    ],
  },
  {
    slug: 'a3-the-sumatran-tiger', theme: 'Wild Animals', emoji: '🐅', title: 'The Sumatran Tiger', titleId: 'Harimau Sumatra', minutes: 3,
    sentences: [
      ['This is a Sumatran tiger.', 'Ini harimau Sumatra.'],
      ['It is orange with black stripes.', 'Warnanya oranye dengan belang hitam.'],
      ['It lives in the forest.', 'Dia tinggal di hutan.'],
      ['It hunts at night.', 'Dia berburu pada malam hari.'],
      ['It can swim very well!', 'Dia bisa berenang dengan sangat baik!', true],
      ['There are not many tigers left.', 'Harimau yang tersisa sudah tidak banyak.'],
      ['We must protect them.', 'Kita harus melindungi mereka.'],
    ],
    vocab: [
      ['tiger', 'harimau', '🐅', 'noun', ['tigers'], 'a Sumatran tiger'],
      ['stripes', 'belang', '🦓', 'noun', ['stripe'], 'black stripes'],
      ['forest', 'hutan', '🌲', 'noun', ['forests'], 'It lives in the forest.'],
      ['hunts', 'berburu', '🎯', 'verb', ['hunt'], 'It hunts at night.'],
      ['left', 'tersisa', '🔻', 'adjective', [], 'not many tigers left'],
      ['protect', 'melindungi', '🛡️', 'verb', ['protects'], 'We must protect them.'],
    ],
    grammar: [P.iCan],
    quiz: [
      ['Where does the tiger live? (Di mana harimau tinggal?)', ['In the forest', 'In the sea', 'In a house'], 0, '"It lives in the forest."'],
      ['When does it hunt? (Kapan dia berburu?)', ['At night', 'In the morning', 'At lunch'], 0, '"It hunts at night."'],
      ['Can tigers swim? (Bisakah harimau berenang?)', ['Yes, very well', 'No, never'], 0, '"It can swim very well!"'],
    ],
  },
  {
    slug: 'a3-the-orangutan', theme: 'Wild Animals', emoji: '🦧', title: 'The Orangutan', titleId: 'Orangutan', minutes: 3,
    sentences: [
      ['The orangutan lives in Borneo and Sumatra.', 'Orangutan tinggal di Kalimantan dan Sumatra.'],
      ['It has long red-brown hair.', 'Bulunya panjang berwarna cokelat kemerahan.'],
      ['It has very long arms.', 'Lengannya sangat panjang.'],
      ['It swings from tree to tree.', 'Dia berayun dari pohon ke pohon.'],
      ['It makes a bed of leaves every night.', 'Dia membuat sarang dari daun setiap malam.', true],
      ['"Orang hutan" means "person of the forest".', '"Orang hutan" artinya "orang dari hutan".'],
    ],
    vocab: [
      ['orangutan', 'orangutan', '🦧', 'noun', ['orangutans'], 'The orangutan lives in Borneo.'],
      ['Borneo', 'Kalimantan', '🗺️', 'noun', [], 'in Borneo and Sumatra'],
      ['swings', 'berayun', '🌿', 'verb', ['swing'], 'It swings from tree to tree.'],
      ['means', 'berarti', '💡', 'verb', ['mean'], 'means "person of the forest"'],
      ['person', 'orang', '🧍', 'noun', [], 'person of the forest'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Where does the orangutan live? (Di mana orangutan tinggal?)', ['Borneo and Sumatra', 'Java and Bali', 'Papua'], 0, '"The orangutan lives in Borneo and Sumatra."'],
      ['What does it make every night? (Apa yang dibuatnya setiap malam?)', ['A bed of leaves', 'A house', 'A fire'], 0, '"It makes a bed of leaves every night."'],
      ['How does it move? (Bagaimana ia bergerak?)', ['It swings from tree to tree', 'It swims', 'It flies'], 0, '"It swings from tree to tree."'],
    ],
  },
  {
    slug: 'a3-the-komodo-dragon', theme: 'Wild Animals', emoji: '🦎', title: 'The Komodo Dragon', titleId: 'Komodo', minutes: 3,
    sentences: [
      ['The Komodo dragon is a giant lizard.', 'Komodo adalah kadal raksasa.'],
      ['It lives only in Indonesia.', 'Komodo hanya hidup di Indonesia.'],
      ['It is long and very heavy.', 'Tubuhnya panjang dan sangat berat.'],
      ['It has a long yellow tongue.', 'Lidahnya panjang dan berwarna kuning.'],
      ['It uses its tongue to smell food.', 'Komodo memakai lidahnya untuk mencium makanan.', true],
      ['Do not go near a Komodo dragon!', 'Jangan mendekati komodo!'],
    ],
    vocab: [
      ['dragon', 'naga', '🐉', 'noun', ['dragons'], 'The Komodo dragon'],
      ['giant', 'raksasa', '🦖', 'adjective', [], 'a giant lizard'],
      ['lizard', 'kadal', '🦎', 'noun', ['lizards'], 'a giant lizard'],
      ['only', 'hanya', '☝️', 'adverb', [], 'It lives only in Indonesia.'],
      ['tongue', 'lidah', '👅', 'noun', [], 'a long yellow tongue'],
    ],
    grammar: [P.commands],
    quiz: [
      ['What is a Komodo dragon? (Komodo itu apa?)', ['A giant lizard', 'A big bird', 'A fish'], 0, '"The Komodo dragon is a giant lizard."'],
      ['Where does it live? (Di mana komodo hidup?)', ['Only in Indonesia', 'In Africa', 'Everywhere'], 0, '"It lives only in Indonesia."'],
      ['What does it use to smell food? (Komodo memakai apa untuk mencium makanan?)', ['Its tongue', 'Its nose', 'Its tail'], 0, '"It uses its tongue to smell food."'],
    ],
  },
  {
    slug: 'a3-the-giraffe', theme: 'Wild Animals', emoji: '🦒', title: 'The Tall Giraffe', titleId: 'Jerapah yang Tinggi', minutes: 3,
    sentences: [
      ['The giraffe is the tallest animal.', 'Jerapah adalah hewan paling tinggi.'],
      ['It has a very long neck.', 'Lehernya sangat panjang.'],
      ['It has brown spots on its body.', 'Ada bintik-bintik cokelat di tubuhnya.'],
      ['It eats leaves from tall trees.', 'Jerapah makan daun dari pohon-pohon tinggi.'],
      ['Giraffes live in Africa.', 'Jerapah hidup di Afrika.', true],
      ['You can see giraffes at the zoo.', 'Kamu bisa melihat jerapah di kebun binatang.'],
    ],
    vocab: [
      ['giraffe', 'jerapah', '🦒', 'noun', ['giraffes'], 'The giraffe is the tallest animal.'],
      ['tallest', 'paling tinggi', '📏', 'adjective', ['tall'], 'the tallest animal'],
      ['neck', 'leher', '🦒', 'noun', ['necks'], 'a very long neck'],
      ['spots', 'bintik', '🟤', 'noun', ['spot'], 'brown spots'],
      ['Africa', 'Afrika', '🌍', 'noun', [], 'Giraffes live in Africa.'],
      ['zoo', 'kebun binatang', '🦁', 'noun', ['zoos'], 'at the zoo'],
    ],
    grammar: [P.iHave],
    quiz: [
      ['What is special about the giraffe? (Apa yang istimewa dari jerapah?)', ['It is the tallest animal', 'It is the smallest', 'It can fly'], 0, '"The giraffe is the tallest animal."'],
      ['What does it eat? (Jerapah makan apa?)', ['Leaves from tall trees', 'Fish', 'Meat'], 0, '"It eats leaves from tall trees."'],
      ['Where do giraffes live? (Di mana jerapah hidup?)', ['Africa', 'Indonesia', 'Japan'], 0, '"Giraffes live in Africa."'],
    ],
  },
  {
    slug: 'a3-the-crocodile', theme: 'Wild Animals', emoji: '🐊', title: 'The Crocodile in the River', titleId: 'Buaya di Sungai', minutes: 3,
    sentences: [
      ['A crocodile lives in the river.', 'Seekor buaya tinggal di sungai.'],
      ['It has rough green skin.', 'Kulitnya kasar dan hijau.'],
      ['It has many sharp teeth.', 'Giginya banyak dan tajam.'],
      ['It lies very still in the water.', 'Dia diam tak bergerak di dalam air.'],
      ['It looks like a log!', 'Dia terlihat seperti batang kayu!', true],
      ['Be careful near rivers.', 'Hati-hati di dekat sungai.'],
    ],
    vocab: [
      ['crocodile', 'buaya', '🐊', 'noun', ['crocodiles'], 'A crocodile lives in the river.'],
      ['river', 'sungai', '🏞️', 'noun', ['rivers'], 'in the river'],
      ['rough', 'kasar', '🪨', 'adjective', [], 'rough green skin'],
      ['looks like', 'terlihat seperti', '👀', 'verb', ['look like'], 'It looks like a log!'],
      ['log', 'batang kayu', '🪵', 'noun', ['logs'], 'a log'],
      ['careful', 'hati-hati', '⚠️', 'adjective', [], 'Be careful near rivers.'],
    ],
    grammar: [P.iHave],
    quiz: [
      ['Where does the crocodile live? (Di mana buaya tinggal?)', ['In the river', 'In a tree', 'In the desert'], 0, '"A crocodile lives in the river."'],
      ['What does it look like in the water? (Seperti apa ia terlihat di air?)', ['A log', 'A boat', 'A fish'], 0, '"It looks like a log!"'],
      ['"Careful" artinya …', ['Hati-hati', 'Cepat', 'Senang'], 0, 'Careful = hati-hati.'],
    ],
  },
  {
    slug: 'a3-the-rhino', theme: 'Wild Animals', emoji: '🦏', title: 'The Javan Rhino', titleId: 'Badak Jawa', minutes: 3,
    sentences: [
      ['The Javan rhino has one horn.', 'Badak Jawa punya satu cula.'],
      ['It has thick gray skin.', 'Kulitnya tebal dan berwarna abu-abu.'],
      ['It lives in Ujung Kulon National Park.', 'Badak Jawa tinggal di Taman Nasional Ujung Kulon.'],
      ['It likes to roll in the mud.', 'Badak suka berguling di lumpur.'],
      ['The mud keeps it cool.', 'Lumpur membuat tubuhnya tetap sejuk.', true],
      ['There are very few Javan rhinos. Let us protect them!', 'Badak Jawa tinggal sangat sedikit. Ayo kita lindungi!'],
    ],
    vocab: [
      ['rhino', 'badak', '🦏', 'noun', ['rhinos'], 'The Javan rhino'],
      ['horn', 'cula / tanduk', '🦏', 'noun', ['horns'], 'one horn'],
      ['thick', 'tebal', '📏', 'adjective', [], 'thick gray skin'],
      ['roll', 'berguling', '🔄', 'verb', ['rolls'], 'roll in the mud'],
      ['mud', 'lumpur', '🟤', 'noun', [], 'in the mud'],
      ['few', 'sedikit', '🤏', 'adjective', [], 'very few'],
    ],
    grammar: [P.iLike],
    quiz: [
      ['How many horns does the Javan rhino have? (Badak Jawa punya berapa cula?)', ['One', 'Two', 'Three'], 0, '"The Javan rhino has one horn."'],
      ['Where does it live? (Di mana badak Jawa tinggal?)', ['Ujung Kulon National Park', 'Komodo Island', 'Bali'], 0, '"It lives in Ujung Kulon National Park."'],
      ['Why does it roll in the mud? (Mengapa ia berguling di lumpur?)', ['To keep cool', 'To eat', 'To sleep'], 0, '"The mud keeps it cool."'],
    ],
  },

  // ── Minggu 20: Hewan Laut ────────────────────────────────────────────────
  {
    slug: 'a3-the-sea-turtle', theme: 'Sea Life', emoji: '🐢', title: 'The Sea Turtle', titleId: 'Penyu', minutes: 3,
    sentences: [
      ['The sea turtle lives in the ocean.', 'Penyu hidup di lautan.'],
      ['It has a hard shell on its back.', 'Ada tempurung keras di punggungnya.'],
      ['It swims with its flippers.', 'Penyu berenang dengan siripnya.'],
      ['At night, the mother turtle comes to the beach.', 'Pada malam hari, induk penyu datang ke pantai.'],
      ['She lays her eggs in the sand.', 'Dia bertelur di pasir.', true],
      ['Baby turtles walk to the sea.', 'Bayi-bayi penyu berjalan menuju laut.'],
    ],
    vocab: [
      ['turtle', 'penyu / kura-kura', '🐢', 'noun', ['turtles'], 'The sea turtle'],
      ['hard', 'keras', '🪨', 'adjective', [], 'a hard shell'],
      ['shell', 'tempurung / cangkang', '🐚', 'noun', ['shells'], 'a hard shell'],
      ['flippers', 'sirip (penyu)', '🐢', 'noun', ['flipper'], 'with its flippers'],
      ['beach', 'pantai', '🏖️', 'noun', ['beaches'], 'to the beach'],
      ['lays', 'bertelur / meletakkan', '🥚', 'verb', ['lay'], 'She lays her eggs.'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Where does the turtle lay her eggs? (Di mana penyu bertelur?)', ['In the sand', 'In the water', 'In a tree'], 0, '"She lays her eggs in the sand."'],
      ['What does it swim with? (Penyu berenang dengan apa?)', ['Its flippers', 'Its tail', 'Its shell'], 0, '"It swims with its flippers."'],
      ['When does the mother turtle come to the beach? (Kapan induk penyu datang ke pantai?)', ['At night', 'At noon', 'In the morning'], 0, '"At night, the mother turtle comes to the beach."'],
    ],
  },
  {
    slug: 'a3-the-dolphin', theme: 'Sea Life', emoji: '🐬', title: 'The Smart Dolphin', titleId: 'Lumba-lumba yang Pintar', minutes: 3,
    sentences: [
      ['Dolphins live in the sea.', 'Lumba-lumba hidup di laut.'],
      ['They are very smart.', 'Mereka sangat pintar.'],
      ['They swim in groups.', 'Mereka berenang berkelompok.'],
      ['They jump out of the water and play.', 'Mereka melompat keluar dari air dan bermain.'],
      ['They talk to each other with clicks and whistles.', 'Mereka berbicara satu sama lain dengan bunyi klik dan siulan.', true],
      ['Dolphins need air, so they come up to breathe.', 'Lumba-lumba butuh udara, jadi mereka naik ke permukaan untuk bernapas.'],
    ],
    vocab: [
      ['dolphins', 'lumba-lumba', '🐬', 'noun', ['dolphin'], 'Dolphins live in the sea.'],
      ['groups', 'kelompok', '👥', 'noun', ['group'], 'in groups'],
      ['each other', 'satu sama lain', '🔁', 'phrase', [], 'talk to each other'],
      ['whistles', 'siulan', '🎶', 'noun', ['whistle'], 'clicks and whistles'],
      ['air', 'udara', '💨', 'noun', [], 'Dolphins need air.'],
      ['breathe', 'bernapas', '😮‍💨', 'verb', ['breathes'], 'to breathe'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['How do dolphins swim? (Bagaimana lumba-lumba berenang?)', ['In groups', 'Alone at night', 'Backwards'], 0, '"They swim in groups."'],
      ['How do they talk? (Bagaimana mereka berbicara?)', ['With clicks and whistles', 'With words', 'With colors'], 0, '"with clicks and whistles"'],
      ['Why do they come up? (Mengapa mereka naik ke permukaan?)', ['To breathe', 'To eat sand', 'To sleep'], 0, '"they come up to breathe"'],
    ],
  },
  {
    slug: 'a3-the-coral-reef', theme: 'Sea Life', emoji: '🪸', title: 'The Coral Reef', titleId: 'Terumbu Karang', minutes: 3,
    sentences: [
      ['Under the sea, there is a coral reef.', 'Di bawah laut, ada terumbu karang.'],
      ['Coral is pink, orange, and purple.', 'Karang berwarna merah muda, oranye, dan ungu.'],
      ['Many colorful fish live there.', 'Banyak ikan warna-warni tinggal di sana.'],
      ['Clownfish hide in the sea anemones.', 'Ikan badut bersembunyi di anemon laut.'],
      ['Indonesia has many beautiful coral reefs.', 'Indonesia punya banyak terumbu karang yang indah.', true],
      ['Don\'t touch or break the coral!', 'Jangan menyentuh atau mematahkan karang!'],
    ],
    vocab: [
      ['coral reef', 'terumbu karang', '🪸', 'noun', ['coral reefs'], 'a coral reef'],
      ['coral', 'karang', '🪸', 'noun', [], 'Coral is pink.'],
      ['clownfish', 'ikan badut', '🐠', 'noun', [], 'Clownfish hide'],
      ['sea anemones', 'anemon laut', '🌺', 'noun', ['sea anemone'], 'in the sea anemones'],
      ['break', 'mematahkan / merusak', '💔', 'verb', ['breaks'], 'Don\'t touch or break the coral!'],
    ],
    grammar: [P.thereIsAre],
    quiz: [
      ['Where do clownfish hide? (Di mana ikan badut bersembunyi?)', ['In the sea anemones', 'In the sand', 'In a boat'], 0, '"Clownfish hide in the sea anemones."'],
      ['What colors is coral? (Apa saja warna karang?)', ['Pink, orange, and purple', 'Black and white', 'Only green'], 0, '"Coral is pink, orange, and purple."'],
      ['What must we not do? (Apa yang tidak boleh kita lakukan?)', ['Touch or break the coral', 'Look at the fish', 'Swim'], 0, '"Don\'t touch or break the coral!"'],
    ],
  },
  {
    slug: 'a3-the-crab', theme: 'Sea Life', emoji: '🦀', title: 'The Funny Crab', titleId: 'Kepiting yang Lucu', minutes: 3,
    sentences: [
      ['A crab lives on the beach.', 'Seekor kepiting tinggal di pantai.'],
      ['It has eight legs and two big claws.', 'Kepiting punya delapan kaki dan dua capit besar.'],
      ['It walks sideways!', 'Dia berjalan menyamping!'],
      ['It digs a hole in the sand.', 'Dia menggali lubang di pasir.'],
      ['When a wave comes, it hides in the hole.', 'Saat ombak datang, dia bersembunyi di lubangnya.', true],
      ['Aisyah tries to walk like a crab. She laughs!', 'Aisyah mencoba berjalan seperti kepiting. Dia tertawa!'],
    ],
    vocab: [
      ['crab', 'kepiting', '🦀', 'noun', ['crabs'], 'A crab lives on the beach.'],
      ['claws', 'capit', '🦀', 'noun', ['claw'], 'two big claws'],
      ['sideways', 'menyamping', '↔️', 'adverb', [], 'It walks sideways!'],
      ['digs', 'menggali', '⛏️', 'verb', ['dig'], 'It digs a hole.'],
      ['hole', 'lubang', '🕳️', 'noun', ['holes'], 'a hole in the sand'],
      ['wave', 'ombak', '🌊', 'noun', ['waves'], 'When a wave comes'],
    ],
    grammar: [P.iHave],
    quiz: [
      ['How does a crab walk? (Bagaimana kepiting berjalan?)', ['Sideways', 'Backwards', 'On two legs'], 0, '"It walks sideways!"'],
      ['How many claws does it have? (Berapa capitnya?)', ['One', 'Two', 'Eight'], 1, '"two big claws"'],
      ['Where does it hide? (Di mana ia bersembunyi?)', ['In the hole', 'In a tree', 'In the boat'], 0, '"it hides in the hole"'],
    ],
  },
  {
    slug: 'a3-the-whale-shark', theme: 'Sea Life', emoji: '🦈', title: 'The Gentle Giant Fish', titleId: 'Ikan Raksasa yang Jinak', minutes: 3,
    sentences: [
      ['The whale shark is the biggest fish.', 'Hiu paus adalah ikan terbesar.'],
      ['It is as long as a bus!', 'Panjangnya sepanjang bus!'],
      ['It has white spots on its back.', 'Ada bintik-bintik putih di punggungnya.'],
      ['It eats tiny plants and animals in the sea.', 'Ia makan tumbuhan dan hewan kecil di laut.'],
      ['It does not hurt people.', 'Ia tidak menyakiti manusia.', true],
      ['People can see whale sharks in Papua.', 'Orang bisa melihat hiu paus di Papua.'],
    ],
    vocab: [
      ['whale shark', 'hiu paus', '🦈', 'noun', ['whale sharks'], 'The whale shark'],
      ['biggest', 'terbesar', '🔝', 'adjective', ['big'], 'the biggest fish'],
      ['as long as', 'sepanjang', '📏', 'phrase', [], 'as long as a bus'],
      ['tiny', 'sangat kecil', '🔬', 'adjective', [], 'tiny plants and animals'],
      ['hurt', 'menyakiti', '🤕', 'verb', ['hurts'], 'It does not hurt people.'],
    ],
    grammar: [P.comparison],
    quiz: [
      ['What is the biggest fish? (Apa ikan terbesar?)', ['The whale shark', 'The goldfish', 'The clownfish'], 0, '"The whale shark is the biggest fish."'],
      ['How long is it? (Seberapa panjang ia?)', ['As long as a bus', 'As long as a pencil', 'As long as a cat'], 0, '"It is as long as a bus!"'],
      ['Does it hurt people? (Apakah ia menyakiti manusia?)', ['Yes', 'No'], 1, '"It does not hurt people."'],
    ],
  },
  {
    slug: 'a3-the-starfish', theme: 'Sea Life', emoji: '⭐', title: 'A Star in the Sea', titleId: 'Bintang di Laut', minutes: 3,
    sentences: [
      ['Rafi finds a starfish on the beach.', 'Rafi menemukan bintang laut di pantai.'],
      ['It has five arms.', 'Ia punya lima lengan.'],
      ['It is orange and a little rough.', 'Warnanya oranye dan agak kasar.'],
      ['A starfish has no brain and no blood!', 'Bintang laut tidak punya otak dan tidak punya darah!'],
      ['It needs sea water to live.', 'Ia butuh air laut untuk hidup.', true],
      ['Rafi puts it back in the sea gently.', 'Rafi mengembalikannya ke laut dengan hati-hati.'],
    ],
    vocab: [
      ['starfish', 'bintang laut', '⭐', 'noun', [], 'a starfish'],
      ['brain', 'otak', '🧠', 'noun', [], 'no brain'],
      ['blood', 'darah', '🩸', 'noun', [], 'no blood'],
      ['puts it back', 'mengembalikannya', '↩️', 'verb', ['put back'], 'Rafi puts it back.'],
      ['gently', 'dengan lembut / hati-hati', '🤲', 'adverb', [], 'gently'],
    ],
    grammar: [P.iHave],
    quiz: [
      ['How many arms does the starfish have? (Bintang laut punya berapa lengan?)', ['Four', 'Five', 'Eight'], 1, '"It has five arms."'],
      ['What does Rafi do with it? (Apa yang Rafi lakukan?)', ['He puts it back in the sea', 'He takes it home', 'He eats it'], 0, '"Rafi puts it back in the sea gently."'],
      ['A starfish has no … (Bintang laut tidak punya …)', ['Arms', 'Brain', 'Color'], 1, '"A starfish has no brain and no blood!"'],
    ],
  },
  {
    slug: 'a3-the-octopus', theme: 'Sea Life', emoji: '🐙', title: 'The Clever Octopus', titleId: 'Gurita yang Cerdik', minutes: 3,
    sentences: [
      ['The octopus has eight long arms.', 'Gurita punya delapan lengan panjang.'],
      ['It can change its color.', 'Ia bisa mengubah warnanya.'],
      ['It hides between the rocks.', 'Ia bersembunyi di antara batu karang.'],
      ['When it is scared, it shoots black ink.', 'Saat takut, ia menyemburkan tinta hitam.'],
      ['Then it swims away fast.', 'Lalu ia berenang pergi dengan cepat.', true],
      ['The octopus is very clever!', 'Gurita sangat cerdik!'],
    ],
    vocab: [
      ['octopus', 'gurita', '🐙', 'noun', [], 'The octopus has eight long arms.'],
      ['change', 'mengubah', '🔄', 'verb', ['changes'], 'It can change its color.'],
      ['rocks', 'batu (karang)', '🪨', 'noun', ['rock'], 'between the rocks'],
      ['ink', 'tinta', '🖋️', 'noun', [], 'black ink'],
      ['away', 'pergi / menjauh', '💨', 'adverb', [], 'it swims away'],
      ['clever', 'cerdik / pintar', '🧠', 'adjective', [], 'very clever'],
    ],
    grammar: [P.iCan],
    quiz: [
      ['How many arms does an octopus have? (Gurita punya berapa lengan?)', ['Six', 'Eight', 'Ten'], 1, '"eight long arms"'],
      ['What does it shoot when it is scared? (Apa yang ia semburkan saat takut?)', ['Black ink', 'Water', 'Bubbles'], 0, '"it shoots black ink"'],
      ['What can it change? (Apa yang bisa ia ubah?)', ['Its color', 'Its name', 'Its home'], 0, '"It can change its color."'],
    ],
  },

  // ── Minggu 21: Serangga & Hewan Kecil ────────────────────────────────────
  {
    slug: 'a3-busy-ants', theme: 'Small Animals', emoji: '🐜', title: 'Busy Ants', titleId: 'Semut yang Rajin', minutes: 3,
    sentences: [
      ['Look! There are many ants on the floor.', 'Lihat! Ada banyak semut di lantai.'],
      ['They walk in a long line.', 'Mereka berjalan dalam barisan panjang.'],
      ['They carry tiny crumbs of bread.', 'Mereka membawa remah-remah roti kecil.'],
      ['They take the food to their nest.', 'Mereka membawa makanan ke sarangnya.'],
      ['Ants work together.', 'Semut bekerja sama.', true],
      ['They are small, but very strong.', 'Mereka kecil, tapi sangat kuat.'],
    ],
    vocab: [
      ['ants', 'semut', '🐜', 'noun', ['ant'], 'many ants'],
      ['crumbs', 'remah-remah', '🍞', 'noun', ['crumb'], 'tiny crumbs of bread'],
      ['nest', 'sarang', '🪺', 'noun', ['nests'], 'to their nest'],
      ['work together', 'bekerja sama', '🤝', 'verb', [], 'Ants work together.'],
      ['strong', 'kuat', '💪', 'adjective', [], 'very strong'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What do the ants carry? (Apa yang dibawa semut?)', ['Crumbs of bread', 'Leaves', 'Stones'], 0, '"They carry tiny crumbs of bread."'],
      ['Where do they take the food? (Ke mana mereka membawa makanan?)', ['To their nest', 'To the kitchen', 'To the river'], 0, '"They take the food to their nest."'],
      ['How do ants work? (Bagaimana semut bekerja?)', ['Together', 'Alone', 'At school'], 0, '"Ants work together."'],
    ],
  },
  {
    slug: 'a3-from-caterpillar-to-butterfly', theme: 'Small Animals', emoji: '🦋', title: 'From Caterpillar to Butterfly', titleId: 'Dari Ulat Menjadi Kupu-kupu', minutes: 4,
    sentences: [
      ['A butterfly lays a tiny egg on a leaf.', 'Kupu-kupu bertelur kecil di atas daun.'],
      ['A caterpillar comes out of the egg.', 'Seekor ulat keluar dari telur itu.'],
      ['The caterpillar eats and eats. It gets fat!', 'Ulat itu makan terus. Ia menjadi gemuk!'],
      ['Then it makes a cocoon.', 'Lalu ia membuat kepompong.'],
      ['It sleeps inside for two weeks.', 'Ia tidur di dalamnya selama dua minggu.', true],
      ['Then a beautiful butterfly comes out!', 'Lalu keluarlah kupu-kupu yang indah!'],
    ],
    vocab: [
      ['caterpillar', 'ulat', '🐛', 'noun', ['caterpillars'], 'A caterpillar comes out.'],
      ['leaf', 'daun', '🍃', 'noun', ['leaves'], 'on a leaf'],
      ['fat', 'gemuk', '🐷', 'adjective', [], 'It gets fat!'],
      ['cocoon', 'kepompong', '🫘', 'noun', ['cocoons'], 'it makes a cocoon'],
      ['butterfly', 'kupu-kupu', '🦋', 'noun', ['butterflies'], 'a beautiful butterfly'],
    ],
    grammar: [{
      title: 'Urutan cerita: First, Then, Finally',
      pattern: 'First … • Then … • Finally …',
      explanation: 'Untuk menceritakan urutan kejadian, pakai first (pertama), then (lalu), dan finally (akhirnya).',
      examples: ['First, it is an egg.', 'Then it is a caterpillar. Finally, it is a butterfly.'],
    }],
    quiz: [
      ['What comes out of the egg? (Apa yang keluar dari telur?)', ['A caterpillar', 'A butterfly', 'A bird'], 0, '"A caterpillar comes out of the egg."'],
      ['What does the caterpillar make? (Apa yang dibuat ulat?)', ['A cocoon', 'A nest', 'A hole'], 0, '"it makes a cocoon"'],
      ['How long does it sleep inside? (Berapa lama ia tidur di dalam?)', ['Two days', 'Two weeks', 'Two years'], 1, '"for two weeks"'],
    ],
  },
  {
    slug: 'a3-the-honey-bee', theme: 'Small Animals', emoji: '🐝', title: 'The Honey Bee', titleId: 'Lebah Madu', minutes: 3,
    sentences: [
      ['Bzzz! A bee flies to a flower.', 'Ngiung! Seekor lebah terbang ke bunga.'],
      ['It drinks the sweet juice from the flower.', 'Ia meminum sari manis dari bunga.'],
      ['It takes the juice to the beehive.', 'Ia membawa sari itu ke sarang lebah.'],
      ['The bees make honey.', 'Lebah-lebah membuat madu.'],
      ['Honey is sweet and healthy.', 'Madu itu manis dan menyehatkan.', true],
      ['Be careful! Bees can sting.', 'Hati-hati! Lebah bisa menyengat.'],
    ],
    vocab: [
      ['bee', 'lebah', '🐝', 'noun', ['bees'], 'A bee flies to a flower.'],
      ['juice', 'sari / jus', '🧃', 'noun', [], 'the sweet juice'],
      ['beehive', 'sarang lebah', '🍯', 'noun', ['beehives'], 'to the beehive'],
      ['honey', 'madu', '🍯', 'noun', [], 'The bees make honey.'],
      ['sting', 'menyengat', '⚠️', 'verb', ['stings'], 'Bees can sting.'],
    ],
    grammar: [P.iCan],
    quiz: [
      ['What do bees make? (Apa yang dibuat lebah?)', ['Honey', 'Milk', 'Silk'], 0, '"The bees make honey."'],
      ['Where do bees take the juice? (Ke mana lebah membawa sari?)', ['To the beehive', 'To the river', 'To the house'], 0, '"It takes the juice to the beehive."'],
      ['"Sting" artinya …', ['Menyengat', 'Terbang', 'Bernyanyi'], 0, 'Sting = menyengat.'],
    ],
  },
  {
    slug: 'a3-the-spider-web', theme: 'Small Animals', emoji: '🕸️', title: 'The Spider\'s Web', titleId: 'Jaring Laba-laba', minutes: 3,
    sentences: [
      ['In the corner of the window, there is a web.', 'Di sudut jendela, ada jaring.'],
      ['A spider makes the web.', 'Seekor laba-laba membuat jaring itu.'],
      ['The web is thin but strong.', 'Jaringnya tipis tapi kuat.'],
      ['A fly gets stuck in the web.', 'Seekor lalat tersangkut di jaring.'],
      ['The spider eats the fly for lunch.', 'Laba-laba memakan lalat itu untuk makan siang.', true],
      ['Spiders help us. They eat bugs!', 'Laba-laba membantu kita. Mereka memakan serangga!'],
    ],
    vocab: [
      ['web', 'jaring', '🕸️', 'noun', ['webs'], 'there is a web'],
      ['thin', 'tipis', '📄', 'adjective', [], 'thin but strong'],
      ['fly', 'lalat', '🪰', 'noun', ['flies'], 'A fly gets stuck.'],
      ['stuck', 'tersangkut', '🪤', 'adjective', [], 'gets stuck in the web'],
      ['bugs', 'serangga', '🐞', 'noun', ['bug'], 'They eat bugs!'],
    ],
    grammar: [P.thereIsAre],
    quiz: [
      ['Where is the web? (Di mana jaringnya?)', ['In the corner of the window', 'Under the bed', 'In the garden'], 0, '"In the corner of the window, there is a web."'],
      ['What gets stuck in the web? (Apa yang tersangkut di jaring?)', ['A fly', 'A bird', 'A leaf'], 0, '"A fly gets stuck in the web."'],
      ['How do spiders help us? (Bagaimana laba-laba membantu kita?)', ['They eat bugs', 'They make honey', 'They sing'], 0, '"They eat bugs!"'],
    ],
  },
  {
    slug: 'a3-the-frog-in-the-rain', theme: 'Small Animals', emoji: '🐸', title: 'The Frog Song', titleId: 'Nyanyian Katak', minutes: 3,
    sentences: [
      ['After the rain, Rafi hears a sound.', 'Setelah hujan, Rafi mendengar sebuah suara.'],
      ['"Ribbit, ribbit!"', '"Kung kong, kung kong!"'],
      ['It is a frog in the puddle.', 'Itu seekor katak di genangan air.'],
      ['The frog is green and wet.', 'Kataknya hijau dan basah.'],
      ['It has strong back legs.', 'Kaki belakangnya kuat.', true],
      ['It jumps far! Jump, jump!', 'Ia melompat jauh! Lompat, lompat!'],
      ['Frogs love the rainy season.', 'Katak suka musim hujan.'],
    ],
    vocab: [
      ['sound', 'suara / bunyi', '🔊', 'noun', ['sounds'], 'Rafi hears a sound.'],
      ['frog', 'katak', '🐸', 'noun', ['frogs'], 'It is a frog.'],
      ['puddle', 'genangan air', '💧', 'noun', ['puddles'], 'in the puddle'],
      ['back legs', 'kaki belakang', '🦵', 'noun', [], 'strong back legs'],
      ['far', 'jauh', '📏', 'adverb', [], 'It jumps far!'],
    ],
    grammar: [P.iHave],
    quiz: [
      ['What does Rafi hear? (Apa yang Rafi dengar?)', ['A frog', 'A dog', 'A bird'], 0, '"It is a frog in the puddle."'],
      ['What color is the frog? (Apa warna kataknya?)', ['Green', 'Brown', 'Red'], 0, '"The frog is green and wet."'],
      ['What season do frogs love? (Katak suka musim apa?)', ['The rainy season', 'The dry season'], 0, '"Frogs love the rainy season."'],
    ],
  },
  {
    slug: 'a3-the-slow-snail', theme: 'Small Animals', emoji: '🐌', title: 'The Slow Snail', titleId: 'Siput yang Lambat', minutes: 3,
    sentences: [
      ['A snail is on a big leaf.', 'Seekor siput ada di atas daun besar.'],
      ['It carries its house on its back.', 'Ia membawa rumahnya di punggungnya.'],
      ['Its house is a spiral shell.', 'Rumahnya adalah cangkang berbentuk spiral.'],
      ['It moves very, very slowly.', 'Ia bergerak sangat, sangat lambat.'],
      ['It leaves a shiny trail behind it.', 'Ia meninggalkan jejak mengilap di belakangnya.', true],
      ['When it is scared, it goes into its shell.', 'Saat takut, ia masuk ke dalam cangkangnya.'],
    ],
    vocab: [
      ['snail', 'siput', '🐌', 'noun', ['snails'], 'A snail is on a big leaf.'],
      ['spiral', 'spiral / berpilin', '🌀', 'adjective', [], 'a spiral shell'],
      ['moves', 'bergerak', '🐢', 'verb', ['move'], 'It moves very slowly.'],
      ['shiny', 'mengilap', '✨', 'adjective', [], 'a shiny trail'],
      ['trail', 'jejak', '👣', 'noun', ['trails'], 'a shiny trail'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What does the snail carry? (Apa yang dibawa siput?)', ['Its house', 'A leaf', 'Food'], 0, '"It carries its house on its back."'],
      ['How does it move? (Bagaimana ia bergerak?)', ['Very slowly', 'Very fast', 'By jumping'], 0, '"It moves very, very slowly."'],
      ['What does it do when it is scared? (Apa yang dilakukannya saat takut?)', ['It goes into its shell', 'It flies away', 'It bites'], 0, '"it goes into its shell"'],
    ],
  },
  {
    slug: 'a3-fireflies-at-night', theme: 'Small Animals', emoji: '✨', title: 'Fireflies at Night', titleId: 'Kunang-kunang di Malam Hari', minutes: 3,
    sentences: [
      ['Rafi visits Grandma\'s village.', 'Rafi mengunjungi desa Nenek.'],
      ['At night, it is very dark outside.', 'Pada malam hari, di luar sangat gelap.'],
      ['Suddenly, he sees little lights in the air.', 'Tiba-tiba, dia melihat cahaya kecil di udara.'],
      ['"What are those?" he asks.', '"Itu apa?" tanyanya.'],
      ['"They are fireflies," says Grandma.', '"Itu kunang-kunang," kata Nenek.', true],
      ['Fireflies make light with their bodies.', 'Kunang-kunang membuat cahaya dengan tubuhnya.'],
      ['They look like tiny stars!', 'Mereka terlihat seperti bintang kecil!'],
    ],
    vocab: [
      ['village', 'desa', '🏘️', 'noun', ['villages'], 'Grandma\'s village'],
      ['lights', 'cahaya', '💡', 'noun', ['light'], 'little lights'],
      ['those', 'itu (jamak)', '👉', 'pronoun', [], 'What are those?'],
      ['fireflies', 'kunang-kunang', '✨', 'noun', ['firefly'], 'They are fireflies.'],
      ['bodies', 'tubuh', '🫀', 'noun', ['body'], 'with their bodies'],
    ],
    grammar: [P.whatIs],
    quiz: [
      ['Where is Rafi? (Di mana Rafi?)', ['In Grandma\'s village', 'At school', 'In the city'], 0, '"Rafi visits Grandma\'s village."'],
      ['What are the little lights? (Apa cahaya kecil itu?)', ['Fireflies', 'Stars', 'Lamps'], 0, '"They are fireflies."'],
      ['What do they look like? (Mereka terlihat seperti apa?)', ['Tiny stars', 'Big moons', 'Birds'], 0, '"They look like tiny stars!"'],
    ],
  },
];
