// Daily English Reading Fase A — tahun pertama, bagian 1 (minggu 1–7).
// Tokoh tetap: Rafi (8 tahun, kelas 2), adiknya Aisyah, kucing Milo, teman Dina & Budi, guru Mrs. Sari.

import { P } from './english-phase-a-patterns';
import type { SeedReading } from './types';

export const englishPhaseAYear1: SeedReading[] = [
  // ── Minggu 1: Salam & Perkenalan ─────────────────────────────────────────
  {
    slug: 'a1-hello-i-am-rafi', theme: 'About Me', emoji: '👋', title: 'Hello, I Am Rafi', titleId: 'Halo, Aku Rafi', minutes: 3,
    sentences: [
      ['Hello!', 'Halo!'],
      ['My name is Rafi.', 'Namaku Rafi.'],
      ['I am eight years old.', 'Aku berumur delapan tahun.'],
      ['I am a student.', 'Aku seorang murid.'],
      ['I live in Bandung.', 'Aku tinggal di Bandung.', true],
      ['I have a cat.', 'Aku punya seekor kucing.'],
      ['Its name is Milo.', 'Namanya Milo.'],
      ['Nice to meet you!', 'Senang bertemu denganmu!'],
    ],
    vocab: [
      ['hello', 'halo', '👋', 'interjection', [], 'Hello! My name is Rafi.'],
      ['name', 'nama', '🏷️', 'noun', ['names'], 'My name is Rafi.'],
      ['old', 'tua / berumur', '🎂', 'adjective', [], 'I am eight years old.'],
      ['student', 'murid', '🧑‍🎓', 'noun', ['students'], 'I am a student.'],
      ['live', 'tinggal', '🏠', 'verb', ['lives'], 'I live in Bandung.'],
    ],
    grammar: [P.myNameIs],
    quiz: [
      ['How old is Rafi? (Berapa umur Rafi?)', ['Seven', 'Eight', 'Nine'], 1, '"I am eight years old." Eight = delapan.'],
      ['Where does Rafi live? (Rafi tinggal di mana?)', ['Jakarta', 'Bandung', 'Bali'], 1, '"I live in Bandung."'],
      ['"Student" artinya …', ['Guru', 'Murid', 'Dokter'], 1, 'Student = murid. I am a student = aku seorang murid.'],
    ],
  },
  {
    slug: 'a1-good-morning', theme: 'Greetings', emoji: '🌅', title: 'Good Morning!', titleId: 'Selamat Pagi!', minutes: 3,
    sentences: [
      ['It is morning.', 'Hari sudah pagi.'],
      ['Rafi wakes up.', 'Rafi bangun.'],
      ['"Good morning, Mom!" he says.', '"Selamat pagi, Bu!" katanya.'],
      ['"Good morning, Rafi!" Mom says.', '"Selamat pagi, Rafi!" kata Ibu.'],
      ['At night, Rafi is sleepy.', 'Pada malam hari, Rafi mengantuk.', true],
      ['"Good night, Dad!" he says.', '"Selamat tidur, Yah!" katanya.'],
      ['"Good night, Rafi. Sleep well!" Dad says.', '"Selamat tidur, Rafi. Tidur yang nyenyak!" kata Ayah.'],
    ],
    vocab: [
      ['morning', 'pagi', '🌅', 'noun', [], 'Good morning, Mom!'],
      ['night', 'malam', '🌙', 'noun', [], 'Good night, Dad!'],
      ['wakes up', 'bangun tidur', '⏰', 'verb', ['wake up'], 'Rafi wakes up.'],
      ['says', 'berkata', '💬', 'verb', ['say'], '"Good morning, Rafi!" Mom says.'],
      ['sleepy', 'mengantuk', '😪', 'adjective', [], 'At night, Rafi is sleepy.'],
    ],
    grammar: [P.greetings],
    quiz: [
      ['What does Rafi say in the morning? (Apa yang Rafi ucapkan pada pagi hari?)', ['Good night', 'Good morning', 'Goodbye'], 1, 'Pagi hari kita mengucapkan "Good morning".'],
      ['When is Rafi sleepy? (Kapan Rafi mengantuk?)', ['In the morning', 'At night', 'At school'], 1, '"At night, Rafi is sleepy."'],
      ['"Good night" diucapkan saat …', ['Bangun tidur', 'Mau tidur', 'Makan siang'], 1, 'Good night diucapkan saat mau tidur atau berpisah di malam hari.'],
    ],
  },
  {
    slug: 'a1-how-are-you', theme: 'Greetings', emoji: '🙂', title: 'How Are You?', titleId: 'Apa Kabar?', minutes: 3,
    sentences: [
      ['Dina sees Rafi at school.', 'Dina melihat Rafi di sekolah.'],
      ['"Hi, Rafi! How are you?"', '"Hai, Rafi! Apa kabar?"'],
      ['"I am fine, thank you. And you?"', '"Aku baik, terima kasih. Kamu?"'],
      ['"I am fine too!"', '"Aku juga baik!"'],
      ['Then Dina sees Budi.', 'Lalu Dina melihat Budi.', true],
      ['"Hi, Budi! How are you?"', '"Hai, Budi! Apa kabar?"'],
      ['"I am not well. I am sick."', '"Aku kurang sehat. Aku sakit."'],
      ['"Oh no! Get well soon, Budi!"', '"Oh tidak! Semoga cepat sembuh, Budi!"'],
    ],
    vocab: [
      ['fine', 'baik-baik saja', '👍', 'adjective', [], 'I am fine, thank you.'],
      ['too', 'juga', '➕', 'adverb', [], 'I am fine too!'],
      ['sick', 'sakit', '🤒', 'adjective', [], 'I am sick.'],
      ['well', 'sehat / baik', '💪', 'adjective', [], 'I am not well.'],
      ['soon', 'segera', '⏩', 'adverb', [], 'Get well soon!'],
    ],
    grammar: [P.howAreYou],
    quiz: [
      ['How is Rafi? (Bagaimana kabar Rafi?)', ['Sick', 'Fine', 'Sad'], 1, '"I am fine, thank you."'],
      ['Who is sick? (Siapa yang sakit?)', ['Dina', 'Rafi', 'Budi'], 2, 'Budi berkata "I am sick."'],
      ['"Get well soon" artinya …', ['Selamat pagi', 'Semoga cepat sembuh', 'Sampai jumpa'], 1, 'Get well soon = semoga cepat sembuh.'],
    ],
  },
  {
    slug: 'a1-my-friend-dina', theme: 'Friends', emoji: '👧', title: 'My Friend Dina', titleId: 'Temanku Dina', minutes: 3,
    sentences: [
      ['This is my friend.', 'Ini temanku.'],
      ['Her name is Dina.', 'Namanya Dina.'],
      ['She is eight years old too.', 'Dia juga berumur delapan tahun.'],
      ['She has long black hair.', 'Rambutnya panjang dan hitam.'],
      ['Dina likes to draw.', 'Dina suka menggambar.', true],
      ['We sit together in class.', 'Kami duduk bersama di kelas.'],
      ['Dina is kind and funny.', 'Dina baik hati dan lucu.'],
    ],
    vocab: [
      ['friend', 'teman', '🤝', 'noun', ['friends'], 'This is my friend.'],
      ['hair', 'rambut', '💇', 'noun', [], 'She has long black hair.'],
      ['draw', 'menggambar', '🖍️', 'verb', ['draws', 'drawing'], 'Dina likes to draw.'],
      ['together', 'bersama-sama', '👫', 'adverb', [], 'We sit together in class.'],
      ['funny', 'lucu', '😄', 'adjective', [], 'Dina is kind and funny.'],
    ],
    grammar: [P.heShe],
    quiz: [
      ['What does Dina like? (Dina suka apa?)', ['To sing', 'To draw', 'To swim'], 1, '"Dina likes to draw."'],
      ['What color is Dina\'s hair? (Apa warna rambut Dina?)', ['Black', 'Brown', 'Red'], 0, '"She has long black hair."'],
      ['Untuk Dina (perempuan), kita memakai …', ['He', 'She', 'It'], 1, 'Perempuan memakai She; namanya: Her name.'],
    ],
  },
  {
    slug: 'a1-thank-you-and-sorry', theme: 'Good Manners', emoji: '🙏', title: 'Thank You and Sorry', titleId: 'Terima Kasih dan Maaf', minutes: 3,
    sentences: [
      ['Mom gives Rafi a glass of water.', 'Ibu memberi Rafi segelas air.'],
      ['"Thank you, Mom," says Rafi.', '"Terima kasih, Bu," kata Rafi.'],
      ['"You are welcome," says Mom.', '"Sama-sama," kata Ibu.'],
      ['Oops! Rafi drops Aisyah\'s doll.', 'Ups! Rafi menjatuhkan boneka Aisyah.', true],
      ['"I am sorry, Aisyah," he says.', '"Maaf, Aisyah," katanya.'],
      ['"That is okay," says Aisyah.', '"Tidak apa-apa," kata Aisyah.'],
      ['Kind words make everyone happy.', 'Kata-kata yang baik membuat semua orang senang.'],
    ],
    vocab: [
      ['gives', 'memberi', '🎁', 'verb', ['give'], 'Mom gives Rafi a glass of water.'],
      ['glass', 'gelas', '🥛', 'noun', ['glasses'], 'a glass of water'],
      ['drops', 'menjatuhkan', '⬇️', 'verb', ['drop'], 'Rafi drops Aisyah\'s doll.'],
      ['doll', 'boneka', '🪆', 'noun', ['dolls'], 'Aisyah\'s doll'],
      ['sorry', 'maaf', '🙇', 'adjective', [], 'I am sorry, Aisyah.'],
    ],
    grammar: [P.politeWords],
    quiz: [
      ['What does Mom give Rafi? (Ibu memberi Rafi apa?)', ['Milk', 'Water', 'Juice'], 1, '"Mom gives Rafi a glass of water."'],
      ['What does Rafi drop? (Apa yang dijatuhkan Rafi?)', ['A doll', 'A ball', 'A book'], 0, '"Rafi drops Aisyah\'s doll."'],
      ['Jawaban yang sopan untuk "Thank you" adalah …', ['I am sorry', 'You are welcome', 'Good night'], 1, 'You are welcome = sama-sama.'],
    ],
  },
  {
    slug: 'a1-a-new-student', theme: 'School', emoji: '🏫', title: 'A New Student', titleId: 'Murid Baru', minutes: 3,
    sentences: [
      ['There is a new student in our class.', 'Ada murid baru di kelas kami.'],
      ['She stands in front of the class.', 'Dia berdiri di depan kelas.'],
      ['"Hello, everyone. My name is Tari."', '"Halo, semuanya. Namaku Tari."'],
      ['"I am from Medan."', '"Aku dari Medan."'],
      ['"I like singing."', '"Aku suka bernyanyi."'],
      ['"Welcome, Tari!" we say.', '"Selamat datang, Tari!" kata kami.', true],
      ['Tari smiles. She is happy.', 'Tari tersenyum. Dia senang.'],
    ],
    vocab: [
      ['new', 'baru', '✨', 'adjective', [], 'There is a new student.'],
      ['class', 'kelas', '🏫', 'noun', ['classes'], 'in our class'],
      ['everyone', 'semua orang', '👨‍👩‍👧‍👦', 'pronoun', [], 'Hello, everyone.'],
      ['singing', 'bernyanyi', '🎤', 'verb', ['sing', 'sings'], 'I like singing.'],
      ['welcome', 'selamat datang', '🤗', 'interjection', [], 'Welcome, Tari!'],
    ],
    grammar: [P.myNameIs],
    quiz: [
      ['What is the new student\'s name? (Siapa nama murid baru?)', ['Dina', 'Tari', 'Aisyah'], 1, '"My name is Tari."'],
      ['Where is Tari from? (Tari berasal dari mana?)', ['Medan', 'Bandung', 'Surabaya'], 0, '"I am from Medan."'],
      ['What does Tari like? (Tari suka apa?)', ['Drawing', 'Singing', 'Running'], 1, '"I like singing."'],
    ],
  },
  {
    slug: 'a1-goodbye-see-you-tomorrow', theme: 'Greetings', emoji: '👋', title: 'See You Tomorrow!', titleId: 'Sampai Jumpa Besok!', minutes: 3,
    sentences: [
      ['School is over.', 'Sekolah sudah selesai.'],
      ['"Goodbye, Mrs. Sari!" say the children.', '"Selamat tinggal, Bu Sari!" kata anak-anak.'],
      ['"Goodbye, children. See you tomorrow!"', '"Selamat tinggal, anak-anak. Sampai jumpa besok!"'],
      ['Rafi waves to Dina.', 'Rafi melambai kepada Dina.'],
      ['Dad is at the school gate.', 'Ayah ada di gerbang sekolah.', true],
      ['"Hi, Dad!" Rafi says.', '"Hai, Yah!" kata Rafi.'],
      ['They go home together.', 'Mereka pulang bersama.'],
    ],
    vocab: [
      ['over', 'selesai', '🏁', 'adjective', [], 'School is over.'],
      ['goodbye', 'selamat tinggal', '👋', 'interjection', [], 'Goodbye, Mrs. Sari!'],
      ['tomorrow', 'besok', '📅', 'noun', [], 'See you tomorrow!'],
      ['waves', 'melambai', '🙋', 'verb', ['wave'], 'Rafi waves to Dina.'],
      ['gate', 'gerbang', '🚪', 'noun', ['gates'], 'at the school gate'],
    ],
    grammar: [P.greetings],
    quiz: [
      ['Who is at the school gate? (Siapa yang ada di gerbang sekolah?)', ['Mom', 'Dad', 'Grandma'], 1, '"Dad is at the school gate."'],
      ['"See you tomorrow" artinya …', ['Sampai jumpa besok', 'Selamat pagi', 'Terima kasih'], 0, 'Tomorrow = besok.'],
      ['Who does Rafi wave to? (Rafi melambai kepada siapa?)', ['Budi', 'Dina', 'Mrs. Sari'], 1, '"Rafi waves to Dina."'],
    ],
  },

  // ── Minggu 2: Tubuhku ────────────────────────────────────────────────────
  {
    slug: 'a1-my-face', theme: 'Body', emoji: '😊', title: 'My Face', titleId: 'Wajahku', minutes: 3,
    sentences: [
      ['This is my face.', 'Ini wajahku.'],
      ['I have two eyes.', 'Aku punya dua mata.'],
      ['I have one nose and one mouth.', 'Aku punya satu hidung dan satu mulut.'],
      ['I have two ears.', 'Aku punya dua telinga.'],
      ['I see with my eyes.', 'Aku melihat dengan mataku.', true],
      ['I smell with my nose.', 'Aku mencium bau dengan hidungku.'],
      ['I eat and talk with my mouth.', 'Aku makan dan berbicara dengan mulutku.'],
    ],
    vocab: [
      ['face', 'wajah', '😊', 'noun', ['faces'], 'This is my face.'],
      ['eyes', 'mata', '👀', 'noun', ['eye'], 'I have two eyes.'],
      ['nose', 'hidung', '👃', 'noun', ['noses'], 'one nose'],
      ['mouth', 'mulut', '👄', 'noun', [], 'one mouth'],
      ['ears', 'telinga', '👂', 'noun', ['ear'], 'I have two ears.'],
    ],
    grammar: [P.iHave],
    quiz: [
      ['How many eyes do I have? (Berapa jumlah mataku?)', ['One', 'Two', 'Three'], 1, '"I have two eyes."'],
      ['I smell with my … (Aku mencium bau dengan …)', ['Eyes', 'Mouth', 'Nose'], 2, '"I smell with my nose."'],
      ['"Ears" artinya …', ['Mata', 'Telinga', 'Mulut'], 1, 'Ears = telinga.'],
    ],
  },
  {
    slug: 'a1-hands-and-feet', theme: 'Body', emoji: '🙌', title: 'Hands and Feet', titleId: 'Tangan dan Kaki', minutes: 3,
    sentences: [
      ['I have two hands.', 'Aku punya dua tangan.'],
      ['I have ten fingers.', 'Aku punya sepuluh jari tangan.'],
      ['I clap my hands. Clap, clap!', 'Aku bertepuk tangan. Prok, prok!'],
      ['I have two feet.', 'Aku punya dua kaki.', true],
      ['I have ten toes.', 'Aku punya sepuluh jari kaki.'],
      ['I jump with my feet. Jump, jump!', 'Aku melompat dengan kakiku. Lompat, lompat!'],
    ],
    vocab: [
      ['hands', 'tangan', '🙌', 'noun', ['hand'], 'I have two hands.'],
      ['fingers', 'jari tangan', '🖐️', 'noun', ['finger'], 'I have ten fingers.'],
      ['clap', 'bertepuk tangan', '👏', 'verb', ['claps'], 'I clap my hands.'],
      ['feet', 'kaki (telapak)', '🦶', 'noun', ['foot'], 'I have two feet.'],
      ['toes', 'jari kaki', '🦶', 'noun', ['toe'], 'I have ten toes.'],
      ['jump', 'melompat', '🤸', 'verb', ['jumps'], 'I jump with my feet.'],
    ],
    grammar: [P.plural],
    quiz: [
      ['How many fingers do I have? (Berapa jumlah jari tanganku?)', ['Five', 'Ten', 'Twenty'], 1, '"I have ten fingers."'],
      ['I jump with my … (Aku melompat dengan …)', ['Hands', 'Feet', 'Ears'], 1, '"I jump with my feet."'],
      ['Bentuk banyak dari "foot" adalah …', ['Foots', 'Feet', 'Feets'], 1, 'One foot → two feet.'],
    ],
  },
  {
    slug: 'a1-wash-your-hands', theme: 'Health', emoji: '🧼', title: 'Wash Your Hands', titleId: 'Cuci Tanganmu', minutes: 3,
    sentences: [
      ['It is time to eat.', 'Sudah waktunya makan.'],
      ['First, I wash my hands.', 'Pertama, aku mencuci tanganku.'],
      ['I use water and soap.', 'Aku memakai air dan sabun.'],
      ['I rub my hands and count to twenty.', 'Aku menggosok tangan dan menghitung sampai dua puluh.'],
      ['Then I dry my hands with a towel.', 'Lalu aku mengeringkan tangan dengan handuk.', true],
      ['Now my hands are clean.', 'Sekarang tanganku bersih.'],
      ['Bye-bye, germs!', 'Dadah, kuman!'],
    ],
    vocab: [
      ['wash', 'mencuci', '🧼', 'verb', ['washes'], 'I wash my hands.'],
      ['soap', 'sabun', '🧴', 'noun', [], 'water and soap'],
      ['rub', 'menggosok', '🤲', 'verb', ['rubs'], 'I rub my hands.'],
      ['towel', 'handuk', '🧻', 'noun', ['towels'], 'with a towel'],
      ['clean', 'bersih', '✨', 'adjective', [], 'My hands are clean.'],
      ['germs', 'kuman', '🦠', 'noun', ['germ'], 'Bye-bye, germs!'],
    ],
    grammar: [P.commands],
    quiz: [
      ['What do I use to wash my hands? (Aku memakai apa untuk mencuci tangan?)', ['Water and soap', 'Milk', 'Sand'], 0, '"I use water and soap."'],
      ['I count to … (Aku menghitung sampai …)', ['Ten', 'Twenty', 'Fifty'], 1, '"count to twenty"'],
      ['"Towel" artinya …', ['Sabun', 'Handuk', 'Sikat'], 1, 'Towel = handuk.'],
    ],
  },
  {
    slug: 'a1-brush-your-teeth', theme: 'Health', emoji: '🪥', title: 'Brush Your Teeth', titleId: 'Sikat Gigimu', minutes: 3,
    sentences: [
      ['I brush my teeth two times a day.', 'Aku menyikat gigi dua kali sehari.'],
      ['I brush them in the morning.', 'Aku menyikatnya pada pagi hari.'],
      ['I brush them before bed.', 'Aku menyikatnya sebelum tidur.'],
      ['I use a toothbrush and toothpaste.', 'Aku memakai sikat gigi dan pasta gigi.', true],
      ['Up and down, round and round.', 'Naik dan turun, berputar-putar.'],
      ['My teeth are white and strong.', 'Gigiku putih dan kuat.'],
      ['Now I can smile!', 'Sekarang aku bisa tersenyum!'],
    ],
    vocab: [
      ['brush', 'menyikat', '🪥', 'verb', ['brushes'], 'I brush my teeth.'],
      ['teeth', 'gigi (banyak)', '🦷', 'noun', ['tooth'], 'My teeth are white.'],
      ['toothpaste', 'pasta gigi', '🧴', 'noun', [], 'a toothbrush and toothpaste'],
      ['strong', 'kuat', '💪', 'adjective', [], 'white and strong'],
      ['smile', 'tersenyum', '😁', 'verb', ['smiles'], 'Now I can smile!'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['How many times a day do I brush my teeth? (Berapa kali sehari aku menyikat gigi?)', ['One', 'Two', 'Five'], 1, '"two times a day"'],
      ['When do I brush my teeth? (Kapan aku menyikat gigi?)', ['Morning and before bed', 'Only at lunch', 'Never'], 0, 'Pagi hari dan sebelum tidur.'],
      ['"Teeth" adalah bentuk banyak dari …', ['Tooth', 'Toothes', 'Teeths'], 0, 'One tooth → many teeth.'],
    ],
  },
  {
    slug: 'a1-five-senses', theme: 'Body', emoji: '👀', title: 'My Five Senses', titleId: 'Lima Indraku', minutes: 3,
    sentences: [
      ['I can see a rainbow with my eyes.', 'Aku bisa melihat pelangi dengan mataku.'],
      ['I can hear birds with my ears.', 'Aku bisa mendengar burung dengan telingaku.'],
      ['I can smell flowers with my nose.', 'Aku bisa mencium bunga dengan hidungku.'],
      ['I can taste a sweet mango with my tongue.', 'Aku bisa merasakan mangga manis dengan lidahku.'],
      ['I can touch my soft cat with my hands.', 'Aku bisa menyentuh kucingku yang lembut dengan tanganku.'],
      ['These are my five senses!', 'Inilah kelima indraku!', true],
    ],
    vocab: [
      ['see', 'melihat', '👀', 'verb', ['sees'], 'I can see a rainbow.'],
      ['hear', 'mendengar', '👂', 'verb', ['hears'], 'I can hear birds.'],
      ['smell', 'mencium bau', '👃', 'verb', ['smells'], 'I can smell flowers.'],
      ['taste', 'mengecap / merasakan', '👅', 'verb', ['tastes'], 'I can taste a sweet mango.'],
      ['touch', 'menyentuh', '✋', 'verb', ['touches'], 'I can touch my soft cat.'],
      ['tongue', 'lidah', '👅', 'noun', [], 'with my tongue'],
    ],
    grammar: [P.iCan],
    quiz: [
      ['I hear with my … (Aku mendengar dengan …)', ['Ears', 'Eyes', 'Nose'], 0, '"I can hear birds with my ears."'],
      ['What can I taste? (Apa yang bisa kurasakan?)', ['A rainbow', 'A sweet mango', 'A bird'], 1, '"I can taste a sweet mango."'],
      ['How many senses do we have? (Berapa jumlah indra kita?)', ['Three', 'Four', 'Five'], 2, '"These are my five senses!"'],
    ],
  },
  {
    slug: 'a1-head-shoulders-knees-and-toes', theme: 'Body', emoji: '🕺', title: 'Head, Shoulders, Knees and Toes', titleId: 'Kepala, Bahu, Lutut, Kaki', minutes: 3,
    sentences: [
      ['Let us play a game!', 'Ayo bermain!'],
      ['Touch your head.', 'Sentuh kepalamu.'],
      ['Touch your shoulders.', 'Sentuh bahumu.'],
      ['Touch your knees.', 'Sentuh lututmu.'],
      ['Touch your toes.', 'Sentuh jari kakimu.'],
      ['Now do it fast!', 'Sekarang lakukan dengan cepat!', true],
      ['Head, shoulders, knees and toes!', 'Kepala, bahu, lutut, dan jari kaki!'],
      ['We laugh and play.', 'Kami tertawa dan bermain.'],
    ],
    vocab: [
      ['head', 'kepala', '🙆', 'noun', [], 'Touch your head.'],
      ['shoulders', 'bahu', '🤷', 'noun', ['shoulder'], 'Touch your shoulders.'],
      ['knees', 'lutut', '🦵', 'noun', ['knee'], 'Touch your knees.'],
      ['fast', 'cepat', '⚡', 'adverb', [], 'Now do it fast!'],
      ['laugh', 'tertawa', '😂', 'verb', ['laughs'], 'We laugh and play.'],
    ],
    grammar: [P.commands],
    quiz: [
      ['"Touch your knees" artinya …', ['Sentuh kepalamu', 'Sentuh lututmu', 'Sentuh bahumu'], 1, 'Knees = lutut.'],
      ['What do we play? (Kita memainkan apa?)', ['A game', 'Football', 'A song on the piano'], 0, '"Let us play a game!"'],
      ['Kalimat perintah dimulai dengan …', ['Kata kerja', 'Nama orang', 'Angka'], 0, 'Contoh: Touch your head.'],
    ],
  },
  {
    slug: 'a1-i-am-growing', theme: 'Health', emoji: '📏', title: 'I Am Growing', titleId: 'Aku Tumbuh Besar', minutes: 3,
    sentences: [
      ['Mom measures me on the wall.', 'Ibu mengukur tinggiku di dinding.'],
      ['"You are taller now!" she says.', '"Kamu sekarang lebih tinggi!" katanya.'],
      ['I eat rice, fish, and vegetables.', 'Aku makan nasi, ikan, dan sayur.'],
      ['I drink milk every day.', 'Aku minum susu setiap hari.'],
      ['I play outside and sleep early.', 'Aku bermain di luar dan tidur lebih awal.', true],
      ['My body is strong and healthy.', 'Tubuhku kuat dan sehat.'],
      ['I am growing every day!', 'Aku tumbuh setiap hari!'],
    ],
    vocab: [
      ['measures', 'mengukur', '📏', 'verb', ['measure'], 'Mom measures me.'],
      ['taller', 'lebih tinggi', '📈', 'adjective', ['tall'], 'You are taller now!'],
      ['vegetables', 'sayuran', '🥦', 'noun', ['vegetable'], 'rice, fish, and vegetables'],
      ['early', 'lebih awal / cepat', '🕗', 'adverb', [], 'I sleep early.'],
      ['healthy', 'sehat', '💚', 'adjective', [], 'strong and healthy'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What does Rafi drink every day? (Apa yang Rafi minum setiap hari?)', ['Milk', 'Soda', 'Coffee'], 0, '"I drink milk every day."'],
      ['What does Mom say? (Apa kata Ibu?)', ['You are taller now!', 'You are sleepy!', 'You are late!'], 0, '"You are taller now!"'],
      ['"Healthy" artinya …', ['Sakit', 'Sehat', 'Lapar'], 1, 'Healthy = sehat.'],
    ],
  },

  // ── Minggu 3: Kelasku ────────────────────────────────────────────────────
  {
    slug: 'a1-in-my-school-bag', theme: 'School', emoji: '🎒', title: 'In My School Bag', titleId: 'Di Dalam Tas Sekolahku', minutes: 3,
    sentences: [
      ['This is my school bag.', 'Ini tas sekolahku.'],
      ['It is blue.', 'Warnanya biru.'],
      ['In my bag, there is a book.', 'Di dalam tasku ada sebuah buku.'],
      ['There is a pencil and an eraser.', 'Ada sebuah pensil dan sebuah penghapus.'],
      ['There is a ruler too.', 'Ada juga sebuah penggaris.'],
      ['There is a lunch box and a water bottle.', 'Ada kotak bekal dan botol minum.', true],
      ['My bag is heavy!', 'Tasku berat!'],
    ],
    vocab: [
      ['bag', 'tas', '🎒', 'noun', ['bags'], 'This is my school bag.'],
      ['pencil', 'pensil', '✏️', 'noun', ['pencils'], 'There is a pencil.'],
      ['eraser', 'penghapus', '🧽', 'noun', ['erasers'], 'an eraser'],
      ['ruler', 'penggaris', '📏', 'noun', ['rulers'], 'a ruler'],
      ['bottle', 'botol', '🍼', 'noun', ['bottles'], 'a water bottle'],
      ['heavy', 'berat', '🏋️', 'adjective', [], 'My bag is heavy!'],
    ],
    grammar: [P.thereIsAre],
    quiz: [
      ['What color is the bag? (Apa warna tasnya?)', ['Red', 'Blue', 'Green'], 1, '"It is blue."'],
      ['"Eraser" artinya …', ['Penggaris', 'Penghapus', 'Pensil'], 1, 'Eraser = penghapus.'],
      ['How is the bag? (Bagaimana tasnya?)', ['Heavy', 'Small', 'Wet'], 0, '"My bag is heavy!"'],
    ],
  },
  {
    slug: 'a1-my-classroom', theme: 'School', emoji: '🏫', title: 'My Classroom', titleId: 'Ruang Kelasku', minutes: 3,
    sentences: [
      ['This is my classroom.', 'Ini ruang kelasku.'],
      ['There is a big whiteboard.', 'Ada papan tulis putih yang besar.'],
      ['There are twenty desks and twenty chairs.', 'Ada dua puluh meja dan dua puluh kursi.'],
      ['There is a clock on the wall.', 'Ada jam di dinding.'],
      ['There are many pictures too.', 'Ada banyak gambar juga.', true],
      ['We keep our classroom clean.', 'Kami menjaga kelas kami tetap bersih.'],
      ['I love my classroom!', 'Aku sayang kelasku!'],
    ],
    vocab: [
      ['classroom', 'ruang kelas', '🏫', 'noun', ['classrooms'], 'This is my classroom.'],
      ['whiteboard', 'papan tulis putih', '⬜', 'noun', [], 'a big whiteboard'],
      ['desks', 'meja (belajar)', '🪑', 'noun', ['desk'], 'twenty desks'],
      ['chairs', 'kursi', '🪑', 'noun', ['chair'], 'twenty chairs'],
      ['wall', 'dinding', '🧱', 'noun', ['walls'], 'on the wall'],
      ['pictures', 'gambar', '🖼️', 'noun', ['picture'], 'many pictures'],
    ],
    grammar: [P.thereIsAre],
    quiz: [
      ['How many desks are there? (Ada berapa meja?)', ['Ten', 'Twelve', 'Twenty'], 2, '"There are twenty desks."'],
      ['Where is the clock? (Di mana jamnya?)', ['On the wall', 'On the desk', 'Under the chair'], 0, '"There is a clock on the wall."'],
      ['Untuk banyak benda kita memakai …', ['There is', 'There are', 'It is'], 1, 'There are + banyak benda.'],
    ],
  },
  {
    slug: 'a1-my-teacher-mrs-sari', theme: 'School', emoji: '👩‍🏫', title: 'My Teacher, Mrs. Sari', titleId: 'Guruku, Bu Sari', minutes: 3,
    sentences: [
      ['This is Mrs. Sari.', 'Ini Bu Sari.'],
      ['She is my teacher.', 'Dia guruku.'],
      ['She teaches English.', 'Dia mengajar bahasa Inggris.'],
      ['She wears glasses.', 'Dia memakai kacamata.'],
      ['Every Friday, she reads us a story.', 'Setiap hari Jumat, dia membacakan cerita untuk kami.', true],
      ['She is kind and funny.', 'Dia baik hati dan lucu.'],
      ['We like Mrs. Sari very much.', 'Kami sangat menyukai Bu Sari.'],
    ],
    vocab: [
      ['teacher', 'guru', '👩‍🏫', 'noun', ['teachers'], 'She is my teacher.'],
      ['teaches', 'mengajar', '📚', 'verb', ['teach'], 'She teaches English.'],
      ['wears', 'memakai', '👓', 'verb', ['wear'], 'She wears glasses.'],
      ['glasses', 'kacamata', '👓', 'noun', [], 'She wears glasses.'],
      ['story', 'cerita', '📖', 'noun', ['stories'], 'she reads us a story'],
    ],
    grammar: [P.heShe],
    quiz: [
      ['What does Mrs. Sari teach? (Bu Sari mengajar apa?)', ['Math', 'English', 'Music'], 1, '"She teaches English."'],
      ['When does she read a story? (Kapan dia membacakan cerita?)', ['Every Monday', 'Every Friday', 'Every Sunday'], 1, '"Every Friday, she reads us a story."'],
      ['"She wears glasses" artinya dia memakai …', ['Topi', 'Kacamata', 'Sepatu'], 1, 'Glasses = kacamata.'],
    ],
  },
  {
    slug: 'a1-can-i-borrow-your-pencil', theme: 'School', emoji: '✏️', title: 'Can I Borrow Your Pencil?', titleId: 'Boleh Aku Pinjam Pensilmu?', minutes: 3,
    sentences: [
      ['Oh no! My pencil is broken.', 'Oh tidak! Pensilku patah.'],
      ['"Dina, can I borrow your pencil, please?"', '"Dina, boleh aku pinjam pensilmu?"'],
      ['"Sure! Here you are," says Dina.', '"Tentu! Ini dia," kata Dina.'],
      ['"Thank you, Dina!"', '"Terima kasih, Dina!"'],
      ['I write my name with Dina\'s pencil.', 'Aku menulis namaku dengan pensil Dina.', true],
      ['After class, I give it back.', 'Setelah pelajaran, aku mengembalikannya.'],
      ['Good friends share.', 'Teman yang baik suka berbagi.'],
    ],
    vocab: [
      ['broken', 'patah / rusak', '💔', 'adjective', [], 'My pencil is broken.'],
      ['borrow', 'meminjam', '🤲', 'verb', ['borrows'], 'Can I borrow your pencil?'],
      ['please', 'tolong / mohon', '🙏', 'adverb', [], 'Can I borrow your pencil, please?'],
      ['write', 'menulis', '✍️', 'verb', ['writes'], 'I write my name.'],
      ['share', 'berbagi', '🤝', 'verb', ['shares'], 'Good friends share.'],
    ],
    grammar: [P.canIQuestion],
    quiz: [
      ['What is broken? (Apa yang patah?)', ['The ruler', 'The pencil', 'The bag'], 1, '"My pencil is broken."'],
      ['Who lends the pencil? (Siapa yang meminjamkan pensil?)', ['Budi', 'Dina', 'Mrs. Sari'], 1, 'Dina berkata "Sure! Here you are."'],
      ['"Borrow" artinya …', ['Meminjam', 'Membeli', 'Membuang'], 0, 'Borrow = meminjam.'],
    ],
  },
  {
    slug: 'a1-art-class', theme: 'Colors', emoji: '🎨', title: 'Art Class', titleId: 'Pelajaran Seni', minutes: 3,
    sentences: [
      ['Today we have art class.', 'Hari ini kami ada pelajaran seni.'],
      ['I paint a picture of my house.', 'Aku melukis gambar rumahku.'],
      ['The sun is yellow.', 'Mataharinya kuning.'],
      ['The sky is blue.', 'Langitnya biru.'],
      ['The grass is green.', 'Rumputnya hijau.'],
      ['The roof is red.', 'Atapnya merah.'],
      ['Mrs. Sari says, "Beautiful!"', 'Bu Sari berkata, "Indah!"', true],
    ],
    vocab: [
      ['art', 'seni', '🎨', 'noun', [], 'art class'],
      ['paint', 'melukis / mengecat', '🖌️', 'verb', ['paints'], 'I paint a picture.'],
      ['sky', 'langit', '🌤️', 'noun', [], 'The sky is blue.'],
      ['grass', 'rumput', '🌱', 'noun', [], 'The grass is green.'],
      ['roof', 'atap', '🏠', 'noun', ['roofs'], 'The roof is red.'],
      ['beautiful', 'indah / cantik', '🌸', 'adjective', [], 'Beautiful!'],
    ],
    grammar: [P.itIs],
    quiz: [
      ['What color is the sky? (Apa warna langitnya?)', ['Blue', 'Yellow', 'Red'], 0, '"The sky is blue."'],
      ['What does Rafi paint? (Rafi melukis apa?)', ['His school', 'His house', 'His cat'], 1, '"I paint a picture of my house."'],
      ['"Roof" artinya …', ['Pintu', 'Atap', 'Jendela'], 1, 'Roof = atap.'],
    ],
  },
  {
    slug: 'a1-recess-time', theme: 'School', emoji: '🔔', title: 'Recess Time', titleId: 'Waktu Istirahat', minutes: 3,
    sentences: [
      ['Ring, ring! The bell rings.', 'Kring, kring! Bel berbunyi.'],
      ['It is recess time.', 'Sekarang waktu istirahat.'],
      ['The children go out of the class.', 'Anak-anak keluar dari kelas.'],
      ['Rafi and Budi eat snacks at the canteen.', 'Rafi dan Budi makan jajan di kantin.'],
      ['Dina and Tari play tag.', 'Dina dan Tari bermain kejar-kejaran.', true],
      ['Ring, ring! The bell rings again.', 'Kring, kring! Bel berbunyi lagi.'],
      ['Everyone goes back to class.', 'Semua kembali ke kelas.'],
    ],
    vocab: [
      ['bell', 'bel / lonceng', '🔔', 'noun', ['bells'], 'The bell rings.'],
      ['recess', 'istirahat (sekolah)', '⏸️', 'noun', [], 'It is recess time.'],
      ['snacks', 'jajanan / camilan', '🍪', 'noun', ['snack'], 'eat snacks'],
      ['canteen', 'kantin', '🏪', 'noun', [], 'at the canteen'],
      ['again', 'lagi', '🔁', 'adverb', [], 'The bell rings again.'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Where do Rafi and Budi eat snacks? (Di mana Rafi dan Budi makan jajan?)', ['At home', 'At the canteen', 'In the library'], 1, '"at the canteen"'],
      ['What do Dina and Tari play? (Dina dan Tari bermain apa?)', ['Tag', 'Football', 'Chess'], 0, '"Dina and Tari play tag."'],
      ['"Recess" artinya …', ['Ujian', 'Istirahat', 'Upacara'], 1, 'Recess = waktu istirahat sekolah.'],
    ],
  },
  {
    slug: 'a1-our-class-rules', theme: 'School', emoji: '📋', title: 'Our Class Rules', titleId: 'Aturan Kelas Kami', minutes: 3,
    sentences: [
      ['These are our class rules.', 'Ini aturan kelas kami.'],
      ['Listen to the teacher.', 'Dengarkan guru.'],
      ['Raise your hand to talk.', 'Angkat tangan untuk berbicara.'],
      ['Be kind to your friends.', 'Bersikaplah baik kepada temanmu.'],
      ['Keep the classroom clean.', 'Jaga kebersihan kelas.'],
      ['Don\'t run in the class.', 'Jangan berlari di dalam kelas.', true],
      ['Good rules make a happy class!', 'Aturan yang baik membuat kelas bahagia!'],
    ],
    vocab: [
      ['rules', 'aturan', '📋', 'noun', ['rule'], 'our class rules'],
      ['listen', 'mendengarkan', '👂', 'verb', ['listens'], 'Listen to the teacher.'],
      ['raise', 'mengangkat', '🙋', 'verb', ['raises'], 'Raise your hand.'],
      ['kind', 'baik hati', '💖', 'adjective', [], 'Be kind to your friends.'],
      ['run', 'berlari', '🏃', 'verb', ['runs'], 'Don\'t run in the class.'],
    ],
    grammar: [P.commands],
    quiz: [
      ['What do we do to talk in class? (Apa yang kita lakukan untuk berbicara di kelas?)', ['Shout', 'Raise our hand', 'Run'], 1, '"Raise your hand to talk."'],
      ['"Don\'t run in the class" artinya …', ['Berlarilah di kelas', 'Jangan berlari di kelas', 'Duduk di kelas'], 1, 'Don\'t = jangan.'],
      ['"Listen" artinya …', ['Mendengarkan', 'Menulis', 'Melompat'], 0, 'Listen = mendengarkan.'],
    ],
  },

  // ── Minggu 4: Angka ──────────────────────────────────────────────────────
  {
    slug: 'a1-five-red-apples', theme: 'Numbers', emoji: '🍎', title: 'Five Red Apples', titleId: 'Lima Apel Merah', minutes: 3,
    sentences: [
      ['Mom has a basket.', 'Ibu punya sebuah keranjang.'],
      ['She puts apples in the basket.', 'Dia memasukkan apel ke keranjang.'],
      ['One apple, two apples, three apples.', 'Satu apel, dua apel, tiga apel.'],
      ['Four apples, five apples.', 'Empat apel, lima apel.'],
      ['"How many apples are there?" asks Mom.', '"Ada berapa apel?" tanya Ibu.', true],
      ['"There are five apples!" says Aisyah.', '"Ada lima apel!" kata Aisyah.'],
      ['"Good job!" says Mom.', '"Hebat!" kata Ibu.'],
    ],
    vocab: [
      ['basket', 'keranjang', '🧺', 'noun', ['baskets'], 'Mom has a basket.'],
      ['apples', 'apel', '🍎', 'noun', ['apple'], 'five apples'],
      ['puts', 'menaruh / memasukkan', '📥', 'verb', ['put'], 'She puts apples in the basket.'],
      ['asks', 'bertanya', '❓', 'verb', ['ask'], 'asks Mom'],
      ['five', 'lima', '5️⃣', 'number', [], 'There are five apples!'],
    ],
    grammar: [P.howMany],
    quiz: [
      ['How many apples are there? (Ada berapa apel?)', ['Three', 'Four', 'Five'], 2, '"There are five apples!"'],
      ['Where does Mom put the apples? (Ibu menaruh apel di mana?)', ['In the basket', 'In the bag', 'On the bed'], 0, '"She puts apples in the basket."'],
      ['"How many" artinya …', ['Berapa banyak', 'Di mana', 'Siapa'], 0, 'How many = berapa banyak.'],
    ],
  },
  {
    slug: 'a1-ten-little-fingers', theme: 'Numbers', emoji: '🖐️', title: 'Ten Little Fingers', titleId: 'Sepuluh Jari Kecil', minutes: 3,
    sentences: [
      ['Aisyah is learning to count.', 'Aisyah sedang belajar berhitung.'],
      ['She counts her fingers.', 'Dia menghitung jari-jarinya.'],
      ['One, two, three, four, five.', 'Satu, dua, tiga, empat, lima.'],
      ['Six, seven, eight, nine, ten.', 'Enam, tujuh, delapan, sembilan, sepuluh.'],
      ['"I have ten fingers!" she says.', '"Aku punya sepuluh jari!" katanya.', true],
      ['Rafi claps. "You are smart, Aisyah!"', 'Rafi bertepuk tangan. "Kamu pintar, Aisyah!"'],
    ],
    vocab: [
      ['learning', 'belajar', '📚', 'verb', ['learn'], 'Aisyah is learning to count.'],
      ['count', 'menghitung', '🔢', 'verb', ['counts'], 'She counts her fingers.'],
      ['seven', 'tujuh', '7️⃣', 'number', [], 'Six, seven, eight'],
      ['ten', 'sepuluh', '🔟', 'number', [], 'I have ten fingers!'],
      ['smart', 'pintar', '🧠', 'adjective', [], 'You are smart, Aisyah!'],
    ],
    grammar: [P.plural],
    quiz: [
      ['What does Aisyah count? (Apa yang Aisyah hitung?)', ['Her toes', 'Her fingers', 'Her toys'], 1, '"She counts her fingers."'],
      ['After six comes … (Setelah enam adalah …)', ['Five', 'Seven', 'Eight'], 1, 'Six, seven, eight.'],
      ['"Smart" artinya …', ['Pintar', 'Lucu', 'Tinggi'], 0, 'Smart = pintar.'],
    ],
  },
  {
    slug: 'a1-numbers-to-twenty', theme: 'Numbers', emoji: '🔢', title: 'Numbers to Twenty', titleId: 'Angka sampai Dua Puluh', minutes: 4,
    sentences: [
      ['We can count to ten.', 'Kita bisa berhitung sampai sepuluh.'],
      ['Let us count to twenty!', 'Ayo berhitung sampai dua puluh!'],
      ['Eleven, twelve, thirteen, fourteen, fifteen.', 'Sebelas, dua belas, tiga belas, empat belas, lima belas.'],
      ['Sixteen, seventeen, eighteen, nineteen, twenty.', 'Enam belas, tujuh belas, delapan belas, sembilan belas, dua puluh.'],
      ['There are twenty children in my class.', 'Ada dua puluh anak di kelasku.', true],
      ['There are twelve girls and eight boys.', 'Ada dua belas anak perempuan dan delapan anak laki-laki.'],
    ],
    vocab: [
      ['eleven', 'sebelas', '1️⃣1️⃣', 'number', [], 'Eleven, twelve'],
      ['twelve', 'dua belas', '🕛', 'number', [], 'twelve girls'],
      ['fifteen', 'lima belas', '1️⃣5️⃣', 'number', [], 'fourteen, fifteen'],
      ['twenty', 'dua puluh', '2️⃣0️⃣', 'number', [], 'Let us count to twenty!'],
      ['girls', 'anak perempuan', '👧', 'noun', ['girl'], 'twelve girls'],
      ['boys', 'anak laki-laki', '👦', 'noun', ['boy'], 'eight boys'],
    ],
    grammar: [P.howMany],
    quiz: [
      ['How many children are in the class? (Ada berapa anak di kelas?)', ['Twelve', 'Eighteen', 'Twenty'], 2, '"There are twenty children in my class."'],
      ['How many boys are there? (Ada berapa anak laki-laki?)', ['Eight', 'Twelve', 'Ten'], 0, '"twelve girls and eight boys"'],
      ['"Fifteen" adalah angka …', ['13', '15', '50'], 1, 'Fifteen = 15. Fifty = 50.'],
    ],
  },
  {
    slug: 'a1-birds-on-the-tree', theme: 'Numbers', emoji: '🐦', title: 'Birds on the Tree', titleId: 'Burung di Pohon', minutes: 3,
    sentences: [
      ['Look at the tree!', 'Lihat pohon itu!'],
      ['There are three birds on the tree.', 'Ada tiga burung di pohon.'],
      ['Two more birds come.', 'Dua burung lagi datang.'],
      ['Now there are five birds.', 'Sekarang ada lima burung.'],
      ['One bird flies away.', 'Satu burung terbang pergi.', true],
      ['How many birds are there now?', 'Ada berapa burung sekarang?'],
      ['There are four birds. Tweet, tweet!', 'Ada empat burung. Cuit, cuit!'],
    ],
    vocab: [
      ['tree', 'pohon', '🌳', 'noun', ['trees'], 'on the tree'],
      ['birds', 'burung', '🐦', 'noun', ['bird'], 'three birds'],
      ['more', 'lagi / lebih', '➕', 'adjective', [], 'Two more birds come.'],
      ['come', 'datang', '🛬', 'verb', ['comes'], 'Two more birds come.'],
      ['flies', 'terbang', '🕊️', 'verb', ['fly'], 'One bird flies away.'],
    ],
    grammar: [P.howMany],
    quiz: [
      ['How many birds are there at first? (Ada berapa burung pada awalnya?)', ['Two', 'Three', 'Five'], 1, '"There are three birds on the tree."'],
      ['3 + 2 = ? (Tiga ditambah dua?)', ['Four', 'Five', 'Six'], 1, '"Now there are five birds."'],
      ['How many birds are there at the end? (Ada berapa burung di akhir?)', ['Four', 'Five', 'Six'], 0, 'Satu terbang pergi: 5 − 1 = 4.'],
    ],
  },
  {
    slug: 'a1-counting-legs', theme: 'Numbers', emoji: '🕷️', title: 'Counting Legs', titleId: 'Menghitung Kaki', minutes: 3,
    sentences: [
      ['Animals have legs.', 'Hewan punya kaki.'],
      ['A chicken has two legs.', 'Ayam punya dua kaki.'],
      ['A cat has four legs.', 'Kucing punya empat kaki.'],
      ['An ant has six legs.', 'Semut punya enam kaki.'],
      ['A spider has eight legs.', 'Laba-laba punya delapan kaki.'],
      ['A snake has no legs at all!', 'Ular tidak punya kaki sama sekali!', true],
      ['How many legs do you have?', 'Kamu punya berapa kaki?'],
    ],
    vocab: [
      ['legs', 'kaki', '🦵', 'noun', ['leg'], 'Animals have legs.'],
      ['chicken', 'ayam', '🐔', 'noun', ['chickens'], 'A chicken has two legs.'],
      ['ant', 'semut', '🐜', 'noun', ['ants'], 'An ant has six legs.'],
      ['spider', 'laba-laba', '🕷️', 'noun', ['spiders'], 'A spider has eight legs.'],
      ['snake', 'ular', '🐍', 'noun', ['snakes'], 'A snake has no legs.'],
    ],
    grammar: [P.iHave],
    quiz: [
      ['How many legs does a spider have? (Laba-laba punya berapa kaki?)', ['Six', 'Eight', 'Four'], 1, '"A spider has eight legs."'],
      ['Which animal has no legs? (Hewan apa yang tidak punya kaki?)', ['Snake', 'Ant', 'Cat'], 0, '"A snake has no legs at all!"'],
      ['An ant has … legs. (Semut punya … kaki.)', ['Two', 'Four', 'Six'], 2, '"An ant has six legs."'],
    ],
  },
  {
    slug: 'a1-eggs-for-a-cake', theme: 'Numbers', emoji: '🥚', title: 'Eggs for a Cake', titleId: 'Telur untuk Kue', minutes: 3,
    sentences: [
      ['Mom wants to make a cake.', 'Ibu ingin membuat kue.'],
      ['There are twelve eggs in the box.', 'Ada dua belas telur di dalam kotak.'],
      ['Mom takes three eggs.', 'Ibu mengambil tiga telur.'],
      ['Rafi counts the eggs in the box.', 'Rafi menghitung telur di dalam kotak.'],
      ['"There are nine eggs now," he says.', '"Sekarang ada sembilan telur," katanya.', true],
      ['"That is right!" says Mom.', '"Betul!" kata Ibu.'],
      ['Soon the cake is ready. Yummy!', 'Tak lama kuenya siap. Enak!'],
    ],
    vocab: [
      ['cake', 'kue', '🎂', 'noun', ['cakes'], 'make a cake'],
      ['eggs', 'telur', '🥚', 'noun', ['egg'], 'twelve eggs'],
      ['takes', 'mengambil', '🤏', 'verb', ['take'], 'Mom takes three eggs.'],
      ['nine', 'sembilan', '9️⃣', 'number', [], 'There are nine eggs now.'],
      ['ready', 'siap', '✅', 'adjective', [], 'The cake is ready.'],
    ],
    grammar: [P.howMany],
    quiz: [
      ['How many eggs are in the box at first? (Ada berapa telur di kotak pada awalnya?)', ['Nine', 'Ten', 'Twelve'], 2, '"There are twelve eggs in the box."'],
      ['How many eggs does Mom take? (Ibu mengambil berapa telur?)', ['Two', 'Three', 'Four'], 1, '"Mom takes three eggs."'],
      ['12 − 3 = ?', ['Nine', 'Eight', 'Ten'], 0, 'Dua belas dikurangi tiga sama dengan sembilan.'],
    ],
  },
  {
    slug: 'a1-counting-stars', theme: 'Numbers', emoji: '⭐', title: 'Counting Stars', titleId: 'Menghitung Bintang', minutes: 3,
    sentences: [
      ['It is a clear night.', 'Malam ini cerah.'],
      ['Rafi and Dad sit in the yard.', 'Rafi dan Ayah duduk di halaman.'],
      ['They look up at the sky.', 'Mereka memandang ke langit.'],
      ['"Let us count the stars!" says Rafi.', '"Ayo kita hitung bintangnya!" kata Rafi.'],
      ['One, two, three … twenty, thirty …', 'Satu, dua, tiga … dua puluh, tiga puluh …', true],
      ['"There are too many stars!" he laughs.', '"Bintangnya terlalu banyak!" dia tertawa.'],
      ['Dad smiles. "Yes, too many to count."', 'Ayah tersenyum. "Ya, terlalu banyak untuk dihitung."'],
    ],
    vocab: [
      ['clear', 'cerah / bersih', '🌌', 'adjective', [], 'a clear night'],
      ['yard', 'halaman', '🏡', 'noun', ['yards'], 'in the yard'],
      ['look up', 'memandang ke atas', '👆', 'verb', [], 'They look up at the sky.'],
      ['stars', 'bintang', '⭐', 'noun', ['star'], 'count the stars'],
      ['thirty', 'tiga puluh', '3️⃣0️⃣', 'number', [], 'twenty, thirty'],
      ['too many', 'terlalu banyak', '🤯', 'phrase', [], 'There are too many stars!'],
    ],
    grammar: [P.plural],
    quiz: [
      ['Where do Rafi and Dad sit? (Di mana Rafi dan Ayah duduk?)', ['In the yard', 'In the car', 'In the kitchen'], 0, '"Rafi and Dad sit in the yard."'],
      ['What do they count? (Apa yang mereka hitung?)', ['Birds', 'Stars', 'Cars'], 1, '"Let us count the stars!"'],
      ['"Too many" artinya …', ['Terlalu sedikit', 'Terlalu banyak', 'Tidak ada'], 1, 'Too many = terlalu banyak.'],
    ],
  },

  // ── Minggu 5: Buah-buahan ────────────────────────────────────────────────
  {
    slug: 'a1-i-like-bananas', theme: 'Fruit', emoji: '🍌', title: 'I Like Bananas', titleId: 'Aku Suka Pisang', minutes: 3,
    sentences: [
      ['I like bananas.', 'Aku suka pisang.'],
      ['Bananas are long and yellow.', 'Pisang itu panjang dan kuning.'],
      ['They are soft and sweet.', 'Pisang lembut dan manis.'],
      ['I eat a banana for breakfast.', 'Aku makan pisang untuk sarapan.'],
      ['Monkeys like bananas too!', 'Monyet juga suka pisang!', true],
      ['I am not a monkey, but I love bananas.', 'Aku bukan monyet, tapi aku sangat suka pisang.'],
    ],
    vocab: [
      ['bananas', 'pisang', '🍌', 'noun', ['banana'], 'I like bananas.'],
      ['long', 'panjang', '📏', 'adjective', [], 'long and yellow'],
      ['soft', 'lembut', '🧸', 'adjective', [], 'soft and sweet'],
      ['sweet', 'manis', '🍬', 'adjective', [], 'soft and sweet'],
      ['breakfast', 'sarapan', '🍳', 'noun', [], 'for breakfast'],
      ['monkeys', 'monyet', '🐒', 'noun', ['monkey'], 'Monkeys like bananas too!'],
    ],
    grammar: [P.iLike],
    quiz: [
      ['What color are bananas? (Apa warna pisang?)', ['Red', 'Yellow', 'Purple'], 1, '"Bananas are long and yellow."'],
      ['When does Rafi eat a banana? (Kapan Rafi makan pisang?)', ['For breakfast', 'For dinner', 'At midnight'], 0, '"I eat a banana for breakfast."'],
      ['Who likes bananas too? (Siapa yang juga suka pisang?)', ['Cats', 'Monkeys', 'Fish'], 1, '"Monkeys like bananas too!"'],
    ],
  },
  {
    slug: 'a1-mango-season', theme: 'Fruit', emoji: '🥭', title: 'Mango Season', titleId: 'Musim Mangga', minutes: 3,
    sentences: [
      ['There is a mango tree in Grandma\'s yard.', 'Ada pohon mangga di halaman Nenek.'],
      ['Now it is mango season.', 'Sekarang musim mangga.'],
      ['The tree has many mangoes.', 'Pohonnya punya banyak mangga.'],
      ['Some are green. Some are yellow.', 'Sebagian hijau. Sebagian kuning.'],
      ['Yellow mangoes are ripe.', 'Mangga kuning sudah matang.', true],
      ['Grandma cuts a ripe mango for me.', 'Nenek memotong mangga matang untukku.'],
      ['It is sweet and juicy. Delicious!', 'Rasanya manis dan berair. Lezat!'],
    ],
    vocab: [
      ['mangoes', 'mangga', '🥭', 'noun', ['mango'], 'many mangoes'],
      ['season', 'musim', '📆', 'noun', ['seasons'], 'mango season'],
      ['ripe', 'matang', '✅', 'adjective', [], 'Yellow mangoes are ripe.'],
      ['cuts', 'memotong', '🔪', 'verb', ['cut'], 'Grandma cuts a ripe mango.'],
      ['juicy', 'berair / segar', '💧', 'adjective', [], 'sweet and juicy'],
      ['delicious', 'lezat', '😋', 'adjective', [], 'Delicious!'],
    ],
    grammar: [P.itIs],
    quiz: [
      ['Where is the mango tree? (Di mana pohon mangganya?)', ['At school', 'In Grandma\'s yard', 'In the park'], 1, '"in Grandma\'s yard"'],
      ['Which mangoes are ripe? (Mangga mana yang matang?)', ['Green ones', 'Yellow ones', 'Small ones'], 1, '"Yellow mangoes are ripe."'],
      ['"Juicy" artinya …', ['Berair / segar', 'Keras', 'Pahit'], 0, 'Juicy = berair dan segar.'],
    ],
  },
  {
    slug: 'a1-an-apple-a-day', theme: 'Fruit', emoji: '🍏', title: 'An Apple a Day', titleId: 'Sebuah Apel Setiap Hari', minutes: 3,
    sentences: [
      ['This is an apple.', 'Ini sebuah apel.'],
      ['It is round.', 'Bentuknya bulat.'],
      ['Some apples are red. Some apples are green.', 'Ada apel merah. Ada apel hijau.'],
      ['I bite the apple. Crunch!', 'Aku menggigit apel itu. Kres!'],
      ['Apples are good for my body.', 'Apel baik untuk tubuhku.', true],
      ['People say, "An apple a day keeps the doctor away."', 'Orang bilang, "Satu apel sehari menjauhkan dokter."'],
    ],
    vocab: [
      ['round', 'bulat', '⚪', 'adjective', [], 'It is round.'],
      ['bite', 'menggigit', '😬', 'verb', ['bites'], 'I bite the apple.'],
      ['crunch', 'bunyi renyah (kres)', '🍏', 'noun', [], 'Crunch!'],
      ['good for', 'baik untuk', '👍', 'phrase', [], 'good for my body'],
      ['doctor', 'dokter', '🧑‍⚕️', 'noun', ['doctors'], 'keeps the doctor away'],
    ],
    grammar: [P.itIs],
    quiz: [
      ['What shape is an apple? (Apa bentuk apel?)', ['Round', 'Square', 'Long'], 0, '"It is round."'],
      ['What colors are apples? (Apa saja warna apel?)', ['Red and green', 'Blue and pink', 'Black and white'], 0, '"Some apples are red. Some apples are green."'],
      ['Apples are good for … (Apel baik untuk …)', ['my body', 'my car', 'my shoes'], 0, '"Apples are good for my body."'],
    ],
  },
  {
    slug: 'a1-watermelon-party', theme: 'Fruit', emoji: '🍉', title: 'Watermelon Party', titleId: 'Pesta Semangka', minutes: 3,
    sentences: [
      ['It is a hot day.', 'Hari ini panas.'],
      ['Dad buys a big watermelon.', 'Ayah membeli semangka besar.'],
      ['It is green outside.', 'Bagian luarnya hijau.'],
      ['It is red inside, with black seeds.', 'Bagian dalamnya merah, dengan biji hitam.'],
      ['Dad cuts it into many slices.', 'Ayah memotongnya menjadi banyak potongan.', true],
      ['We share it with our neighbors.', 'Kami membaginya dengan tetangga kami.'],
      ['Everyone is happy and cool!', 'Semua orang senang dan segar!'],
    ],
    vocab: [
      ['hot', 'panas', '🥵', 'adjective', [], 'It is a hot day.'],
      ['watermelon', 'semangka', '🍉', 'noun', ['watermelons'], 'a big watermelon'],
      ['outside', 'bagian luar', '⬅️', 'adverb', [], 'green outside'],
      ['inside', 'bagian dalam', '➡️', 'adverb', [], 'red inside'],
      ['seeds', 'biji', '🌱', 'noun', ['seed'], 'black seeds'],
      ['neighbors', 'tetangga', '🏘️', 'noun', ['neighbor'], 'with our neighbors'],
    ],
    grammar: [P.itIs],
    quiz: [
      ['What color is the watermelon inside? (Apa warna bagian dalam semangka?)', ['Green', 'Red', 'Yellow'], 1, '"It is red inside."'],
      ['Who buys the watermelon? (Siapa yang membeli semangka?)', ['Mom', 'Dad', 'Rafi'], 1, '"Dad buys a big watermelon."'],
      ['Who do they share it with? (Dengan siapa mereka berbagi?)', ['Their neighbors', 'Their teacher', 'A monkey'], 0, '"We share it with our neighbors."'],
    ],
  },
  {
    slug: 'a1-the-king-of-fruits', theme: 'Fruit', emoji: '🌰', title: 'The King of Fruits', titleId: 'Raja Buah', minutes: 3,
    sentences: [
      ['Durian is a big fruit.', 'Durian adalah buah yang besar.'],
      ['It has sharp spikes.', 'Kulitnya berduri tajam.'],
      ['It smells very strong.', 'Baunya sangat menyengat.'],
      ['Dad loves durian.', 'Ayah sangat suka durian.'],
      ['Aisyah doesn\'t like durian.', 'Aisyah tidak suka durian.', true],
      ['She holds her nose. "It smells bad!"', 'Dia menutup hidungnya. "Baunya tidak enak!"'],
      ['People call durian "the king of fruits".', 'Orang menyebut durian "raja buah".'],
    ],
    vocab: [
      ['fruit', 'buah', '🍓', 'noun', ['fruits'], 'a big fruit'],
      ['sharp', 'tajam', '🔪', 'adjective', [], 'sharp spikes'],
      ['spikes', 'duri', '🌵', 'noun', ['spike'], 'It has sharp spikes.'],
      ['smells', 'berbau', '👃', 'verb', ['smell'], 'It smells very strong.'],
      ['king', 'raja', '👑', 'noun', ['kings'], 'the king of fruits'],
    ],
    grammar: [P.iLike],
    quiz: [
      ['Who loves durian? (Siapa yang sangat suka durian?)', ['Aisyah', 'Dad', 'Milo'], 1, '"Dad loves durian."'],
      ['What does durian have? (Durian punya apa?)', ['Sharp spikes', 'Soft fur', 'Long legs'], 0, '"It has sharp spikes."'],
      ['"Aisyah doesn\'t like durian" artinya Aisyah …', ['Suka durian', 'Tidak suka durian', 'Menjual durian'], 1, 'Doesn\'t like = tidak suka.'],
    ],
  },
  {
    slug: 'a1-hairy-rambutan', theme: 'Fruit', emoji: '🔴', title: 'The Hairy Fruit', titleId: 'Buah Berambut', minutes: 3,
    sentences: [
      ['Look at this fruit!', 'Lihat buah ini!'],
      ['It is small and red.', 'Buahnya kecil dan merah.'],
      ['It has hair on its skin!', 'Kulitnya berambut!'],
      ['It is a rambutan.', 'Itu rambutan.'],
      ['I open the skin with my fingers.', 'Aku membuka kulitnya dengan jari.', true],
      ['Inside, it is white and sweet.', 'Di dalamnya putih dan manis.'],
      ['Don\'t eat the seed!', 'Jangan makan bijinya!'],
    ],
    vocab: [
      ['small', 'kecil', '🤏', 'adjective', [], 'It is small and red.'],
      ['skin', 'kulit', '🟤', 'noun', [], 'on its skin'],
      ['open', 'membuka', '📂', 'verb', ['opens'], 'I open the skin.'],
      ['white', 'putih', '⚪', 'adjective', [], 'it is white and sweet'],
      ['seed', 'biji', '🌱', 'noun', ['seeds'], 'Don\'t eat the seed!'],
    ],
    grammar: [P.itIs],
    quiz: [
      ['What color is a rambutan outside? (Apa warna rambutan di luar?)', ['Red', 'Blue', 'Brown'], 0, '"It is small and red."'],
      ['What color is it inside? (Apa warnanya di dalam?)', ['Red', 'White', 'Green'], 1, '"Inside, it is white and sweet."'],
      ['What must you not eat? (Apa yang tidak boleh dimakan?)', ['The seed', 'The fruit', 'The sweet part'], 0, '"Don\'t eat the seed!"'],
    ],
  },
  {
    slug: 'a1-fruit-salad', theme: 'Fruit', emoji: '🥗', title: 'Fruit Salad', titleId: 'Salad Buah', minutes: 3,
    sentences: [
      ['Mom and I make a fruit salad.', 'Ibu dan aku membuat salad buah.'],
      ['We need papaya, mango, banana, and pineapple.', 'Kami butuh pepaya, mangga, pisang, dan nanas.'],
      ['Mom cuts the fruit into small pieces.', 'Ibu memotong buah menjadi potongan kecil.'],
      ['I put the pieces in a big bowl.', 'Aku memasukkan potongannya ke mangkuk besar.'],
      ['We add some yogurt.', 'Kami menambahkan sedikit yoghurt.', true],
      ['I mix it with a spoon.', 'Aku mengaduknya dengan sendok.'],
      ['Our fruit salad is colorful and yummy!', 'Salad buah kami warna-warni dan enak!'],
    ],
    vocab: [
      ['papaya', 'pepaya', '🧡', 'noun', ['papayas'], 'papaya, mango'],
      ['pineapple', 'nanas', '🍍', 'noun', ['pineapples'], 'and pineapple'],
      ['pieces', 'potongan', '🧩', 'noun', ['piece'], 'small pieces'],
      ['bowl', 'mangkuk', '🥣', 'noun', ['bowls'], 'a big bowl'],
      ['mix', 'mengaduk / mencampur', '🥄', 'verb', ['mixes'], 'I mix it with a spoon.'],
      ['colorful', 'warna-warni', '🌈', 'adjective', [], 'colorful and yummy'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What do they make? (Apa yang mereka buat?)', ['A cake', 'A fruit salad', 'A sandwich'], 1, '"Mom and I make a fruit salad."'],
      ['What does Rafi mix it with? (Rafi mengaduk dengan apa?)', ['A spoon', 'A fork', 'His hand'], 0, '"I mix it with a spoon."'],
      ['"Pineapple" artinya …', ['Pepaya', 'Nanas', 'Apel'], 1, 'Pineapple = nanas.'],
    ],
  },

  // ── Minggu 6: Hewan Peliharaan & Ternak ─────────────────────────────────
  {
    slug: 'a1-my-rabbit-snow', theme: 'Animals', emoji: '🐰', title: 'My Rabbit, Snow', titleId: 'Kelinciku, Snow', minutes: 3,
    sentences: [
      ['Dina has a rabbit.', 'Dina punya seekor kelinci.'],
      ['Its name is Snow.', 'Namanya Snow.'],
      ['Snow is white and fluffy.', 'Snow putih dan berbulu lembut.'],
      ['It has long ears and a short tail.', 'Telinganya panjang dan ekornya pendek.'],
      ['Snow likes carrots.', 'Snow suka wortel.', true],
      ['It hops around the garden.', 'Dia melompat-lompat di kebun.'],
      ['Hop, hop, hop!', 'Lompat, lompat, lompat!'],
    ],
    vocab: [
      ['rabbit', 'kelinci', '🐰', 'noun', ['rabbits'], 'Dina has a rabbit.'],
      ['fluffy', 'berbulu lembut', '☁️', 'adjective', [], 'white and fluffy'],
      ['short', 'pendek', '✂️', 'adjective', [], 'a short tail'],
      ['carrots', 'wortel', '🥕', 'noun', ['carrot'], 'Snow likes carrots.'],
      ['hops', 'melompat-lompat', '🐇', 'verb', ['hop'], 'It hops around the garden.'],
    ],
    grammar: [P.iHave],
    quiz: [
      ['Whose rabbit is Snow? (Snow kelinci milik siapa?)', ['Rafi\'s', 'Dina\'s', 'Budi\'s'], 1, '"Dina has a rabbit."'],
      ['What does Snow like? (Snow suka apa?)', ['Fish', 'Carrots', 'Milk'], 1, '"Snow likes carrots."'],
      ['A rabbit has … ears. (Kelinci punya telinga yang …)', ['Long', 'Short', 'No'], 0, '"It has long ears."'],
    ],
  },
  {
    slug: 'a1-uncle-jokos-farm', theme: 'Animals', emoji: '🐄', title: 'Uncle Joko\'s Farm', titleId: 'Peternakan Paman Joko', minutes: 3,
    sentences: [
      ['Uncle Joko has a farm.', 'Paman Joko punya peternakan.'],
      ['There is a cow. The cow says "moo".', 'Ada seekor sapi. Sapi bersuara "moo".'],
      ['There are goats. The goats say "meh".', 'Ada kambing-kambing. Kambing bersuara "meh".'],
      ['There are ducks. The ducks say "quack".', 'Ada bebek-bebek. Bebek bersuara "kwek".'],
      ['There is a rooster. It says "cock-a-doodle-doo".', 'Ada seekor ayam jantan. Dia berkokok "kukuruyuk".', true],
      ['The farm is noisy but fun!', 'Peternakannya ramai tapi menyenangkan!'],
    ],
    vocab: [
      ['farm', 'peternakan / pertanian', '🚜', 'noun', ['farms'], 'Uncle Joko has a farm.'],
      ['cow', 'sapi', '🐄', 'noun', ['cows'], 'There is a cow.'],
      ['goats', 'kambing', '🐐', 'noun', ['goat'], 'There are goats.'],
      ['ducks', 'bebek', '🦆', 'noun', ['duck'], 'There are ducks.'],
      ['rooster', 'ayam jantan', '🐓', 'noun', ['roosters'], 'There is a rooster.'],
      ['noisy', 'ramai / berisik', '📢', 'adjective', [], 'The farm is noisy.'],
    ],
    grammar: [P.animalSounds],
    quiz: [
      ['Who has a farm? (Siapa yang punya peternakan?)', ['Uncle Joko', 'Mrs. Sari', 'Dina'], 0, '"Uncle Joko has a farm."'],
      ['What does a duck say? (Apa suara bebek?)', ['Moo', 'Quack', 'Meow'], 1, '"The ducks say quack."'],
      ['"Rooster" artinya …', ['Ayam jantan', 'Bebek', 'Kambing'], 0, 'Rooster = ayam jantan.'],
    ],
  },
  {
    slug: 'a1-the-hen-and-her-chicks', theme: 'Animals', emoji: '🐣', title: 'The Hen and Her Chicks', titleId: 'Induk Ayam dan Anak-anaknya', minutes: 3,
    sentences: [
      ['The hen sits on her eggs.', 'Induk ayam mengerami telurnya.'],
      ['She sits there for many days.', 'Dia duduk di sana selama berhari-hari.'],
      ['One day, the eggs crack.', 'Suatu hari, telurnya retak.'],
      ['Little chicks come out!', 'Anak-anak ayam keluar!'],
      ['They are yellow and small.', 'Mereka kuning dan kecil.', true],
      ['"Peep, peep!" say the chicks.', '"Ciap, ciap!" kata anak-anak ayam.'],
      ['The hen keeps them warm.', 'Induk ayam menjaga mereka tetap hangat.'],
    ],
    vocab: [
      ['hen', 'induk ayam / ayam betina', '🐔', 'noun', ['hens'], 'The hen sits on her eggs.'],
      ['crack', 'retak', '🥚', 'verb', ['cracks'], 'the eggs crack'],
      ['chicks', 'anak ayam', '🐥', 'noun', ['chick'], 'Little chicks come out!'],
      ['little', 'kecil / mungil', '🤏', 'adjective', [], 'Little chicks'],
      ['warm', 'hangat', '🔥', 'adjective', [], 'keeps them warm'],
    ],
    grammar: [P.plural],
    quiz: [
      ['What does the hen sit on? (Induk ayam duduk di atas apa?)', ['Her eggs', 'A chair', 'The grass'], 0, '"The hen sits on her eggs."'],
      ['What color are the chicks? (Apa warna anak-anak ayam?)', ['Black', 'Yellow', 'Blue'], 1, '"They are yellow and small."'],
      ['What do the chicks say? (Apa suara anak ayam?)', ['Peep, peep', 'Moo', 'Woof'], 0, '"Peep, peep!" say the chicks.'],
    ],
  },
  {
    slug: 'a1-milo-and-the-fish', theme: 'Animals', emoji: '🐟', title: 'Milo and the Fish', titleId: 'Milo dan Ikan', minutes: 3,
    sentences: [
      ['We have a fish bowl.', 'Kami punya akuarium kecil.'],
      ['There are two goldfish in it.', 'Ada dua ikan mas koki di dalamnya.'],
      ['Milo sits next to the bowl.', 'Milo duduk di sebelah akuarium.'],
      ['He looks at the fish. He wants to catch them!', 'Dia memandangi ikan. Dia ingin menangkapnya!'],
      ['"No, Milo!" says Mom.', '"Jangan, Milo!" kata Ibu.', true],
      ['Mom puts the bowl on a high shelf.', 'Ibu menaruh akuarium di rak yang tinggi.'],
      ['Now the fish are safe.', 'Sekarang ikan-ikannya aman.'],
    ],
    vocab: [
      ['goldfish', 'ikan mas koki', '🐠', 'noun', [], 'two goldfish'],
      ['next to', 'di sebelah', '↔️', 'preposition', [], 'next to the bowl'],
      ['catch', 'menangkap', '🫳', 'verb', ['catches'], 'He wants to catch them!'],
      ['high', 'tinggi', '⬆️', 'adjective', [], 'a high shelf'],
      ['shelf', 'rak', '🗄️', 'noun', ['shelves'], 'on a high shelf'],
      ['safe', 'aman', '🛡️', 'adjective', [], 'the fish are safe'],
    ],
    grammar: [P.wantTo],
    quiz: [
      ['How many goldfish are there? (Ada berapa ikan mas koki?)', ['One', 'Two', 'Three'], 1, '"There are two goldfish in it."'],
      ['What does Milo want? (Apa yang Milo inginkan?)', ['To sleep', 'To catch the fish', 'To drink milk'], 1, '"He wants to catch them!"'],
      ['Where does Mom put the bowl? (Ibu menaruh akuarium di mana?)', ['On a high shelf', 'On the floor', 'In the bag'], 0, '"on a high shelf"'],
    ],
  },
  {
    slug: 'a1-ducks-in-the-pond', theme: 'Animals', emoji: '🦆', title: 'Ducks in the Pond', titleId: 'Bebek di Kolam', minutes: 3,
    sentences: [
      ['There is a pond in the village.', 'Ada kolam di desa.'],
      ['A mother duck swims in the pond.', 'Seekor induk bebek berenang di kolam.'],
      ['Five little ducklings follow her.', 'Lima anak bebek mengikutinya.'],
      ['They swim in a line.', 'Mereka berenang berbaris.'],
      ['Then they walk out of the water.', 'Lalu mereka berjalan keluar dari air.', true],
      ['Quack, quack! They go home.', 'Kwek, kwek! Mereka pulang.'],
    ],
    vocab: [
      ['pond', 'kolam', '🏞️', 'noun', ['ponds'], 'There is a pond.'],
      ['village', 'desa', '🏘️', 'noun', ['villages'], 'in the village'],
      ['swims', 'berenang', '🏊', 'verb', ['swim'], 'A mother duck swims.'],
      ['ducklings', 'anak bebek', '🐤', 'noun', ['duckling'], 'Five little ducklings'],
      ['follow', 'mengikuti', '👣', 'verb', ['follows'], 'They follow her.'],
      ['line', 'barisan', '➖', 'noun', ['lines'], 'in a line'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['How many ducklings are there? (Ada berapa anak bebek?)', ['Three', 'Four', 'Five'], 2, '"Five little ducklings follow her."'],
      ['Where do the ducks swim? (Di mana bebek-bebek berenang?)', ['In the pond', 'In the sea', 'In the bath'], 0, '"A mother duck swims in the pond."'],
      ['"Ducklings" artinya …', ['Induk bebek', 'Anak bebek', 'Angsa'], 1, 'Ducklings = anak bebek.'],
    ],
  },
  {
    slug: 'a1-the-friendly-dog', theme: 'Animals', emoji: '🐕', title: 'The Friendly Dog', titleId: 'Anjing yang Ramah', minutes: 3,
    sentences: [
      ['Mr. Joni lives next door.', 'Pak Joni tinggal di sebelah rumah.'],
      ['He has a big brown dog.', 'Dia punya anjing cokelat yang besar.'],
      ['The dog\'s name is Bruno.', 'Nama anjingnya Bruno.'],
      ['Bruno guards the house.', 'Bruno menjaga rumah.'],
      ['"Woof, woof!" he barks at strangers.', '"Guk, guk!" dia menggonggong pada orang asing.', true],
      ['But Bruno knows me.', 'Tapi Bruno mengenalku.'],
      ['When he sees me, he wags his tail.', 'Saat melihatku, dia mengibaskan ekornya.'],
    ],
    vocab: [
      ['next door', 'sebelah rumah', '🏘️', 'phrase', [], 'Mr. Joni lives next door.'],
      ['brown', 'cokelat', '🟫', 'adjective', [], 'a big brown dog'],
      ['guards', 'menjaga', '💂', 'verb', ['guard'], 'Bruno guards the house.'],
      ['barks', 'menggonggong', '🐕', 'verb', ['bark'], 'he barks at strangers'],
      ['strangers', 'orang asing', '🕵️', 'noun', ['stranger'], 'at strangers'],
      ['wags', 'mengibaskan', '🐾', 'verb', ['wag'], 'he wags his tail'],
    ],
    grammar: [P.animalSounds],
    quiz: [
      ['What is the dog\'s name? (Siapa nama anjingnya?)', ['Milo', 'Bruno', 'Snow'], 1, '"The dog\'s name is Bruno."'],
      ['What does Bruno do when he sees Rafi? (Apa yang Bruno lakukan saat melihat Rafi?)', ['He barks', 'He wags his tail', 'He sleeps'], 1, '"he wags his tail"'],
      ['What does a dog say? (Apa suara anjing?)', ['Woof', 'Moo', 'Quack'], 0, '"Woof, woof!"'],
    ],
  },
  {
    slug: 'a1-milk-from-the-cow', theme: 'Animals', emoji: '🥛', title: 'Milk from the Cow', titleId: 'Susu dari Sapi', minutes: 3,
    sentences: [
      ['This is Bella. She is a cow.', 'Ini Bella. Dia seekor sapi.'],
      ['Bella is black and white.', 'Bella berwarna hitam putih.'],
      ['She eats grass all day.', 'Dia makan rumput sepanjang hari.'],
      ['Every morning, the farmer milks Bella.', 'Setiap pagi, petani memerah susu Bella.'],
      ['The milk goes to the shop.', 'Susunya dikirim ke toko.', true],
      ['Mom buys the milk.', 'Ibu membeli susunya.'],
      ['I drink it. Thank you, Bella!', 'Aku meminumnya. Terima kasih, Bella!'],
    ],
    vocab: [
      ['black and white', 'hitam putih', '🐄', 'phrase', [], 'Bella is black and white.'],
      ['all day', 'sepanjang hari', '🌞', 'phrase', [], 'She eats grass all day.'],
      ['farmer', 'petani / peternak', '👨‍🌾', 'noun', ['farmers'], 'the farmer milks Bella'],
      ['milks', 'memerah susu', '🥛', 'verb', ['milk'], 'the farmer milks Bella'],
      ['shop', 'toko', '🏪', 'noun', ['shops'], 'to the shop'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What does Bella eat? (Bella makan apa?)', ['Grass', 'Fish', 'Bread'], 0, '"She eats grass all day."'],
      ['Who milks Bella? (Siapa yang memerah susu Bella?)', ['Mom', 'The farmer', 'Rafi'], 1, '"the farmer milks Bella"'],
      ['What color is Bella? (Apa warna Bella?)', ['Brown', 'Black and white', 'Gray'], 1, '"Bella is black and white."'],
    ],
  },

  // ── Minggu 7: Rumahku ────────────────────────────────────────────────────
  {
    slug: 'a1-this-is-my-house', theme: 'Home', emoji: '🏠', title: 'This Is My House', titleId: 'Ini Rumahku', minutes: 3,
    sentences: [
      ['This is my house.', 'Ini rumahku.'],
      ['It is not big, but it is nice.', 'Rumahku tidak besar, tapi bagus.'],
      ['There is a living room and a kitchen.', 'Ada ruang tamu dan dapur.'],
      ['There are two bedrooms.', 'Ada dua kamar tidur.'],
      ['There is one bathroom.', 'Ada satu kamar mandi.'],
      ['There is a small garden in front.', 'Ada kebun kecil di depan.', true],
      ['My family lives here. I love my home.', 'Keluargaku tinggal di sini. Aku sayang rumahku.'],
    ],
    vocab: [
      ['house', 'rumah', '🏠', 'noun', ['houses'], 'This is my house.'],
      ['living room', 'ruang tamu / ruang keluarga', '🛋️', 'noun', [], 'a living room'],
      ['kitchen', 'dapur', '🍳', 'noun', ['kitchens'], 'and a kitchen'],
      ['bedrooms', 'kamar tidur', '🛏️', 'noun', ['bedroom'], 'two bedrooms'],
      ['bathroom', 'kamar mandi', '🛁', 'noun', ['bathrooms'], 'one bathroom'],
      ['garden', 'kebun / taman', '🌷', 'noun', ['gardens'], 'a small garden'],
    ],
    grammar: [P.thereIsAre],
    quiz: [
      ['How many bedrooms are there? (Ada berapa kamar tidur?)', ['One', 'Two', 'Three'], 1, '"There are two bedrooms."'],
      ['Where is the garden? (Di mana kebunnya?)', ['In front', 'On the roof', 'In the kitchen'], 0, '"a small garden in front"'],
      ['"Kitchen" artinya …', ['Kamar mandi', 'Dapur', 'Kamar tidur'], 1, 'Kitchen = dapur.'],
    ],
  },
  {
    slug: 'a1-in-the-kitchen', theme: 'Home', emoji: '🍳', title: 'In the Kitchen', titleId: 'Di Dapur', minutes: 3,
    sentences: [
      ['Mom is in the kitchen.', 'Ibu ada di dapur.'],
      ['There is a stove and a big pot.', 'Ada kompor dan panci besar.'],
      ['There are plates and cups on the shelf.', 'Ada piring dan cangkir di rak.'],
      ['There is a fridge in the corner.', 'Ada kulkas di sudut.'],
      ['The fridge is cold inside.', 'Di dalam kulkas dingin.', true],
      ['Mom cooks soup on the stove.', 'Ibu memasak sup di atas kompor.'],
      ['It smells good!', 'Baunya harum!'],
    ],
    vocab: [
      ['stove', 'kompor', '🔥', 'noun', ['stoves'], 'There is a stove.'],
      ['pot', 'panci', '🍲', 'noun', ['pots'], 'a big pot'],
      ['plates', 'piring', '🍽️', 'noun', ['plate'], 'plates and cups'],
      ['cups', 'cangkir', '☕', 'noun', ['cup'], 'plates and cups'],
      ['fridge', 'kulkas', '🧊', 'noun', ['fridges'], 'a fridge in the corner'],
      ['cooks', 'memasak', '👩‍🍳', 'verb', ['cook'], 'Mom cooks soup.'],
    ],
    grammar: [P.thereIsAre],
    quiz: [
      ['What does Mom cook? (Ibu memasak apa?)', ['Rice', 'Soup', 'Cake'], 1, '"Mom cooks soup on the stove."'],
      ['Where are the plates? (Di mana piringnya?)', ['On the shelf', 'In the bed', 'Under the stove'], 0, '"There are plates and cups on the shelf."'],
      ['"Fridge" artinya …', ['Kompor', 'Kulkas', 'Panci'], 1, 'Fridge = kulkas.'],
    ],
  },
  {
    slug: 'a1-my-bedroom', theme: 'Home', emoji: '🛏️', title: 'My Bedroom', titleId: 'Kamar Tidurku', minutes: 3,
    sentences: [
      ['This is my bedroom.', 'Ini kamar tidurku.'],
      ['I share it with Aisyah.', 'Aku berbagi kamar dengan Aisyah.'],
      ['There are two small beds.', 'Ada dua tempat tidur kecil.'],
      ['Each bed has a pillow and a blanket.', 'Setiap tempat tidur punya bantal dan selimut.'],
      ['There is a desk and a lamp.', 'Ada meja belajar dan lampu.', true],
      ['I do my homework at the desk.', 'Aku mengerjakan PR di meja itu.'],
      ['My clothes are in the wardrobe.', 'Bajuku ada di dalam lemari.'],
    ],
    vocab: [
      ['pillow', 'bantal', '🛌', 'noun', ['pillows'], 'a pillow and a blanket'],
      ['blanket', 'selimut', '🧣', 'noun', ['blankets'], 'a pillow and a blanket'],
      ['lamp', 'lampu', '💡', 'noun', ['lamps'], 'a desk and a lamp'],
      ['homework', 'PR / pekerjaan rumah', '📝', 'noun', [], 'I do my homework.'],
      ['clothes', 'pakaian', '👕', 'noun', [], 'My clothes are in the wardrobe.'],
      ['wardrobe', 'lemari pakaian', '🚪', 'noun', ['wardrobes'], 'in the wardrobe'],
    ],
    grammar: [P.thereIsAre],
    quiz: [
      ['Who does Rafi share his bedroom with? (Rafi berbagi kamar dengan siapa?)', ['Dina', 'Aisyah', 'Budi'], 1, '"I share it with Aisyah."'],
      ['Where does Rafi do his homework? (Di mana Rafi mengerjakan PR?)', ['At the desk', 'In the kitchen', 'On the roof'], 0, '"I do my homework at the desk."'],
      ['"Pillow" artinya …', ['Selimut', 'Bantal', 'Lampu'], 1, 'Pillow = bantal.'],
    ],
  },
  {
    slug: 'a1-the-living-room', theme: 'Home', emoji: '🛋️', title: 'The Living Room', titleId: 'Ruang Keluarga', minutes: 3,
    sentences: [
      ['After dinner, we sit in the living room.', 'Setelah makan malam, kami duduk di ruang keluarga.'],
      ['There is a big sofa.', 'Ada sofa besar.'],
      ['There is a TV and a bookcase.', 'Ada TV dan rak buku.'],
      ['There are family photos on the wall.', 'Ada foto keluarga di dinding.'],
      ['Dad reads the newspaper.', 'Ayah membaca koran.', true],
      ['Mom and Aisyah watch TV.', 'Ibu dan Aisyah menonton TV.'],
      ['Milo sleeps on the sofa. Shh!', 'Milo tidur di atas sofa. Ssst!'],
    ],
    vocab: [
      ['dinner', 'makan malam', '🍽️', 'noun', [], 'After dinner'],
      ['sofa', 'sofa', '🛋️', 'noun', ['sofas'], 'a big sofa'],
      ['bookcase', 'rak buku', '📚', 'noun', ['bookcases'], 'a TV and a bookcase'],
      ['photos', 'foto', '🖼️', 'noun', ['photo'], 'family photos'],
      ['newspaper', 'koran', '📰', 'noun', ['newspapers'], 'Dad reads the newspaper.'],
      ['watch', 'menonton', '📺', 'verb', ['watches'], 'Mom and Aisyah watch TV.'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What does Dad read? (Ayah membaca apa?)', ['A comic', 'The newspaper', 'A letter'], 1, '"Dad reads the newspaper."'],
      ['Where does Milo sleep? (Di mana Milo tidur?)', ['On the sofa', 'In the kitchen', 'On the roof'], 0, '"Milo sleeps on the sofa."'],
      ['What is on the wall? (Apa yang ada di dinding?)', ['Family photos', 'A TV', 'A sofa'], 0, '"There are family photos on the wall."'],
    ],
  },
  {
    slug: 'a1-where-is-milo', theme: 'Home', emoji: '📦', title: 'Where Is Milo?', titleId: 'Di Mana Milo?', minutes: 3,
    sentences: [
      ['"Where is Milo?" asks Aisyah.', '"Di mana Milo?" tanya Aisyah.'],
      ['Is he on the bed? No, he isn\'t.', 'Apakah dia di atas kasur? Tidak.'],
      ['Is he under the table? No, he isn\'t.', 'Apakah dia di bawah meja? Tidak.'],
      ['Is he behind the door? No, he isn\'t.', 'Apakah dia di balik pintu? Tidak.'],
      ['Look! There is a big box.', 'Lihat! Ada kotak besar.', true],
      ['Milo is in the box!', 'Milo ada di dalam kotak!'],
      ['"Meow!" says Milo. He is happy.', '"Meong!" kata Milo. Dia senang.'],
    ],
    vocab: [
      ['where', 'di mana', '❓', 'adverb', [], 'Where is Milo?'],
      ['on', 'di atas', '⬆️', 'preposition', [], 'on the bed'],
      ['under', 'di bawah', '⬇️', 'preposition', [], 'under the table'],
      ['behind', 'di belakang / di balik', '🔙', 'preposition', [], 'behind the door'],
      ['box', 'kotak', '📦', 'noun', ['boxes'], 'Milo is in the box!'],
    ],
    grammar: [P.prepositions],
    quiz: [
      ['Where is Milo? (Di mana Milo?)', ['On the bed', 'In the box', 'Under the table'], 1, '"Milo is in the box!"'],
      ['"Under the table" artinya …', ['Di atas meja', 'Di bawah meja', 'Di samping meja'], 1, 'Under = di bawah.'],
      ['Who looks for Milo? (Siapa yang mencari Milo?)', ['Aisyah', 'Dad', 'Dina'], 0, '"Where is Milo?" asks Aisyah.'],
    ],
  },
  {
    slug: 'a1-cleaning-day', theme: 'Home', emoji: '🧹', title: 'Cleaning Day', titleId: 'Hari Bersih-bersih', minutes: 3,
    sentences: [
      ['Today is Sunday. It is cleaning day!', 'Hari ini Minggu. Saatnya bersih-bersih!'],
      ['Dad sweeps the floor.', 'Ayah menyapu lantai.'],
      ['Mom mops the kitchen.', 'Ibu mengepel dapur.'],
      ['I put my toys in the box.', 'Aku memasukkan mainanku ke kotak.'],
      ['Aisyah wipes the table.', 'Aisyah mengelap meja.'],
      ['We work together.', 'Kami bekerja bersama.', true],
      ['Now our house is clean and tidy!', 'Sekarang rumah kami bersih dan rapi!'],
    ],
    vocab: [
      ['sweeps', 'menyapu', '🧹', 'verb', ['sweep'], 'Dad sweeps the floor.'],
      ['floor', 'lantai', '🟫', 'noun', ['floors'], 'the floor'],
      ['mops', 'mengepel', '🪣', 'verb', ['mop'], 'Mom mops the kitchen.'],
      ['toys', 'mainan', '🧸', 'noun', ['toy'], 'my toys'],
      ['wipes', 'mengelap', '🧽', 'verb', ['wipe'], 'Aisyah wipes the table.'],
      ['tidy', 'rapi', '🗂️', 'adjective', [], 'clean and tidy'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['Who sweeps the floor? (Siapa yang menyapu lantai?)', ['Mom', 'Dad', 'Aisyah'], 1, '"Dad sweeps the floor."'],
      ['What does Rafi do? (Apa yang Rafi lakukan?)', ['He puts his toys in the box', 'He cooks', 'He mops'], 0, '"I put my toys in the box."'],
      ['What day is cleaning day? (Hari apa hari bersih-bersih?)', ['Monday', 'Friday', 'Sunday'], 2, '"Today is Sunday."'],
    ],
  },
  {
    slug: 'a1-grandmas-garden', theme: 'Home', emoji: '🌺', title: 'Grandma\'s Garden', titleId: 'Kebun Nenek', minutes: 3,
    sentences: [
      ['Grandma has a lovely garden.', 'Nenek punya kebun yang indah.'],
      ['There are red and pink flowers.', 'Ada bunga merah dan merah muda.'],
      ['There are chili plants and tomato plants.', 'Ada tanaman cabai dan tanaman tomat.'],
      ['Every morning, Grandma waters the plants.', 'Setiap pagi, Nenek menyiram tanaman.'],
      ['I help her with a small watering can.', 'Aku membantunya dengan penyiram kecil.', true],
      ['Butterflies fly over the flowers.', 'Kupu-kupu terbang di atas bunga.'],
      ['I like Grandma\'s garden.', 'Aku suka kebun Nenek.'],
    ],
    vocab: [
      ['lovely', 'indah / menyenangkan', '💐', 'adjective', [], 'a lovely garden'],
      ['flowers', 'bunga', '🌸', 'noun', ['flower'], 'red and pink flowers'],
      ['plants', 'tanaman', '🪴', 'noun', ['plant'], 'chili plants'],
      ['waters', 'menyiram', '🚿', 'verb', ['water'], 'Grandma waters the plants.'],
      ['help', 'membantu', '🤝', 'verb', ['helps'], 'I help her.'],
      ['butterflies', 'kupu-kupu', '🦋', 'noun', ['butterfly'], 'Butterflies fly over the flowers.'],
    ],
    grammar: [P.everyday],
    quiz: [
      ['What does Grandma do every morning? (Apa yang Nenek lakukan setiap pagi?)', ['She waters the plants', 'She swims', 'She sleeps'], 0, '"Grandma waters the plants."'],
      ['What flies over the flowers? (Apa yang terbang di atas bunga?)', ['Birds', 'Butterflies', 'Planes'], 1, '"Butterflies fly over the flowers."'],
      ['"Plants" artinya …', ['Tanaman', 'Pohon besar', 'Batu'], 0, 'Plants = tanaman.'],
    ],
  },
];
