// Materi IPA — Fase A–B (SD Kelas 1–4), Kurikulum Merdeka (IPAS).
// Markdown (dirender MathRenderer) + latihan singkat.

import type { SeedLesson } from './types';

export const ipaFaseAB: SeedLesson[] = [
  {
    slug: 'ipa-panca-indra',
    theme: 'IPA: Tubuh Manusia',
    emoji: '👀',
    title: 'Panca Indra',
    titleId: 'Lima alat indra dan fungsinya',
    minutes: 5,
    intro: [
      'Manusia memiliki **lima indra** yang disebut **panca indra**. Dengan indra, kita bisa mengenal dunia di sekitar kita.',
      '',
      '👁️ **Mata** — indra **penglihat**. Untuk melihat warna, bentuk, dan benda.',
      '👂 **Telinga** — indra **pendengar**. Untuk mendengar suara.',
      '👃 **Hidung** — indra **pencium**. Untuk mencium bau harum atau busuk.',
      '👅 **Lidah** — indra **pengecap**. Untuk merasakan manis, asin, asam, dan pahit.',
      '✋ **Kulit** — indra **peraba**. Untuk merasakan halus, kasar, panas, dan dingin.',
      '',
      '**Cara merawat panca indra:**',
      '• Membaca di tempat yang terang dan tidak terlalu dekat.',
      '• Tidak memasukkan benda tajam ke telinga.',
      '• Menggosok gigi dan lidah setiap hari.',
      '• Mandi dua kali sehari agar kulit bersih.',
      '',
      '> Indra mana yang kamu gunakan saat makan es krim? Ternyata banyak: mata, hidung, lidah, dan kulit!',
    ].join('\n'),
    quiz: [
      ['Indra pencium adalah …', ['Mata', 'Hidung', 'Telinga'], 1, 'Hidung adalah indra pencium.'],
      ['Untuk merasakan rasa manis dan asin, kita menggunakan …', ['Lidah', 'Kulit', 'Mata'], 0, 'Lidah adalah indra pengecap.'],
      ['Kulit berfungsi sebagai indra …', ['Pendengar', 'Peraba', 'Penglihat'], 1, 'Kulit adalah indra peraba.'],
      ['Cara merawat mata yang benar adalah …', ['Membaca di tempat gelap', 'Membaca di tempat yang terang', 'Menonton TV sangat dekat'], 1, 'Membaca di tempat terang menjaga mata tetap sehat.'],
    ],
  },
  {
    slug: 'ipa-ciri-makhluk-hidup',
    theme: 'IPA: Makhluk Hidup',
    emoji: '🌱',
    title: 'Ciri-Ciri Makhluk Hidup',
    titleId: 'Membedakan benda hidup dan benda mati',
    minutes: 5,
    intro: [
      'Di sekitar kita ada **makhluk hidup** (manusia, hewan, tumbuhan) dan **benda mati** (batu, meja, buku).',
      '',
      '**Ciri-ciri makhluk hidup:**',
      '1️⃣ **Bernapas** — manusia dan hewan menghirup udara; tumbuhan bernapas lewat daun.',
      '2️⃣ **Memerlukan makanan dan minuman.**',
      '3️⃣ **Tumbuh** — bayi menjadi dewasa, biji menjadi pohon.',
      '4️⃣ **Bergerak** — hewan berlari; tumbuhan bergerak, misalnya daun putri malu menguncup saat disentuh.',
      '5️⃣ **Berkembang biak** — memiliki keturunan. Kucing beranak, ayam bertelur, tumbuhan berbiji.',
      '6️⃣ **Peka terhadap rangsangan** — tangan kita menghindar saat menyentuh benda panas.',
      '',
      '**Benda mati** tidak memiliki ciri-ciri di atas. Batu tidak makan, tidak tumbuh, dan tidak berkembang biak.',
      '',
      '> Mobil bisa bergerak, tetapi bukan makhluk hidup, karena tidak tumbuh dan tidak berkembang biak.',
    ].join('\n'),
    quiz: [
      ['Berikut yang termasuk makhluk hidup adalah …', ['Batu', 'Kucing', 'Kursi'], 1, 'Kucing bernapas, makan, tumbuh, dan berkembang biak.'],
      ['Daun putri malu menguncup saat disentuh. Ini menunjukkan ciri …', ['Peka terhadap rangsangan', 'Bernapas', 'Berkembang biak'], 0, 'Putri malu bereaksi terhadap sentuhan (rangsangan).'],
      ['Mengapa mobil bukan makhluk hidup?', ['Karena tidak bisa bergerak', 'Karena tidak tumbuh dan tidak berkembang biak', 'Karena berwarna'], 1, 'Mobil bisa bergerak, tetapi tidak tumbuh dan tidak berkembang biak.'],
    ],
  },
  {
    slug: 'ipa-bagian-tumbuhan',
    theme: 'IPA: Makhluk Hidup',
    emoji: '🌳',
    title: 'Bagian-Bagian Tumbuhan',
    titleId: 'Akar, batang, daun, bunga, dan buah',
    minutes: 5,
    intro: [
      'Tumbuhan memiliki bagian-bagian dengan tugas masing-masing.',
      '',
      '🟫 **Akar** — menyerap air dan zat hara dari tanah, serta menguatkan tumbuhan agar tidak roboh.',
      '🪵 **Batang** — menyangga tumbuhan dan mengangkut air dari akar ke daun.',
      '🍃 **Daun** — tempat tumbuhan **membuat makanan** dengan bantuan sinar matahari. Daun juga tempat tumbuhan bernapas.',
      '🌸 **Bunga** — alat perkembangbiakan. Dari bunga akan terbentuk buah dan biji.',
      '🍎 **Buah** — melindungi biji. Banyak buah yang bisa kita makan.',
      '🌰 **Biji** — jika ditanam, biji dapat tumbuh menjadi tumbuhan baru.',
      '',
      '**Bagian tumbuhan yang kita makan:**',
      '• Akar: wortel, singkong',
      '• Batang: tebu',
      '• Daun: bayam, kangkung',
      '• Bunga: brokoli, kembang kol',
      '• Buah: mangga, tomat',
      '• Biji: kacang, beras',
    ].join('\n'),
    quiz: [
      ['Bagian tumbuhan yang menyerap air dari tanah adalah …', ['Daun', 'Akar', 'Bunga'], 1, 'Akar menyerap air dan zat hara.'],
      ['Di bagian manakah tumbuhan membuat makanan?', ['Daun', 'Batang', 'Akar'], 0, 'Daun membuat makanan dengan bantuan sinar matahari.'],
      ['Wortel adalah bagian … yang bisa dimakan.', ['Batang', 'Akar', 'Buah'], 1, 'Wortel adalah akar.'],
      ['Bayam yang kita makan adalah bagian …', ['Daun', 'Bunga', 'Biji'], 0, 'Kita memakan daun bayam.'],
    ],
  },
  {
    slug: 'ipa-wujud-benda',
    theme: 'IPA: Materi',
    emoji: '🧊',
    title: 'Wujud Benda dan Perubahannya',
    titleId: 'Padat, cair, dan gas',
    minutes: 6,
    intro: [
      'Benda di sekitar kita memiliki tiga wujud:',
      '',
      '🧱 **Padat** — bentuknya **tetap**. Contoh: batu, kayu, es batu, buku.',
      '💧 **Cair** — bentuknya **mengikuti wadah**. Contoh: air, susu, minyak, kecap.',
      '💨 **Gas** — tidak terlihat dan **memenuhi ruangan**. Contoh: udara di dalam balon, uap air.',
      '',
      '**Perubahan wujud benda:**',
      '• **Mencair** (padat → cair): es batu dibiarkan di luar kulkas.',
      '• **Membeku** (cair → padat): air dimasukkan ke freezer menjadi es.',
      '• **Menguap** (cair → gas): air yang dipanaskan menjadi uap.',
      '• **Mengembun** (gas → cair): titik-titik air di luar gelas berisi es.',
      '',
      '> Coba tiup balon! Udara yang kamu tiupkan adalah benda gas yang memenuhi balon.',
    ].join('\n'),
    quiz: [
      ['Benda yang bentuknya mengikuti wadah adalah benda …', ['Padat', 'Cair', 'Gas'], 1, 'Benda cair bentuknya mengikuti wadah.'],
      ['Es batu yang dibiarkan di luar akan …', ['Membeku', 'Mencair', 'Mengembun'], 1, 'Es batu (padat) berubah menjadi air (cair) → mencair.'],
      ['Air yang dimasak sampai mendidih akan …', ['Menguap', 'Membeku', 'Mencair'], 0, 'Air (cair) berubah menjadi uap (gas) → menguap.'],
      ['Udara di dalam balon termasuk benda …', ['Padat', 'Cair', 'Gas'], 2, 'Udara adalah benda gas.'],
    ],
  },
  {
    slug: 'ipa-hewan-dan-makanannya',
    theme: 'IPA: Makhluk Hidup',
    emoji: '🦁',
    title: 'Hewan dan Makanannya',
    titleId: 'Herbivora, karnivora, dan omnivora',
    minutes: 5,
    intro: [
      'Hewan dapat dikelompokkan berdasarkan jenis makanannya.',
      '',
      '🐄 **Herbivora** — hewan **pemakan tumbuhan**. Contoh: sapi, kambing, kelinci, gajah, kuda.',
      '🦁 **Karnivora** — hewan **pemakan daging**. Contoh: singa, harimau, buaya, elang.',
      '🐔 **Omnivora** — hewan **pemakan tumbuhan dan daging**. Contoh: ayam, beruang, tikus.',
      '',
      '**Tahukah kamu?**',
      '• Karnivora biasanya memiliki gigi taring yang tajam untuk merobek daging.',
      '• Herbivora memiliki gigi geraham yang lebar untuk mengunyah rumput.',
      '• Manusia juga termasuk omnivora karena makan nasi, sayur, ikan, dan daging.',
    ].join('\n'),
    quiz: [
      ['Kambing termasuk hewan …', ['Herbivora', 'Karnivora', 'Omnivora'], 0, 'Kambing memakan tumbuhan.'],
      ['Hewan pemakan daging disebut …', ['Herbivora', 'Karnivora', 'Omnivora'], 1, 'Karnivora = pemakan daging.'],
      ['Ayam memakan biji-bijian dan cacing. Ayam termasuk …', ['Herbivora', 'Karnivora', 'Omnivora'], 2, 'Memakan tumbuhan dan hewan → omnivora.'],
      ['Gigi taring yang tajam biasanya dimiliki hewan …', ['Karnivora', 'Herbivora', 'Semua hewan'], 0, 'Gigi taring untuk merobek daging.'],
    ],
  },
  {
    slug: 'ipa-sumber-energi',
    theme: 'IPA: Energi',
    emoji: '⚡',
    title: 'Sumber Energi Panas dan Cahaya',
    titleId: 'Matahari, api, dan listrik',
    minutes: 5,
    intro: [
      '**Energi** adalah kemampuan untuk melakukan kegiatan. Tanpa energi, kita tidak bisa bergerak, memasak, atau menyalakan lampu.',
      '',
      '☀️ **Matahari** — sumber energi **terbesar** bagi Bumi. Memberi panas dan cahaya untuk menjemur pakaian, mengeringkan padi, dan membantu tumbuhan membuat makanan.',
      '🔥 **Api** — menghasilkan panas dan cahaya. Digunakan untuk memasak.',
      '💡 **Listrik** — menyalakan lampu, kipas angin, dan televisi.',
      '🔋 **Baterai** — menyimpan energi listrik untuk senter, mainan, dan jam.',
      '',
      '**Hemat energi, yuk!**',
      '• Matikan lampu dan televisi jika tidak digunakan.',
      '• Buka jendela pada siang hari agar cahaya matahari masuk.',
      '• Cabut pengisi daya (charger) setelah dipakai.',
    ].join('\n'),
    quiz: [
      ['Sumber energi terbesar bagi Bumi adalah …', ['Lampu', 'Matahari', 'Baterai'], 1, 'Matahari adalah sumber energi terbesar.'],
      ['Contoh pemanfaatan panas matahari adalah …', ['Menjemur pakaian', 'Menyalakan televisi', 'Menelepon'], 0, 'Panas matahari mengeringkan pakaian.'],
      ['Cara menghemat energi listrik adalah …', ['Menyalakan lampu sepanjang hari', 'Mematikan lampu jika tidak digunakan', 'Membiarkan TV menyala'], 1, 'Matikan alat listrik yang tidak digunakan.'],
    ],
  },
  {
    slug: 'ipa-fotosintesis',
    theme: 'IPA: Makhluk Hidup',
    emoji: '🍃',
    title: 'Fotosintesis: Dapur Tumbuhan',
    titleId: 'Bagaimana tumbuhan membuat makanan',
    minutes: 5,
    intro: [
      'Hewan dan manusia mencari makanan. Tumbuhan hijau berbeda: tumbuhan **membuat makanannya sendiri**!',
      'Proses ini disebut **fotosintesis**. *Foto* artinya cahaya, *sintesis* artinya menyusun.',
      '',
      '**Bahan yang dibutuhkan:**',
      '• 💧 **Air** — diserap akar dari tanah.',
      '• 🌫️ **Karbon dioksida** — gas dari udara yang masuk lewat daun.',
      '• ☀️ **Cahaya matahari** — sumber energinya.',
      '• 🟢 **Klorofil** — zat hijau daun yang menangkap cahaya.',
      '',
      '**Hasil fotosintesis:**',
      '• 🍬 **Gula (zat makanan)** — digunakan untuk tumbuh, sebagian disimpan di umbi, buah, atau biji.',
      '• 🫧 **Oksigen** — dilepaskan ke udara dan kita hirup untuk bernapas.',
      '',
      '> Karena itu, menanam pohon membuat udara lebih segar!',
    ].join('\n'),
    quiz: [
      ['Fotosintesis terjadi di bagian …', ['Akar', 'Daun', 'Bunga'], 1, 'Fotosintesis terjadi di daun yang berklorofil.'],
      ['Zat hijau daun disebut …', ['Klorofil', 'Oksigen', 'Karbon dioksida'], 0, 'Klorofil adalah zat hijau daun.'],
      ['Gas yang dihasilkan fotosintesis dan kita hirup adalah …', ['Karbon dioksida', 'Oksigen', 'Uap air'], 1, 'Fotosintesis menghasilkan oksigen.'],
      ['Yang BUKAN bahan fotosintesis adalah …', ['Air', 'Cahaya matahari', 'Pasir'], 2, 'Bahannya: air, karbon dioksida, cahaya matahari.'],
    ],
  },
  {
    slug: 'ipa-gaya-dorong-tarik',
    theme: 'IPA: Gaya',
    emoji: '🛒',
    title: 'Gaya: Dorongan dan Tarikan',
    titleId: 'Mengenal gaya di sekitar kita',
    minutes: 5,
    intro: [
      '**Gaya** adalah **dorongan** atau **tarikan** yang dapat mengubah keadaan benda.',
      '',
      '**Contoh dorongan:** 🫸 mendorong troli belanja, menendang bola, menutup pintu.',
      '**Contoh tarikan:** 🫷 menarik laci, menimba air dari sumur, bermain tarik tambang.',
      '',
      '**Pengaruh gaya pada benda:**',
      '• Benda diam menjadi **bergerak** — bola ditendang.',
      '• Benda bergerak menjadi **berhenti** — kiper menangkap bola.',
      '• **Arah** gerak berubah — bola dipantulkan ke dinding.',
      '• **Bentuk** benda berubah — membuat bentuk dari plastisin.',
      '',
      '**Gaya gravitasi** ⬇️ adalah tarikan Bumi. Karena gravitasi, buah yang matang jatuh ke bawah, bukan ke atas.',
    ].join('\n'),
    quiz: [
      ['Membuka laci adalah contoh gaya …', ['Dorongan', 'Tarikan', 'Gravitasi'], 1, 'Laci ditarik untuk dibuka.'],
      ['Menendang bola adalah contoh gaya …', ['Dorongan', 'Tarikan', 'Magnet'], 0, 'Kaki mendorong bola.'],
      ['Buah mangga jatuh ke tanah karena …', ['Gaya gravitasi', 'Gaya magnet', 'Angin saja'], 0, 'Gravitasi adalah tarikan Bumi.'],
      ['Membentuk plastisin menjadi bola menunjukkan bahwa gaya dapat …', ['Mengubah bentuk benda', 'Membuat benda hilang', 'Mengubah warna benda'], 0, 'Gaya dapat mengubah bentuk benda.'],
    ],
  },
];
