// Materi Matematika — Fase A (SD Kelas 1–2), Kurikulum Merdeka.
// Ditulis dalam Markdown + KaTeX (dirender oleh MathRenderer), masing-masing dengan latihan singkat.

import type { SeedLesson } from './types';

const susun = (a: string, op: string, b: string, result: string, carry = '') =>
  `$$\\begin{array}{r}${carry ? `\\scriptsize ${carry} \\\\ ` : ''}${a} \\\\ ${op}\\; ${b} \\\\ \\hline ${result}\\end{array}$$`;

export const matematikaFaseA: SeedLesson[] = [
  {
    slug: 'mtk-puluhan-dan-satuan',
    theme: 'Matematika: Bilangan',
    emoji: '🔢',
    title: 'Puluhan dan Satuan',
    titleId: 'Nilai tempat bilangan sampai 100',
    minutes: 5,
    intro: [
      'Bilangan dua angka terdiri dari **puluhan** dan **satuan**.',
      '',
      '1 puluhan = 10 satuan. Bayangkan 10 batang lidi diikat menjadi satu ikat.',
      '',
      '**Contoh: bilangan 47**',
      '• Angka **4** ada di tempat puluhan → nilainya 40',
      '• Angka **7** ada di tempat satuan → nilainya 7',
      '$$47 = 40 + 7$$',
      '',
      '**Contoh lain:**',
      '• 25 = 2 puluhan + 5 satuan = 20 + 5',
      '• 90 = 9 puluhan + 0 satuan = 90 + 0',
      '• 100 = 10 puluhan = **seratus**',
      '',
      '> Tips: angka di sebelah kiri adalah puluhan, angka di sebelah kanan adalah satuan.',
    ].join('\n'),
    quiz: [
      ['Pada bilangan 63, angka 6 menempati tempat …', ['Satuan', 'Puluhan', 'Ratusan'], 1, '6 berada di sebelah kiri, yaitu tempat puluhan (nilainya 60).'],
      ['3 puluhan + 8 satuan = …', ['38', '83', '11'], 0, '30 + 8 = 38.'],
      ['Nilai angka 5 pada bilangan 75 adalah …', ['50', '5', '75'], 1, '5 berada di tempat satuan, jadi nilainya 5.'],
      ['Bilangan yang terdiri dari 10 puluhan adalah …', ['10', '100', '1.000'], 1, '10 puluhan = 100 (seratus).'],
    ],
  },
  {
    slug: 'mtk-penjumlahan-bersusun',
    theme: 'Matematika: Operasi Hitung',
    emoji: '➕',
    title: 'Penjumlahan Bersusun',
    titleId: 'Menjumlahkan bilangan dua angka',
    minutes: 6,
    intro: [
      'Untuk menjumlahkan bilangan dua angka, kita bisa menulisnya **bersusun ke bawah**.',
      'Satuan ditulis lurus dengan satuan, puluhan lurus dengan puluhan.',
      '',
      '**Contoh 1: 25 + 13**',
      susun('25', '+', '13', '38'),
      '• Satuan: 5 + 3 = 8',
      '• Puluhan: 2 + 1 = 3',
      '• Hasilnya **38**',
      '',
      '**Contoh 2 (dengan menyimpan): 27 + 15**',
      susun('27', '+', '15', '42', '1\\;\\;'),
      '• Satuan: 7 + 5 = 12. Tulis **2**, simpan **1** ke puluhan.',
      '• Puluhan: 2 + 1 + 1 (simpanan) = 4',
      '• Hasilnya **42**',
      '',
      '> Selalu mulai menghitung dari **satuan** (paling kanan).',
    ].join('\n'),
    quiz: [
      ['34 + 25 = …', ['59', '69', '58'], 0, 'Satuan 4 + 5 = 9, puluhan 3 + 2 = 5. Hasilnya 59.'],
      ['46 + 18 = …', ['54', '64', '514'], 1, 'Satuan 6 + 8 = 14, tulis 4 simpan 1. Puluhan 4 + 1 + 1 = 6. Hasilnya 64.'],
      ['Pada penjumlahan bersusun, kita mulai menghitung dari …', ['Puluhan', 'Satuan', 'Bebas'], 1, 'Mulai dari satuan (paling kanan).'],
      ['Ani punya 23 kelereng. Ia diberi 19 kelereng lagi. Berapa kelereng Ani sekarang?', ['32', '42', '41'], 1, '23 + 19 = 42.'],
    ],
  },
  {
    slug: 'mtk-pengurangan-bersusun',
    theme: 'Matematika: Operasi Hitung',
    emoji: '➖',
    title: 'Pengurangan Bersusun',
    titleId: 'Mengurangkan bilangan dua angka',
    minutes: 6,
    intro: [
      'Pengurangan juga bisa ditulis **bersusun ke bawah**. Bilangan yang lebih besar ditulis di atas.',
      '',
      '**Contoh 1: 48 − 23**',
      susun('48', '-', '23', '25'),
      '• Satuan: 8 − 3 = 5',
      '• Puluhan: 4 − 2 = 2',
      '• Hasilnya **25**',
      '',
      '**Contoh 2 (dengan meminjam): 52 − 17**',
      susun('52', '-', '17', '35'),
      '• Satuan: 2 − 7 tidak bisa. **Pinjam 1 puluhan** dari 5, sehingga 2 menjadi 12.',
      '• 12 − 7 = 5',
      '• Puluhan: 5 sudah dipinjam 1 menjadi 4. Lalu 4 − 1 = 3',
      '• Hasilnya **35**',
      '',
      '> Cek jawabanmu: 35 + 17 = 52. Benar!',
    ].join('\n'),
    quiz: [
      ['67 − 25 = …', ['42', '32', '92'], 0, 'Satuan 7 − 5 = 2, puluhan 6 − 2 = 4. Hasilnya 42.'],
      ['43 − 18 = …', ['35', '25', '21'], 1, 'Pinjam 1 puluhan: 13 − 8 = 5, puluhan 3 − 1 = 2. Hasilnya 25.'],
      ['Untuk mengecek 50 − 20 = 30, kita bisa menghitung …', ['30 + 20', '30 − 20', '50 + 30'], 0, '30 + 20 = 50, jadi jawabannya benar.'],
      ['Budi punya 35 permen. Ia memberikan 12 permen kepada adiknya. Sisa permen Budi …', ['47', '23', '13'], 1, '35 − 12 = 23.'],
    ],
  },
  {
    slug: 'mtk-perkalian-penjumlahan-berulang',
    theme: 'Matematika: Operasi Hitung',
    emoji: '✖️',
    title: 'Perkalian sebagai Penjumlahan Berulang',
    titleId: 'Mengenal perkalian',
    minutes: 5,
    intro: [
      'Perkalian adalah **penjumlahan berulang** dari bilangan yang sama.',
      '',
      '**Contoh:** Ada 3 piring. Setiap piring berisi 4 kue. 🍪',
      '$$4 + 4 + 4 = 12$$',
      'Bilangan 4 dijumlahkan sebanyak 3 kali. Dapat ditulis:',
      '$$3 \\times 4 = 12$$',
      'Dibaca: **tiga kali empat sama dengan dua belas**.',
      '',
      '**Contoh lain:**',
      '• $2 \\times 5 = 5 + 5 = 10$',
      '• $4 \\times 3 = 3 + 3 + 3 + 3 = 12$',
      '• $5 \\times 2 = 2 + 2 + 2 + 2 + 2 = 10$',
      '',
      '> Perhatikan: $3 \\times 4$ dan $4 \\times 3$ hasilnya sama, yaitu 12.',
    ].join('\n'),
    quiz: [
      ['5 + 5 + 5 sama dengan …', ['3 × 5', '5 × 5', '3 + 5'], 0, 'Bilangan 5 dijumlahkan 3 kali, jadi 3 × 5.'],
      ['2 × 6 = …', ['8', '12', '26'], 1, '6 + 6 = 12.'],
      ['Ada 4 kandang, setiap kandang berisi 2 ayam. Jumlah ayam seluruhnya …', ['6', '8', '42'], 1, '4 × 2 = 2 + 2 + 2 + 2 = 8.'],
    ],
  },
  {
    slug: 'mtk-membaca-jam',
    theme: 'Matematika: Pengukuran',
    emoji: '🕐',
    title: 'Membaca Jam',
    titleId: 'Jam tepat dan jam setengah',
    minutes: 5,
    intro: [
      'Jam dinding memiliki dua jarum:',
      '• **Jarum pendek** menunjukkan **jam**.',
      '• **Jarum panjang** menunjukkan **menit**.',
      '',
      '**Jam tepat** 🕖',
      'Jika jarum panjang menunjuk angka **12** dan jarum pendek menunjuk angka **7**, maka waktunya **pukul 7 tepat** (ditulis 07.00).',
      '',
      '**Jam setengah** 🕢',
      'Jika jarum panjang menunjuk angka **6**, artinya sudah lewat 30 menit.',
      'Jarum pendek berada di antara angka 7 dan 8. Waktunya **pukul setengah delapan** (ditulis 07.30).',
      '',
      '> Ingat: 1 jam = 60 menit. Setengah jam = 30 menit.',
    ].join('\n'),
    quiz: [
      ['Jarum pendek pada jam menunjukkan …', ['Menit', 'Jam', 'Detik'], 1, 'Jarum pendek menunjukkan jam.'],
      ['Jarum panjang di angka 12 dan jarum pendek di angka 9. Pukul berapa?', ['Pukul 12.00', 'Pukul 09.00', 'Pukul 09.30'], 1, 'Jarum panjang di 12 berarti jam tepat; jarum pendek di 9 → pukul 9 tepat.'],
      ['Pukul 07.30 dibaca …', ['Setengah tujuh', 'Setengah delapan', 'Tujuh tepat'], 1, '07.30 = 30 menit setelah pukul 7, yaitu setengah delapan.'],
      ['1 jam sama dengan … menit.', ['30', '60', '100'], 1, '1 jam = 60 menit.'],
    ],
  },
  {
    slug: 'mtk-mengenal-uang',
    theme: 'Matematika: Pengukuran',
    emoji: '💰',
    title: 'Mengenal Uang Rupiah',
    titleId: 'Koin, uang kertas, dan berbelanja',
    minutes: 5,
    intro: [
      'Mata uang Indonesia adalah **Rupiah**, disingkat **Rp**.',
      '',
      '**Uang logam (koin):** Rp100, Rp200, Rp500, Rp1.000',
      '**Uang kertas:** Rp1.000, Rp2.000, Rp5.000, Rp10.000, Rp20.000, Rp50.000, Rp100.000',
      '',
      '**Contoh menjumlahkan uang:**',
      'Rp2.000 + Rp5.000 = **Rp7.000**',
      '',
      '**Contoh berbelanja:**',
      'Sari membeli roti seharga Rp3.000. Ia membayar dengan uang Rp5.000.',
      'Uang kembaliannya: Rp5.000 − Rp3.000 = **Rp2.000**',
      '',
      '> Gunakan uang dengan bijak dan sisihkan untuk menabung! 🐷',
    ].join('\n'),
    quiz: [
      ['Mata uang Indonesia adalah …', ['Dolar', 'Rupiah', 'Ringgit'], 1, 'Mata uang Indonesia adalah Rupiah (Rp).'],
      ['Rp5.000 + Rp5.000 = …', ['Rp10.000', 'Rp15.000', 'Rp5.500'], 0, '5.000 + 5.000 = 10.000.'],
      ['Harga pensil Rp2.000. Kamu membayar Rp5.000. Kembaliannya …', ['Rp2.000', 'Rp3.000', 'Rp7.000'], 1, 'Rp5.000 − Rp2.000 = Rp3.000.'],
    ],
  },
  {
    slug: 'mtk-bangun-datar',
    theme: 'Matematika: Geometri',
    emoji: '🔷',
    title: 'Mengenal Bangun Datar',
    titleId: 'Segitiga, persegi, persegi panjang, lingkaran',
    minutes: 5,
    intro: [
      'Bangun datar adalah bentuk yang rata, seperti gambar di atas kertas.',
      '',
      '🔺 **Segitiga** — memiliki **3 sisi** dan **3 sudut**. Contoh: potongan semangka, rambu lalu lintas.',
      '',
      '🟥 **Persegi** — memiliki **4 sisi yang sama panjang** dan 4 sudut. Contoh: papan catur, ubin lantai.',
      '',
      '▭ **Persegi panjang** — memiliki **4 sisi**, dua sisi panjang dan dua sisi pendek. Contoh: pintu, buku, papan tulis.',
      '',
      '⚪ **Lingkaran** — **tidak memiliki sudut**, bentuknya bulat. Contoh: jam dinding, roda, piring.',
      '',
      '> Coba cari benda berbentuk bangun datar di rumahmu!',
    ].join('\n'),
    quiz: [
      ['Bangun datar yang memiliki 3 sisi adalah …', ['Persegi', 'Segitiga', 'Lingkaran'], 1, 'Segitiga memiliki 3 sisi.'],
      ['Bangun datar yang tidak memiliki sudut adalah …', ['Lingkaran', 'Persegi panjang', 'Segitiga'], 0, 'Lingkaran tidak memiliki sudut.'],
      ['Persegi memiliki … sisi yang sama panjang.', ['3', '4', '5'], 1, 'Keempat sisi persegi sama panjang.'],
      ['Pintu rumah biasanya berbentuk …', ['Lingkaran', 'Segitiga', 'Persegi panjang'], 2, 'Pintu memiliki dua sisi panjang dan dua sisi pendek.'],
    ],
  },
];
