// Surat Pendek Juz 30 — Bagian 2: Surat 91 s.d. 104.
// Teks Arab berharakat standar Mushaf Kemenag RI, transliterasi Latin, dan terjemahan resmi Kemenag RI.

import type { SeedLesson } from './types';
import { BASMALAH } from './surat-pendek-105-114';

export const suratPendek91to104: SeedLesson[] = [
  {
    slug: 'surat-asy-syams',
    theme: 'Surat Pendek',
    emoji: '☀️',
    title: 'Surat Asy-Syams',
    titleId: 'Matahari · 15 ayat',
    minutes: 4,
    intro:
      "**Surat ke-91** · **15 ayat** · Makkiyah.\n\n" +
      "Asy-Syams artinya **matahari**. Dimulai dengan sumpah Allah atas ciptaan-Nya yang agung. Mengajarkan bahwa sungguh beruntung orang yang menyucikan jiwanya, dan merugi orang yang mengotorinya, sebagaimana kaum Tsamud yang dibinasakan karena mendustakan Nabi Saleh.",
    lines: [
      BASMALAH,
      ['وَالشَّمْسِ وَضُحٰىهَا', 'Wasy syamsi wa dhuhaahaa', 'Demi matahari dan sinarnya pada pagi hari,', 1],
      ['وَالْقَمَرِ اِذَا تَلٰىهَا', 'Wal qamari idzaa talaahaa', 'demi bulan apabila mengiringinya,', 2],
      ['وَالنَّهَارِ اِذَا جَلّٰىهَا', 'Wan nahaari idzaa jallaahaa', 'demi siang apabila menampakkannya,', 3],
      ['وَالَّيْلِ اِذَا يَغْشٰىهَا', 'Wal laili idzaa yaghsyaahaa', 'demi malam apabila menutupinya (gelap gulita),', 4],
      ['وَالسَّمَاءِ وَمَا بَنٰىهَا', 'Was samaa-i wa maa banaahaa', 'demi langit serta pembuatannya,', 5],
      ['وَالْاَرْضِ وَمَا طَحٰىهَا', 'Wal ardhi wa maa thahaahaa', 'demi bumi serta penghamparannya,', 6],
      ['وَنَفْسٍ وَّمَا سَوّٰىهَا', 'Wa nafsiw wa maa sawwaahaa', 'demi jiwa serta penyempurnaan (ciptaan)nya,', 7],
      ['فَاَلْهَمَهَا فُجُوْرَهَا وَتَقْوٰىهَا', 'Fa alhamahaa fujuurahaa wa taqwaahaa', 'maka Dia mengilhamkan kepadanya (jalan) kejahatan dan ketakwaannya,', 8],
      ['قَدْ اَفْلَحَ مَنْ زَكّٰىهَا', 'Qad aflaha man zakkaahaa', 'sungguh beruntung orang yang menyucikannya (jiwa itu),', 9],
      ['وَقَدْ خَابَ مَنْ دَسّٰىهَا', 'Wa qad khaaba man dassaahaa', 'dan sungguh rugi orang yang mengotorinya.', 10],
      ['كَذَّبَتْ ثَمُوْدُ بِطَغْوٰىهَا', 'Kadz-dzabat tsamuudu bithaghwaahaa', '(Kaum) Tsamud telah mendustakan (rasulnya) karena mereka melampaui batas,', 11],
      ['اِذِ انْۢبَعَثَ اَشْقٰىهَا', "Idzimba'atsa asyqaahaa", 'ketika bangkit orang yang paling celaka di antara mereka,', 12],
      ['فَقَالَ لَهُمْ رَسُوْلُ اللّٰهِ نَاقَةَ اللّٰهِ وَسُقْيٰهَا', 'Fa qaala lahum rasuulullaahi naaqatallaahi wa suqyaahaa', 'lalu Rasul Allah (Saleh) berkata kepada mereka, "(Biarkanlah) unta betina Allah ini beserta minumannya."', 13],
      ['فَكَذَّبُوْهُ فَعَقَرُوْهَا دَمْدَمَ عَلَيْهِمْ رَبُّهُمْ بِذَنْۢبِهِمْ فَسَوّٰىهَا', "Fa kadz-dzabuuhu fa 'aqaruuhaa fa damdama 'alaihim rabbuhum bidzambihim fa sawwaahaa", 'Namun mereka mendustakannya dan menyembelih unta itu, maka Tuhan membinasakan mereka karena dosa-dosanya, lalu meratakan mereka (dengan tanah),', 14],
      ['وَلَا يَخَافُ عُقْبٰهَا', "Wa laa yakhaafu 'uqbaahaa", 'dan Dia tidak takut terhadap akibatnya.', 15],
    ],
    quiz: [
      ['Asy-Syams artinya …', ['Bulan', 'Matahari', 'Bintang'], 1, 'Asy-Syams = matahari.'],
      ['Menurut ayat ke-9, orang yang beruntung adalah orang yang …', ['Memiliki banyak harta', 'Menyucikan jiwanya', 'Menyembelih unta'], 1, 'Qad aflaha man zakkaahaa = beruntung orang yang menyucikan jiwanya.'],
      ['Kaum yang diazab karena menyembelih unta Nabi Saleh dalam surat ini adalah …', ['Kaum Tsamud', "Kaum 'Ad", 'Kaum Quraisy'], 0, 'Kadz-dzabat tsamuudu bithaghwaahaa = kaum Tsamud.'],
    ],
  },
  {
    slug: 'surat-al-lail',
    theme: 'Surat Pendek',
    emoji: '🌌',
    title: 'Surat Al-Lail',
    titleId: 'Malam · 21 ayat',
    minutes: 4,
    intro:
      "**Surat ke-92** · **21 ayat** · Makkiyah.\n\n" +
      "Al-Lail artinya **malam**. Menjelaskan dua jalan manusia: orang yang dermawan, bertakwa, dan membenarkan kebaikan akan dimudahkan ke jalan kebahagiaan (surga); sedangkan orang yang kikir dan merasa serba cukup akan dimudahkan ke jalan kesengsaraan.",
    lines: [
      BASMALAH,
      ['وَالَّيْلِ اِذَا يَغْشٰى', 'Wal laili idzaa yaghsyaa', 'Demi malam apabila menutupi (cahaya siang),', 1],
      ['وَالنَّهَارِ اِذَا تَجَلّٰى', 'Wan nahaari idzaa tajallaa', 'demi siang apabila terang benderang,', 2],
      ['وَمَا خَلَقَ الذَّكَرَ وَالْاُنْثٰى', 'Wa maa khalaqadz dzakara wal untsaa', 'demi penciptaan laki-laki dan perempuan,', 3],
      ['اِنَّ سَعْيَكُمْ لَشَتّٰى', "Inna sa'yakum lasyattaa", 'sungguh, usahamu memang beraneka ragam.', 4],
      ['فَاَمَّا مَنْ اَعْطٰى وَاتَّقٰى', "Fa ammaa man a'thaa wattaqaa", 'Maka barangsiapa memberikan (hartanya di jalan Allah) dan bertakwa,', 5],
      ['وَصَدَّقَ بِالْحُسْنٰى', 'Wa shaddaqa bil husnaa', 'dan membenarkan adanya (pahala) yang terbaik (surga),', 6],
      ['فَسَنُيَسِّرُهٗ لِلْيُسْرٰى', 'Fa sanuyassiruhuu lil yusraa', 'maka Kami akan memudahkan baginya jalan kemudahan.', 7],
      ['وَاَمَّا مَنْۢ بَخِلَ وَاسْتَغْنٰى', 'Wa ammaa mam bakhila wastaghnaa', 'Dan adapun orang yang kikir dan merasa dirinya cukup,', 8],
      ['وَكَذَّبَ بِالْحُسْنٰى', 'Wa kadz-dzaba bil husnaa', 'serta mendustakan (pahala) yang terbaik,', 9],
      ['فَسَنُيَسِّرُهٗ لِلْعُسْرٰى', "Fa sanuyassiruhuu lil 'usraa", 'maka Kami akan memudahkan baginya jalan kesukaran.', 10],
      ['وَمَا يُغْنِيْ عَنْهُ مَالُهٗٓ اِذَا تَرَدّٰى', 'Wa maa yughnii \'anhu maaluhuu idzaa taraddaa', 'Dan hartanya tidak bermanfaat baginya apabila dia telah binasa.', 11],
      ['اِنَّ عَلَيْنَا لَلْهُدٰى', "Inna 'alainaa lal hudaa", 'Sesungguhnya kewajiban Kamilah memberi petunjuk,', 12],
      ['وَاِنَّ لَنَا لَلْاٰخِرَةَ وَالْاُوْلٰى', 'Wa inna lanaa lal aakhirata wal uulaa', 'dan sesungguhnya milik Kamilah akhirat dan dunia.', 13],
      ['فَاَنْذَرْتُكُمْ نَارًا تَلَظّٰى', 'Fa andzartukum naaran talazh-zhaa', 'Maka Aku memperingatkan kamu dengan neraka yang menyala-nyala,', 14],
      ['لَا يَصْلٰىهَآ اِلَّا الْاَشْقَى', 'Laa yashlaahaa illal asyqaa', 'yang tidak dimasuki kecuali oleh orang yang paling celaka,', 15],
      ['الَّذِيْ كَذَّبَ وَتَوَلّٰى', 'Alladzii kadz-dzaba wa tawallaa', 'yang mendustakan (kebenaran) dan berpaling (dari iman).', 16],
      ['وَسَيُجَنَّبُهَا الْاَتْقَى', 'Wa sayujannabuhal atqaa', 'Dan kelak akan dijauhkan darinya (neraka) orang yang paling bertakwa,', 17],
      ['الَّذِيْ يُؤْتِيْ مَالَهٗ يَتَزَكّٰى', "Alladzii yu'tii maalahuu yatazakkaa", 'yang menginfakkan hartanya (di jalan Allah) untuk membersihkan (dirinya),', 18],
      ['وَمَا لِاَحَدٍ عِنْدَهٗ مِنْ نِّعْمَةٍ تُجْزٰى', 'Wa maa li-ahadin \'indahuu min ni\'matin tujzaa', 'dan tidak ada suatu nikmat pun pada orang lain yang harus dibalasnya,', 19],
      ['اِلَّا ابْتِغَاۤءَ وَجْهِ رَبِّهِ الْاَعْلٰى', "Illabtighaa-a wajhi rabbihil a'laa", 'tetapi (dia berinfak semata-mata) karena mencari keridaan Tuhannya Yang Mahatinggi.', 20],
      ['وَلَسَوْفَ يَرْضٰى', 'Wa lasaufa yardhaa', 'Dan niscaya kelak dia akan mendapat kepuasan (pahala).', 21],
    ],
    quiz: [
      ['Al-Lail artinya …', ['Malam', 'Siang', 'Fajar'], 0, 'Al-Lail = malam.'],
      ['Orang yang dermawan dan bertakwa akan dimudahkan ke jalan …', ['Kemudahan (kebahagiaan)', 'Kesukaran', 'Kegelapan'], 0, 'Fa sanuyassiruhuu lil yusraa = dimudahkan ke jalan kemudahan.'],
      ['Orang yang paling bertakwa berinfak semata-mata mengharap …', ['Pujian manusia', 'Keridaan Allah Yang Maha Tinggi', 'Balasan hadiah'], 1, 'Illabtighaa-a wajhi rabbihil a\'laa.'],
    ],
  },
  {
    slug: 'surat-ad-duha',
    theme: 'Surat Pendek',
    emoji: '🌅',
    title: 'Surat Ad-Duha',
    titleId: 'Waktu Dhuha · 11 ayat',
    minutes: 3,
    intro:
      "**Surat ke-93** · **11 ayat** · Makkiyah.\n\n" +
      "Ad-Duha artinya **waktu duha (pagi hari)**. Diturunkan sebagai penghibur ketika wahyu sempat terhenti. Allah menegaskan bahwa Dia tidak pernah meninggalkan Nabi Muhammad ﷺ, dan memerintahkan menyayangi anak yatim, tidak menghardik orang yang meminta-minta, serta mensyukuri nikmat Tuhan.",
    lines: [
      BASMALAH,
      ['وَالضُّحٰى', 'Wad dhuhaa', 'Demi waktu duha (ketika matahari naik sepenggalah),', 1],
      ['وَالَّيْلِ اِذَا سَجٰى', 'Wal laili idzaa sajaa', 'dan demi malam apabila telah sunyi,', 2],
      ['مَا وَدَّعَكَ رَبُّكَ وَمَا قَلٰى', "Maa wadda'aka rabbuka wa maa qalaa", 'Tuhanmu tidak meninggalkan engkau (Muhammad) dan tidak (pula) membencimu,', 3],
      ['وَلَلْاٰخِرَةُ خَيْرٌ لَّكَ مِنَ الْاُوْلٰى', 'Wa lal-aakhiratu khairul laka minal uulaa', 'dan sungguh, yang kemudian (akhirat) itu lebih baik bagimu daripada yang permulaan (dunia).', 4],
      ['وَلَسَوْفَ يُعْطِيْكَ رَبُّكَ فَتَرْضٰى', "Wa lasaufa yu'thiika rabbuka fa tardhaa", 'Dan sungguh, kelak Tuhanmu pasti memberikan karunia-Nya kepadamu, sehingga engkau menjadi puas.', 5],
      ['اَلَمْ يَجِدْكَ يَتِيْمًا فَاٰوٰى', 'A lam yajidka yatiiman fa aawaa', 'Bukankah Dia mendapatimu sebagai seorang yatim, lalu Dia melindungi(mu),', 6],
      ['وَوَجَدَكَ ضَاۤلًّا فَهَدٰى', 'Wa wajadaka dhaallan fa hadaa', 'dan Dia mendapatimu sebagai seorang yang bingung, lalu Dia memberikan petunjuk,', 7],
      ['وَوَجَدَكَ عَاۤىِٕلًا فَاَغْنٰى', "Wa wajadaka 'aa-ilan fa aghnaa", 'dan Dia mendapatimu sebagai seorang yang kekurangan, lalu Dia memberikan kecukupan?', 8],
      ['فَاَمَّا الْيَتِيْمَ فَلَا تَقْهَرْ', 'Fa ammal yatiima falaa taqhar', 'Maka terhadap anak yatim janganlah engkau berlaku sewenang-wenang.', 9],
      ['وَاَمَّا السَّاۤىِٕلَ فَلَا تَنْهَرْ', 'Wa ammas saa-ila falaa tanhar', 'Dan terhadap orang yang meminta-minta janganlah engkau menghardik(nya).', 10],
      ['وَاَمَّا بِنِعْمَةِ رَبِّكَ فَحَدِّثْ', "Wa ammaa bini'mati rabbika fahaddits", 'Dan terhadap nikmat Tuhanmu hendaklah engkau nyatakan (dengan bersyukur).', 11],
    ],
    quiz: [
      ['Ad-Duha artinya …', ['Waktu duha (pagi hari)', 'Waktu maghrib', 'Tengah malam'], 0, 'Ad-Duha = waktu pagi hari ketika matahari mulai naik.'],
      ['Sikap kita terhadap anak yatim menurut surat ini adalah …', ['Boleh membentaknya', 'Jangan berlaku sewenang-wenang', 'Mengabaikannya'], 1, 'Fa ammal yatiima falaa taqhar = jangan sewenang-wenang.'],
      ['Terhadap nikmat yang Allah berikan, kita diperintahkan untuk …', ['Menyembunyikannya', 'Menyatakan dan mensyukurinya', 'Mengeluh'], 1, 'Fahaddits = nyatakanlah dengan bersyukur.'],
    ],
  },
  {
    slug: 'surat-asy-syarh',
    theme: 'Surat Pendek',
    emoji: '🌸',
    title: 'Surat Asy-Syarh',
    titleId: 'Melapangkan · 8 ayat',
    minutes: 3,
    intro:
      "**Surat ke-94** · **8 ayat** · Makkiyah. Dikenal juga sebagai **Surat Al-Insyirah**.\n\n" +
      "Asy-Syarh artinya **kelapangan**. Menegaskan bahwa di balik setiap kesulitan pasti ada kemudahan yang menyertainya. Allah memerintahkan agar setelah menyelesaikan suatu urusan, kita tetap bersungguh-sungguh beribadah dan hanya berharap kepada Allah.",
    lines: [
      BASMALAH,
      ['اَلَمْ نَشْرَحْ لَكَ صَدْرَكَ', 'A lam nasyrah laka shadrak', 'Bukankah Kami telah melapangkan dadamu (Muhammad)?', 1],
      ['وَوَضَعْنَا عَنْكَ وِزْرَكَ', "Wa wadha'naa 'anka wizrak", 'dan Kami pun telah menurunkan bebanmu darimu,', 2],
      ['الَّذِيْٓ اَنْقَضَ ظَهْرَكَ', 'Alladzii anqadha zhahrak', 'yang memberatkan punggungmu,', 3],
      ['وَرَفَعْنَا لَكَ ذِكْرَكَ', 'Wa rafa\'naa laka dzikrak', 'dan Kami tinggikan sebutan (nama)mu bagimu.', 4],
      ['فَاِنَّ مَعَ الْعُسْرِ يُسْرًا', "Fa inna ma'al 'usri yusraa", 'Maka sesungguhnya bersama kesulitan ada kemudahan,', 5],
      ['اِنَّ مَعَ الْعُسْرِ يُسْرًا', "Inna ma'al 'usri yusraa", 'sesungguhnya bersama kesulitan ada kemudahan.', 6],
      ['فَاِذَا فَرَغْتَ فَانْصَبْ', 'Fa idzaa faraghta fanshab', 'Maka apabila engkau telah selesai (dari suatu urusan), tetaplah bekerja keras (untuk urusan yang lain),', 7],
      ['وَاِلٰى رَبِّكَ فَارْغَبْ', 'Wa ilaa rabbika farghab', 'dan hanya kepada Tuhanmulah engkau berharap.', 8],
    ],
    quiz: [
      ['Surat Asy-Syarh juga dikenal dengan nama Surat …', ['Al-Insyirah', 'At-Tin', 'Al-Alaq'], 0, 'Asy-Syarh sering disebut Al-Insyirah.'],
      ['Kabar gembira yang diulang dua kali dalam surat ini adalah …', ['Kekayaan melimpah', 'Bersama kesulitan pasti ada kemudahan', 'Kemenangan perang'], 1, 'Inna ma\'al \'usri yusraa = bersama kesulitan ada kemudahan.'],
      ['Hanya kepada siapakah kita hendaknya menggantungkan harapan?', ['Manusia', 'Hanya kepada Allah Swt.', 'Teman dekat'], 1, 'Wa ilaa rabbika farghab = hanya kepada Tuhanmu engkau berharap.'],
    ],
  },
  {
    slug: 'surat-at-tin',
    theme: 'Surat Pendek',
    emoji: '🌿',
    title: 'Surat At-Tin',
    titleId: 'Buah Tin · 8 ayat',
    minutes: 3,
    intro:
      "**Surat ke-95** · **8 ayat** · Makkiyah.\n\n" +
      "At-Tin artinya **buah tin**. Allah bersumpah demi buah Tin, Zaitun, Bukit Sinai, dan Kota Makkah yang aman. Menegaskan bahwa manusia diciptakan dalam bentuk yang sebaik-baiknya, namun bisa jatuh ke derajat paling rendah kecuali orang yang beriman dan beramal saleh.",
    lines: [
      BASMALAH,
      ['وَالتِّيْنِ وَالزَّيْتُوْنِ', 'Wat tiini waz zaituun', 'Demi (buah) Tin dan (buah) Zaitun,', 1],
      ['وَطُوْرِ سِيْنِيْنَ', 'Wa thuuri siiniin', 'demi gunung Sinai,', 2],
      ['وَهٰذَا الْبَلَدِ الْاَمِيْنِ', 'Wa haadzal baladil amiin', 'dan demi negeri (Makkah) yang aman ini.', 3],
      ['لَقَدْ خَلَقْنَا الْاِنْسَانَ فِيْٓ اَحْسَنِ تَقْوِيْمٍ', 'Laqad khalaqnal insaana fii ahsani taqwiim', 'Sungguh, Kami telah menciptakan manusia dalam bentuk yang sebaik-baiknya,', 4],
      ['ثُمَّ رَدَدْنٰهُ اَسْفَلَ سٰفِلِيْنَ', 'Tsumma radadnaahu asfala saafiliin', 'kemudian Kami kembalikan dia ke tempat yang serendah-rendahnya,', 5],
      ['اِلَّا الَّذِيْنَ اٰمَنُوْا وَعَمِلُوا الصّٰلِحٰتِ فَلَهُمْ اَجْرٌ غَيْرُ مَمْنُوْنٍ', "Illal ladziina aamanuu wa 'amilush shaalihaati fa lahum ajrun ghairu mamnuun", 'kecuali orang-orang yang beriman dan mengerjakan kebajikan; maka mereka akan mendapat pahala yang tidak putus-putusnya.', 6],
      ['فَمَا يُكَذِّبُكَ بَعْدُ بِالدِّيْنِ', "Fa maa yukadz-dzibuka ba'du bid-diin", 'Maka apa yang menyebabkan mereka mendustakanmu tentang hari pembalasan setelah (adanya bukti-bukti) itu?', 7],
      ['اَلَيْسَ اللّٰهُ بِاَحْكَمِ الْحٰكِمِيْنَ', 'A laisallaahu bi-ahkamil haakimiin', 'Bukankah Allah hakim yang paling adil?', 8],
    ],
    quiz: [
      ['At-Tin artinya …', ['Buah kurma', 'Buah tin', 'Buah anggur'], 1, 'At-Tin = buah tin.'],
      ['Manusia diciptakan oleh Allah dalam bentuk …', ['Sebaik-baiknya (ahsani taqwiim)', 'Paling buruk', 'Biasa saja'], 0, 'Laqad khalaqnal insaana fii ahsani taqwiim.'],
      ['Siapakah yang tidak dikembalikan ke derajat yang paling rendah?', ['Orang kaya', 'Orang yang beriman dan beramal saleh', 'Orang yang berbadan kuat'], 1, 'Kecuali orang yang beriman dan beramal kebajikan.'],
    ],
  },
  {
    slug: 'surat-al-alaq',
    theme: 'Surat Pendek',
    emoji: '📖',
    title: "Surat Al-'Alaq",
    titleId: 'Segumpal Darah · 19 ayat',
    minutes: 4,
    intro:
      "**Surat ke-96** · **19 ayat** · Makkiyah.\n\n" +
      "Ayat 1–5 surat ini adalah **wahyu Al-Qur'an pertama** yang turun kepada Nabi Muhammad ﷺ di Gua Hira melalui Malaikat Jibril. Memerintahkan umat manusia untuk membaca dan menuntut ilmu dengan nama Allah Yang Maha Pemurah.",
    lines: [
      BASMALAH,
      ['اِقْرَأْ بِاسْمِ رَبِّكَ الَّذِيْ خَلَقَ', 'Iqra\' bismi rabbikal ladzii khalaq', 'Bacalah dengan (menyebut) nama Tuhanmu yang menciptakan,', 1],
      ['خَلَقَ الْاِنْسَانَ مِنْ عَلَقٍ', "Khalaqal insaana min 'alaq", 'Dia telah menciptakan manusia dari segumpal darah.', 2],
      ['اِقْرَأْ وَرَبُّكَ الْاَكْرَمُ', 'Iqra\' wa rabbukal akram', 'Bacalah, dan Tuhanmulah Yang Mahamulia,', 3],
      ['الَّذِيْ عَلَّمَ بِالْقَلَمِ', "Alladzii 'allama bil qalam", 'yang mengajar (manusia) dengan pena.', 4],
      ['عَلَّمَ الْاِنْسَانَ مَا لَمْ يَعْلَمْ', "'Allamal insaana maa lam ya'lam", 'Dia mengajarkan manusia apa yang tidak diketahuinya.', 5],
      ['كَلَّآ اِنَّ الْاِنْسَانَ لَيَطْغٰى', 'Kallaa innal insaana layath-ghaa', 'Sekali-kali tidak! Sungguh, manusia itu benar-benar melampaui batas,', 6],
      ['اَنْ رَّاٰهُ اسْتَغْنٰى', "Ar ra-aahustaghnaa", 'apabila melihat dirinya serbacukup.', 7],
      ['اِنَّ اِلٰى رَبِّكَ الرُّجْعٰى', 'Inna ilaa rabbikar ruj\'aa', 'Sungguh, hanya kepada Tuhanmulah tempat kembali(mu).', 8],
      ['اَرَءَيْتَ الَّذِيْ يَنْهٰى', "A ra-aital ladzii yan-haa", 'Tahukah kamu orang yang melarang,', 9],
      ['عَبْدًا اِذَا صَلّٰى', "'Abdan idzaa shallaa", 'seorang hamba ketika dia melaksanakan salat?', 10],
      ['اَرَءَيْتَ اِنْ كَانَ عَلَى الْهُدٰى', "A ra-aita in kaana 'alal hudaa", 'Tahukah kamu jika dia (yang dilarang salat itu) berada di atas kebenaran,', 11],
      ['اَوْ اَمَرَ بِالتَّقْوٰى', "Au amara bit taqwaa", 'atau dia menyuruh bertakwa (kepada Allah)?', 12],
      ['اَرَءَيْتَ اِنْ كَذَّبَ وَتَوَلّٰى', 'A ra-aita in kadz-dzaba wa tawallaa', 'Tahukah kamu jika dia (yang melarang itu) mendustakan dan berpaling?', 13],
      ['اَلَمْ يَعْلَمْ بِاَنَّ اللّٰهَ يَرٰى', "A lam ya'lam bi-annallaaha yaraa", 'Tidakkah dia mengetahui bahwa sesungguhnya Allah melihat (segala perbuatannya)?', 14],
      ['كَلَّا لَىِٕنْ لَّمْ يَنْتَهِ لَنَسْفَعًا بِالنَّاصِيَةِ', "Kallaa la-il lam yantahi lanasfa'am bin naashiyah", 'Sekali-kali tidak! Sungguh, jika dia tidak berhenti (berbuat demikian), niscaya Kami tarik ubun-ubunnya (ke neraka),', 15],
      ['نَاصِيَةٍ كَاذِبَةٍ خَاطِئَةٍ', "Naashiyatin kaadzibatin khaathi-ah", '(yaitu) ubun-ubun orang yang mendustakan dan durhaka.', 16],
      ['فَلْيَدْعُ نَادِيَهٗ', "Falyad'u naadiyah", 'Maka biarlah dia memanggil golongannya (untuk menolongnya),', 17],
      ['سَنَدْعُ الزَّبَانِيَةَ', "Sanad'uz zabaaniyah", 'Kelak Kami akan memanggil malaikat Zabaniyah (penyiksa),', 18],
      ['كَلَّا لَا تُطِعْهُ وَاسْجُدْ وَاقْتَرِبْ', "Kallaa laa tuthi'hu wasjud waqtarib", 'Sekali-kali tidak! Janganlah kamu patuh kepadanya; sujudlah dan dekatkanlah (dirimu kepada Allah).', 19],
    ],
    quiz: [
      ["Al-'Alaq artinya …", ['Segumpal darah', 'Segumpal daging', 'Segumpal tanah'], 0, "Al-'Alaq = segumpal darah."],
      ['Ayat 1–5 surat Al-Alaq adalah wahyu yang pertama kali turun di …', ['Masjid Nabawi', 'Gua Hira', 'Padang Arafah'], 1, 'Wahyu pertama turun kepada Nabi Muhammad ﷺ di Gua Hira.'],
      ['Kata pertama dalam wahyu pertama adalah "Iqra\'" yang artinya …', ['Tuliskanlah', 'Bacalah', 'Dengarkanlah'], 1, "Iqra' = bacalah."],
    ],
  },
  {
    slug: 'surat-al-qadr',
    theme: 'Surat Pendek',
    emoji: '⭐',
    title: 'Surat Al-Qadr',
    titleId: 'Kemuliaan · 5 ayat',
    minutes: 3,
    intro:
      "**Surat ke-97** · **5 ayat** · Makkiyah.\n\n" +
      "Al-Qadr artinya **kemuliaan**. Menceritakan malam Lailatul Qadar di bulan Ramadan saat Al-Qur'an pertama kali diturunkan. Malam kemuliaan ini nilainya lebih baik daripada seribu bulan, di mana para malaikat turun membawa kedamaian hingga terbit fajar.",
    lines: [
      BASMALAH,
      ['اِنَّآ اَنْزَلْنٰهُ فِيْ لَيْلَةِ الْقَدْرِ', 'Innaa anzalnaahu fii lailatil qadr', 'Sesungguhnya Kami telah menurunkannya (Al-Qur\'an) pada malam kemuliaan.', 1],
      ['وَمَآ اَدْرٰىكَ مَا لَيْلَةُ الْقَدْرِ', 'Wa maa adraaka maa lailatul qadr', 'Dan tahukah kamu apakah malam kemuliaan itu?', 2],
      ['لَيْلَةُ الْقَدْرِ خَيْرٌ مِّنْ اَلْفِ شَهْرٍ', 'Lailatul qadri khairum min alfi syahr', 'Malam kemuliaan itu lebih baik daripada seribu bulan.', 3],
      ['تَنَزَّلُ الْمَلٰۤىِٕكَةُ وَالرُّوْحُ فِيْهَا بِاِذْنِ رَبِّهِمْ مِنْ كُلِّ اَمْرٍ', 'Tanazzalul malaa-ikatu war ruuhu fiihaa bi-idzni rabbihim min kulli amr', 'Pada malam itu turun para malaikat dan Rūḥ (Jibril) dengan izin Tuhannya untuk mengatur semua urusan.', 4],
      ['سَلٰمٌ هِيَ حَتّٰى مَطْلَعِ الْفَجْرِ', "Salaamun hiya hattaa mathla'il fajr", 'Sejahteralah (malam itu) sampai terbit fajar.', 5],
    ],
    quiz: [
      ['Al-Qadr artinya …', ['Kekuasaan', 'Kemuliaan', 'Bulan purnama'], 1, 'Al-Qadr = kemuliaan.'],
      ['Malam Lailatul Qadar lebih baik daripada …', ['Seratus hari', 'Seribu bulan', 'Sepuluh tahun'], 1, 'Khairum min alfi syahr = lebih baik dari seribu bulan.'],
      ['Malaikat Ar-Ruuh yang turun pada malam itu adalah Malaikat …', ['Mikail', 'Jibril', 'Israfil'], 1, 'Ar-Ruuh dalam ayat ini adalah Malaikat Jibril.'],
    ],
  },
  {
    slug: 'surat-al-bayyinah',
    theme: 'Surat Pendek',
    emoji: '📜',
    title: 'Surat Al-Bayyinah',
    titleId: 'Bukti Nyata · 8 ayat',
    minutes: 4,
    intro:
      "**Surat ke-98** · **8 ayat** · Madaniyah.\n\n" +
      "Al-Bayyinah artinya **bukti yang nyata**. Menjelaskan kedatangan Nabi Muhammad ﷺ membawa kitab suci yang lurus. Manusia hanya diperintahkan menyembah Allah dengan ikhlas, melaksanakan salat, dan menunaikan zakat.",
    lines: [
      BASMALAH,
      ['لَمْ يَكُنِ الَّذِيْنَ كَفَرُوْا مِنْ اَهْلِ الْكِتٰبِ وَالْمُشْرِكِيْنَ مُنْفَكِّيْنَ حَتّٰى تَأْتِيَهُمُ الْبَيِّنَةُ', 'Lam yakunil ladziina kafaruu min ahlil kitaabi wal musyrikiina munfakkiina hattaa ta\'tiyahumul bayyinah', 'Orang-orang yang kafir dari golongan Ahli Kitab dan orang-orang musyrik tidak akan meninggalkan (agamanya) sampai datang kepada mereka bukti yang nyata,', 1],
      ['رَسُوْلٌ مِّنَ اللّٰهِ يَتْلُوْا صُحُفًا مُّطَهَّرَةً', 'Rasuulum minallaahi yatluu suhufam muthahharah', '(yaitu) seorang Rasul dari Allah (Muhammad) yang membacakan lembaran-lembaran yang disucikan (Al-Qur\'an),', 2],
      ['فِيْهَا كُتُبٌ قَيِّمَةٌ', 'Fiihaa kutubun qayyimah', 'di dalamnya terdapat (isi) kitab-kitab yang lurus (benar).', 3],
      ['وَمَا تَفَرَّقَ الَّذِيْنَ اُوْتُوا الْكِتٰبَ اِلَّا مِنْۢ بَعْدِ مَا جَاۤءَتْهُمُ الْبَيِّنَةُ', "Wa maa tafarraqal ladziina uutul kitaaba illaa mim ba'di maa jaa-at-humul bayyinah", 'Dan tidaklah terpecah-belah orang-orang Ahli Kitab melainkan setelah datang kepada mereka bukti yang nyata.', 4],
      ['وَمَآ اُمِرُوْٓا اِلَّا لِيَعْبُدُوا اللّٰهَ مُخْلِصِيْنَ لَهُ الدِّيْنَ حُنَفَاۤءَ وَيُقِيْمُوا الصَّلٰوةَ وَيُؤْتُوا الزَّكٰوةَ وَذٰلِكَ دِيْنُ الْقَيِّمَةِ', 'Wa maa umiruu illaa liya\'budullaaha mukhlishiina lahud diina hunafaa-a wa yuqiimush shalaata wa yu\'tuz zakaata wa dzaalika diinul qayyimah', 'Padahal mereka hanya diperintahkan menyembah Allah dengan ikhlas menaati-Nya semata-mata karena (menjalankan) agama, dan juga melaksanakan salat dan menunaikan zakat; dan yang demikian itulah agama yang lurus.', 5],
      ['اِنَّ الَّذِيْنَ كَفَرُوْا مِنْ اَهْلِ الْكِتٰبِ وَالْمُشْرِكِيْنَ فِيْ نَارِ جَهَنَّمَ خٰلِدِيْنَ فِيْهَا اُولٰۤىِٕكَ هُمْ شَرُّ الْبَرِيَّةِ', 'Innal ladziina kafaruu min ahlil kitaabi wal musyrikiina fii naari jahannama khaalidiina fiihaa ulaa-ika hum syarrul bariyyah', 'Sungguh, orang-orang yang kafir dari golongan Ahli Kitab dan orang-orang musyrik (akan masuk) ke neraka Jahanam; mereka kekal di dalamnya. Mereka itu adalah seburuk-buruk makhluk.', 6],
      ['اِنَّ الَّذِيْنَ اٰمَنُوْا وَعَمِلُوا الصّٰلِحٰتِ اُولٰۤىِٕكَ هُمْ خَيْرُ الْبَرِيَّةِ', "Innal ladziina aamanuu wa 'amilush shaalihaati ulaa-ika hum khairul bariyyah", 'Sungguh, orang-orang yang beriman dan mengerjakan kebajikan, mereka itu adalah sebaik-baik makhluk.', 7],
      ['جَزَاۤؤُهُمْ عِنْدَ رَبِّهِمْ جَنّٰتُ عَدْنٍ تَجْرِيْ مِنْ تَحْتِهَا الْاَنْهٰرُ خٰلِدِيْنَ فِيْهَآ اَبَدًا رَضِيَ اللّٰهُ عَنْهُمْ وَرَضُوْا عَنْهُ ذٰلِكَ لِمَنْ خَشِيَ رَبَّهٗ', "Jazaa-uhum 'inda rabbihim jannaatu 'adnin tajrii min tahtihal anhaaru khaalidiina fiihaa abadaa, radhiyallaahu 'anhum wa radhuu 'anh, dzaalika liman khasyiya rabbah", 'Balasan mereka di sisi Tuhan mereka ialah surga \'Adn yang mengalir di bawahnya sungai-sungai; mereka kekal di dalamnya selama-lamanya. Allah rida terhadap mereka dan mereka pun rida kepada-Nya. Yang demikian itu adalah (balasan) bagi orang yang takut kepada Tuhannya.', 8],
    ],
    quiz: [
      ['Al-Bayyinah artinya …', ['Bukti yang nyata', 'Kabar gembira', 'Perjanjian'], 0, 'Al-Bayyinah = bukti yang nyata.'],
      ['Menurut ayat ke-5, manusia diperintahkan untuk menyembah Allah dengan …', ['Riya dan sombong', 'Ikhlas menaati-Nya semata', 'Keterpaksaan'], 1, 'Mukhlishiina lahud diin = ikhlas dalam beragama.'],
      ['Sebaik-baik makhluk (khairul bariyyah) menurut surat ini adalah …', ['Orang yang beriman dan beramal saleh', 'Orang yang paling kaya', 'Orang yang berkuasa'], 0, 'Innal ladziina aamanuu wa \'amilush shaalihaati ulaa-ika hum khairul bariyyah.'],
    ],
  },
  {
    slug: 'surat-az-zalzalah',
    theme: 'Surat Pendek',
    emoji: '🌋',
    title: 'Surat Az-Zalzalah',
    titleId: 'Kegoncangan · 8 ayat',
    minutes: 3,
    intro:
      "**Surat ke-99** · **8 ayat** · Madaniyah.\n\n" +
      "Az-Zalzalah artinya **kegoncangan yang dahsyat**. Menggambarkan hari Kiamat ketika bumi digoncangkan dan mengeluarkan isi perutnya. Setiap perbuatan manusia, sekecil biji zarah sekalipun, akan diperlihatkan balasannya.",
    lines: [
      BASMALAH,
      ['اِذَا زُلْزِلَتِ الْاَرْضُ زِلْزَالَهَا', 'Idzaa zulzilatil ardhu zilzaalahaa', 'Apabila bumi diguncangkan dengan guncangan yang dahsyat,', 1],
      ['وَاَخْرَجَتِ الْاَرْضُ اَثْقَالَهَا', 'Wa akhrajatil ardhu atsqaalahaa', 'dan bumi telah mengeluarkan beban-beban berat (yang dikandung)nya,', 2],
      ['وَقَالَ الْاِنْسَانُ مَا لَهَا', 'Wa qaalal insaanu maa lahaa', 'dan manusia bertanya, "Apa yang terjadi pada bumi ini?"', 3],
      ['يَوْمَىِٕذٍ تُحَدِّثُ اَخْبَارَهَا', 'Yauma-idzin tuhadditsu akhbaarahaa', 'Pada hari itu bumi menyampaikan berita (tentang apa yang terjadi di atasnya),', 4],
      ['بِاَنَّ رَبَّكَ اَوْحٰى لَهَا', 'Bi-anna rabbaka auhaa lahaa', 'karena sesungguhnya Tuhanmu telah memerintahkan (yang demikian itu) kepadanya.', 5],
      ['يَوْمَىِٕذٍ يَّصْدُرُ النَّاسُ اَشْتَاتًا لِّيُرَوْا اَعْمَالَهُمْ', "Yauma-idziy yashdurun naasu asytaatal liyurau a'maalahum", 'Pada hari itu manusia keluar dari kuburnya dalam keadaan berkelompok-kelompok, untuk diperlihatkan kepada mereka (balasan) semua perbuatannya.', 6],
      ['فَمَنْ يَّعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَّرَهٗ', "Fa may ya'mal mitsqaala dzarratin khairay yarah", 'Maka barangsiapa mengerjakan kebaikan seberat zarrah, niscaya dia akan melihat (balasan)nya,', 7],
      ['وَمَنْ يَّعْمَلْ مِثْقَالَ ذَرَّةٍ شَرًّا يَّرَهٗ', "Wa may ya'mal mitsqaala dzarratin syarray yarah", 'dan barangsiapa mengerjakan kejahatan seberat zarrah, niscaya dia akan melihat (balasan)nya.', 8],
    ],
    quiz: [
      ['Az-Zalzalah artinya …', ['Kegoncangan yang dahsyat', 'Petir menggelegar', 'Angin kencang'], 0, 'Az-Zalzalah = guncangan yang dahsyat.'],
      ['"Fa may ya\'mal mitsqaala dzarratin khairay yarah" artinya barangsiapa berbuat kebaikan seberat … niscaya melihat balasannya.', ['Gunung', 'Zarrah (biji terkecil)', 'Batu'], 1, 'Mitsqaala dzarrah = seberat biji zarrah.'],
      ['Kapan peristiwa yang diceritakan dalam surat ini terjadi?', ['Pada saat hari kiamat', 'Saat musim hujan', 'Saat gerhana matahari'], 0, 'Surat ini menceritakan peristiwa dahsyat hari kiamat.'],
    ],
  },
  {
    slug: 'surat-al-adiyat',
    theme: 'Surat Pendek',
    emoji: '🐎',
    title: "Surat Al-'Adiyat",
    titleId: 'Kuda Perang yang Berlari Kencang · 11 ayat',
    minutes: 3,
    intro:
      "**Surat ke-100** · **11 ayat** · Makkiyah.\n\n" +
      "Al-'Adiyat artinya **kuda perang yang berlari kencang terengah-engah**. Mengingatkan manusia yang sering ingkar dan kikir karena cinta berlebihan pada harta duniawi, padahal segala rahasia di dalam dada akan dibongkar pada hari kiamat.",
    lines: [
      BASMALAH,
      ['وَالْعٰدِيٰتِ ضَبْحًا', "Wal 'aadiyaati dhab-haa", 'Demi kuda perang yang berlari kencang terengah-engah,', 1],
      ['فَالْمُوْرِيٰتِ قَدْحًا', 'Fal muuriyaati qad-haa', 'dan kuda yang memercikkan bunga api (dengan pukulan kuku kakinya),', 2],
      ['فَالْمُغِيْرٰتِ صُبْحًا', 'Fal mughiiraati shub-haa', 'dan kuda yang menyerang (dengan tiba-tiba) pada waktu subuh,', 3],
      ['فَاَثَرْنَ بِهٖ نَقْعًا', "Fa atsarna bihii naq'aa", 'lalu menerbangkan debu,', 4],
      ['فَوَسَطْنَ بِهٖ جَمْعًا', "Fa wasathna bihii jam'aa", 'lalu menyerbu ke tengah-tengah kumpulan musuh,', 5],
      ['اِنَّ الْاِنْسَانَ لِرَبِّهٖ لَكَنُوْدٌ', 'Innal insaana lirabbihii lakanuud', 'sungguh, manusia itu sangat ingkar (tidak bersyukur) kepada Tuhannya,', 6],
      ['وَاِنَّهٗ عَلٰى ذٰلِكَ لَشَهِيْدٌ', "Wa innahuu 'alaa dzaalika lasyahiid", 'dan sesungguhnya dia benar-benar menyaksikan (sendiri) keingkarannya itu,', 7],
      ['وَاِنَّهٗ لِحُبِّ الْخَيْرِ لَشَدِيْدٌ', 'Wa innahuu lihubbil khairi lasyadiid', 'dan sesungguhnya cintanya kepada harta benar-benar berlebihan.', 8],
      ['اَفَلَا يَعْلَمُ اِذَا بُعْثِرَ مَا فِى الْقُبُوْرِ', "A falaa ya'lamu idzaa bu'tsira maa fil qubuur", 'Maka tidakkah dia mengetahui apabila apa yang di dalam kubur dibangkitkan,', 9],
      ['وَحُصِّلَ مَا فِى الصُّدُوْرِ', 'Wa hush-shila maa fish shuduur', 'dan apa yang tersimpan di dalam dada dilahirkan (dan ditampakkan)?', 10],
      ['اِنَّ رَبَّهُمْ بِهِمْ يَوْمَىِٕذٍ لَّخَبِيْرٌ', 'Inna rabbahum bihim yauma-idzil lakhabiir', 'Sungguh, Tuhan mereka pada hari itu Mahateliti terhadap keadaan mereka.', 11],
    ],
    quiz: [
      ["Al-'Adiyat artinya …", ['Kuda perang yang berlari kencang', 'Burung ababil', 'Gajah perang'], 0, "Al-'Adiyat = kuda perang yang berlari kencang."],
      ['Sifat buruk manusia yang ditegur dalam ayat ke-6 adalah …', ['Kanuud (sangat ingkar / tidak bersyukur)', 'Pemberani', 'Suka menolong'], 0, 'Innal insaana lirabbihii lakanuud.'],
      ['"Wa innahuu lihubbil khairi lasyadiid" artinya cinta manusia yang sangat berlebihan terhadap …', ['Kuda', 'Harta benda', 'Tidur'], 1, 'Manusia sangat mencintai harta secara berlebihan.'],
    ],
  },
  {
    slug: 'surat-al-qariah',
    theme: 'Surat Pendek',
    emoji: '⚖️',
    title: "Surat Al-Qari'ah",
    titleId: 'Hari Kiamat · 11 ayat',
    minutes: 3,
    intro:
      "**Surat ke-101** · **11 ayat** · Makkiyah.\n\n" +
      "Al-Qari'ah artinya **hari kiamat yang menggetarkan hati**. Menggambarkan manusia berhamburan seperti anai-anai dan gunung seperti bulu yang dihambur-hamburkan. Timbangan amal kebaikan akan menentukan apakah seseorang masuk surga yang memuaskan atau neraka Hawiyah yang panas membara.",
    lines: [
      BASMALAH,
      ['اَلْقَارِعَةُ', "Al-qaari'ah", 'Hari Kiamat,', 1],
      ['مَا الْقَارِعَةُ', "Mal qaari'ah", 'Apakah hari Kiamat itu?', 2],
      ['وَمَآ اَدْرٰىكَ مَا الْقَارِعَةُ', "Wa maa adraaka mal qaari'ah", 'Dan tahukah kamu apakah hari Kiamat itu?', 3],
      ['يَوْمَ يَكُوْنُ النَّاسُ كَالْفَرَاشِ الْمَبْثُوْثِ', 'Yauma yakuunun naasu kal faraasyil mabtsuuts', 'Pada hari itu manusia seperti laron yang berterbangan,', 4],
      ['وَتَكُوْنُ الْجِبَالُ كَالْعِهْنِ الْمَنْفُوْشِ', "Wa takuunul jibaalu kal 'ihnil manfuusy", 'dan gunung-gunung seperti bulu yang dihambur-hamburkan.', 5],
      ['فَاَمَّا مَنْ ثَقُلَتْ مَوَازِينُهٗ', 'Fa ammaa man tsaqulat mawaaziinuh', 'Maka adapun orang yang berat timbangan (kebaikan)nya,', 6],
      ['فَهُوَ فِيْ عِيْشَةٍ رَّاضِيَةٍ', "Fa huwa fii 'iisyatir raadhiyah", 'maka dia berada dalam kehidupan yang memuaskan (senang).', 7],
      ['وَاَمَّا مَنْ خَفَّتْ مَوَازِينُهٗ', 'Wa ammaa man khaffat mawaaziinuh', 'Dan adapun orang yang ringan timbangan (kebaikan)nya,', 8],
      ['فَاُمُّهٗ هَاوِيَةٌ', 'Fa ummuhuu haawiyah', 'maka tempat kembalinya adalah neraka Hawiyah.', 9],
      ['وَمَآ اَدْرٰىكَ مَا هِيَهْ', 'Wa maa adraaka maa hiyah', 'Dan tahukah kamu apakah neraka Hawiyah itu?', 10],
      ['نَارٌ حَامِيَةٌ', 'Naarun haamiyah', '(Yaitu) api yang sangat panas.', 11],
    ],
    quiz: [
      ["Al-Qari'ah artinya …", ['Hari Kiamat', 'Hari Raya', 'Hari Kemenangan'], 0, "Al-Qari'ah = Hari Kiamat yang mengguncang hati."],
      ['Pada hari kiamat, manusia digambarkan seperti … yang berterbangan.', ['Kupu-kupu', 'Laron / anai-anai', 'Burung elang'], 1, 'Kal faraasyil mabtsuuts = seperti laron yang bertebaran.'],
      ['Orang yang berat timbangan kebaikannya akan berada dalam kehidupan yang …', ['Sengsara', 'Memuaskan (surga)', 'Penuh ketakutan'], 1, 'Fii \'iisyatir raadhiyah = kehidupan yang memuaskan dan bahagia.'],
    ],
  },
  {
    slug: 'surat-at-takatsur',
    theme: 'Surat Pendek',
    emoji: '🏆',
    title: 'Surat At-Takatsur',
    titleId: 'Bermegah-megahan · 8 ayat',
    minutes: 3,
    intro:
      "**Surat ke-102** · **8 ayat** · Makkiyah.\n\n" +
      "At-Takatsur artinya **bermegah-megahan**. Menegur manusia yang lalai dari ibadah dan akhirat karena sibuk berlomba menumpuk harta dan kebanggaan dunia sampai masuk liang kubur. Setiap nikmat yang dinikmati di dunia pasti akan dimintai pertanggungjawaban di akhirat.",
    lines: [
      BASMALAH,
      ['اَلْهٰىكُمُ التَّكَاثُرُ', 'Al-haakumut takaatsur', 'Bermegah-megahan telah melalaikan kamu,', 1],
      ['حَتّٰى زُرْتُمُ الْمَقَابِرَ', 'Hattaa zurtumul maqaabir', 'sampai kamu masuk ke dalam kubur.', 2],
      ['كَلَّا سَوْفَ تَعْلَمُوْنَ', 'Kallaa saufa ta\'lamuun', 'Sekali-kali tidak! Kelak kamu akan mengetahui (akibat perbuatanmu itu),', 3],
      ['ثُمَّ كَلَّا سَوْفَ تَعْلَمُوْنَ', 'Tsumma kallaa saufa ta\'lamuun', 'kemudian sekali-kali tidak! Kelak kamu akan mengetahui.', 4],
      ['كَلَّا لَوْ تَعْلَمُوْنَ عِلْمَ الْيَقِيْنِ', "Kallaa lau ta'lamuuna 'ilmal yaqiin", 'Sekali-kali tidak! Sekiranya kamu mengetahui dengan pasti,', 5],
      ['لَتَرَوُنَّ الْجَحِيْمَ', 'Latarawunnal jahiim', 'niscaya kamu benar-benar akan melihat neraka Jahim,', 6],
      ['ثُمَّ لَتَرَوُنَّهَا عَيْنَ الْيَقِيْنِ', "Tsumma latarawunnahaa 'ainal yaqiin", 'kemudian kamu benar-benar akan melihatnya dengan mata kepala sendiri,', 7],
      ['ثُمَّ لَتُسْـَٔلُنَّ يَوْمَىِٕذٍ عَنِ النَّعِيْمِ', "Tsumma latus-alunna yauma-idzin 'anin na'iim", 'kemudian kamu benar-benar akan ditanya pada hari itu tentang kenikmatan (yang megah di dunia itu).', 8],
    ],
    quiz: [
      ['At-Takatsur artinya …', ['Bermegah-megahan', 'Berlomba lari', 'Masa lalu'], 0, 'At-Takatsur = bermegah-megahan menumpuk harta dan kebanggaan.'],
      ['Apa yang melalaikan manusia menurut ayat pertama?', ['Tidur', 'Bermegah-megahan dalam keduniaan', 'Bermain bola'], 1, 'Al-haakumut takaatsur = bermegah-megahan telah melalaikanmu.'],
      ['Pada hari kiamat, manusia pasti akan ditanya tentang …', ['Nama kakeknya', 'Kenikmatan yang dinikmati selama hidup', 'Warna bajunya'], 1, 'Tsumma latus-alunna yauma-idzin \'anin na\'iim.'],
    ],
  },
  {
    slug: 'surat-al-asr',
    theme: 'Surat Pendek',
    emoji: '⏳',
    title: "Surat Al-'Asr",
    titleId: 'Masa · 3 ayat',
    minutes: 2,
    intro:
      "**Surat ke-103** · **3 ayat** · Makkiyah.\n\n" +
      "Al-'Asr artinya **masa/waktu**. Manusia berada dalam kerugian, kecuali mereka yang beriman, beramal saleh, serta saling menasihati untuk kebenaran dan kesabaran. Pesan intinya: manfaatkan waktu sebaik-baiknya!",
    lines: [
      BASMALAH,
      ['وَالْعَصْرِ', "Wal 'ashr", 'Demi masa,', 1],
      ['اِنَّ الْاِنْسَانَ لَفِيْ خُسْرٍ', 'Innal insaana lafii khusr', 'sungguh, manusia berada dalam kerugian,', 2],
      [
        'اِلَّا الَّذِيْنَ اٰمَنُوْا وَعَمِلُوا الصّٰلِحٰتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ',
        "Illal ladziina aamanuu wa 'amilush shaalihaati wa tawaashau bil haqqi wa tawaashau bish shabr",
        'kecuali orang-orang yang beriman dan mengerjakan kebajikan serta saling menasihati untuk kebenaran dan saling menasihati untuk kesabaran.',
        3,
      ],
    ],
    quiz: [
      ["Al-'Asr artinya …", ['Masa / waktu', 'Manusia', 'Subuh'], 0, "Al-'Asr = masa atau waktu."],
      ['Menurut surat ini, manusia berada dalam …', ['Kebahagiaan', 'Kerugian', 'Kemenangan'], 1, 'Innal insaana lafii khusr = manusia dalam kerugian.'],
      ['Orang yang TIDAK merugi adalah yang …', ['Banyak bermain', 'Beriman, beramal saleh, dan saling menasihati', 'Banyak tidur'], 1, 'Kecuali orang yang beriman, beramal saleh, dan saling menasihati.'],
    ],
  },
  {
    slug: 'surat-al-humazah',
    theme: 'Surat Pendek',
    emoji: '🗣️',
    title: 'Surat Al-Humazah',
    titleId: 'Pengumpat · 9 ayat',
    minutes: 3,
    intro:
      "**Surat ke-104** · **9 ayat** · Makkiyah.\n\n" +
      "Al-Humazah artinya **pengumpat dan pencela**. Memberikan ancaman keras bagi orang yang suka mencela orang lain dan mengumpulkan harta sambil mengira hartanya akan mengekalkannya. Mereka akan dilemparkan ke dalam neraka Huthamah.",
    lines: [
      BASMALAH,
      ['وَيْلٌ لِّكُلِّ هُمَزَةٍ لُّمَزَةٍ', 'Wailul likulli humazatil lumazah', 'Celakalah bagi setiap pengumpat dan pencela,', 1],
      ['الَّذِيْ جَمَعَ مَالًا وَّعَدَّدَهٗ', "Alladzii jama'a maalaw wa 'addadah", 'yang mengumpulkan harta dan menghitung-hitungnya,', 2],
      ['يَحْسَبُ اَنَّ مَالَهٗٓ اَخْلَدَهٗ', 'Yahsabu anna maalahuu akhladah', 'dia mengira bahwa hartanya itu dapat mengekalkannya.', 3],
      ['كَلَّا لَيُنْۢبَذَنَّ فِى الْحُطَمَةِ', 'Kallaa layumbadzanna fil huthamah', 'Sekali-kali tidak! Sungguh, dia benar-benar akan dilemparkan ke dalam Huthamah.', 4],
      ['وَمَآ اَدْرٰىكَ مَا الْحُطَمَةُ', 'Wa maa adraaka mal huthamah', 'Dan tahukah kamu apakah Huthamah itu?', 5],
      ['نَارُ اللّٰهِ الْمُوْقَدَةُ', 'Naarullaahil muuqadah', '(Yaitu) api (azab) Allah yang dinyalakan,', 6],
      ['الَّتِيْ تَطَّلِعُ عَلَى الْاَفْـِٕدَةِ', "Allatii tath-thali'u 'alal af-idah", 'yang (naik) sampai ke hati.', 7],
      ['اِنَّهَا عَلَيْهِمْ مُّؤْصَدَةٌ', "Innahaa 'alaihim mu'shadah", 'Sungguh, api itu ditutup rapat atas mereka,', 8],
      ['فِيْ عَمَدٍ مُّمَدَّدَةٍ', "Fii 'amadim mumaddadah", '(sedang mereka itu) diikat pada tiang-tiang yang panjang.', 9],
    ],
    quiz: [
      ['Al-Humazah artinya …', ['Pengumpat dan pencela', 'Pembawa kayu bakar', 'Orang munafik'], 0, 'Al-Humazah = pengumpat / pencela.'],
      ['Tempat balasan bagi pengumpat dan penumpuk harta yang sombong adalah neraka …', ['Hawiyah', 'Huthamah', 'Jahim'], 1, 'Fil huthamah = di dalam neraka Huthamah.'],
      ['Sikap buruk yang dilarang dalam surat ini adalah …', ['Rajin menabung', 'Mencela orang lain dan merasa sombong karena harta', 'Bekerja keras'], 1, 'Mengumpat, mencela sesama, dan mengira harta mengekalkannya.'],
    ],
  },
];
