// Surat Pendek Juz 30 — Bagian 1A: Surat 78 s.d. 84.
// Teks Arab berharakat standar Mushaf Kemenag RI, transliterasi Latin, dan terjemahan resmi Kemenag RI.

import type { SeedLesson } from './types';
import { BASMALAH } from './surat-pendek-105-114';

export const suratPendek78to84: SeedLesson[] = [
  {
    slug: 'surat-an-naba',
    theme: 'Surat Pendek',
    emoji: '📢',
    title: "Surat An-Naba'",
    titleId: 'Berita Besar · 40 ayat',
    minutes: 6,
    intro:
      "**Surat ke-78** (pembuka Juz 30 / Juz 'Amma) · **40 ayat** · Makkiyah.\n\n" +
      "An-Naba' artinya **berita besar** (tentang hari Kebangkitan dan Kiamat). Menegaskan kekuasaan Allah yang menciptakan bumi terhampar, gunung sebagai pasak, siang untuk mencari nafkah, dan malam untuk beristirahat. Menggambarkan kedahsyatan kiamat, azab neraka Jahannam, serta balasan surga bagi orang bertakwa.",
    lines: [
      BASMALAH,
      ['عَمَّ يَتَسَاۤءَلُوْنَ', "'Amma yatasaa-aluun", 'Tentang apakah mereka saling bertanya-tanya?', 1],
      ['عَنِ النَّبَاِ الْعَظِيْمِ', "'Anin naba-il 'azhiim", 'Tentang berita yang besar (hari Kebangkitan),', 2],
      ['الَّذِيْ هُمْ فِيْهِ مُخْتَلِفُوْنَ', 'Alladzii hum fiihi mukhtalifuun', 'yang dalam hal itu mereka berselisih.', 3],
      ['كَلَّا سَيَعْلَمُوْنَ', 'Kallaa saya\'lamuun', 'Sama sekali tidak! Kelak mereka akan mengetahui,', 4],
      ['ثُمَّ كَلَّا سَيَعْلَمُوْنَ', 'Tsumma kallaa saya\'lamuun', 'kemudian sama sekali tidak! Kelak mereka akan mengetahui.', 5],
      ['اَلَمْ نَجْعَلِ الْاَرْضَ مِهٰدًا', "A lam naj'alil ardha mihaadaa", 'Bukankah Kami telah menjadikan bumi sebagai hamparan,', 6],
      ['وَّالْجِبَالَ اَوْتَادًا', 'Wal jibaala autaadaa', 'dan gunung-gunung sebagai pasak?', 7],
      ['وَّخَلَقْنٰكُمْ اَزْوَاجًا', 'Wa khalaqnaakum azwaajaa', 'Dan Kami menciptakan kamu berpasang-pasangan,', 8],
      ['وَّجَعَلْنَا نَوْمَكُمْ سُبَاتًا', 'Wa ja\'alnaa naumakum subaataa', 'dan Kami menjadikan tidurmu untuk istirahat,', 9],
      ['وَّجَعَلْنَا الَّيْلَ لِبَاسًا', 'Wa ja\'alnal laila libaasaa', 'dan Kami menjadikan malam sebagai pakaian (penutup),', 10],
      ['وَّجَعَلْنَا النَّهَارَ مَعَاشًا', "Wa ja'alnan nahaara ma'aasyaa", 'dan Kami menjadikan siang untuk mencari penghidupan,', 11],
      ['وَبَنَيْنَا فَوْقَكُمْ سَبْعًا شِدَادًا', 'Wa banainaa fauqakum sab\'an syidaadaa', 'dan Kami membangun di atas kamu tujuh (langit) yang kokoh,', 12],
      ['وَّجَعَلْنَا سِرَاجًا وَّهَّاجًا', 'Wa ja\'alnaa siraajaw wahhaajaa', 'dan Kami menjadikan pelita yang terang-benderang (matahari),', 13],
      ['وَّاَنْزَلْنَا مِنَ الْمُعْصِرٰتِ مَآءً ثَجَّاجًا', "Wa anzalnaa minal mu'shiraati maa-an tsajjaajaa", 'dan Kami turunkan dari awan air hujan yang tercurah dengan lebat,', 14],
      ['لِّنُخْرِجَ بِهٖ حَبًّا وَّنَبَاتًا', "Linukhrija bihii habbaw wa nabaataa", 'agar Kami tumbuhkan dengan air itu biji-bijian dan tanam-tanaman,', 15],
      ['وَّجَنّٰتٍ اَلْفَافًا', 'Wa jannaatin alfaafaa', 'dan kebun-kebun yang rindang.', 16],
      ['اِنَّ يَوْمَ الْفَصْلِ كَانَ مِيْقَاتًا', 'Inna yaumal fashli kaana miiqaataa', 'Sungguh, hari Keputusan adalah suatu waktu yang telah ditetapkan,', 17],
      ['يَّوْمَ يُنْفَخُ فِى الصُّوْرِ فَتَأْتُوْنَ اَفْوَاجًا', 'Yauma yunfakhu fish-shuuri fata\'tuuna afwaajaa', '(yaitu) pada hari (ketika) sangkakala ditiup, lalu kamu datang berbondong-bondong,', 18],
      ['وَّفُتِحَتِ السَّمَاۤءُ فَكَانَتْ اَبْوَابًا', 'Wa futihatis samaa-u fakaanat abwaabaa', 'dan langit pun dibuka, maka terdapatlah beberapa pintu,', 19],
      ['وَّسُيِّرَتِ الْجِبَالُ فَكَانَتْ سَرَابًا', 'Wa suyyiratil jibaalu fakaanat saraabaa', 'dan gunung-gunung pun dijalankan sehingga menjadi fatamorgana.', 20],
      ['اِنَّ جَهَنَّمَ كَانَتْ مِرْصَادًا', 'Inna jahannama kaanat mirshaadaa', 'Sungguh, (neraka) Jahanam itu (sebagai) tempat mengintai (bagi penjaga neraka),', 21],
      ['لِّلطَّاغِيْنَ مَاٰبًا', "Lith-thaaghiina ma-aabaa", 'menjadi tempat kembali bagi orang-orang yang melampaui batas.', 22],
      ['لّٰبِثِيْنَ فِيْهَآ اَحْقَابًا', 'Laabitsiina fiihaa ahqaabaa', 'Mereka tinggal di sana berabad-abad lamanya,', 23],
      ['لَا يَذُوْقُوْنَ فِيْهَا بَرْدًا وَّلَا شَرَابًا', 'Laa yadzuuquuna fiihaa bardaw wa laa syaraabaa', 'mereka tidak merasakan kesejukan di dalamnya dan tidak (pula mendapat) minuman,', 24],
      ['اِلَّا حَمِيْمًا وَّغَسَّاقًا', 'Illaa hamiimaw wa ghassaaqaa', 'selain air yang mendidih dan nanah,', 25],
      ['جَزَاۤءً وِّفَاقًا', "Jazaa-aw wifaaqaa", 'sebagai pembalasan yang setimpal.', 26],
      ['اِنَّهُمْ كَانُوْا لَا يَرْجُوْنَ حِسَابًا', 'Innahum kaanuu laa yarjuuna hisaabaa', 'Sesungguhnya dahulu mereka tidak pernah mengharapkan perhitungan,', 27],
      ['وَّكَذَّبُوْا بِاٰيٰتِنَا كِذَّابًا', 'Wa kadz-dzabuu bi-aayaatinaa kidzdzaabaa', 'dan mereka benar-benar mendustakan ayat-ayat Kami.', 28],
      ['وَكُلَّ شَيْءٍ اَحْصَيْنٰهُ كِتٰبًا', "Wa kulla syai-in ahshainaahu kitaabaa", 'Dan segala sesuatu telah Kami catat dalam suatu Kitab (buku catatan amal).', 29],
      ['فَذُوْقُوْا فَلَنْ نَّزِيْدَكُمْ اِلَّا عَذَابًا', "Fadzuuquu falan naziidakum illaa 'adzaabaa", 'Maka rasakanlah! Dan Kami tidak akan menambah kepadamu selain azab.', 30],
      ['اِنَّ لِلْمُتَّقِيْنَ مَفَازًا', 'Inna lil-muttaqiina mafaazaa', 'Sungguh, bagi orang-orang yang bertakwa ada kemenangan (kebahagiaan besar),', 31],
      ['حَدَاۤىِٕقَ وَاَعْنَابًا', "Hadaa-iqa wa a'naabaa", '(yaitu) kebun-kebun dan buah anggur,', 32],
      ['وَّكَوَاعِبَ اَتْرَابًا', "Wa kawaa'iba atraabaa", 'dan gadis-gadis sebaya,', 33],
      ['وَّكَأْسًا دِهَاقًا', 'Wa ka\'san dihaaqaa', 'dan gelas-gelas yang penuh (berisi minuman).', 34],
      ['لَا يَسْمَعُوْنَ فِيْهَا لَغْوًا وَّلَا كِذَّابًا', 'Laa yasma\'uuna fiihaa laghwaw wa laa kidzdzaabaa', 'Di sana mereka tidak mendengar perkataan yang sia-sia dan tidak (pula perkataan) dusta.', 35],
      ['جَزَاۤءً مِّنْ رَّبِّكَ عَطَاۤءً حِسَابًا', "Jazaa-am mir rabbika 'athaa-an hisaabaa", 'Sebagai balasan dan pemberian yang cukup banyak dari Tuhanmu,', 36],
      ['رَبِّ السَّمٰوٰتِ وَالْاَرْضِ وَمَا بَيْنَهُمَا الرَّحْمٰنِ لَا يَمْلِكُوْنَ مِنْهُ خِطَابًا', "Rabbis samaawaati wal ardhi wa maa bainahumar rahmaani laa yamlikuuna minhu khithaabaa", 'Tuhan (pemilik) langit dan bumi dan apa yang ada di antara keduanya; Yang Maha Pengasih, mereka tidak mampu berbicara dengan-Nya,', 37],
      ['يَوْمَ يَقُوْمُ الرُّوْحُ وَالْمَلٰۤىِٕكَةُ صَفًّا لَّا يَتَكَلَّمُوْنَ اِلَّا مَنْ اَذِنَ لَهُ الرَّحْمٰنُ وَقَالَ صَوَابًا', 'Yauma yaquumur ruuhu wal malaa-ikatu shaffal laa yatakallamuuna illaa man adzina lahur rahmaanu wa qaala shawaabaa', 'pada hari ketika Rūḥ (Jibril) dan para malaikat berdiri bersaf-saf, mereka tidak berbicara, kecuali siapa yang diberi izin kepadanya oleh Yang Maha Pengasih dan dia mengatakan yang benar.', 38],
      ['ذٰلِكَ الْيَوْمُ الْحَقُّ فَمَنْ شَاۤءَ اتَّخَذَ اِلٰى رَبِّهٖ مَاٰبًا', "Dzaalikal yaumul haqqu faman syaa-attakhadza ilaa rabbihii ma-aabaa", 'Itulah hari yang pasti terjadi. Maka barangsiapa menghendaki, niscaya dia menempuh jalan kembali kepada Tuhannya.', 39],
      ['اِنَّآ اَنْذَرْنٰكُمْ عَذَابًا قَرِيْبًا يَّوْمَ يَنْظُرُ الْمَرْءُ مَا قَدَّمَتْ يَدَاهُ وَيَقُوْلُ الْكَافِرُ يٰلَيْتَنِيْ كُنْتُ تُرٰبًا', "Innaa andzarnaakum 'adzaaban qariibay yauma yanzhurul mar-u maa qaddamat yadaahu wa yaquulul kaafiru yaa laitanii kuntu turaabaa", 'Sungguh, Kami telah memperingatkan kepadamu (orang kafir) azab yang dekat, pada hari manusia melihat apa yang telah diperbuat oleh kedua tangannya; dan orang kafir berkata, "Alangkah baiknya sekiranya dahulu aku jadi tanah saja."', 40],
    ],
    quiz: [
      ["An-Naba' artinya …", ['Berita besar', 'Bintang jatuh', 'Hari kemenangan'], 0, "An-Naba' = berita besar tentang hari kebangkitan."],
      ['Surat An-Naba\' adalah surat pembuka juz ke- …', ['29', '30 (Juz \'Amma)', '1'], 1, 'An-Naba\' adalah surat pertama di Juz 30.'],
      ['Di akhir surat, orang kafir menyesali perbuatannya dan berandai-andai sekiranya menjadi …', ['Batu kali', 'Tanah saja', 'Pohon rindang'], 1, 'Yaa laitanii kuntu turaabaa = alangkah baiknya sekiranya aku jadi tanah saja.'],
    ],
  },
  {
    slug: 'surat-an-naziat',
    theme: 'Surat Pendek',
    emoji: '💨',
    title: "Surat An-Nazi'at",
    titleId: 'Malaikat Pencabut · 46 ayat',
    minutes: 6,
    intro:
      "**Surat ke-79** · **46 ayat** · Makkiyah.\n\n" +
      "An-Nazi'at artinya **malaikat-malaikat yang mencabut nyawa orang kafir dengan keras**. Menceritakan kedahsyatan kiamat, kisah Nabi Musa menghadapi kedurhakaan Fir'aun, serta kepastian bahwa hari Kiamat hanya Allah yang mengetahui waktunya.",
    lines: [
      BASMALAH,
      ['وَالنّٰزِعٰتِ غَرْقًا', "Wan naazi'aati gharqaa", 'Demi (malaikat) yang mencabut (nyawa) dengan keras,', 1],
      ['وَالنّٰشِطٰتِ نَشْطًا', 'Wan naasyithaati nasythaa', 'demi (malaikat) yang mencabut (nyawa) dengan lemah lembut,', 2],
      ['وَالسّٰبِحٰتِ سَبْحًا', 'Was saabihaati sab-haa', 'demi (malaikat) yang turun dari langit dengan cepat,', 3],
      ['فَالسّٰبِقٰتِ سَبْقًا', 'Fas saabiqaati sabqaa', 'dan (malaikat) yang mendahului dengan cepat,', 4],
      ['فَالْمُدَبِّرٰتِ اَمْرًا', "Fal mudabbiraati amraa", 'dan (malaikat) yang mengatur urusan (dunia).', 5],
      ['يَوْمَ تَرْجُفُ الرَّاجِفَةُ', 'Yauma tarjufur raajifah', '(Sungguh, kamu akan dibangkitkan) pada hari ketika tiupan pertama mengguncangkan alam,', 6],
      ['تَتْبَعُهَا الرَّادِفَةُ', 'Tatba\'uhar raadifah', '(tiupan pertama) itu diiringi oleh tiupan kedua.', 7],
      ['قُلُوْبٌ يَّوْمَىِٕذٍ وَّاجِفَةٌ', 'Quluubuy yauma-idziw waajifah', 'Hati manusia pada hari itu merasa sangat takut,', 8],
      ['اَبْصَارُهَا خَاشِعَةٌ', "Abshaaruhaa khaasyi'ah", 'pandangannya tunduk.', 9],
      ['يَقُوْلُوْنَ اَىِٕنَّا لَمَرْدُوْدُوْنَ فِى الْحَافِرَةِ', 'Yaquuluuna a-innaa lamarduuduuna fil haafirah', '(Orang-orang kafir) berkata, "Apakah kita benar-benar akan dikembalikan kepada kehidupan yang semula?', 10],
      ['اَىِٕذَا كُنَّا عِظَامًا نَّخِرَةً', 'A-idzaa kunnaa \'izhaaman nakhirah', 'Apakah (akan dibangkitkan juga) apabila kita telah menjadi tulang-belulang yang hancur?"', 11],
      ['قَالُوْا تِلْكَ اِذًا كَرَّةٌ خَاسِرَةٌ', 'Qaaluu tilka idzan karratun khaasirah', 'Mereka berkata, "Kalau demikian, itu adalah suatu pengembalian yang merugikan."', 12],
      ['فَاِنَّمَا هِيَ زَجْرَةٌ وَّاحِدَةٌ', 'Fa innamaa hiya zajratuw waahidah', 'Maka pengembalian itu hanyalah dengan satu kali tiupan saja,', 13],
      ['فَاِذَا هُمْ بِالسَّاهِرَةِ', 'Fa idzaa hum bis saahirah', 'maka seketika itu mereka hidup kembali di bumi yang baru.', 14],
      ['هَلْ اَتٰىكَ حَدِيْثُ مُوْسٰى', 'Hal ataaka hadiitsu muusaa', 'Sudahkah sampai kepadamu (Muhammad) kisah Musa?', 15],
      ['اِذْ نَادٰىهُ رَبُّهٗ بِالْوَادِ الْمُقَدَّسِ طُوًى', 'Idz naadaahu rabbuhuu bil waadil muqaddasi thuwaa', 'Ketika Tuhannya memanggilnya di lembah suci Thuwa,', 16],
      ['اِذْهَبْ اِلٰى فِرْعَوْنَ اِنَّهٗ طَغٰى', "Idzhab ilaa fir'auna innahuu thaghaa", '"Pergilah engkau kepada Fir\'aun! Sesungguhnya dia telah melampaui batas,', 17],
      ['فَقُلْ هَلْ لَّكَ اِلٰٓى اَنْ تَزَكّٰى', 'Fa qul hal laka ilaa an tazakkaa', 'maka katakanlah (kepadanya), \'Adakah keinginanmu untuk menyucikan diri (dari kesesatan),', 18],
      ['وَاَهْدِيَكَ اِلٰى رَبِّكَ فَتَخْشٰى', 'Wa ahdiyaka ilaa rabbika fatakhsyaa', 'dan engkau akan kupimpin ke jalan Tuhanmu agar engkau takut kepada-Nya?\'"', 19],
      ['فَاَرٰىهُ الْاٰيَةَ الْكُبْرٰى', 'Fa araahul aayatal kubraa', 'Lalu (Musa) memperlihatkan kepadanya mukjizat yang besar.', 20],
      ['فَكَذَّبَ وَعَصٰى', "'Fa kadz-dzaba wa 'ashaa", 'Tetapi dia (Fir\'aun) mendustakan dan mendurhakai.', 21],
      ['ثُمَّ اَدْبَرَ يَسْعٰى', "Tsumma adbara yas'aa", 'Kemudian dia berpaling seraya berusaha menentang (Musa),', 22],
      ['فَحَشَرَ فَنَادٰى', 'Fa hasyara fanaadaa', 'maka dia mengumpulkan (pembesar-pembesarnya) lalu berseru (memanggil kaumnya),', 23],
      ['فَقَالَ اَنَا۠ رَبُّكُمُ الْاَعْلٰى', "Fa qaala ana rabbukumul a'laa", 'seraya berkata, "Akulah tuhanmu yang paling tinggi."', 24],
      ['فَاَخَذَهُ اللّٰهُ نَكَالَ الْاٰخِرَةِ وَالْاُوْلٰى', 'Fa akhadzahullaahu nakaalal aakhirati wal uulaa', 'Maka Allah menghukumnya dengan azab di akhirat dan azab di dunia.', 25],
      ['اِنَّ فِيْ ذٰلِكَ لَعِبْرَةً لِّمَنْ يَّخْشٰى', "Inna fii dzaalika la'ibratal limay yakhsyaa", 'Sungguh, pada yang demikian itu terdapat pelajaran bagi orang yang takut (kepada Allah).', 26],
      ['ءَاَنْتُمْ اَشَدُّ خَلْقًا اَمِ السَّمَاۤءُ بَنٰىهَا', "A antum asyaddu khalqan amis samaa-u banaahaa", 'Apakah penciptaan kamu yang lebih hebat ataukah langit yang telah dibangun-Nya?', 27],
      ['رَفَعَ سَمْكَهَا فَسَوّٰىهَا', 'Rafa\'a samkahaa fa sawwaahaa', 'Dia telah meninggikan bangunannya lalu menyempurnakannya,', 28],
      ['وَاَغْطَشَ لَيْلَهَا وَاَخْرَجَ ضُحٰىهَا', 'Wa aghthasya lailahaa wa akhraja dhuhaahaa', 'dan Dia menjadikan malamnya (gelap gulita), dan menjadikan siangnya (terang benderang),', 29],
      ['وَالْاَرْضَ بَعْدَ ذٰلِكَ دَحٰىهَا', 'Wal ardha ba\'da dzaalika dahaahaa', 'dan setelah itu bumi Dia hamparkan,', 30],
      ['اَخْرَجَ مِنْهَا مَآءَهَا وَمَرْعٰىهَا', "Akhraja minhaa maa-ahaa wa mar'aahaa", 'darinya Dia memancarkan mata airnya, dan (menumbuhkan) tumbuh-tumbuhannya,', 31],
      ['وَالْجِبَالَ اَرْسٰىهَا', 'Wal jibaala arsaahaa', 'dan gunung-gunung Dia pancangkan dengan kukuh,', 32],
      ['مَتَاعًا لَّكُمْ وَلِاَنْعَامِكُمْ', "Mataa'al lakum wa li-an'aamikum", '(semua itu) untuk kesenanganmu dan untuk hewan-hewan ternakmu.', 33],
      ['فَاِذَا جَاۤءَتِ الطَّآ مَّةُ الْكُبْرٰى', 'Fa idzaa jaa-atith thaammatul kubraa', 'Maka apabila malapetaka yang sangat besar (hari Kiamat) telah datang,', 34],
      ['يَوْمَ يَتَذَكَّرُ الْاِنْسَانُ مَا سَعٰى', "Yauma yatadzakkarul insaanu maa sa'aa", 'pada hari (ketika) manusia teringat apa yang telah dikerjakannya,', 35],
      ['وَبُرِّزَتِ الْجَحِيْمُ لِمَنْ يَّرٰى', "Wa burrizatil jahiimu limay yaraa", 'dan neraka Jahim diperlihatkan dengan jelas kepada setiap orang yang melihat.', 36],
      ['فَاَمَّا مَنْ طَغٰى', 'Fa ammaa man thaghaa', 'Maka adapun orang yang melampaui batas,', 37],
      ['وَاٰثَرَ الْحَيٰوةَ الدُّنْيَا', "Wa aatsaral hayaatad dun-yaa", 'dan lebih mengutamakan kehidupan duniawi,', 38],
      ['فَاِنَّ الْجَحِيْمَ هِيَ الْمَأْوٰى', "Fa innal jahiima hiyal ma'waa", 'maka sungguh, nerakalah tempat tinggal(nya).', 39],
      ['وَاَمَّا مَنْ خَافَ مَقَامَ رَبِّهٖ وَنَهَى النَّفْسَ عَنِ الْهَوٰى', 'Wa ammaa man khaafa maqaama rabbihii wa nahan nafsa \'anil hawaa', 'Dan adapun orang-orang yang takut kepada kebesaran Tuhannya dan menahan diri dari (keinginan) hawa nafsunya,', 40],
      ['فَاِنَّ الْجَنَّةَ هِيَ الْمَأْوٰى', "Fa innal jannata hiyal ma'waa", 'maka sungguh, surgalah tempat tinggal(nya).', 41],
      ['يَسْـَٔلُوْنَكَ عَنِ السَّاعَةِ اَيَّانَ مُرْسٰىهَا', "Yas-aluunaka 'anis saa'ati ayyaana mursaahaa", 'Mereka (orang-orang kafir) bertanya kepadamu (Muhammad) tentang hari Kiamat, "Kapankah terjadinya?"', 42],
      ['فِيْمَ اَنْتَ مِنْ ذِكْرٰىهَا', 'Fiima anta min dzikraahaa', 'Untuk apa engkau perlu menyebutkannya (waktunya)?', 43],
      ['اِلٰى رَبِّكَ مُنْتَهٰىهَا', 'Ilaa rabbika muntahaahaa', 'Kepada Tuhanmulah dikembalikan kesudahannya (ketentuan waktunya).', 44],
      ['اِنَّمَآ اَنْتَ مُنْذِرُ مَنْ يَّخْشٰىهَا', 'Innamaa anta mundziru may yakhsyaahaa', 'Engkau (Muhammad) hanyalah pemberi peringatan bagi siapa yang takut kepadanya (hari Kiamat).', 45],
      ['كَاَنَّهُمْ يَوْمَ يَرَوْنَهَا لَمْ يَلْبَثُوْٓا اِلَّا عَشِيَّةً اَوْ ضُحٰىهَا', "Ka-annahum yauma yaraunahaa lam yalbatsuu illaa 'asyiyyatan au dhuhaahaa", 'Pada hari ketika mereka melihat hari Kiamat itu (mereka merasa) seakan-akan hanya tinggal (di dunia) pada waktu sore atau pagi hari saja.', 46],
    ],
    quiz: [
      ["An-Nazi'at artinya …", ['Malaikat-malaikat yang mencabut nyawa', 'Bintang-bintang bersinar', 'Angin kencang'], 0, "An-Nazi'at = malaikat yang mencabut nyawa dengan keras."],
      ['Kisah nabi yang diutus menghadapi Fir\'aun dalam surat ini adalah Nabi …', ['Ibrahim a.s.', 'Musa a.s.', 'Yusuf a.s.'], 1, 'Kisah Nabi Musa menghadapi Fir\'aun di lembah Thuwa.'],
      ['Siapakah yang berhak masuk ke dalam surga menurut ayat ke-40 dan 41?', ['Orang yang sombong', 'Orang yang takut kepada kebesaran Allah dan menahan hawa nafsu', 'Orang yang mencintai dunia berlebihan'], 1, 'Wa nahan nafsa \'anil hawaa = menahan diri dari hawa nafsu.'],
    ],
  },
  {
    slug: 'surat-abasa',
    theme: 'Surat Pendek',
    emoji: '👤',
    title: "Surat 'Abasa",
    titleId: 'Bermuka Masam · 42 ayat',
    minutes: 5,
    intro:
      "**Surat ke-80** · **42 ayat** · Makkiyah.\n\n" +
      "'Abasa artinya **bermuka masam**. Berisi teguran Allah kepada Nabi Muhammad ﷺ ketika memalingkan muka dari sahabat tunanetra Ibnu Ummi Maktum yang datang ingin belajar Islam karena sedang sibuk mendakwahi para pembesar Quraisy. Menegaskan kemuliaan Al-Qur'an dan kedahsyatan hari kiamat ketika seseorang lari dari saudara dan orang tuanya.",
    lines: [
      BASMALAH,
      ['عَبَسَ وَتَوَلّٰى', "'Abasa wa tawallaa", 'Dia (Muhammad) berwajah masam dan berpaling,', 1],
      ['اَنْ جَاۤءَهُ الْاَعْمٰى', "An jaa-ahul a'maa", 'karena seorang buta (Abdullah bin Ummi Maktum) telah datang kepadanya.', 2],
      ['وَمَا يُدْرِيْكَ لَعَلَّهٗ يَزَّكّٰى', 'Wa maa yudriika la\'allahuu yazzakkaa', 'Dan tahukah kamu barangkali dia ingin menyucikan dirinya (dari dosa),', 3],
      ['اَوْ يَذَّكَّرُ فَتَنْفَعَهُ الذِّكْرٰى', 'Au yadz-dzakkaru fatanfa\'ahudz dzikraa', 'atau dia (ingin) mendapatkan pengajaran, yang memberi manfaat kepadanya?', 4],
      ['اَمَّا مَنِ اسْتَغْنٰى', "Ammaa manistaghnaa", 'Adapun orang yang merasa dirinya serbacukup (pembesar kafir),', 5],
      ['فَاَنْتَ لَهٗ تَصَدّٰى', 'Fa anta lahuu tashaddaa', 'maka engkau melayaninya,', 6],
      ['وَمَا عَلَيْكَ اَلَّا يَزَّكّٰى', 'Wa maa \'alaika allaa yazzakkaa', 'padahal tidak ada cela atasmu kalau dia tidak menyucikan diri.', 7],
      ['وَاَمَّا مَنْ جَاۤءَكَ يَسْعٰى', "Wa ammaa man jaa-aka yas'aa", 'Dan adapun orang yang datang kepadamu dengan bersegera (untuk belajar),', 8],
      ['وَهُوَ يَخْشٰى', 'Wa huwa yakhsyaa', 'sedang dia takut (kepada Allah),', 9],
      ['فَاَنْتَ عَنْهُ تَلَهّٰى', 'Fa anta \'anhu talahhaa', 'maka engkau mengabaikannya.', 10],
      ['كَلَّآ اِنَّهَا تَذْكِرَةٌ', 'Kallaa innahaa tadzkirah', 'Sekali-kali jangan (begitu)! Sungguh, (ajaran Allah) itu suatu peringatan,', 11],
      ['فَمَنْ شَاۤءَ ذَكَرَهٗ', 'Faman syaa-a dzakarah', 'maka barangsiapa menghendaki, tentulah dia mengingatnya,', 12],
      ['فِيْ صُحُفٍ مُّكَرَّمَةٍ', 'Fii suhufim mukarramah', 'di dalam kitab-kitab yang dimuliakan (Lauh Mahfuzh),', 13],
      ['مَّرْفُوْعَةٍ مُّطَهَّرَةٍ', 'Marfuu\'atim muthahharah', 'yang ditinggikan lagi disucikan,', 14],
      ['بِاَيْدِيْ سَفَرَةٍ', 'Bi-aidii safarah', 'di tangan para utusan (malaikat),', 15],
      ['كِرَامٍۢ بَرَرَةٍ', 'Kiraamim bararah', 'yang mulia lagi berbakti.', 16],
      ['قُتِلَ الْاِنْسَانُ مَآ اَكْفَرَهٗ', 'Qutilal insaanu maa akfarah', 'Binasalah manusia; alangkah kufurnya dia!', 17],
      ['مِنْ اَيِّ شَيْءٍ خَلَقَهٗ', 'Min ayyi syai-in khalaqah', 'Dari apakah Dia menciptakannya?', 18],
      ['مِنْ نُّطْفَةٍ خَلَقَهٗ فَقَدَّرَهٗ', 'Min nuthfatin khalaqahuu faqaddarah', 'Dari setetes mani, Dia menciptakannya lalu menentukannya (takdirnya).', 19],
      ['ثُمَّ السَّبِيْلَ يَسَّرَهٗ', 'Tsummas sabiila yassarah', 'Kemudian jalannya Dia mudahkan,', 20],
      ['ثُمَّ اَمَاتَهٗ فَاَقْبَرَهٗ', 'Tsumma amaatahuu fa-aqbarah', 'kemudian Dia mematikannya lalu memasukkannya ke dalam kubur,', 21],
      ['ثُمَّ اِذَا شَاۤءَ اَنْشَرَهٗ', 'Tsumma idzaa syaa-a ansyarah', 'kemudian jika Dia menghendaki, Dia membangkitkannya kembali.', 22],
      ['كَلَّا لَمَّا يَقْضِ مَآ اَمَرَهٗ', 'Kallaa lammaa yaqdhi maa amarah', 'Sekali-kali jangan (begitu)! Dia belum melaksanakan apa yang diperintahkan-Nya kepadanya.', 23],
      ['فَلْيَنْظُرِ الْاِنْسَانُ اِلٰى طَعَامِهٖٓ', "Falyanzhuril insaanu ilaa tha'aamih", 'Maka hendaklah manusia memperhatikan makanannya.', 24],
      ['اَنَّا صَبَبْنَا الْمَاۤءَ صَبًّا', 'Annaa shababnal maa-a shabbaa', 'Sesungguhnya Kami telah mencurahkan air (dari langit) dengan berlimpah,', 25],
      ['ثُمَّ شَقَقْنَا الْاَرْضَ شَقًّا', 'Tsumma syaqaqnal ardha syaqqaa', 'kemudian Kami belah bumi dengan sebaik-baiknya,', 26],
      ['فَاَنْۢبَتْنَا فِيْهَا حَبًّا', 'Fa-ambatnaa fiihaa habbaa', 'lalu Kami tumbuhkan padanya biji-bijian,', 27],
      ['وَّعِنَبًا وَّقَضْبًا', "Wa 'inabaw wa qadhbaa", 'dan anggur dan sayur-sayuran,', 28],
      ['وَّزَيْتُوْنًا وَّنَخْلًا', 'Wa zaituunaw wa nakhlaa', 'dan zaitun dan pohon kurma,', 29],
      ['وَحَدَاۤىِٕقَ غُلْبًا', 'Wa hadaa-iqa ghulbaa', 'dan kebun-kebun yang lebat,', 30],
      ['وَفَاكِهَةً وَّاَبًّا', 'Wa faakihataw wa abbaa', 'dan buah-buahan serta rumput-rumputan,', 31],
      ['مَّتَاعًا لَّكُمْ وَلِاَنْعَامِكُمْ', "Mataa'al lakum wa li-an'aamikum", '(semua itu) untuk kesenanganmu dan untuk hewan-hewan ternakmu.', 32],
      ['فَاِذَا جَاۤءَتِ الصَّاۤخَّةُ', 'Fa idzaa jaa-atish shaakh-khah', 'Maka apabila datang suara yang memekakkan (tiupan sangkakala kedua),', 33],
      ['يَوْمَ يَفِرُّ الْمَرْءُ مِنْ اَخِيْهِ', 'Yauma yafirrul mar-u min akhiih', 'pada hari itu manusia lari dari saudaranya,', 34],
      ['وَاُمِّهٖ وَاَبِيْهِ', 'Wa ummihii wa abiih', 'dan dari ibu dan bapaknya,', 35],
      ['وَصَاحِبَتِهٖ وَبَنِيْهِ', 'Wa shaahibatihii wa baniih', 'dan dari istri dan anak-anaknya.', 36],
      ['لِكُلِّ امْرِئٍ مِّنْهُمْ يَوْمَىِٕذٍ شَأْنٌ يُّغْنِيْهِ', "Likullimri-im minhum yauma-idzin sya'nuy yughniih", 'Setiap orang dari mereka pada hari itu mempunyai urusan yang menyibukkannya.', 37],
      ['وُجُوْهٌ يَّوْمَىِٕذٍ مُّسْفِرَةٌ', 'Wujuuhuy yauma-idzim musfirah', 'Pada hari itu ada wajah-wajah yang berseri-seri,', 38],
      ['ضَاحِكَةٌ مُّسْتَبْشِرَةٌ', 'Dhaahikatum mustabsyirah', 'tertawa dan gembira ria,', 39],
      ['وَوُجُوْهٌ يَّوْمَىِٕذٍ عَلَيْهَا غَبَرَةٌ', 'Wa wujuuhuy yauma-idzin \'alaihaa ghabarah', 'dan pada hari itu ada (pula) wajah-wajah yang tertutup debu,', 40],
      ['تَرْهَقُهَا قَتَرَةٌ', 'Tarhaquhaa qatarah', 'tertutup oleh kegelapan (suram).', 41],
      ['اُولٰۤىِٕكَ هُمُ الْكَفَرَةُ الْفَجَرَةُ', 'Ulaa-ika humul kafaratul fajarah', 'Mereka itulah orang-orang kafir lagi durhaka.', 42],
    ],
    quiz: [
      ["'Abasa artinya …", ['Bermuka masam', 'Malaikat penjaga', 'Kuda perang'], 0, "'Abasa = bermuka masam."],
      ['Sahabat tunanetra yang datang kepada Nabi Muhammad ﷺ dalam surat ini adalah …', ['Abu Bakar Ash-Shiddiq', 'Abdullah bin Ummi Maktum', 'Bilal bin Rabah'], 1, 'Abdullah bin Ummi Maktum r.a.'],
      ['Pada hari kiamat, manusia saking takutnya akan lari meninggalkan …', ['Rumah mewahnya', 'Saudara, ibu, ayah, istri, dan anak-anaknya', 'Kendaraannya'], 1, 'Setiap orang sibuk dengan urusannya sendiri dan lari dari keluarganya.'],
    ],
  },
  {
    slug: 'surat-at-takwir',
    theme: 'Surat Pendek',
    emoji: '☀️',
    title: 'Surat At-Takwir',
    titleId: 'Menggulung · 29 ayat',
    minutes: 4,
    intro:
      "**Surat ke-81** · **29 ayat** · Makkiyah.\n\n" +
      "At-Takwir artinya **menggulung (matahari)**. Menggambarkan kedahsyatan perubahan alam semesta saat hari Kiamat: matahari digulung, bintang berjatuhan, gunung dihancurkan, dan lautan meluap. Menegaskan bahwa Al-Qur'an dibawa oleh malaikat Jibril yang mulia dan terpercaya.",
    lines: [
      BASMALAH,
      ['اِذَا الشَّمْسُ كُوِّرَتْ', 'Idzasy syamsu kuwwirat', 'Apabila matahari digulung,', 1],
      ['وَاِذَا النُّجُوْمُ انْكَدَرَتْ', 'Wa idzan nujuumunkadarat', 'dan apabila bintang-bintang berjatuhan,', 2],
      ['وَاِذَا الْجِبَالُ سُيِّرَتْ', 'Wa idzal jibaalu suyyirat', 'dan apabila gunung-gunung dihancurkan,', 3],
      ['وَاِذَا الْعِشَارُ عُطِّلَتْ', "Wa idzal 'isyaaru 'uth-thilat", 'dan apabila unta-unta yang bunting ditinggalkan (tidak terurus),', 4],
      ['وَاِذَا الْوُحُوْشُ حُشِرَتْ', 'Wa idzal wuhuusyu husyirat', 'dan apabila binatang-binatang liar dikumpulkan,', 5],
      ['وَاِذَا الْبِحَارُ سُجِّرَتْ', 'Wa idzal bihaaru sujjirat', 'dan apabila lautan dipanaskan (meluap),', 6],
      ['وَاِذَا النُّفُوْسُ زُوِّجَتْ', 'Wa idzan nufuusu zuwwijat', 'dan apabila jiwa-jiwa dipertemukan (dengan jasadnya),', 7],
      ['وَاِذَا الْمَوْءٗدَةُ سُىِٕلَتْ', "Wa idzal mau-uudatu su-ilat", 'dan apabila bayi-bayi perempuan yang dikubur hidup-hidup ditanya,', 8],
      ['بِاَيِّ ذَنْۢبٍ قُتِلَتْ', 'Bi-ayyi dzambin qutilat', 'karena dosa apakah dia dibunuh?', 9],
      ['وَاِذَا الصُّحُفُ نُشِرَتْ', 'Wa idzash shuhufu nusyirat', 'Dan apabila lembaran-lembaran (catatan amal) dibuka,', 10],
      ['وَاِذَا السَّمَاۤءُ كُشِطَتْ', 'Wa idzas samaa-u kusyithat', 'dan apabila langit dilenyapkan,', 11],
      ['وَاِذَا الْجَحِيْمُ سُعِّرَتْ', "Wa idzal jahiimu su''irat", 'dan apabila neraka Jahim dinyalakan,', 12],
      ['وَاِذَا الْجَنَّةُ اُزْلِفَتْ', 'Wa idzal jannatu uzlifat', 'dan apabila surga didekatkan,', 13],
      ['عَلِمَتْ نَفْسٌ مَّآ اَحْضَرَتْ', '‘Alimat nafsum maa ahdharat', 'setiap jiwa akan mengetahui apa yang telah dikerjakannya.', 14],
      ['فَلَآ اُقْسِمُ بِالْخُنَّسِ', 'Falaa uqsimu bil khunnas', 'Aku bersumpah demi bintang-bintang,', 15],
      ['الْجَوَارِ الْكُنَّسِ', 'Al-jawaaril kunnas', 'yang beredar dan terbenam,', 16],
      ['وَالَّيْلِ اِذَا عَسْعَسَ', "'Wal laili idzaa 'as'as", 'demi malam apabila telah larut,', 17],
      ['وَالصُّبْحِ اِذَا تَنَفَّسَ', 'Wash shub-hi idzaa tanaffas', 'dan demi subuh apabila fajar telah menyingsing,', 18],
      ['اِنَّهٗ لَقَوْلُ رَسُوْلٍ كَرِيْمٍ', 'Innahuu laqaulu rasuulin kariim', 'sesungguhnya (Al-Qur\'an) itu benar-benar firman (Allah yang dibawa oleh) utusan yang mulia (Jibril),', 19],
      ['ذِيْ قُوَّةٍ عِنْدَ ذِى الْعَرْشِ مَكِيْنٍ', "Dzii quwwatin 'inda dzil 'arsyi makiin", 'yang memiliki kekuatan, memiliki kedudukan tinggi di sisi (Allah) yang memiliki \'Arsy,', 20],
      ['مُّطَاعٍ ثَمَّ اَمِيْنٍ', 'Muthaa\'in tsamma amiin', 'yang di sana (di alam malaikat) ditaati lagi dipercaya.', 21],
      ['وَمَا صَاحِبُكُمْ بِمَجْنُوْنٍ', 'Wa maa shaahibukum bimajnuun', 'Dan temanmu (Muhammad) itu bukanlah orang gila.', 22],
      ['وَلَقَدْ رَاٰهُ بِالْاُفُقِ الْمُبِيْنِ', "Wa laqad ra-aahu bil ufuqil mubiin", 'Dan sungguh, dia (Muhammad) telah melihatnya (Jibril) di ufuk yang terang.', 23],
      ['وَمَا هُوَ عَلَى الْغَيْبِ بِضَنِيْنٍ', 'Wa maa huwa \'alal ghaibi bidhaniin', 'Dan dia (Muhammad) bukanlah seorang yang kikir tentang yang gaib.', 24],
      ['وَمَا هُوَ بِقَوْلِ شَيْطٰنٍ رَّجِيْمٍ', 'Wa maa huwa biqauli syaithaanir rajiim', 'Dan (Al-Qur\'an) itu bukanlah perkataan setan yang terkutuk,', 25],
      ['فَاَيْنَ تَذْهَبُوْنَ', 'Fa aina tadz-habuun', 'maka ke manakah kamu akan pergi?', 26],
      ['اِنْ هُوَ اِلَّا ذِكْرٌ لِّلْعٰلَمِيْنَ', "In huwa illaa dzikrul lil-'aalamiin", '(Al-Qur\'an) itu tidak lain hanyalah peringatan bagi seluruh alam,', 27],
      ['لِمَنْ شَاۤءَ مِنْكُمْ اَنْ يَّسْتَقِيْمَ', 'Liman syaa-a minkum ay yastaqiim', '(yaitu) bagi siapa di antara kamu yang menghendaki menempuh jalan yang lurus.', 28],
      ['وَمَا تَشَاۤءُوْنَ اِلَّآ اَنْ يَّشَاۤءَ اللّٰهُ رَبُّ الْعٰلَمِيْنَ', "Wa maa tasyaa-uuna illaa ay yasyaa-allaahu rabbul 'aalamiin", 'Dan kamu tidak dapat menghendaki (menempuh jalan itu) kecuali apabila dikehendaki Allah, Tuhan seluruh alam.', 29],
    ],
    quiz: [
      ['At-Takwir artinya …', ['Menggulung', 'Membelah', 'Memecahkan'], 0, 'At-Takwir = menggulung (seperti matahari yang digulung cahayanya).'],
      ['Malaikat utusan yang mulia pembawa wahyu Al-Qur\'an dalam surat ini adalah Malaikat …', ['Israfil', 'Jibril', 'Izrail'], 1, 'Malaikat Jibril a.s. yang kuat dan dipercaya di sisi Allah.'],
      ['Al-Qur\'an diturunkan sebagai peringatan bagi …', ['Suku Quraisy saja', 'Seluruh alam semesta', 'Para malaikat'], 1, 'In huwa illaa dzikrul lil-\'aalamiin = peringatan bagi seluruh alam.'],
    ],
  },
  {
    slug: 'surat-al-infitar',
    theme: 'Surat Pendek',
    emoji: '🌌',
    title: 'Surat Al-Infitar',
    titleId: 'Terbelah · 19 ayat',
    minutes: 4,
    intro:
      "**Surat ke-82** · **19 ayat** · Makkiyah.\n\n" +
      "Al-Infitar artinya **terbelah (langit)**. Mengingatkan manusia yang sering tertipu oleh kenikmatan dunia hingga melupakan kemuliaan Tuhannya yang telah menciptakannya dengan sempurna. Mengabarkan malaikat pencatat amal (*Kiraaman Kaatibiin*) yang selalu mengawasi segala perbuatan.",
    lines: [
      BASMALAH,
      ['اِذَا السَّمَاۤءُ انْفَطَرَتْ', 'Idzas samaa-unfatharat', 'Apabila langit terbelah,', 1],
      ['وَاِذَا الْكَوَاكِبُ انْتَثَرَتْ', 'Wa idzal kawaakibuntatsarat', 'dan apabila bintang-bintang jatuh berserakan,', 2],
      ['وَاِذَا الْبِحَارُ فُجِّرَتْ', 'Wa idzal bihaaru fujjirat', 'dan apabila lautan meluap,', 3],
      ['وَاِذَا الْقُبُوْرُ بُعْثِرَتْ', "Wa idzal qubuuru bu'tsirat", 'dan apabila kuburan-kuburan dibongkar,', 4],
      ['عَلِمَتْ نَفْسٌ مَّا قَدَّمَتْ وَاَخَّرَتْ', "'Alimat nafsum maa qaddamat wa akh-kharat", '(maka) setiap jiwa akan mengetahui apa yang telah dikerjakan dan yang dilalaikannya.', 5],
      ['يٰٓاَيُّهَا الْاِنْسَانُ مَا غَرَّكَ بِرَبِّكَ الْكَرِيْمِ', 'Yaa ayyuhal insaanu maa gharraka birabbikal kariim', 'Wahai manusia! Apakah yang telah memperdayakan kamu (berbuat durhaka) terhadap Tuhanmu Yang Mahamulia,', 6],
      ['الَّذِيْ خَلَقَكَ فَسَوّٰىكَ فَعَدَلَكَ', 'Alladzii khalaqaka fasawwaaka fa\'adalak', 'yang telah menciptakanmu lalu menyempurnakan kejadianmu dan menjadikan (susunan tubuh)mu seimbang,', 7],
      ['فِيْٓ اَيِّ صُوْرَةٍ مَّا شَاۤءَ رَكَّبَكَ', 'Fii ayyi shuuratim maa syaa-a rakkabak', 'dalam bentuk apa saja yang dikehendaki, Dia menyusun tubuhmu.', 8],
      ['كَلَّا بَلْ تُكَذِّبُوْنَ بِالدِّيْنِ', 'Kallaa bal tukadz-dzibuuna bid-diin', 'Sekali-kali jangan begitu! Bahkan kamu mendustakan hari pembalasan.', 9],
      ['وَاِنَّ عَلَيْكُمْ لَحٰفِظِيْنَ', "Wa inna 'alaikum lahaafizhiin", 'Dan sesungguhnya bagi kamu ada (malaikat-malaikat) yang mengawasi (pekerjaanmu),', 10],
      ['كِرَامًا كَاتِبِيْنَ', 'Kiraaman kaatibiin', 'yang mulia (di sisi Allah) dan yang mencatat (amal perbuatanmu),', 11],
      ['يَعْلَمُوْنَ مَا تَفْعَلُوْنَ', "Ya'lamuuna maa taf'aluun", 'mereka mengetahui apa yang kamu kerjakan.', 12],
      ['اِنَّ الْاَبْرَارَ لَفِيْ نَعِيْمٍ', "Innal abraara lafii na'iim", 'Sesungguhnya orang-orang yang berbakti benar-benar berada dalam (surga yang penuh) kenikmatan,', 13],
      ['وَّاِنَّ الْفُجَّارَ لَفِيْ جَحِيْمٍ', 'Wa innal fujjaara lafii jahiim', 'dan sesungguhnya orang-orang yang durhaka benar-benar berada dalam neraka Jahim.', 14],
      ['يَصْلَوْنَهَا يَوْمَ الدِّيْنِ', 'Yashlaunahaa yaumad diin', 'Mereka masuk ke dalamnya pada hari pembalasan.', 15],
      ['وَمَا هُمْ عَنْهَا بِغَاۤىِٕبِيْنَ', 'Wa maa hum \'anhaa bighaa-ibiin', 'Dan mereka tidak mungkin keluar dari neraka itu.', 16],
      ['وَمَآ اَدْرٰىكَ مَا يَوْمُ الدِّيْنِ', 'Wa maa adraaka maa yaumud diin', 'Dan tahukah kamu apakah hari pembalasan itu?', 17],
      ['ثُمَّ مَآ اَدْرٰىكَ مَا يَوْمُ الدِّيْنِ', 'Tsumma maa adraaka maa yaumud diin', 'Sekali lagi, tahukah kamu apakah hari pembalasan itu?', 18],
      ['يَوْمَ لَا تَمْلِكُ نَفْسٌ لِّنَفْسٍ شَيْـًٔا وَالْاَمْرُ يَوْمَىِٕذٍ لِّلّٰهِ', "Yauma laa tamliku nafsul linafsin syai-aa, wal amru yauma-idzil lillaah", '(Yaitu) pada hari (ketika) seseorang sama sekali tidak berdaya (menolong) orang lain. Dan segala urusan pada hari itu dalam kekuasaan Allah.', 19],
    ],
    quiz: [
      ['Al-Infitar artinya …', ['Terbelah (langit)', 'Matahari terbit', 'Bulan purnama'], 0, 'Al-Infitar = terbelah.'],
      ['Nama malaikat pencatat amal yang mulia dalam surat ini adalah …', ['Kiraaman Kaatibiin', 'Malik dan Ridwan', 'Munkar dan Nakir'], 0, 'Kiraaman kaatibiin = para pencatat yang mulia.'],
      ['Pada hari pembalasan, segala urusan sepenuhnya berada dalam kekuasaan …', ['Para penguasa dunia', 'Hanya milik Allah Swt.', 'Manusia masing-masing'], 1, 'Wal amru yauma-idzil lillaah = segala urusan adalah milik Allah.'],
    ],
  },
  {
    slug: 'surat-al-muthaffifin',
    theme: 'Surat Pendek',
    emoji: '⚖️',
    title: 'Surat Al-Muthaffifin',
    titleId: 'Orang-Orang Curang · 36 ayat',
    minutes: 5,
    intro:
      "**Surat ke-83** · **36 ayat** · Makkiyah.\n\n" +
      "Al-Muthaffifin artinya **orang-orang yang curang dalam menakar dan menimbang**. Mengancam keras para pedagang atau siapapun yang mengurangi hak orang lain saat menimbang. Menjelaskan kitab catatan orang durhaka di *Sijjin* dan catatan orang berbakti di *'Illiyyin* yang dimuliakan para malaikat.",
    lines: [
      BASMALAH,
      ['وَيْلٌ لِّلْمُطَفِّفِيْنَ', 'Wailul lil muthaffifiin', 'Celakalah bagi orang-orang yang curang (dalam menakar dan menimbang)!', 1],
      ['الَّذِيْنَ اِذَا اكْتَالُوْا عَلَى النَّاسِ يَسْتَوْفُوْنَ', "Alladziina idzaktaluu 'alan naasi yastaufuun", '(Yaitu) orang-orang yang apabila menerima takaran dari orang lain mereka minta dipenuhi,', 2],
      ['وَاِذَا كَالُوْهُمْ اَوْ وَّزَنُوْهُمْ يُخْسِرُوْنَ', 'Wa idzaa kaaluuhum au wazanuuhum yukhsiruun', 'dan apabila mereka menakar atau menimbang (untuk orang lain), mereka mengurangi.', 3],
      ['اَلَا يَظُنُّ اُولٰۤىِٕكَ اَنَّهُمْ مَّبْعُوْثُوْنَ', 'A laa yazhunnu ulaa-ika annahum mab\'uutsuun', 'Tidakkah mereka itu mengira bahwa sesungguhnya mereka akan dibangkitkan,', 4],
      ['لِيَوْمٍ عَظِيْمٍ', "Liyaumin 'azhiim", 'pada suatu hari yang besar,', 5],
      ['يَّوْمَ يَقُوْمُ النَّاسُ لِرَبِّ الْعٰلَمِيْنَ', "Yauma yaquumun naasu lirabbil 'aalamiin", '(yaitu) pada hari (ketika) semua manusia bangkit menghadap Tuhan seluruh alam?', 6],
      ['كَلَّآ اِنَّ كِتٰبَ الْفُجَّارِ لَفِيْ سِجِّيْنٍ', 'Kallaa inna kitaabal fujjaari lafii sijjiin', 'Sekali-kali jangan begitu! Sesungguhnya catatan orang yang durhaka benar-benar tersimpan dalam Sijjin.', 7],
      ['وَمَآ اَدْرٰىكَ مَا سِجِّيْنٌ', 'Wa maa adraaka maa sijjiin', 'Dan tahukah kamu apakah Sijjin itu?', 8],
      ['كِتٰبٌ مَّرْقُوْمٌ', 'Kitaabum marquum', '(Yaitu) kitab yang tertulis.', 9],
      ['وَيْلٌ يَّوْمَىِٕذٍ لِّلْمُكَذِّبِيْنَ', 'Wailuy yauma-idzil lil-mukadz-dzibiin', 'Celakalah pada hari itu bagi orang-orang yang mendustakan!', 10],
      ['الَّذِيْنَ يُكَذِّبُوْنَ بِيَوْمِ الدِّيْنِ', 'Alladziina yukadz-dzibuuna biyaumid diin', '(yaitu) orang-orang yang mendustakan hari pembalasan.', 11],
      ['وَمَا يُكَذِّبُ بِهٖٓ اِلَّا كُلُّ مُعْتَدٍ اَثِيْمٍ', "Wa maa yukadz-dzibu bihii illaa kullu mu'tadin atsiim", 'Dan tidak ada yang mendustakannya melainkan setiap orang yang melampaui batas dan berdosa,', 12],
      ['اِذَا تُتْلٰى عَلَيْهِ اٰيٰتُنَا قَالَ اَسَاطِيْرُ الْاَوَّلِيْنَ', "Idzaa tutlaa 'alaihi aayaatunaa qaala asaathiirul awwaliin", 'yang apabila dibacakan kepadanya ayat-ayat Kami, dia berkata, "Itu adalah dongeng orang-orang dahulu."', 13],
      ['كَلَّا بَلْ رَانَ عَلٰى قُلُوْبِهِمْ مَّا كَانُوْا يَكْسِبُوْنَ', 'Kallaa bal raana \'alaa quluubihim maa kaanuu yaksibuun', 'Sekali-kali tidak! Bahkan apa yang mereka kerjakan itu telah menutupi hati mereka.', 14],
      ['كَلَّآ اِنَّهُمْ عَنْ رَّبِّهِمْ يَوْمَىِٕذٍ لَّمَحْجُوْبُوْنَ', 'Kallaa innahum \'an rabbihim yauma-idzil lamahjuubuun', 'Sekali-kali tidak! Sesungguhnya mereka pada hari itu benar-benar terhalang dari (melihat) Tuhannya.', 15],
      ['ثُمَّ اِنَّهُمْ لَصَالُوا الْجَحِيْمِ', 'Tsumma innahum lashaalul jahiim', 'Kemudian, sesungguhnya mereka benar-benar masuk neraka Jahim.', 16],
      ['ثُمَّ يُقَالُ هٰذَا الَّذِيْ كُنْتُمْ بِهٖ تُكَذِّبُوْنَ', 'Tsumma yuqaalu haadzal ladzii kuntum bihii tukadz-dzibuun', 'Kemudian dikatakan (kepada mereka), "Inilah (azab) yang dahulu kamu dustakan."', 17],
      ['كَلَّآ اِنَّ كِتٰبَ الْاَبْرَارِ لَفِيْ عِلِّيِّيْنَ', "Kallaa inna kitaabal abraari lafii 'illiyyiin", 'Sekali-kali tidak! Sesungguhnya catatan orang-orang yang berbakti benar-benar tersimpan dalam \'Illiyyin.', 18],
      ['وَمَآ اَدْرٰىكَ مَا عِلِّيُّوْنَ', "Wa maa adraaka maa 'illiyyuun", 'Dan tahukah kamu apakah \'Illiyyin itu?', 19],
      ['كِتٰبٌ مَّرْقُوْمٌ', 'Kitaabum marquum', '(Yaitu) kitab yang tertulis,', 20],
      ['يَّشْهَدُهُ الْمُقَرَّبُوْنَ', 'Yasyhaduhul muqarrabuun', 'yang disaksikan oleh (malaikat-malaikat) yang didekatkan (kepada Allah).', 21],
      ['اِنَّ الْاَبْرَارَ لَفِيْ نَعِيْمٍ', "Innal abraara lafii na'iim", 'Sesungguhnya orang-orang yang berbakti benar-benar berada dalam (surga yang penuh) kenikmatan,', 22],
      ['عَلَى الْاَرَاۤىِٕكِ يَنْظُرُوْنَ', "‘Alal araa-iki yanzhuruun", 'mereka (duduk) di atas dipan-dipan melepas pandangan.', 23],
      ['تَعْرِفُ فِيْ وُجُوْهِهِمْ نَضْرَةَ النَّعِيْمِ', "Ta'rifu fii wujuuhihim nadhratan na'iim", 'Kamu dapat mengetahui dari wajah mereka kesenangan hidup yang penuh kenikmatan.', 24],
      ['يُسْقَوْنَ مِنْ رَّحِيْقٍ مَّخْتُوْمٍ', 'Yusqauna mir rahiiqim makhtuum', 'Mereka diberi minum dari khamar murni yang (tempatnya) masih dilak (disegel),', 25],
      ['خِتٰمُهٗ مِسْكٌ وَفِيْ ذٰلِكَ فَلْيَتَنَافَسِ الْمُتَنَافِسُوْنَ', 'Khitaamuhuu misk, wa fii dzaalika falyatanaafasil mutanaafisuun', 'laknya adalah kesturi. Dan untuk yang demikian itu hendaknya orang berlomba-lomba.', 26],
      ['وَمِزَاجُهٗ مِنْ تَسْنِيْمٍ', 'Wa mizaajuhuu min tasniim', 'Dan campurannya adalah dari Tasnim,', 27],
      ['عَيْنًا يَّشْرَبُ بِهَا الْمُقَرَّبُوْنَ', '‘Ainay yasyrabu bihal muqarrabuun', '(yaitu) mata air yang diminum oleh mereka yang dekat (kepada Allah).', 28],
      ['اِنَّ الَّذِيْنَ اَجْرَمُوْا كَانُوْا مِنَ الَّذِيْنَ اٰمَنُوْا يَضْحَكُوْنَ', 'Innal ladziina ajramuu kaanuu minal ladziina aamanuu yadh-hakuun', 'Sesungguhnya orang-orang yang berdosa dahulu menertawakan orang-orang yang beriman.', 29],
      ['وَاِذَا مَرُّوْا بِهِمْ يَتَغَامَزُوْنَ', 'Wa idzaa marruu bihim yataghaamazuun', 'Dan apabila mereka (orang mukmin) melintas di hadapan mereka, mereka saling mengedipkan mata,', 30],
      ['وَاِذَا انْقَلَبُوْٓا اِلٰٓى اَهْلِهِمُ انْقَلَبُوْا فَكِهِيْنَ', 'Wa idzanqalabuu ilaa ahlihimunqalabuu fakihiin', 'dan apabila mereka kembali kepada keluarganya, mereka kembali dengan gembira ria (mengejek),', 31],
      ['وَاِذَا رَاَوْهُمْ قَالُوْٓا اِنَّ هٰٓؤُلَاۤءِ لَضَاۤلُّوْنَ', 'Wa idzaa ra-auhum qaaluu inna haa-ulaa-i ladhaalluun', 'dan apabila mereka melihatnya, mereka berkata, "Sesungguhnya mereka benar-benar orang yang sesat."', 32],
      ['وَمَآ اُرْسِلُوْا عَلَيْهِمْ حٰفِظِيْنَ', 'Wa maa ursiluu \'alaihim haafizhiin', 'Padahal mereka tidak diutus sebagai penjaga bagi orang-orang mukmin.', 33],
      ['فَالْيَوْمَ الَّذِيْنَ اٰمَنُوْا مِنَ الْكُفَّارِ يَضْحَكُوْنَ', 'Fal yaumal ladziina aamanuu minal kuffaari yadh-hakuun', 'Maka pada hari ini, orang-orang yang beriman yang menertawakan orang-orang kafir,', 34],
      ['عَلَى الْاَرَاۤىِٕكِ يَنْظُرُوْنَ', "‘Alal araa-iki yanzhuruun", 'mereka (duduk) di atas dipan-dipan melepas pandangan.', 35],
      ['هَلْ ثُوِّبَ الْكُفَّارُ مَا كَانُوْا يَفْعَلُوْنَ', 'Hal tsuwwibal kuffaaru maa kaanuu yaf\'aluun', 'Apakah orang-orang kafir itu telah diberi balasan (hukuman) terhadap apa yang telah mereka perbuat?', 36],
    ],
    quiz: [
      ['Al-Muthaffifin artinya …', ['Orang-orang yang curang dalam menakar/menimbang', 'Para pedagang yang jujur', 'Pemberi sedekah'], 0, 'Al-Muthaffifin = orang-orang yang curang.'],
      ['Buku catatan amal orang yang durhaka tersimpan di dalam …', ['Sijjin', "'Illiyyin", 'Mizan'], 0, 'Kallaa inna kitaabal fujjaari lafii sijjiin.'],
      ['Sedangkan catatan amal orang-orang yang berbakti (al-abraar) tersimpan di …', ["'Illiyyin", 'Sijjin', 'Bumi ketujuh'], 0, "Inna kitaabal abraari lafii 'Illiyyiin."],
    ],
  },
  {
    slug: 'surat-al-insyiqaq',
    theme: 'Surat Pendek',
    emoji: '🌌',
    title: 'Surat Al-Insyiqaq',
    titleId: 'Terbelah · 25 ayat',
    minutes: 4,
    intro:
      "**Surat ke-84** · **25 ayat** · Makkiyah.\n\n" +
      "Al-Insyiqaq artinya **terbelah (langit)**. Menggambarkan ketaatan langit dan bumi pada perintah Tuhannya saat kiamat tiba. Menjelaskan dua golongan penerima buku catatan amal: orang yang menerima buku dari sebelah kanannya akan dihisab dengan hisab yang mudah, sedangkan yang menerima dari belakang punggungnya akan berteriak celaka dan masuk neraka Sa'ir.",
    lines: [
      BASMALAH,
      ['اِذَا السَّمَاۤءُ انْشَقَّتْ', 'Idzas samaa-unsyaqqat', 'Apabila langit terbelah,', 1],
      ['وَاَذِنَتْ لِرَبِّهَا وَحُقَّتْ', 'Wa adzinat lirabbihaa wa huqqat', 'dan patuh kepada Tuhannya, dan sudah semestinya patuh,', 2],
      ['وَاِذَا الْاَرْضُ مُدَّتْ', 'Wa idzal ardhu muddat', 'dan apabila bumi diratakan,', 3],
      ['وَاَلْقَتْ مَا فِيْهَا وَتَخَلَّتْ', 'Wa alqat maa fiihaa wa takhallat', 'dan memuntahkan apa yang ada di dalamnya dan menjadi kosong,', 4],
      ['وَاَذِنَتْ لِرَبِّهَا وَحُقَّتْ', 'Wa adzinat lirabbihaa wa huqqat', 'dan patuh kepada Tuhannya, dan sudah semestinya patuh.', 5],
      ['يٰٓاَيُّهَا الْاِنْسَانُ اِنَّكَ كَادِحٌ اِلٰى رَبِّكَ كَدْحًا فَمُلٰقِيْهِ', 'Yaa ayyuhal insaanu innaka kaadihun ilaa rabbika kad-han famulaaqiih', 'Wahai manusia! Sesungguhnya kamu telah bekerja keras menuju Tuhanmu, maka kamu pasti akan menemui-Nya.', 6],
      ['فَاَمَّا مَنْ اُوْتِيَ كِتٰبَهٗ بِيَمِيْنِهٖ', 'Fa ammaa man uutiya kitaabahuu biyamiinih', 'Maka adapun orang yang diberikan kitabnya dari sebelah kanannya,', 7],
      ['فَسَوْفَ يُحَاسَبُ حِسَابًا يَّسِيْرًا', 'Fa saufa yuhaasabu hisaabay yasiiraa', 'maka dia akan dihisab dengan hisab yang mudah,', 8],
      ['وَّيَنْقَلِبُ اِلٰٓى اَهْلِهٖ مَسْرُوْرًا', 'Wa yanqalibu ilaa ahlihii masruuraa', 'dan dia akan kembali kepada keluarganya (yang sama-sama beriman) dengan gembira.', 9],
      ['وَاَمَّا مَنْ اُوْتِيَ كِتٰبَهٗ وَرَاۤءَ ظَهْرِهٖ', 'Wa ammaa man uutiya kitaabahuu waraa-a zhahrih', 'Dan adapun orang yang diberikan kitabnya dari belakang punggungnya,', 10],
      ['فَسَوْفَ يَدْعُوْا ثُبُوْرًا', 'Fa saufa yad\'uu tsubuuraa', 'maka dia akan berteriak, "Celakalah aku!"', 11],
      ['وَّيَصْلٰى سَعِيْرًا', "Wa yashlaa sa'iiraa", 'Dan dia akan masuk ke dalam api yang menyala-nyala (neraka).', 12],
      ['اِنَّهٗ كَانَ فِيْٓ اَهْلِهٖ مَسْرُوْرًا', 'Innahuu kaana fii ahlihii masruuraa', 'Sesungguhnya dahulu dia (di dunia) bergembira di kalangan keluarganya (dalam kedurhakaan).', 13],
      ['اِنَّهٗ ظَنَّ اَنْ لَّنْ يَّحُوْرَ', 'Innahuu zhanna al lay yahuur', 'Sesungguhnya dia mengira bahwa dia tidak akan kembali (kepada Tuhannya).', 14],
      ['بَلٰىٓ اِنَّ رَبَّهٗ كَانَ بِهٖ بَصِيْرًا', 'Balaa inna rabbahuu kaana bihii bashiiraa', 'Bahkan sungguh, Tuhannya selalu melihatnya.', 15],
      ['فَلَآ اُقْسِمُ بِالشَّفَقِ', 'Falaa uqsimu bisy syafaq', 'Maka Aku bersumpah demi cahaya merah pada waktu senja,', 16],
      ['وَالَّيْلِ وَمَا وَسَقَ', 'Wal laili wa maa wasaq', 'demi malam dan apa yang diselubunginya,', 17],
      ['وَالْقَمَرِ اِذَا اتَّسَقَ', 'Wal qamari idzattasaq', 'demi bulan apabila telah purnama,', 18],
      ['لَتَرْكَبُنَّ طَبَقًا عَنْ طَبَقٍ', "Latarkabunna thabaqan 'an thabaq", 'sungguh, kamu akan menjalani tingkat demi tingkat (dalam kehidupan).', 19],
      ['فَمَا لَهُمْ لَا يُؤْمِنُوْنَ', "Fa maa lahum laa yu'minuun", 'Maka mengapa mereka tidak mau beriman?', 20],
      ['وَاِذَا قُرِئَ عَلَيْهِمُ الْقُرْاٰنُ لَا يَسْجُدُوْنَ', 'Wa idzaa quri-a \'alaihimul qur-aanu laa yasjuduun', 'Dan apabila Al-Qur\'an dibacakan kepada mereka, mereka tidak mau bersujud,', 21],
      ['بَلِ الَّذِيْنَ كَفَرُوْا يُكَذِّبُوْنَ', 'Balil ladziina kafaruu yukadz-dzibuun', 'bahkan orang-orang kafir itu mendustakan(nya).', 22],
      ['وَاللّٰهُ اَعْلَمُ بِمَا يُوْعُوْنَ', "Wallaahu a'lamu bimaa yuu'uun", 'Dan Allah lebih mengetahui apa yang mereka sembunyikan (dalam hati mereka).', 23],
      ['فَبَشِّرْهُمْ بِعَذَابٍ اَلِيْمٍ', "Fabasy-syirhum bi'adzaabin aliim", 'Maka sampaikanlah kabar gembira kepada mereka (dengan) azab yang pedih,', 24],
      ['اِلَّا الَّذِيْنَ اٰمَنُوْا وَعَمِلُوا الصّٰلِحٰتِ لَهُمْ اَجْرٌ غَيْرُ مَمْنُوْنٍ', "Illal ladziina aamanuu wa 'amilush shaalihaati lahum ajrun ghairu mamnuun", 'kecuali orang-orang yang beriman dan mengerjakan kebajikan; mereka akan mendapat pahala yang tidak putus-putusnya.', 25],
    ],
    quiz: [
      ['Al-Insyiqaq artinya …', ['Terbelah (langit)', 'Malam hari', 'Waktu fajar'], 0, 'Al-Insyiqaq = terbelah.'],
      ['Bagaimana keadaan orang yang menerima kitab catatan amalnya dari sebelah kanan?', ['Dihisab dengan hisab yang mudah', 'Dilempar ke neraka', 'Ketakutan menangis'], 0, 'Fa saufa yuhaasabu hisaabay yasiiraa = dihisab dengan hisab yang mudah.'],
      ['Orang yang menerima kitab dari belakang punggungnya akan …', ['Mendapat hadiah', 'Masuk ke neraka yang menyala-nyala (Sa\'ir)', 'Tertawa gembira'], 1, 'Wa yashlaa sa\'iiraa = masuk neraka Sa\'ir.'],
    ],
  },
];
