// Surat Pendek Juz 30 — Bagian 1B: Surat 85 s.d. 90.
// Teks Arab berharakat standar Mushaf Kemenag RI, transliterasi Latin, dan terjemahan resmi Kemenag RI.

import type { SeedLesson } from './types';
import { BASMALAH } from './surat-pendek-105-114';

export const suratPendek85to90: SeedLesson[] = [
  {
    slug: 'surat-al-buruj',
    theme: 'Surat Pendek',
    emoji: '🌌',
    title: 'Surat Al-Buruj',
    titleId: 'Gugusan Bintang · 22 ayat',
    minutes: 4,
    intro:
      "**Surat ke-85** · **22 ayat** · Makkiyah.\n\n" +
      "Al-Buruj artinya **gugusan bintang**. Menceritakan keteguhan iman orang-orang mukmin dalam kisah *Ashabul Ukhdud* (orang-orang yang dilempar ke parit berapi karena beriman kepada Allah). Menegaskan bahwa siksa Allah sangat pedih dan Al-Qur'an tersimpan mulia di Lauh Mahfuzh.",
    lines: [
      BASMALAH,
      ['وَالسَّمَاءِ ذَاتِ الْبُرُوْجِ', 'Was samaa-i dzaatil buruuj', 'Demi langit yang mempunyai gugusan bintang,', 1],
      ['وَالْيَوْمِ الْمَوْعُوْدِ', 'Wal yaumil mau\'uud', 'dan demi hari yang dijanjikan (hari Kiamat),', 2],
      ['وَشَاهِدٍ وَّمَشْهُوْدٍ', 'Wa syaahidiw wa masyhuud', 'demi yang menyaksikan dan yang disaksikan.', 3],
      ['قُتِلَ اَصْحٰبُ الْاُخْدُوْدِ', "Qutila ash-haabul ukhduud", 'Binasalah orang-orang yang membuat parit (berapi),', 4],
      ['النَّارِ ذَاتِ الْوَقُوْدِ', 'An-naari dzaatil waquud', '(yaitu) api yang mempunyai kayu bakar,', 5],
      ['اِذْ هُمْ عَلَيْهَا قُعُوْدٌ', "Idz hum 'alaihaa qu'uud", 'ketika mereka duduk di sekitarnya,', 6],
      ['وَهُمْ عَلٰى مَا يَفْعَلُوْنَ بِالْمُؤْمِنِيْنَ شُهُوْدٌ', "Wa hum 'alaa maa yaf'aluuna bil-mu'miniina syuhuud", 'sedang mereka menyaksikan apa yang mereka perbuat terhadap orang-orang mukmin.', 7],
      ['وَمَا نَقَمُوْا مِنْهُمْ اِلَّآ اَنْ يُّؤْمِنُوْا بِاللّٰهِ الْعَزِيْزِ الْحَمِيْدِ', "Wa maa naqamuu minhum illaa ay yu'minuu billaahil 'aziizil hamiid", 'Dan mereka tidak menyiksa orang-orang mukmin itu melainkan karena mereka beriman kepada Allah Yang Mahaperkasa, Maha Terpuji,', 8],
      ['الَّذِيْ لَهٗ مُلْكُ السَّمٰوٰتِ وَالْاَرْضِ وَاللّٰهُ عَلٰى كُلِّ شَيْءٍ شَهِيْدٌ', "Alladzii lahuu mulkus samaawaati wal ardh, wallaahu 'alaa kulli syai-in syahiid", 'yang memiliki kerajaan langit dan bumi. Dan Allah Maha Menyaksikan segala sesuatu.', 9],
      ['اِنَّ الَّذِيْنَ فَتَنُوا الْمُؤْمِنِيْنَ وَالْمُؤْمِنٰتِ ثُمَّ لَمْ يَتُوْبُوْا فَلَهُمْ عَذَابُ جَهَنَّمَ وَلَهُمْ عَذَابُ الْحَرِيْقِ', "Innal ladziina fatanul mu'miniina wal mu'minaati tsumma lam yatuubuu fa lahum 'adzaabu jahannama wa lahum 'adzaabul hariiq", 'Sungguh, orang-orang yang mendatangkan cobaan (siksaan) kepada orang-orang mukmin laki-laki dan perempuan lalu mereka tidak bertobat, maka mereka akan mendapat azab Jahanam dan azab (neraka) yang membakar.', 10],
      ['اِنَّ الَّذِيْنَ اٰمَنُوْا وَعَمِلُوا الصّٰلِحٰتِ لَهُمْ جَنّٰتٌ تَجْرِيْ مِنْ تَحْتِهَا الْاَنْهٰرُ ذٰلِكَ الْفَوْزُ الْكَبِيْرُ', "Innal ladziina aamanuu wa 'amilush shaalihaati lahum jannaatun tajrii min tahtihal anhaaru dzaalikal fauzul kabiir", 'Sungguh, orang-orang yang beriman dan mengerjakan kebajikan, mereka akan mendapat surga yang mengalir di bawahnya sungai-sungai; itulah kemenangan yang agung.', 11],
      ['اِنَّ بَطْشَ رَبِّكَ لَشَدِيْدٌ', 'Inna bath-sya rabbika lasyadiid', 'Sungguh, azab Tuhanmu sangat keras.', 12],
      ['اِنَّهٗ هُوَ يُبْدِئُ وَيُعِيْدُ', "Innahuu huwa yubdi-u wa yu'iid", 'Sungguh, Dialah yang memulai penciptaan (makhluk) dan yang menghidupkannya (kembali).', 13],
      ['وَهُوَ الْغَفُوْرُ الْوَدُوْدُ', 'Wa huwal ghafuurul waduud', 'Dan Dialah Yang Maha Pengampun, Maha Penyayang,', 14],
      ['ذُو الْعَرْشِ الْمَجِيْدُ', "Dzul 'arsyil majiid", 'pemilik \'Arsy yang mahamulia,', 15],
      ['فَعَّالٌ لِّمَا يُرِيْدُ', "Fa''aalul limaa yuriid", 'Maha Kuasa berbuat apa yang Dia kehendaki.', 16],
      ['هَلْ اَتٰىكَ حَدِيْثُ الْجُنُوْدِ', 'Hal ataaka hadiitsul junuud', 'Sudahkah sampai kepadamu berita tentang bala tentara,', 17],
      ['فِرْعَوْنَ وَثَمُوْدَ', "Fir'auna wa tsamuud", '(yaitu) Fir\'aun dan Tsamud?', 18],
      ['بَلِ الَّذِيْنَ كَفَرُوْا فِيْ تَكْذِيْبٍ', 'Balil ladziina kafaruu fii takdziib', 'Bahkan orang-orang kafir (selalu) dalam kedustaan,', 19],
      ['وَاللّٰهُ مِنْ وَّرَاۤىِٕهِمْ مُّحِيْطٌ', "Wallaahu miw waraa-ihim muhiith", 'padahal Allah mengepung mereka dari belakang mereka.', 20],
      ['بَلْ هُوَ قُرْاٰنٌ مَّجِيْدٌ', "Bal huwa qur-aanum majiid", 'Bahkan (yang didustakan itu) adalah Al-Qur\'an yang mulia,', 21],
      ['فِيْ لَوْحٍ مَّحْفُوْظٍ', 'Fii lauhim mahfuuzh', 'yang (tersimpan) dalam Lauh Mahfuzh.', 22],
    ],
    quiz: [
      ['Al-Buruj artinya …', ['Gugusan bintang', 'Kuda perang', 'Waktu fajar'], 0, 'Al-Buruj = gugusan bintang.'],
      ['Kisah orang-orang yang dilemparkan ke parit api karena beriman disebut kisah …', ['Ashabul Kahfi', 'Ashabul Ukhdud', 'Ashabul Fil'], 1, 'Ashabul Ukhdud adalah para pembuat parit api yang menyiksa kaum mukmin.'],
      ['Di manakah Al-Qur\'an yang mulia terjaga dan tersimpan?', ['Lauh Mahfuzh', 'Gua Tursina', 'Baitul Maqdis'], 0, 'Fii lauhim mahfuuzh = tersimpan aman di Lauh Mahfuzh.'],
    ],
  },
  {
    slug: 'surat-at-tariq',
    theme: 'Surat Pendek',
    emoji: '⭐',
    title: 'Surat At-Tariq',
    titleId: 'Yang Datang di Malam Hari · 17 ayat',
    minutes: 3,
    intro:
      "**Surat ke-86** · **17 ayat** · Makkiyah.\n\n" +
      "At-Tariq artinya **bintang yang datang pada malam hari menembus kegelapan**. Menjelaskan penciptaan manusia dari air yang terpancar, kekuasaan Allah membangkitkan manusia kembali pada hari kiamat ketika segala rahasia diuji, serta kebenaran Al-Qur'an sebagai pemutus perkara.",
    lines: [
      BASMALAH,
      ['وَالسَّمَاءِ وَالطَّارِقِ', 'Was samaa-i wath thaariq', 'Demi langit dan yang datang pada malam hari,', 1],
      ['وَمَآ اَدْرٰىكَ مَا الطَّارِقُ', 'Wa maa adraaka math thaariq', 'dan tahukah kamu apakah yang datang pada malam hari itu?', 2],
      ['النَّجْمُ الثَّاقِبُ', 'An-najmuts tsaaqib', '(yaitu) bintang yang bersinar tajam (menembus kegelapan),', 3],
      ['اِنْ كُلُّ نَفْسٍ لَّمَّا عَلَيْهَا حَافِظٌ', "In kullu nafsil lammaa 'alaihaa haafizh", 'setiap jiwa pasti ada penjaganya.', 4],
      ['فَلْيَنْظُرِ الْاِنْسَانُ مِمَّ خُلِقَ', "Falyanzhuril insaanu mimma khuliq", 'Maka hendaklah manusia memperhatikan dari apa dia diciptakan.', 5],
      ['خُلِقَ مِنْ مَّآءٍ دَافِقٍ', "Khuliqa mim maa-in daafiq", 'Dia diciptakan dari air (mani) yang terpancar,', 6],
      ['يَّخْرُجُ مِنْۢ بَيْنِ الصُّلْبِ وَالتَّرَاۤىِٕبِ', "Yakhruju mim bainish shulbi wat taraa-ib", 'yang keluar dari antara tulang punggung dan tulang dada.', 7],
      ['اِنَّهٗ عَلٰى رَجْعِهٖ لَقَادِرٌ', "Innahuu 'alaa raj'ihii laqaadir", 'Sungguh, Allah benar-benar kuasa untuk mengembalikannya (hidup kembali),', 8],
      ['يَوْمَ تُبْلَى السَّرَاۤىِٕرُ', 'Yauma tublas saraa-ir', 'pada hari ditampakkannya segala rahasia,', 9],
      ['فَمَا لَهٗ مِنْ قُوَّةٍ وَّلَا نَاصِرٍ', "Fa maa lahuu min quwwatiw wa laa naashir", 'maka manusia tidak lagi mempunyai suatu kekuatan dan tidak (pula) penolong.', 10],
      ['وَالسَّمَاءِ ذَاتِ الرَّجْعِ', "Was samaa-i dzaatir raj'", 'Demi langit yang mengandung hujan,', 11],
      ['وَالْاَرْضِ ذَاتِ الصَّدْعِ', "Wal ardhi dzaatish shad'", 'dan demi bumi yang mempunyai belahan (tumbuh-tumbuhan),', 12],
      ['اِنَّهٗ لَقَوْلٌ فَصْلٌ', 'Innahuu laqaulun fashl', 'sungguh, (Al-Qur\'an) itu benar-benar firman pemutus (kebenaran dan kebatilan),', 13],
      ['وَمَا هُوَ بِالْهَزْلِ', 'Wa maa huwa bil hazl', 'dan bukanlah perkataan yang senda gurau.', 14],
      ['اِنَّهُمْ يَكِيْدُوْنَ كَيْدًا', 'Innahum yakiiduuna kaidaa', 'Sungguh, mereka (orang kafir) merencanakan tipu daya yang jahat,', 15],
      ['وَاَكِيْدُ كَيْدًا', 'Wa akiidu kaidaa', 'dan Aku pun membuat rencana (balasan) yang pasti.', 16],
      ['فَمَهِّلِ الْكٰفِرِيْنَ اَمْهِلْهُمْ رُوَيْدًا', 'Fa mahhilil kaafiriina amhilhum ruwaidaa', 'Karena itu berilah penangguhan kepada orang-orang kafir itu, berilah mereka kesempatan barang sejenak.', 17],
    ],
    quiz: [
      ['At-Tariq artinya …', ['Bintang malam yang bersinar tajam', 'Matahari terbit', 'Bulan purnama'], 0, 'At-Tariq = bintang penembus kegelapan malam.'],
      ['Al-Qur\'an dalam surat ini disifatkan sebagai "Qaulun Fashl" yang artinya …', ['Perkataan senda gurau', 'Firman pemutus antara kebenaran dan kebatilan', 'Buku dongeng masa lalu'], 1, 'Innahuu laqaulun fashl = firman pemutus kebenaran dan kebatilan.'],
      ['Pada hari kiamat, apa yang akan terjadi menurut ayat ke-9?', ['Segala rahasia batin akan diuji dan ditampakkan', 'Hujan emas turun', 'Matahari padam seketika'], 0, 'Yauma tublas saraa-ir = pada hari ditampakkannya segala rahasia.'],
    ],
  },
  {
    slug: 'surat-al-ala',
    theme: 'Surat Pendek',
    emoji: '🏔️',
    title: "Surat Al-A'la",
    titleId: 'Yang Maha Tinggi · 19 ayat',
    minutes: 4,
    intro:
      "**Surat ke-87** · **19 ayat** · Makkiyah.\n\n" +
      "Al-A'la artinya **Yang Maha Tinggi**. Sangat dicintai oleh Rasulullah ﷺ dan sering dibaca pada salat Jumat, Idulfitri, Iduladha, dan witir. Memerintahkan bertasbih menyucikan nama Allah, memberi kabar gembira bahwa Nabi tidak akan lupa Al-Qur'an, dan mengingatkan bahwa kehidupan akhirat lebih baik dan lebih kekal.",
    lines: [
      BASMALAH,
      ['سَبِّحِ اسْمَ رَبِّكَ الْاَعْلَى', "Sabbihisma rabbikal a'laa", 'Sucikanlah nama Tuhanmu Yang Mahatinggi,', 1],
      ['الَّذِيْ خَلَقَ فَسَوّٰى', 'Alladzii khalaqa fa sawwaa', 'yang menciptakan, lalu menyempurnakan (ciptaan-Nya),', 2],
      ['وَالَّذِيْ قَدَّرَ فَهَدٰى', 'Walladzii qaddara fa hadaa', 'yang menentukan kadar (masing-masing) dan memberi petunjuk,', 3],
      ['وَالَّذِيْٓ اَخْرَجَ الْمَرْعٰى', "Walladzii akhrajal mar'aa", 'dan yang menumbuhkan rerumputan,', 4],
      ['فَجَعَلَهٗ غُثَاۤءً اَحْوٰى', "Fa ja'alahuu ghutsaa-an ahwaa", 'lalu menjadikannya kering kehitam-hitaman.', 5],
      ['سَنُقْرِئُكَ فَلَا تَنْسٰى', 'Sanuqri-uka falaa tansaa', 'Kami akan membacakan (Al-Qur\'an) kepadamu (Muhammad) sehingga engkau tidak akan lupa,', 6],
      ['اِلَّا مَا شَاۤءَ اللّٰهُ اِنَّهٗ يَعْلَمُ الْجَهْرَ وَمَا يَخْفٰى', "Illaa maa syaa-allaah, innahuu ya'lamul jahra wa maa yakhfaa", 'kecuali jika Allah menghendaki. Sungguh, Dia mengetahui yang terang dan yang tersembunyi.', 7],
      ['وَنُيَسِّرُكَ لِلْيُسْرٰى', 'Wa nuyassiruka lil yusraa', 'Dan Kami akan memudahkan bagimu jalan kemudahan (dalam segala urusan).', 8],
      ['فَذَكِّرْ اِنْ نَّفَعَتِ الذِّكْرٰى', 'Fa dzakkir in nafa\'atidz dzikraa', 'Oleh sebab itu berikanlah peringatan, karena peringatan itu bermanfaat,', 9],
      ['سَيَذَّكَّرُ مَنْ يَّخْشٰى', "Sayadz-dzakkaru may yakhsyaa", 'orang yang takut (kepada Allah) akan mendapat pelajaran,', 10],
      ['وَيَتَجَنَّبُهَا الْاَشْقَى', 'Wa yatajannabuhal asyqaa', 'dan orang yang celaka (kafir) akan menjauhinya,', 11],
      ['الَّذِيْ يَصْلَى النَّارَ الْكُبْرٰى', 'Alladzii yashlan naaral kubraa', '(yaitu) orang yang akan memasuki api yang besar (neraka).', 12],
      ['ثُمَّ لَا يَمُوْتُ فِيْهَا وَلَا يَحْيٰى', 'Tsumma laa yamuutu fiihaa wa laa yahyaa', 'Selanjutnya dia di sana tidak mati dan tidak (pula) hidup.', 13],
      ['قَدْ اَفْلَحَ مَنْ تَزَكّٰى', 'Qad aflaha man tazakkaa', 'Sungguh beruntung orang yang menyucikan diri (dengan beriman),', 14],
      ['وَذَكَرَ اسْمَ رَبِّهٖ فَصَلّٰى', 'Wa dzakarasma rabbihii fa shallaa', 'dan mengingat nama Tuhannya, lalu dia salat.', 15],
      ['بَلْ تُؤْثِرُوْنَ الْحَيٰوةَ الدُّنْيَا', "Bal tu'tsiruunal hayaatad dun-yaa", 'Tetapi kamu (orang-orang kafir) memilih kehidupan duniawi,', 16],
      ['وَالْاٰخِرَةُ خَيْرٌ وَّاَبْقٰى', 'Wal aakhiratu khairuw wa abqaa', 'padahal kehidupan akhirat itu lebih baik dan lebih kekal.', 17],
      ['اِنَّ هٰذَا لَفِى الصُّحُفِ الْاُوْلٰى', 'Inna haadzaa lafish suhufil uulaa', 'Sesungguhnya ini terdapat dalam kitab-kitab yang terdahulu,', 18],
      ['صُحُفِ اِبْرٰهِيْمَ وَمُوْسٰى', 'Suhufi ibraahiima wa muusaa', '(yaitu) kitab-kitab Ibrahim dan Musa.', 19],
    ],
    quiz: [
      ["Al-A'la artinya …", ['Yang Maha Pengasih', 'Yang Mahatinggi', 'Yang Maha Melihat'], 1, "Al-A'la = Yang Maha Tinggi."],
      ['Menurut ayat ke-17, kehidupan yang lebih baik dan lebih kekal adalah kehidupan …', ['Dunia', 'Akhirat', 'Mimpi'], 1, 'Wal aakhiratu khairuw wa abqaa = akhirat lebih baik dan lebih kekal.'],
      ['Ajaran dalam surat Al-A\'la ini juga terdapat dalam lembaran suci (suhuf) Nabi …', ['Nuh dan Luth', 'Ibrahim dan Musa', 'Daud dan Sulaiman'], 1, 'Suhufi Ibraahiima wa Muusaa = suhuf Ibrahim dan Musa.'],
    ],
  },
  {
    slug: 'surat-al-ghasyiyah',
    theme: 'Surat Pendek',
    emoji: '🌾',
    title: 'Surat Al-Ghasyiyah',
    titleId: 'Hari Kiamat yang Menyelubungi · 26 ayat',
    minutes: 4,
    intro:
      "**Surat ke-88** · **26 ayat** · Makkiyah.\n\n" +
      "Al-Ghasyiyah artinya **hari pembalasan yang menyelubungi semua manusia**. Menggambarkan wajah orang-orang celaka yang tertunduk hina di neraka, dan wajah orang-orang beriman yang berseri-seri penuh kenikmatan di surga. Diakhiri ajakan memperhatikan tanda kebesaran Allah pada unta, langit, gunung, dan bumi.",
    lines: [
      BASMALAH,
      ['هَلْ اَتٰىكَ حَدِيْثُ الْغَاشِيَةِ', 'Hal ataaka hadiitsul ghaasyiyah', 'Sudahkah sampai kepadamu berita tentang hari Kiamat (yang menyelubungi)?', 1],
      ['وُجُوْهٌ يَّوْمَىِٕذٍ خَاشِعَةٌ', "Wujuuhuy yauma-idzin khaasyi'ah", 'Pada hari itu banyak wajah yang tertunduk terhina,', 2],
      ['عَامِلَةٌ نَّاصِبَةٌ', "‘Aamilatun naashibah", 'bekerja keras lagi kepayahan,', 3],
      ['تَصْلٰى نَارًا حَامِيَةً', 'Tashlaa naaran haamiyah', 'memasuki api yang sangat panas (neraka),', 4],
      ['تُسْقٰى مِنْ عَيْنٍ اٰنِيَةٍ', 'Tusqaa min \'ainin aaniyah', 'diberi minum dari sumber mata air yang sangat panas.', 5],
      ['لَيْسَ لَهُمْ طَعَامٌ اِلَّا مِنْ ضَرِيْعٍ', "Laisa lahum tha'aamun illaa min dharii'", 'Tidak ada makanan bagi mereka selain dari pohon berduri,', 6],
      ['لَا يُسْمِنُ وَلَا يُغْنِيْ مِنْ جُوْعٍ', 'Laa yusminu wa laa yughnii min juu\'', 'yang tidak menggemukkan dan tidak menghilangkan lapar.', 7],
      ['وُجُوْهٌ يَّوْمَىِٕذٍ نَّاعِمَةٌ', "Wujuuhuy yauma-idzin naa'imah", 'Pada hari itu banyak (pula) wajah yang berseri-seri,', 8],
      ['لِّسَعْيِهَا رَاضِيَةٌ', "Li sa'yihaa raadhiyah", 'merasa senang karena usahanya (kebaikan di dunia),', 9],
      ['فِيْ جَنَّةٍ عَالِيَةٍ', "Fii jannatin 'aaliyah", 'dalam surga yang tinggi,', 10],
      ['لَّا تَسْمَعُ فِيْهَا لَاغِيَةً', "Laa tasma'u fiihaa laaghiyah", 'di sana kamu tidak mendengar perkataan yang tidak berguna.', 11],
      ['فِيْهَا عَيْنٌ جَارِيَةٌ', "Fiihaa 'ainun jaariyah", 'Di sana ada mata air yang mengalir.', 12],
      ['فِيْهَا سُرُرٌ مَّرْفُوْعَةٌ', 'Fiihaa sururum marfuu\'ah', 'Di sana ada dipan-dipan yang ditinggikan,', 13],
      ['وَّاَكْوَابٌ مَّوْضُوْعَةٌ', "Wa akwaabum maudhuu'ah", 'dan gelas-gelas yang tersedia (di dekatnya),', 14],
      ['وَّنَمَارِقُ مَصْفُوْفَةٌ', 'Wa namaariqu mashfuufah', 'dan bantal-bantal sandaran yang tersusun,', 15],
      ['وَّزَرَابِيُّ مَبْثُوْثَةٌ', 'Wa zaraabiyyu mabtsuuttsah', 'dan permadani-permadani yang terhampar.', 16],
      ['اَفَلَا يَنْظُرُوْنَ اِلَى الْاِبِلِ كَيْفَ خُلِقَتْ', 'A falaa yanzhuruuna ilal ibili kaifa khuliqat', 'Maka tidakkah mereka memperhatikan unta, bagaimana ia diciptakan?', 17],
      ['وَاِلَى السَّمَاءِ كَيْفَ رُفِعَتْ', "Wa ilas samaa-i kaifa rufi'at", 'Dan langit, bagaimana ia ditinggikan?', 18],
      ['وَاِلَى الْجِبَالِ كَيْفَ نُصِبَتْ', 'Wa ilal jibaali kaifa nushibat', 'Dan gunung-gunung, bagaimana ia ditegakkan?', 19],
      ['وَاِلَى الْاَرْضِ كَيْفَ سُطِحَتْ', 'Wa ilal ardhi kaifa suthihat', 'Dan bumi, bagaimana ia dihamparkan?', 20],
      ['فَذَكِّرْ اِنَّمَآ اَنْتَ مُذَكِّرٌ', 'Fa dzakkir innamaa anta mudzakkir', 'Maka berilah peringatan, karena sesungguhnya engkau (Muhammad) hanyalah pemberi peringatan.', 21],
      ['لَّسْتَ عَلَيْهِمْ بِمُصَيْطِرٍ', "Lasta 'alaihim bimushaitir", 'Engkau bukanlah orang yang berkuasa atas mereka,', 22],
      ['اِلَّا مَنْ تَوَلّٰى وَكَفَرَ', 'Illaa man tawallaa wa kafar', 'kecuali orang yang berpaling dan kafir,', 23],
      ['فَيُعَذِّبُهُ اللّٰهُ الْعَذَابَ الْاَكْبَرَ', "Fa yu'adz-dzibuhullaahul 'adzaabal akbar", 'maka Allah akan mengazabnya dengan azab yang besar.', 24],
      ['اِنَّ اِلَيْنَآ اِيَابَهُمْ', 'Inna ilainaa iyaabahum', 'Sungguh, kepada Kamilah mereka kembali,', 25],
      ['ثُمَّ اِنَّ عَلَيْنَا حِسَابَهُمْ', 'Tsumma inna \'alainaa hisaabahum', 'kemudian sesungguhnya Kamilah yang akan menghisab (memeriksa) mereka.', 26],
    ],
    quiz: [
      ['Al-Ghasyiyah artinya …', ['Hari Kiamat yang menyelubungi', 'Malam gelap gulita', 'Bintang terang'], 0, 'Al-Ghasyiyah = hari pembalasan yang menyelubungi segala hal.'],
      ['Hewan apa yang diajak untuk diperhatikan keajaiban penciptaannya dalam surat ini?', ['Gajah', 'Unta (al-ibil)', 'Kuda'], 1, 'Afalaa yanzhuruuna ilal ibili kaifa khuliqat = tidakkah memperhatikan unta.'],
      ['Tugas Rasulullah ﷺ menurut ayat ke-21 adalah sebagai …', ['Pemberi peringatan (mudzakkir)', 'Hakim penghukum', 'Penguasa mutlak'], 0, 'Innamaa anta mudzakkir = engkau hanyalah pemberi peringatan.'],
    ],
  },
  {
    slug: 'surat-al-fajr',
    theme: 'Surat Pendek',
    emoji: '🌄',
    title: 'Surat Al-Fajr',
    titleId: 'Fajar · 30 ayat',
    minutes: 5,
    intro:
      "**Surat ke-89** · **30 ayat** · Makkiyah.\n\n" +
      "Al-Fajr artinya **waktu fajar**. Menceritakan kehancuran kaum-kaum terdahulu yang sombong seperti kaum 'Ad, Tsamud, dan Fir'aun. Menegur manusia yang lupa diri saat kaya dan mengeluh saat miskin. Diakhiri panggilan lembut kepada jiwa yang tenang (*an-nafsul muthma'innah*) untuk masuk ke dalam surga Allah.",
    lines: [
      BASMALAH,
      ['وَالْفَجْرِ', 'Wal fajr', 'Demi fajar,', 1],
      ['وَلَيَالٍ عَشْرٍ', "Wa layaalin 'asyr", 'demi malam yang sepuluh (awal Zulhijah),', 2],
      ['وَالشَّفْعِ وَالْوَتْرِ', 'Wasy syaf\'i wal watr', 'demi yang genap dan yang ganjil,', 3],
      ['وَالَّيْلِ اِذَا يَسْرِ', 'Wal laili idzaa yasr', 'demi malam apabila berlalu.', 4],
      ['هَلْ فِيْ ذٰلِكَ قَسَمٌ لِّذِيْ حِجْرٍ', 'Hal fii dzaalika qasamul lidzii hijr', 'Adakah pada yang demikian itu sumpah (yang dapat diterima) bagi orang yang berakal?', 5],
      ['اَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِعَادٍ', "A lam tara kaifa fa'ala rabbuka bi 'aad", 'Tidakkah engkau (Muhammad) memperhatikan bagaimana Tuhanmu berbuat terhadap kaum \'Ad?', 6],
      ['اِرَمَ ذَاتِ الْعِمَادِ', "Irama dzaatil 'imaad", '(yaitu) penduduk Iram yang mempunyai bangunan-bangunan yang tinggi,', 7],
      ['الَّتِيْ لَمْ يُخْلَقْ مِثْلُهَا فِى الْبِلَادِ', 'Allatii lam yukhlaq mitsluhaa fil bilaad', 'yang belum pernah dibangun (suatu kota) seperti itu di negeri-negeri lain,', 8],
      ['وَثَمُوْدَ الَّذِيْنَ جَابُوا الصَّخْرَ بِالْوَادِ', 'Wa tsamuudal ladziina jaabush shakhra bil waad', 'dan (terhadap) kaum Tsamud yang memotong batu-batu besar di lembah,', 9],
      ['وَفِرْعَوْنَ ذِى الْاَوْتَادِ', "Wa fir'auna dzil autaad", 'dan (terhadap) Fir\'aun yang mempunyai pasak-pasak (tentara yang banyak),', 10],
      ['الَّذِيْنَ طَغَوْا فِى الْبِلَادِ', 'Alladziina thaghau fil bilaad', 'yang berbuat sewenang-wenang dalam negeri,', 11],
      ['فَاَكْثَرُوْا فِيْهَا الْفَسَادَ', 'Fa aktsaruu fiihal fasaad', 'lalu mereka banyak berbuat kerusakan dalam negeri itu,', 12],
      ['فَصَبَّ عَلَيْهِمْ رَبُّكَ سَوْطَ عَذَابٍ', "Fa shabba 'alaihim rabbuka sautha 'adzaab", 'karena itu Tuhanmu menimpakan cemeti azab kepada mereka,', 13],
      ['اِنَّ رَبَّكَ لَبِالْمِرْصَادِ', 'Inna rabbaka labil mirshaad', 'sungguh, Tuhanmu benar-benar mengawasi.', 14],
      ['فَاَمَّا الْاِنْسَانُ اِذَا مَا ابْتَلٰىهُ رَبُّهٗ فَاَكْرَمَهٗ وَنَعَّمَهٗ فَيَقُوْلُ رَبِّيْٓ اَكْرَمَنِ', "Fa ammal insaanu idzaa mabtalaahu rabbuhuu fa akramahuu wa na''amahuu fa yaquulu rabbii akraman", 'Maka adapun manusia, apabila Tuhannya mengujinya lalu memuliakannya dan memberinya kesenangan, maka dia berkata, "Tuhanku telah memuliakanku."', 15],
      ['وَاَمَّآ اِذَا مَا ابْتَلٰىهُ فَقَدَرَ عَلَيْهِ رِزْقَهٗ فَيَقُوْلُ رَبِّيْٓ اَهَانَنِ', "Wa ammaa idzaa mabtalaahu faqadara 'alaihi rizqahuu fa yaquulu rabbii ahaanan", 'Namun apabila Tuhan mengujinya lalu membatasi rezekinya, maka dia berkata, "Tuhanku telah menghinakanku."', 16],
      ['كَلَّا بَلْ لَّا تُكْرِمُوْنَ الْيَتِيْمَ', 'Kallaa bal laa tukrimuunal yatiim', 'Sekali-kali tidak! Bahkan kamu tidak memuliakan anak yatim,', 17],
      ['وَلَا تَحٰۤضُّوْنَ عَلٰى طَعَامِ الْمِسْكِيْنِ', "Wa laa tahaadh-dhuuna 'alaa tha'aamil miskiin", 'dan kamu tidak saling mengajak memberi makan orang miskin,', 18],
      ['وَتَأْكُلُوْنَ التُّرَاثَ اَكْلًا لَّمًّا', "Wa ta'kuluunat turaatsa aklal lammaa", 'sedangkan kamu memakan harta warisan dengan cara mencampurbaurkan (yang halal dan yang batil),', 19],
      ['وَتُحِبُّوْنَ الْمَالَ حُبًّا جَمًّا', 'Wa tuhibbuunal maala hubban jammaa', 'dan kamu mencintai harta dengan kecintaan yang berlebihan.', 20],
      ['كَلَّآ اِذَا دُكَّتِ الْاَرْضُ دَكًّا دَكًّا', 'Kallaa idzaa dukkatil ardhu dakkan dakkaa', 'Sekali-kali tidak! Apabila bumi diguncangkan berturut-turut,', 21],
      ['وَجَاۤءَ رَبُّكَ وَالْمَلَكُ صَفًّا صَفًّا', 'Wa jaa-a rabbuka wal malaku shaffan shaffaa', 'dan datanglah Tuhanmu, dan malaikat berbaris-baris,', 22],
      ['وَجِايْۤءَ يَوْمَىِٕذٍۢ بِجَهَنَّمَ يَوْمَىِٕذٍ يَّتَذَكَّرُ الْاِنْسَانُ وَاَنّٰى لَهُ الذِّكْرٰى', 'Wa jii-a yauma-idzim bijahannama yauma-idziy yatadzakkarul insaanu wa annaa lahudz dzikraa', 'dan pada hari itu diperlihatkan neraka Jahanam; pada hari itu sadarlah manusia, tetapi tidak berguna lagi baginya kesadaran itu.', 23],
      ['يَقُوْلُ يٰلَيْتَنِيْ قَدَّمْتُ لِحَيَاتِيْ', 'Yaquulu yaa laitanii qaddamtu lihayaatii', 'Dia berkata, "Alangkah baiknya sekiranya dahulu aku mengerjakan (kebajikan) untuk hidupku ini."', 24],
      ['فَيَوْمَىِٕذٍ لَّا يُعَذِّبُ عَذَابَهٗٓ اَحَدٌ', "Fa yauma-idzil laa yu'adz-dzibu 'adzaabahuu ahad", 'Maka pada hari itu tidak ada seorang pun yang mengazab seperti azab-Nya (yang adil),', 25],
      ['وَّلَا يُوْثِقُ وَثَاقَهٗٓ اَحَدٌ', 'Wa laa yuutsiqu watsaaqahuu ahad', 'dan tidak ada seorang pun yang mengikat seperti ikatan-Nya.', 26],
      ['يٰٓاَيَّتُهَا النَّفْسُ الْمُطْمَىِٕنَّةُ', 'Yaa ayyatuhan nafsul muthma-innah', 'Wahai jiwa yang tenang!', 27],
      ['ارْجِعِيْٓ اِلٰى رَبِّكِ رَاضِيَةً مَّرْضِيَّةً', 'Irji\'ii ilaa rabbiki raadhiyatam mardhiyyah', 'Kembalilah kepada Tuhanmu dengan hati yang rida dan diridai-Nya.', 28],
      ['فَادْخُلِيْ فِيْ عِبٰدِيْ', "Fadkhulii fii 'ibaadii", 'Maka masuklah ke dalam golongan hamba-hamba-Ku,', 29],
      ['وَادْخُلِيْ جَنَّتِيْ', 'Wadkhulii jannatii', 'dan masuklah ke dalam surga-Ku.', 30],
    ],
    quiz: [
      ['Al-Fajr artinya …', ['Waktu fajar', 'Waktu maghrib', 'Malam hari'], 0, 'Al-Fajr = waktu fajar.'],
      ['Panggilan mulia bagi orang beriman pada akhir surat Al-Fajr adalah …', ['Jiwa yang sombong', 'Jiwa yang tenang (an-nafsul muthma\'innah)', 'Jiwa yang gelisah'], 1, 'Yaa ayyatuhan nafsul muthma-innah = wahai jiwa yang tenang.'],
      ['Sikap yang dikecam dalam surat ini adalah mencintai harta secara …', ['Wajar', 'Berlebihan (hubban jammaa)', 'Tidak peduli'], 1, 'Wa tuhibbuunal maala hubban jammaa = mencintai harta berlebihan.'],
    ],
  },
  {
    slug: 'surat-al-balad',
    theme: 'Surat Pendek',
    emoji: '🏙️',
    title: 'Surat Al-Balad',
    titleId: 'Negeri · 20 ayat',
    minutes: 4,
    intro:
      "**Surat ke-90** · **20 ayat** · Makkiyah.\n\n" +
      "Al-Balad artinya **negeri (Kota Makkah)**. Mengingatkan bahwa manusia diciptakan dalam perjuangan menghadapi kesulitan (*kabad*). Mengajak manusia menempuh jalan mendaki lagi sukar (*al-'aqabah*), yaitu memerdekakan budak, memberi makan anak yatim kerabat dan orang miskin, serta saling berpesan dalam kesabaran dan kasih sayang.",
    lines: [
      BASMALAH,
      ['لَآ اُقْسِمُ بِهٰذَا الْبَلَدِ', 'Laa uqsimu bihaadzal balad', 'Aku bersumpah demi negeri ini (Makkah),', 1],
      ['وَاَنْتَ حِلٌّۢ بِهٰذَا الْبَلَدِ', 'Wa anta hillum bihaadzal balad', 'dan engkau (Muhammad), bertempat tinggal di negeri ini (Makkah),', 2],
      ['وَوَالِدٍ وَّمَا وَلَدَ', 'Wa waalidiw wa maa walad', 'dan demi pertalian bapak dan anaknya.', 3],
      ['لَقَدْ خَلَقْنَا الْاِنْسَانَ فِيْ كَبَدٍ', 'Laqad khalaqnal insaana fii kabad', 'Sungguh, Kami telah menciptakan manusia berada dalam susah payah.', 4],
      ['اَيَحْسَبُ اَنْ لَّنْ يَّقْدِرَ عَلَيْهِ اَحَدٌ', "A yahsabu al lay yaqdira 'alaihi ahad", 'Apakah dia (manusia) itu mengira bahwa tidak ada seorang pun yang berkuasa atasnya?', 5],
      ['يَقُوْلُ اَهْلَكْتُ مَالًا لُّبَدًا', 'Yaquulu ahlaktu maalal lubadaa', 'Dia mengatakan, "Aku telah menghabiskan harta yang banyak."', 6],
      ['اَيَحْسَبُ اَنْ لَّمْ يَرَهٗٓ اَحَدٌ', 'A yahsabu al lam yarahuu ahad', 'Apakah dia mengira bahwa tidak ada seorang pun yang melihatnya?', 7],
      ['اَلَمْ نَجْعَلْ لَّهٗ عَيْنَيْنِ', "A lam naj'al lahuu 'ainain", 'Bukankah Kami telah menjadikan untuknya sepasang mata,', 8],
      ['وَلِسَانًا وَّشَفَتَيْنِ', 'Wa lisaanaw wa syafatain', 'dan lidah dan sepasang bibir,', 9],
      ['وَهَدَيْنٰهُ النَّجْدَيْنِ', 'Wa hadainaahun najdain', 'dan Kami telah menunjukkan kepadanya dua jalan (kebajikan dan kejahatan)?', 10],
      ['فَلَا اقْتَحَمَ الْعَقَبَةَ', "Falaqtahamal 'aqabah", 'Tetapi dia tidak menempuh jalan yang mendaki dan sukar.', 11],
      ['وَمَآ اَدْرٰىكَ مَا الْعَقَبَةُ', "Wa maa adraaka mal 'aqabah", 'Dan tahukah kamu apakah jalan yang mendaki dan sukar itu?', 12],
      ['فَكُّ رَقَبَةٍ', 'Fakku raqabah', '(Yaitu) melepaskan perbudakan (hamba sahaya),', 13],
      ['اَوْ اِطْعَامٌ فِيْ يَوْمٍ ذِيْ مَسْغَبَةٍ', 'Au ith\'aamun fii yaumin dzii masghabah', 'atau memberi makan pada hari kelaparan,', 14],
      ['يَّتِيْمًا ذَا مَقْرَبَةٍ', 'Yatiiman dzaa maqrabah', '(kepada) anak yatim yang ada hubungan kerabat,', 15],
      ['اَوْ مِسْكِيْنًا ذَا مَتْرَبَةٍ', 'Au miskiinan dzaa matrabah', 'atau orang miskin yang sangat fakir.', 16],
      ['ثُمَّ كَانَ مِنَ الَّذِيْنَ اٰمَنُوْا وَتَوَاصَوْا بِالصَّبْرِ وَتَوَاصَوْا بِالْمَرْحَمَةِ', 'Tsumma kaana minal ladziina aamanuu wa tawaashau bish shabri wa tawaashau bil marhamah', 'Kemudian dia termasuk orang-orang yang beriman dan saling berpesan untuk bersabar dan saling berpesan untuk berkasih sayang.', 17],
      ['اُولٰۤىِٕكَ اَصْحٰبُ الْمَيْمَنَةِ', 'Ulaa-ika ash-haabul maimanah', 'Mereka (orang-orang yang beriman itu) adalah golongan kanan.', 18],
      ['وَالَّذِيْنَ كَفَرُوْا بِاٰيٰتِنَا هُمْ اَصْحٰبُ الْمَشْـَٔمَةِ', "Wal ladziina kafaruu bi-aayaatinaa hum ash-haabul masya-amah", 'Dan orang-orang yang kafir kepada ayat-ayat Kami, mereka itulah golongan kiri.', 19],
      ['عَلَيْهِمْ نَارٌ مُّؤْصَدَةٌ', "‘Alaihim naarum mu'shadah", 'Mereka berada dalam neraka yang ditutup rapat.', 20],
    ],
    quiz: [
      ['Al-Balad artinya …', ['Negeri (Kota Makkah)', 'Bukit Sinai', 'Laut Merah'], 0, 'Al-Balad = negeri (yaitu Kota suci Makkah).'],
      ['Apakah yang dimaksud dengan jalan mendaki lagi sukar (al-\'aqabah) dalam surat ini?', ['Mendaki gunung tertinggi', 'Memerdekakan budak, menyantuni anak yatim dan fakir miskin', 'Berlari kencang'], 1, 'Menolong sesama yang lemah adalah jalan mulia yang menuntut pengorbanan.'],
      ['Orang-orang beriman yang saling menasihati dalam kesabaran dan kasih sayang disebut golongan …', ['Kiri', 'Kanan (ash-haabul maimanah)', 'Ragu-ragu'], 1, 'Ulaa-ika ash-haabul maimanah = golongan kanan yang beruntung.'],
    ],
  },
];
